# find osgText
#
# exports:
#
#   OSGTEXT_FOUND
#   OSGTEXT_INCLUDE_DIR
#   OSGTEXT_LIBRARY

INCLUDE(FindPackageHandleStandardArgs)

SET(OSGTEXT_IncludeSearchPaths
  ${CMAKE_SOURCE_DIR}/lib/OpenSceneGraph-2.8.5/include
)

SET(OSGTEXT_LibrarySearchPaths
  ${CMAKE_SOURCE_DIR}/lib/OpenSceneGraph-2.8.5/lib64
)

FIND_PATH(OSGTEXT_INCLUDE_DIR osgText/Version
  PATHS ${OSGTEXT_IncludeSearchPaths}
  NO_DEFAULT_PATH
)

FIND_LIBRARY(OSGTEXT_LIBRARY
  NAMES osgText
  PATHS ${OSGTEXT_LibrarySearchPaths}
  NO_DEFAULT_PATH
)

# Handle the REQUIRED argument and set the <UPPERCASED_NAME>_FOUND variable
FIND_PACKAGE_HANDLE_STANDARD_ARGS(osgText "Could NOT find osgText SDK"
  OSGTEXT_LIBRARY
  OSGTEXT_INCLUDE_DIR
)

IF(OSGTEXT_FOUND)
  FIND_PACKAGE_MESSAGE(osgText_FOUND "Found osgText: ${OSGTEXT_INCLUDE_DIR}" "[${OSGTEXT_LIBRARY}][${OSGTEXT_INCLUDE_DIR}]")
ELSE(OSGTEXT_FOUND)
  SET(OSGTEXT_INCLUDE_DIR "")
  SET(OSGTEXT_LIBRARY "")
ENDIF(OSGTEXT_FOUND)

MARK_AS_ADVANCED(
  OSGTEXT_INCLUDE_DIR
  OSGTEXT_LIBRARY
)

