# find OpenThreads
#
# exports:
#
#   OPENTHREADS_FOUND
#   OPENTHREADS_INCLUDE_DIR
#   OPENTHREADS_LIBRARY

INCLUDE(FindPackageHandleStandardArgs)

SET(OPENTHREADS_IncludeSearchPaths
  ${CMAKE_SOURCE_DIR}/lib/OpenSceneGraph-2.8.5/include
)

SET(OPENTHREADS_LibrarySearchPaths
  ${CMAKE_SOURCE_DIR}/lib/OpenSceneGraph-2.8.5/lib64
)

FIND_PATH(OPENTHREADS_INCLUDE_DIR OpenThreads/Version
  PATHS ${OPENTHREADS_IncludeSearchPaths}
  NO_DEFAULT_PATH
)

FIND_LIBRARY(OPENTHREADS_LIBRARY
  NAMES OpenThreads
  PATHS ${OPENTHREADS_LibrarySearchPaths}
  NO_DEFAULT_PATH
)

# Handle the REQUIRED argument and set the <UPPERCASED_NAME>_FOUND variable
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenThreads "Could NOT find OpenThreads SDK"
  OPENTHREADS_LIBRARY
  OPENTHREADS_INCLUDE_DIR
)

IF(OPENTHREADS_FOUND)
  FIND_PACKAGE_MESSAGE(OPENTHREADS_FOUND "Found OpenThreads: ${OPENTHREADS_INCLUDE_DIR}" "[${OPENTHREADS_LIBRARY}][${OPENTHREADS_INCLUDE_DIR}]")
ELSE(OPENTHREADS_FOUND)
  SET(OPENTHREADS_INCLUDE_DIR "")
  SET(OPENTHREADS_LIBRARY "")
ENDIF(OPENTHREADS_FOUND)

MARK_AS_ADVANCED(
  OPENTHREADS_INCLUDE_DIR
  OPENTHREADS_LIBRARY
)

