# find osgViewer
#
# exports:
#
#   OSGVIEWER_FOUND=TRUE
#   OSGVIEWER_INCLUDE_DIR=/usr/include
#   OSGVIEWER_LIBRARIES=/usr/lib/libosgViewer.so
#   OSGVIEWER_LIBRARY=/usr/lib/libosgViewer.so

INCLUDE(FindPackageHandleStandardArgs)

SET(OSGVIEWER_IncludeSearchPaths
  ${CMAKE_SOURCE_DIR}/lib/OpenSceneGraph-2.8.5/include
)

SET(OSGVIEWER_LibrarySearchPaths
  ${CMAKE_SOURCE_DIR}/lib/OpenSceneGraph-2.8.5/lib64
)

FIND_PATH(OSGVIEWER_INCLUDE_DIR osgViewer/Version
  PATHS ${OSGVIEWER_IncludeSearchPaths}
  NO_DEFAULT_PATH
)

FIND_LIBRARY(OSGVIEWER_LIBRARY
  NAMES osgViewer
  PATHS ${OSGVIEWER_LibrarySearchPaths}
  NO_DEFAULT_PATH
)

# Handle the REQUIRED argument and set the <UPPERCASED_NAME>_FOUND variable
FIND_PACKAGE_HANDLE_STANDARD_ARGS(osgViewer "Could NOT find osgViewer SDK"
  OSGVIEWER_LIBRARY
  OSGVIEWER_INCLUDE_DIR
)

IF(OSGVIEWER_FOUND)
  FIND_PACKAGE_MESSAGE(osgViewer_FOUND "Found osgViewer: ${OSGVIEWER_INCLUDE_DIR}" "[${OSGVIEWER_LIBRARY}][${OSGVIEWER_INCLUDE_DIR}]")
ELSE(OSGVIEWER_FOUND)
  SET(OSGVIEWER_INCLUDE_DIR "")
  SET(OSGVIEWER_LIBRARY "")
ENDIF(OSGVIEWER_FOUND)

MARK_AS_ADVANCED(
  OSGVIEWER_INCLUDE_DIR
  OSGVIEWER_LIBRARY
)

