OpenSceneGraph: osg::AnimationPath::ControlPoint Class Reference
osg::AnimationPath::ControlPoint Class Reference
Public Member Functions
ControlPoint ()
ControlPoint (const osg::Vec3d &position)
ControlPoint (const osg::Vec3d &position, const osg::Quat &rotation)
ControlPoint (const osg::Vec3d &position, const osg::Quat &rotation, const osg::Vec3d &scale)
void setPosition (const osg::Vec3d &position)
const osg::Vec3d & getPosition () const
void setRotation (const osg::Quat &rotation)
const osg::Quat & getRotation () const
void setScale (const osg::Vec3d &scale)
const osg::Vec3d & getScale () const
void interpolate (float ratio, const ControlPoint &first, const ControlPoint &second)
void interpolate (double ratio, const ControlPoint &first, const ControlPoint &second)
void getMatrix (Matrixf &matrix) const
void getMatrix (Matrixd &matrix) const
void getInverse (Matrixf &matrix) const
void getInverse (Matrixd &matrix) const
Protected Attributes
osg::Vec3d _position
osg::Quat _rotation
osg::Vec3d _scale
Constructor & Destructor Documentation
osg::AnimationPath::ControlPoint::ControlPoint () [inline]
osg::AnimationPath::ControlPoint::ControlPoint (const osg::Vec3d & position) [inline]
osg::AnimationPath::ControlPoint::ControlPoint (const osg::Vec3d & position, const osg::Quat & rotation) [inline]
osg::AnimationPath::ControlPoint::ControlPoint (const osg::Vec3d & position, const osg::Quat & rotation, const osg::Vec3d & scale) [inline]
Member Function Documentation
void osg::AnimationPath::ControlPoint::getInverse (Matrixf & matrix) const [inline]
References osg::Matrixf::makeRotate(), osg::Matrixf::postMultScale(), and osg::Matrixf::preMultTranslate().
Referenced by osg::AnimationPath::getInverse().
void osg::AnimationPath::ControlPoint::getInverse (Matrixd & matrix) const [inline]
References osg::Matrixd::makeRotate(), osg::Matrixd::postMultScale(), and osg::Matrixd::preMultTranslate().
void osg::AnimationPath::ControlPoint::getMatrix (Matrixf & matrix) const [inline]
References osg::Matrixf::makeRotate(), osg::Matrixf::postMultTranslate(), and osg::Matrixf::preMultScale().
Referenced by osg::AnimationPath::getMatrix().
void osg::AnimationPath::ControlPoint::getMatrix (Matrixd & matrix) const [inline]
References osg::Matrixd::makeRotate(), osg::Matrixd::postMultTranslate(), and osg::Matrixd::preMultScale().
const osg::Vec3d& osg::AnimationPath::ControlPoint::getPosition () const [inline]
const osg::Quat& osg::AnimationPath::ControlPoint::getRotation () const [inline]
const osg::Vec3d& osg::AnimationPath::ControlPoint::getScale () const [inline]
void osg::AnimationPath::ControlPoint::interpolate (double ratio, const ControlPoint & first, const ControlPoint & second) [inline]
References _position, _rotation, and _scale.
void osg::AnimationPath::ControlPoint::interpolate (float ratio, const ControlPoint & first, const ControlPoint & second) [inline]
References _position, _rotation, and _scale.
void osg::AnimationPath::ControlPoint::setPosition (const osg::Vec3d & position) [inline]
void osg::AnimationPath::ControlPoint::setRotation (const osg::Quat & rotation) [inline]
void osg::AnimationPath::ControlPoint::setScale (const osg::Vec3d & scale) [inline]
Member Data Documentation
osg::Vec3d osg::AnimationPath::ControlPoint::_position [protected]
Referenced by interpolate().
osg::Quat osg::AnimationPath::ControlPoint::_rotation [protected]
Referenced by interpolate().
osg::Vec3d osg::AnimationPath::ControlPoint::_scale [protected]
Referenced by interpolate().
The documentation for this class was generated from the following file:
osg/AnimationPath
Generated at Thu Jun 9 2011 16:37:14 for the OpenSceneGraph by doxygen 1.7.1.