OpenSceneGraph: osg::Drawable::CullCallback Struct Reference
osg::Drawable::CullCallback Struct Reference
Public Member Functions
CullCallback ()
CullCallback (const CullCallback &, const CopyOp &)
META_Object (osg, CullCallback)
virtual bool cull (osg::NodeVisitor *, osg::Drawable *, osg::State *) const
deprecated.
virtual bool cull (osg::NodeVisitor *nv, osg::Drawable *drawable, osg::RenderInfo *renderInfo) const
do customized cull code, return true if drawable should be culled.
Constructor & Destructor Documentation
osg::Drawable::CullCallback::CullCallback () [inline]
osg::Drawable::CullCallback::CullCallback (const CullCallback & , const CopyOp &) [inline]
Member Function Documentation
virtual bool osg::Drawable::CullCallback::cull (osg::NodeVisitor * , osg::Drawable * , osg::State *) const [inline, virtual]
deprecated.
virtual bool osg::Drawable::CullCallback::cull (osg::NodeVisitor * nv, osg::Drawable * drawable, osg::RenderInfo * renderInfo) const [inline, virtual]
do customized cull code, return true if drawable should be culled.
Reimplemented in osgViewer::InteractiveImageHandler.
References cull(), and osg::RenderInfo::getState().
Referenced by cull().
osg::Drawable::CullCallback::META_Object (osg , CullCallback)
The documentation for this struct was generated from the following file:
osg/Drawable
Generated at Thu Jun 9 2011 16:37:14 for the OpenSceneGraph by doxygen 1.7.1.