OpenSceneGraph: osg::Drawable Class Reference
osg::Drawable Class Reference
Pure virtual base class for drawable geometry.
Classes
class AttributeFunctor
struct ComputeBoundingBoxCallback
Callback to allow users to override the default computation of bounding volume.
class ConstAttributeFunctor
struct CullCallback
struct DrawCallback
Callback attached to an Drawable which allows the users to customize the drawing of an exist Drawable object.
struct EventCallback
class Extensions
Extensions class which encapsulates the querying of extensions and associated function pointers, and provide convenience wrappers to check for the extensions or use the associated functions.
struct UpdateCallback
Public Types
enum AttributeTypes {
VERTICES = 0, WEIGHTS = 1, NORMALS = 2, COLORS = 3,
SECONDARY_COLORS = 4, FOG_COORDS = 5, ATTRIBUTE_6 = 6, ATTRIBUTE_7 = 7,
TEXTURE_COORDS = 8, TEXTURE_COORDS_0 = TEXTURE_COORDS, TEXTURE_COORDS_1 = TEXTURE_COORDS_0+1, TEXTURE_COORDS_2 = TEXTURE_COORDS_0+2,
TEXTURE_COORDS_3 = TEXTURE_COORDS_0+3, TEXTURE_COORDS_4 = TEXTURE_COORDS_0+4, TEXTURE_COORDS_5 = TEXTURE_COORDS_0+5, TEXTURE_COORDS_6 = TEXTURE_COORDS_0+6,
TEXTURE_COORDS_7 = TEXTURE_COORDS_0+7
}
typedef std::vector< Node * > ParentList
A vector of osg::Node pointers which is used to store the parent(s) of drawable.
typedef unsigned int AttributeType
Public Member Functions
Drawable ()
Drawable (const Drawable &drawable, const CopyOp &copyop=CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
virtual bool isSameKindAs (const Object *obj) const
virtual const char * libraryName () const
return the name of the object's library.
virtual const char * className () const
return the name of the object's class type.
virtual Geometry * asGeometry ()
Convert 'this' into a Geometry pointer if Drawable is a Geometry, otherwise return 0.
virtual const Geometry * asGeometry () const
Convert 'const this' into a const Geometry pointer if Drawable is a Geometry, otherwise return 0.
virtual void computeDataVariance ()
Compute the DataVariance based on an assessment of callback etc.
const ParentList & getParents () const
Get the parent list of drawable.
ParentList getParents ()
Get the a copy of parent list of node.
Node * getParent (unsigned int i)
Get a single parent of Drawable.
const Node * getParent (unsigned int i) const
Get a single const parent of Drawable.
unsigned int getNumParents () const
Get the number of parents of node.
MatrixList getWorldMatrices (const osg::Node *haltTraversalAtNode=0) const
Get the list of matrices that transform this node from local coordinates to world coordinates.
void setStateSet (StateSet *stateset)
Set the StateSet attached to the Drawable.
StateSet * getStateSet ()
Get the attached StateSet.
const StateSet * getStateSet () const
Get the attached const StateSet.
StateSet * getOrCreateStateSet ()
Get the attached const StateSet, if one is not already attached create one, attach it to the drawable and return a pointer to it.
void setInitialBound (const osg::BoundingBox &bbox)
Set the initial bounding volume to use when computing the overall bounding volume.
const BoundingBox & getInitialBound () const
Set the initial bounding volume to use when computing the overall bounding volume.
void dirtyBound ()
Dirty the bounding box, forcing a computeBound() on the next call to getBound().
const BoundingBox & getBound () const
Get BoundingBox of Drawable.
virtual BoundingBox computeBound () const
Compute the bounding box around Drawables's geometry.
void setComputeBoundingBoxCallback (ComputeBoundingBoxCallback *callback)
Set the compute bound callback to override the default computeBound.
ComputeBoundingBoxCallback * getComputeBoundingBoxCallback ()
Get the compute bound callback.
const ComputeBoundingBoxCallback * getComputeBoundingBoxCallback () const
Get the const compute bound callback.
void setShape (Shape *shape)
Set the Shape of the Drawable.
Shape * getShape ()
Get the Shape of the Drawable.
const Shape * getShape () const
Get the const Shape of the const Drawable.
void setSupportsDisplayList (bool flag)
Set the drawable so that it can or cannot be used in conjunction with OpenGL display lists.
bool getSupportsDisplayList () const
Get whether display lists are supported for this drawable instance.
void setUseDisplayList (bool flag)
When set to true, force the draw method to use OpenGL Display List for rendering.
bool getUseDisplayList () const
Return whether OpenGL display lists are being used for rendering.
GLuint & getDisplayList (unsigned int contextID) const
Return OpenGL display list for specified contextID.
virtual void setUseVertexBufferObjects (bool flag)
When set to true, ignore the setUseDisplayList() settings, and hints to the drawImplementation method to use OpenGL vertex buffer objects for rendering.
bool getUseVertexBufferObjects () const
Return whether OpenGL vertex buffer objects should be used when supported by OpenGL driver.
virtual void dirtyDisplayList ()
Force a recompile on next draw() of any OpenGL display list associated with this geoset.
virtual unsigned int getGLObjectSizeHint () const
Return the estimated size of GLObjects (display lists/vertex buffer objects) that are associated with this drawable.
void draw (RenderInfo &renderInfo) const
Draw OpenGL primitives.
virtual void compileGLObjects (RenderInfo &renderInfo) const
Immediately compile this Drawable into an OpenGL Display List.
virtual void setThreadSafeRefUnref (bool threadSafe)
Set whether to use a mutex to ensure ref() and unref() are thread safe.
virtual void resizeGLObjectBuffers (unsigned int maxSize)
Resize any per context GLObject buffers to specified size.
virtual void releaseGLObjects (State *state=0) const
If State is non-zero, this function releases OpenGL objects for the specified graphics context.
virtual void setUpdateCallback (UpdateCallback *ac)
Set the UpdateCallback which allows users to attach customize the updating of an object during the update traversal.
UpdateCallback * getUpdateCallback ()
Get the non const UpdateCallback.
const UpdateCallback * getUpdateCallback () const
Get the const UpdateCallback.
bool requiresUpdateTraversal () const
Return whether this Drawable has update callbacks associated with it, and therefore must be traversed.
virtual void setEventCallback (EventCallback *ac)
Set the EventCallback which allows users to attach customize the updating of an object during the Event traversal.
EventCallback * getEventCallback ()
Get the non const EventCallback.
const EventCallback * getEventCallback () const
Get the const EventCallback.
bool requiresEventTraversal () const
Return whether this Drawable has event callbacks associated with it, and therefore must be traversed.
virtual void setCullCallback (CullCallback *cc)
Set the CullCallback which allows users to customize the culling of Drawable during the cull traversal.
CullCallback * getCullCallback ()
Get the non const CullCallback.
const CullCallback * getCullCallback () const
Get the const CullCallback.
virtual void setDrawCallback (DrawCallback *dc)
Set the DrawCallback which allows users to attach customize the drawing of existing Drawable object.
DrawCallback * getDrawCallback ()
Get the non const DrawCallback.
const DrawCallback * getDrawCallback () const
Get the const DrawCallback.
virtual void drawImplementation (RenderInfo &renderInfo) const =0
drawImplementation(RenderInfo&) is a pure virtual method for the actual implementation of OpenGL drawing calls, such as vertex arrays and primitives, that must be implemented in concrete subclasses of the Drawable base class, examples include osg::Geometry and osg::ShapeDrawable.
virtual bool supports (const AttributeFunctor &) const
Return true if the Drawable subclass supports accept(AttributeFunctor&).
virtual void accept (AttributeFunctor &)
accept an AttributeFunctor and call its methods to tell it about the internal attributes that this Drawable has.
virtual bool supports (const ConstAttributeFunctor &) const
Return true if the Drawable subclass supports accept(ConstAttributeFunctor&).
virtual void accept (ConstAttributeFunctor &) const
Accept an AttributeFunctor and call its methods to tell it about the internal attributes that this Drawable has.
virtual bool supports (const PrimitiveFunctor &) const
Return true if the Drawable subclass supports accept(PrimitiveFunctor&).
virtual void accept (PrimitiveFunctor &) const
Accept a PrimitiveFunctor and call its methods to tell it about the internal primitives that this Drawable has.
virtual bool supports (const PrimitiveIndexFunctor &) const
Return true if the Drawable subclass supports accept(PrimitiveIndexFunctor&).
virtual void accept (PrimitiveIndexFunctor &) const
Accept a PrimitiveIndexFunctor and call its methods to tell it about the internal primitives that this Drawable has.
Static Public Member Functions
static GLuint generateDisplayList (unsigned int contextID, unsigned int sizeHint=0)
Return a OpenGL display list handle a newly generated or reused from display list cache.
static void setMinimumNumberOfDisplayListsToRetainInCache (unsigned int minimum)
Set the minimum number of display lists to retain in the deleted display list cache.
static unsigned int getMinimumNumberOfDisplayListsToRetainInCache ()
Get the minimum number of display lists to retain in the deleted display list cache.
static void deleteDisplayList (unsigned int contextID, GLuint globj, unsigned int sizeHint=0)
Use deleteDisplayList instead of glDeleteList to allow OpenGL display list to be cached until they can be deleted by the OpenGL context in which they were created, specified by contextID.
static void flushAllDeletedDisplayLists (unsigned int contextID)
Flush all the cached display list which need to be deleted in the OpenGL context related to contextID.
static void discardAllDeletedDisplayLists (unsigned int contextID)
Flush all the cached display list which need to be deleted in the OpenGL context related to contextID.
static void flushDeletedDisplayLists (unsigned int contextID, double &availableTime)
Flush the cached display list which need to be deleted in the OpenGL context related to contextID.
static Extensions * getExtensions (unsigned int contextID, bool createIfNotInitalized)
Function to call to get the extension of a specified context.
static void setExtensions (unsigned int contextID, Extensions *extensions)
setExtensions allows users to override the extensions across graphics contexts.
Static Public Attributes
static unsigned int s_numberDrawablesReusedLastInLastFrame
static unsigned int s_numberNewDrawablesInLastFrame
static unsigned int s_numberDeletedDrawablesInLastFrame
Protected Types
typedef osg::buffered_value
< GLuint > GLObjectList
Protected Member Functions
Drawable & operator= (const Drawable &)
virtual ~Drawable ()
void setBound (const BoundingBox &bb) const
set the bounding box .
void addParent (osg::Node *node)
void removeParent (osg::Node *node)
void setNumChildrenRequiringUpdateTraversal (unsigned int num)
unsigned int getNumChildrenRequiringUpdateTraversal () const
void setNumChildrenRequiringEventTraversal (unsigned int num)
unsigned int getNumChildrenRequiringEventTraversal () const
Protected Attributes
ParentList _parents
ref_ptr< StateSet > _stateset
BoundingBox _initialBound
ref_ptr
< ComputeBoundingBoxCallback > _computeBoundCallback
BoundingBox _boundingBox
bool _boundingBoxComputed
ref_ptr< Shape > _shape
bool _supportsDisplayList
bool _useDisplayList
bool _supportsVertexBufferObjects
bool _useVertexBufferObjects
GLObjectList _globjList
ref_ptr< UpdateCallback > _updateCallback
unsigned int _numChildrenRequiringUpdateTraversal
ref_ptr< EventCallback > _eventCallback
unsigned int _numChildrenRequiringEventTraversal
ref_ptr< CullCallback > _cullCallback
ref_ptr< DrawCallback > _drawCallback
Friends
class Node
class Geode
class StateSet
Detailed Description
Pure virtual base class for drawable geometry.
In OSG, everything that can be rendered is implemented as a class derived from Drawable. The Drawable class contains no drawing primitives, since these are provided by subclasses such as osg::Geometry.
Notice that a Drawable is not a Node, and therefore it cannot be directly added to a scene graph. Instead, Drawables are attached to Geodes, which are scene graph nodes.
The OpenGL state that must be used when rendering a Drawable is represented by a StateSet. Since a Drawable has a reference (osg::ref_ptr) to a StateSet, StateSets can be shared between different Drawables. In fact, sharing StateSets is a good way to improve performance, since this allows OSG to reduce the number of expensive changes in the OpenGL state.
Finally, Drawables can also be shared between different Geodes, so that the same geometry (loaded to memory just once) can be used in different parts of the scene graph.
Member Typedef Documentation
typedef unsigned int osg::Drawable::AttributeType
typedef osg::buffered_value<GLuint> osg::Drawable::GLObjectList [protected]
typedef std::vector<Node*> osg::Drawable::ParentList
A vector of osg::Node pointers which is used to store the parent(s) of drawable.
Member Enumeration Documentation
enum osg::Drawable::AttributeTypes
Enumerator:
VERTICES
WEIGHTS
NORMALS
COLORS
SECONDARY_COLORS
FOG_COORDS
ATTRIBUTE_6
ATTRIBUTE_7
TEXTURE_COORDS
TEXTURE_COORDS_0
TEXTURE_COORDS_1
TEXTURE_COORDS_2
TEXTURE_COORDS_3
TEXTURE_COORDS_4
TEXTURE_COORDS_5
TEXTURE_COORDS_6
TEXTURE_COORDS_7
Constructor & Destructor Documentation
osg::Drawable::Drawable ()
osg::Drawable::Drawable (const Drawable & drawable, const CopyOp & copyop = CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
virtual osg::Drawable::~Drawable () [protected, virtual]
Member Function Documentation
virtual void osg::Drawable::accept (AttributeFunctor &) [inline, virtual]
accept an AttributeFunctor and call its methods to tell it about the internal attributes that this Drawable has.
return true if functor handled by drawable, return false on failure of drawable to generate functor calls.
Reimplemented in osg::Geometry.
virtual void osg::Drawable::accept (ConstAttributeFunctor &) const [inline, virtual]
Accept an AttributeFunctor and call its methods to tell it about the internal attributes that this Drawable has.
return true if functor handled by drawable, return false on failure of drawable to generate functor calls.
Reimplemented in osg::Geometry, osg::ShapeDrawable, and osgText::Text.
virtual void osg::Drawable::accept (PrimitiveFunctor &) const [inline, virtual]
Accept a PrimitiveFunctor and call its methods to tell it about the internal primitives that this Drawable has.
return true if functor handled by drawable, return false on failure of drawable to generate functor calls. Note, PrimtiveFunctor only provides const access of the primitives, as primitives may be procedurally generated so one cannot modify it.
Reimplemented in osg::Geometry, osg::ShapeDrawable, osgParticle::PrecipitationEffect::PrecipitationDrawable, osgSim::ImpostorSprite, and osgText::Text.
virtual void osg::Drawable::accept (PrimitiveIndexFunctor &) const [inline, virtual]
Accept a PrimitiveIndexFunctor and call its methods to tell it about the internal primitives that this Drawable has.
return true if functor handled by drawable, return false on failure of drawable to generate functor calls. Note, PrimtiveIndexFunctor only provide const access of the primitives, as primitives may be procedurally generated so one cannot modify it.
Reimplemented in osg::Geometry, and osgParticle::PrecipitationEffect::PrecipitationDrawable.
void osg::Drawable::addParent (osg::Node * node) [protected]
virtual Geometry* osg::Drawable::asGeometry () [inline, virtual]
Convert 'this' into a Geometry pointer if Drawable is a Geometry, otherwise return 0.
Equivalent to dynamic_cast<Geometry*>(this).
Reimplemented in osg::Geometry.
virtual const Geometry* osg::Drawable::asGeometry () const [inline, virtual]
Convert 'const this' into a const Geometry pointer if Drawable is a Geometry, otherwise return 0.
Equivalent to dynamic_cast<const Geometry*>(this).
Reimplemented in osg::Geometry.
virtual const char* osg::Drawable::className () const [inline, virtual]
return the name of the object's class type.
Must be defined by derived classes.
Implements osg::Object.
Reimplemented in osg::DrawPixels, osg::Geometry, osg::ShapeDrawable, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgText::Text, osgText::TextBase, and osgAnimation::MorphGeometry.
virtual void osg::Drawable::compileGLObjects (RenderInfo & renderInfo) const [virtual]
Immediately compile this Drawable into an OpenGL Display List.
Note:
Operation is ignored if _useDisplayList is false.
virtual BoundingBox osg::Drawable::computeBound () const [virtual]
Compute the bounding box around Drawables's geometry.
Reimplemented in osg::DrawPixels, osg::ShapeDrawable, osgParticle::ParticleSystem, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgText::Text3D, and osgText::TextBase.
virtual void osg::Drawable::computeDataVariance () [virtual]
Compute the DataVariance based on an assessment of callback etc.
Reimplemented from osg::Object.
static void osg::Drawable::deleteDisplayList (unsigned int contextID, GLuint globj, unsigned int sizeHint = 0) [static]
Use deleteDisplayList instead of glDeleteList to allow OpenGL display list to be cached until they can be deleted by the OpenGL context in which they were created, specified by contextID.
void osg::Drawable::dirtyBound ()
Dirty the bounding box, forcing a computeBound() on the next call to getBound().
Should be called in the internal geometry of the Drawable is modified.
virtual void osg::Drawable::dirtyDisplayList () [virtual]
Force a recompile on next draw() of any OpenGL display list associated with this geoset.
Reimplemented in osg::Geometry.
static void osg::Drawable::discardAllDeletedDisplayLists (unsigned int contextID) [static]
Flush all the cached display list which need to be deleted in the OpenGL context related to contextID.
Note, unlike flush no OpenGL calls are made, instead the handles are all removed. this call is useful for when an OpenGL context has been destroyed.
void osg::Drawable::draw (RenderInfo & renderInfo) const [inline]
Draw OpenGL primitives.
If the Drawable has _useDisplayList set to true, then use an OpenGL display list, automatically compiling one if required. Otherwise, call drawImplementation().
Note:
This method should not be overridden in subclasses, as it manages the optional display list (notice this is not even virtual). Subclasses should override drawImplementation() instead.
References _drawCallback, _globjList, _supportsVertexBufferObjects, _useDisplayList, _useVertexBufferObjects, drawImplementation(), generateDisplayList(), osg::RenderInfo::getContextID(), getGLObjectSizeHint(), osg::RenderInfo::getState(), osg::State::isVertexBufferObjectSupported(), and osg::ref_ptr< T >::valid().
virtual void osg::Drawable::drawImplementation (RenderInfo & renderInfo) const [pure virtual]
drawImplementation(RenderInfo&) is a pure virtual method for the actual implementation of OpenGL drawing calls, such as vertex arrays and primitives, that must be implemented in concrete subclasses of the Drawable base class, examples include osg::Geometry and osg::ShapeDrawable.
drawImplementation(RenderInfo&) is called from the draw(RenderInfo&) method, with the draw method handling management of OpenGL display lists, and drawImplementation(RenderInfo&) handling the actual drawing itself.
Parameters:
renderInfo The osg::RenderInfo object that encapsulates the current rendering information including the osg::State OpenGL state for the current graphics context.
Implemented in osg::DrawPixels, osg::Geometry, osg::QueryGeometry, osg::ShapeDrawable, osgParticle::ConnectedParticleSystem, osgParticle::ParticleSystem, osgParticle::PrecipitationEffect::PrecipitationDrawable, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgText::FadeText, osgText::Text, osgText::Text3D, and osgAnimation::RigGeometry.
Referenced by draw().
static void osg::Drawable::flushAllDeletedDisplayLists (unsigned int contextID) [static]
Flush all the cached display list which need to be deleted in the OpenGL context related to contextID.
static void osg::Drawable::flushDeletedDisplayLists (unsigned int contextID, double & availableTime) [static]
Flush the cached display list which need to be deleted in the OpenGL context related to contextID.
static GLuint osg::Drawable::generateDisplayList (unsigned int contextID, unsigned int sizeHint = 0) [static]
Return a OpenGL display list handle a newly generated or reused from display list cache.
Referenced by draw().
const BoundingBox& osg::Drawable::getBound () const [inline]
Get BoundingBox of Drawable.
If the BoundingBox is not up to date then its updated via an internal call to computeBond().
ComputeBoundingBoxCallback* osg::Drawable::getComputeBoundingBoxCallback () [inline]
Get the compute bound callback.
const ComputeBoundingBoxCallback* osg::Drawable::getComputeBoundingBoxCallback () const [inline]
Get the const compute bound callback.
CullCallback* osg::Drawable::getCullCallback () [inline]
Get the non const CullCallback.
Referenced by osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
const CullCallback* osg::Drawable::getCullCallback () const [inline]
Get the const CullCallback.
GLuint& osg::Drawable::getDisplayList (unsigned int contextID) const [inline]
Return OpenGL display list for specified contextID.
Referenced by osgDB::DatabasePager::isCompiled().
DrawCallback* osg::Drawable::getDrawCallback () [inline]
Get the non const DrawCallback.
const DrawCallback* osg::Drawable::getDrawCallback () const [inline]
Get the const DrawCallback.
EventCallback* osg::Drawable::getEventCallback () [inline]
Get the non const EventCallback.
Referenced by osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
const EventCallback* osg::Drawable::getEventCallback () const [inline]
Get the const EventCallback.
static Extensions* osg::Drawable::getExtensions (unsigned int contextID, bool createIfNotInitalized) [static]
Function to call to get the extension of a specified context.
If the Extension object for that context has not yet been created and the 'createIfNotInitalized' flag been set to false then returns NULL. If 'createIfNotInitalized' is true then the Extensions object is automatically created. However, in this case the extension object is only created with the graphics context associated with ContextID..
virtual unsigned int osg::Drawable::getGLObjectSizeHint () const [inline, virtual]
Return the estimated size of GLObjects (display lists/vertex buffer objects) that are associated with this drawable.
This size is used a hint for reuse of deleted display lists/vertex buffer objects.
Reimplemented in osg::Geometry.
Referenced by draw().
const BoundingBox& osg::Drawable::getInitialBound () const [inline]
Set the initial bounding volume to use when computing the overall bounding volume.
static unsigned int osg::Drawable::getMinimumNumberOfDisplayListsToRetainInCache () [static]
Get the minimum number of display lists to retain in the deleted display list cache.
unsigned int osg::Drawable::getNumChildrenRequiringEventTraversal () const [inline, protected]
unsigned int osg::Drawable::getNumChildrenRequiringUpdateTraversal () const [inline, protected]
unsigned int osg::Drawable::getNumParents () const [inline]
Get the number of parents of node.
Returns:
the number of parents of this node.
StateSet* osg::Drawable::getOrCreateStateSet ()
Get the attached const StateSet, if one is not already attached create one, attach it to the drawable and return a pointer to it.
Node* osg::Drawable::getParent (unsigned int i) [inline]
Get a single parent of Drawable.
Parameters:
i index of the parent to get.
Returns:
the parent i.
const Node* osg::Drawable::getParent (unsigned int i) const [inline]
Get a single const parent of Drawable.
Parameters:
i index of the parent to get.
Returns:
the parent i.
const ParentList& osg::Drawable::getParents () const [inline]
Get the parent list of drawable.
Referenced by osgAnimation::RigGeometry::UpdateVertex::update().
ParentList osg::Drawable::getParents () [inline]
Get the a copy of parent list of node.
A copy is returned to prevent modification of the parent list.
Shape* osg::Drawable::getShape () [inline]
Get the Shape of the Drawable.
const Shape* osg::Drawable::getShape () const [inline]
Get the const Shape of the const Drawable.
StateSet* osg::Drawable::getStateSet () [inline]
Get the attached StateSet.
const StateSet* osg::Drawable::getStateSet () const [inline]
Get the attached const StateSet.
bool osg::Drawable::getSupportsDisplayList () const [inline]
Get whether display lists are supported for this drawable instance.
UpdateCallback* osg::Drawable::getUpdateCallback () [inline]
Get the non const UpdateCallback.
Referenced by osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
const UpdateCallback* osg::Drawable::getUpdateCallback () const [inline]
Get the const UpdateCallback.
bool osg::Drawable::getUseDisplayList () const [inline]
Return whether OpenGL display lists are being used for rendering.
Referenced by osgDB::DatabasePager::isCompiled().
bool osg::Drawable::getUseVertexBufferObjects () const [inline]
Return whether OpenGL vertex buffer objects should be used when supported by OpenGL driver.
MatrixList osg::Drawable::getWorldMatrices (const osg::Node * haltTraversalAtNode = 0) const
Get the list of matrices that transform this node from local coordinates to world coordinates.
The optional Node* haltTraversalAtNode allows the user to prevent traversal beyond a specifed node.
virtual bool osg::Drawable::isSameKindAs (const Object * obj) const [inline, virtual]
Reimplemented from osg::Object.
Reimplemented in osg::DrawPixels, osg::Geometry, osg::ShapeDrawable, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgText::Text, osgText::TextBase, and osgAnimation::MorphGeometry.
References NULL.
virtual const char* osg::Drawable::libraryName () const [inline, virtual]
return the name of the object's library.
Must be defined by derived classes. The OpenSceneGraph convention is that the namespace of a library is the same as the library name.
Implements osg::Object.
Reimplemented in osg::DrawPixels, osg::Geometry, osg::ShapeDrawable, osgShadow::OccluderGeometry, osgShadow::ShadowVolumeGeometry, osgSim::ImpostorSprite, osgText::Text, osgText::TextBase, and osgAnimation::MorphGeometry.
Drawable& osg::Drawable::operator= (const Drawable &) [inline, protected]
virtual void osg::Drawable::releaseGLObjects (State * state = 0) const [virtual]
If State is non-zero, this function releases OpenGL objects for the specified graphics context.
Otherwise, releases OpenGL objects for all graphics contexts.
Reimplemented from osg::Object.
Reimplemented in osg::Geometry, osgText::Text, osgText::Text3D, and osgText::TextBase.
void osg::Drawable::removeParent (osg::Node * node) [protected]
bool osg::Drawable::requiresEventTraversal () const [inline]
Return whether this Drawable has event callbacks associated with it, and therefore must be traversed.
bool osg::Drawable::requiresUpdateTraversal () const [inline]
Return whether this Drawable has update callbacks associated with it, and therefore must be traversed.
virtual void osg::Drawable::resizeGLObjectBuffers (unsigned int maxSize) [virtual]
Resize any per context GLObject buffers to specified size.
Reimplemented from osg::Object.
Reimplemented in osg::Geometry, osgText::Text, osgText::Text3D, and osgText::TextBase.
void osg::Drawable::setBound (const BoundingBox & bb) const [protected]
set the bounding box .
void osg::Drawable::setComputeBoundingBoxCallback (ComputeBoundingBoxCallback * callback) [inline]
Set the compute bound callback to override the default computeBound.
virtual void osg::Drawable::setCullCallback (CullCallback * cc) [inline, virtual]
Set the CullCallback which allows users to customize the culling of Drawable during the cull traversal.
virtual void osg::Drawable::setDrawCallback (DrawCallback * dc) [inline, virtual]
Set the DrawCallback which allows users to attach customize the drawing of existing Drawable object.
virtual void osg::Drawable::setEventCallback (EventCallback * ac) [virtual]
Set the EventCallback which allows users to attach customize the updating of an object during the Event traversal.
static void osg::Drawable::setExtensions (unsigned int contextID, Extensions * extensions) [static]
setExtensions allows users to override the extensions across graphics contexts.
typically used when you have different extensions supported across graphics pipes but need to ensure that they all use the same low common denominator extensions.
void osg::Drawable::setInitialBound (const osg::BoundingBox & bbox) [inline]
Set the initial bounding volume to use when computing the overall bounding volume.
static void osg::Drawable::setMinimumNumberOfDisplayListsToRetainInCache (unsigned int minimum) [static]
Set the minimum number of display lists to retain in the deleted display list cache.
void osg::Drawable::setNumChildrenRequiringEventTraversal (unsigned int num) [protected]
void osg::Drawable::setNumChildrenRequiringUpdateTraversal (unsigned int num) [protected]
void osg::Drawable::setShape (Shape * shape) [inline]
Set the Shape of the Drawable.
The shape can be used to speed up collision detection or as a guide for procedural geometry generation.
See also:
osg::Shape.
void osg::Drawable::setStateSet (StateSet * stateset)
Set the StateSet attached to the Drawable.
Previously attached StateSet are automatically unreferenced on assignment of a new drawstate.
void osg::Drawable::setSupportsDisplayList (bool flag)
Set the drawable so that it can or cannot be used in conjunction with OpenGL display lists.
When set to true, calls to Drawable::setUseDisplayList, whereas when set to false, no display lists can be created and calls to setUseDisplayList are ignored, and a warning is produced. The latter is typically used to guard against the switching on of display lists on objects with dynamic internal data such as continuous Level of Detail algorithms.
virtual void osg::Drawable::setThreadSafeRefUnref (bool threadSafe) [virtual]
Set whether to use a mutex to ensure ref() and unref() are thread safe.
Reimplemented from osg::Referenced.
Reimplemented in osgText::Text, osgText::Text3D, and osgText::TextBase.
virtual void osg::Drawable::setUpdateCallback (UpdateCallback * ac) [virtual]
Set the UpdateCallback which allows users to attach customize the updating of an object during the update traversal.
void osg::Drawable::setUseDisplayList (bool flag)
When set to true, force the draw method to use OpenGL Display List for rendering.
If false, rendering directly. If the display list has not been compiled already, the next call to draw will automatically create the display list.
virtual void osg::Drawable::setUseVertexBufferObjects (bool flag) [virtual]
When set to true, ignore the setUseDisplayList() settings, and hints to the drawImplementation method to use OpenGL vertex buffer objects for rendering.
Reimplemented in osg::Geometry.
virtual bool osg::Drawable::supports (const PrimitiveIndexFunctor &) const [inline, virtual]
Return true if the Drawable subclass supports accept(PrimitiveIndexFunctor&).
Reimplemented in osg::Geometry, and osgParticle::PrecipitationEffect::PrecipitationDrawable.
virtual bool osg::Drawable::supports (const ConstAttributeFunctor &) const [inline, virtual]
Return true if the Drawable subclass supports accept(ConstAttributeFunctor&).
Reimplemented in osg::Geometry, osg::ShapeDrawable, osgText::Text, and osgText::Text3D.
virtual bool osg::Drawable::supports (const PrimitiveFunctor &) const [inline, virtual]
Return true if the Drawable subclass supports accept(PrimitiveFunctor&).
Reimplemented in osg::Geometry, osg::ShapeDrawable, osgParticle::PrecipitationEffect::PrecipitationDrawable, osgSim::ImpostorSprite, osgText::Text, and osgText::Text3D.
virtual bool osg::Drawable::supports (const AttributeFunctor &) const [inline, virtual]
Return true if the Drawable subclass supports accept(AttributeFunctor&).
Reimplemented in osg::Geometry, osg::ShapeDrawable, osgText::Text, and osgText::Text3D.
Friends And Related Function Documentation
friend class Geode [friend]
friend class Node [friend]
friend class StateSet [friend]
Member Data Documentation
BoundingBox osg::Drawable::_boundingBox [mutable, protected]
bool osg::Drawable::_boundingBoxComputed [mutable, protected]
ref_ptr<ComputeBoundingBoxCallback> osg::Drawable::_computeBoundCallback [protected]
ref_ptr<CullCallback> osg::Drawable::_cullCallback [protected]
ref_ptr<DrawCallback> osg::Drawable::_drawCallback [protected]
Referenced by draw().
ref_ptr<EventCallback> osg::Drawable::_eventCallback [protected]
GLObjectList osg::Drawable::_globjList [mutable, protected]
Referenced by draw().
BoundingBox osg::Drawable::_initialBound [protected]
unsigned int osg::Drawable::_numChildrenRequiringEventTraversal [protected]
unsigned int osg::Drawable::_numChildrenRequiringUpdateTraversal [protected]
ParentList osg::Drawable::_parents [protected]
ref_ptr<Shape> osg::Drawable::_shape [protected]
ref_ptr<StateSet> osg::Drawable::_stateset [protected]
bool osg::Drawable::_supportsDisplayList [protected]
bool osg::Drawable::_supportsVertexBufferObjects [protected]
Referenced by draw().
ref_ptr<UpdateCallback> osg::Drawable::_updateCallback [protected]
bool osg::Drawable::_useDisplayList [protected]
Referenced by draw().
bool osg::Drawable::_useVertexBufferObjects [protected]
Referenced by draw().
unsigned int osg::Drawable::s_numberDeletedDrawablesInLastFrame [static]
unsigned int osg::Drawable::s_numberDrawablesReusedLastInLastFrame [static]
unsigned int osg::Drawable::s_numberNewDrawablesInLastFrame [static]
The documentation for this class was generated from the following file:
osg/Drawable
Generated at Thu Jun 9 2011 16:37:14 for the OpenSceneGraph by doxygen 1.7.1.