OpenSceneGraph: osgViewer::GraphicsWindowEmbedded Class Reference
osgViewer::GraphicsWindowEmbedded Class Reference
Public Member Functions
GraphicsWindowEmbedded (osg::GraphicsContext::Traits *traits=0)
GraphicsWindowEmbedded (int x, int y, int width, int height)
virtual bool isSameKindAs (const Object *object) const
virtual const char * libraryName () const
virtual const char * className () const
void init ()
virtual bool valid () const
Create a new mouse cursor from the usual bitmap data.
virtual bool realizeImplementation ()
Realize the GraphicsContext implementation, Pure virtual - must be implemented by concrete implementations of GraphicsContext.
virtual bool isRealizedImplementation () const
Return true if the graphics context has been realized, and is ready to use, implementation.
virtual void closeImplementation ()
Close the graphics context implementation.
virtual bool makeCurrentImplementation ()
Make this graphics context current implementation.
virtual bool releaseContextImplementation ()
Release the graphics context.
virtual void swapBuffersImplementation ()
Swap the front and back buffers implementation.
virtual void grabFocus ()
Get focus.
virtual void grabFocusIfPointerInWindow ()
Get focus on if the pointer is in this window.
virtual void raiseWindow ()
Raise the window to the top.
Constructor & Destructor Documentation
osgViewer::GraphicsWindowEmbedded::GraphicsWindowEmbedded (osg::GraphicsContext::Traits * traits = 0) [inline]
References osg::GraphicsContext::_traits, and init().
osgViewer::GraphicsWindowEmbedded::GraphicsWindowEmbedded (int x, int y, int width, int height) [inline]
References osg::GraphicsContext::_traits, and init().
Member Function Documentation
virtual const char* osgViewer::GraphicsWindowEmbedded::className () const [inline, virtual]
Reimplemented from osgViewer::GraphicsWindow.
virtual void osgViewer::GraphicsWindowEmbedded::closeImplementation () [inline, virtual]
Close the graphics context implementation.
Pure virtual - must be implemented by concrete implementations of GraphicsContext.
Reimplemented from osgViewer::GraphicsWindow.
virtual void osgViewer::GraphicsWindowEmbedded::grabFocus () [inline, virtual]
Get focus.
Reimplemented from osgViewer::GraphicsWindow.
virtual void osgViewer::GraphicsWindowEmbedded::grabFocusIfPointerInWindow () [inline, virtual]
Get focus on if the pointer is in this window.
Reimplemented from osgViewer::GraphicsWindow.
void osgViewer::GraphicsWindowEmbedded::init () [inline]
References osg::GraphicsContext::_traits, osg::GraphicsContext::createNewContextID(), osg::GraphicsContext::getState(), osg::GraphicsContext::incrementContextIDUsageCount(), osg::GraphicsContext::setState(), and valid().
Referenced by GraphicsWindowEmbedded().
virtual bool osgViewer::GraphicsWindowEmbedded::isRealizedImplementation () const [inline, virtual]
Return true if the graphics context has been realized, and is ready to use, implementation.
Pure virtual - must be implemented by concrete implementations of GraphicsContext.
Reimplemented from osgViewer::GraphicsWindow.
virtual bool osgViewer::GraphicsWindowEmbedded::isSameKindAs (const Object * object) const [inline, virtual]
Reimplemented from osgViewer::GraphicsWindow.
virtual const char* osgViewer::GraphicsWindowEmbedded::libraryName () const [inline, virtual]
Reimplemented from osgViewer::GraphicsWindow.
virtual bool osgViewer::GraphicsWindowEmbedded::makeCurrentImplementation () [inline, virtual]
Make this graphics context current implementation.
Pure virtual - must be implemented by concrete implementations of GraphicsContext.
Reimplemented from osgViewer::GraphicsWindow.
virtual void osgViewer::GraphicsWindowEmbedded::raiseWindow () [inline, virtual]
Raise the window to the top.
Reimplemented from osgViewer::GraphicsWindow.
virtual bool osgViewer::GraphicsWindowEmbedded::realizeImplementation () [inline, virtual]
Realize the GraphicsContext implementation, Pure virtual - must be implemented by concrete implementations of GraphicsContext.
Reimplemented from osgViewer::GraphicsWindow.
virtual bool osgViewer::GraphicsWindowEmbedded::releaseContextImplementation () [inline, virtual]
Release the graphics context.
Reimplemented from osgViewer::GraphicsWindow.
virtual void osgViewer::GraphicsWindowEmbedded::swapBuffersImplementation () [inline, virtual]
Swap the front and back buffers implementation.
Pure virtual - must be implemented by concrete implementations of GraphicsContext.
Reimplemented from osgViewer::GraphicsWindow.
virtual bool osgViewer::GraphicsWindowEmbedded::valid () const [inline, virtual]
Create a new mouse cursor from the usual bitmap data.
Return whether a valid and usable GraphicsContext has been created.
Reimplemented from osgViewer::GraphicsWindow.
Referenced by init().
The documentation for this class was generated from the following file:
osgViewer/GraphicsWindow
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.