OpenSceneGraph: osgGA::GUIEventHandler Class Reference
osgGA::GUIEventHandler Class Reference
GUIEventHandler provides a basic interface for any class which wants to handle a GUI Events.
Public Member Functions
GUIEventHandler ()
GUIEventHandler (const GUIEventHandler &eh, const osg::CopyOp &)
META_Object (osgGA, GUIEventHandler)
virtual void operator() (osg::Node *node, osg::NodeVisitor *nv)
Event traversal node callback method.
virtual void event (osg::NodeVisitor *nv, osg::Drawable *drawable)
Event traversal drawable callback method.
virtual bool handle (const GUIEventAdapter &ea, GUIActionAdapter &aa, osg::Object *, osg::NodeVisitor *)
Handle events, return true if handled, false otherwise.
bool handleWithCheckAgainstIgnoreHandledEventsMask (const GUIEventAdapter &ea, GUIActionAdapter &aa, osg::Object *object, osg::NodeVisitor *nv)
Convenience method that only passes on to the handle(,,,) method events that either haven't been handled yet, or have been handled but haven't be set to be ignored by the IgnoreHandledEventsMask.
virtual bool handle (const GUIEventAdapter &, GUIActionAdapter &)
Deprecated, Handle events, return true if handled, false otherwise.
bool handleWithCheckAgainstIgnoreHandledEventsMask (const GUIEventAdapter &ea, GUIActionAdapter &aa)
Convenience method that only passes on to the handle(,) method events that either haven't been handled yet, or have been handled but haven't be set to be ignored by the IgnoreHandledEventsMask.
virtual void getUsage (osg::ApplicationUsage &) const
Get the keyboard and mouse usage of this manipulator.
void setIgnoreHandledEventsMask (unsigned int mask)
Set a mask of osgGA::GUIEeventAdapter::Event to be ignored if marked as handled.
unsigned int getIgnoreHandledEventsMask () const
Get the event mask of the osgGA::GUIEeventAdapter::Event to be ignored if marked as handled.
Protected Attributes
unsigned int _ignoreHandledEventsMask
Detailed Description
GUIEventHandler provides a basic interface for any class which wants to handle a GUI Events.
The GUIEvent is supplied by a GUIEventAdapter. Feedback resulting from the handle method is supplied by a GUIActionAdapter, which allows the GUIEventHandler to ask the GUI to take some action in response to an incoming event.
For example, consider a Trackball Viewer class which takes mouse events and manipulates a scene camera in response. The Trackball Viewer is a GUIEventHandler, and receives the events via the handle method. If the user 'throws' the model, the Trackball Viewer class can detect this via the incoming events, and request that the GUI set up a timer callback to continually redraw the view. This request is made via the GUIActionAdapter class.
Constructor & Destructor Documentation
osgGA::GUIEventHandler::GUIEventHandler () [inline]
osgGA::GUIEventHandler::GUIEventHandler (const GUIEventHandler & eh, const osg::CopyOp &) [inline]
Member Function Documentation
virtual void osgGA::GUIEventHandler::event (osg::NodeVisitor * nv, osg::Drawable * drawable) [virtual]
Event traversal drawable callback method.
Reimplemented from osg::Drawable::EventCallback.
unsigned int osgGA::GUIEventHandler::getIgnoreHandledEventsMask () const [inline]
Get the event mask of the osgGA::GUIEeventAdapter::Event to be ignored if marked as handled.
virtual void osgGA::GUIEventHandler::getUsage (osg::ApplicationUsage &) const [inline, virtual]
Get the keyboard and mouse usage of this manipulator.
Reimplemented in osgGA::AnimationPathManipulator, osgGA::CameraViewSwitchManipulator, osgGA::DriveManipulator, osgGA::FlightManipulator, osgGA::KeySwitchMatrixManipulator, osgGA::NodeTrackerManipulator, osgGA::StateSetManipulator, osgGA::TerrainManipulator, osgGA::TrackballManipulator, osgGA::UFOManipulator, osgViewer::HelpHandler, osgViewer::StatsHandler, osgViewer::WindowSizeHandler, osgViewer::ThreadingHandler, osgViewer::RecordCameraPathHandler, osgViewer::LODScaleHandler, osgViewer::ScreenCaptureHandler, and osgAnimation::StatsHandler.
virtual bool osgGA::GUIEventHandler::handle (const GUIEventAdapter & ea, GUIActionAdapter & aa, osg::Object * , osg::NodeVisitor *) [inline, virtual]
Handle events, return true if handled, false otherwise.
Reimplemented in osgWidget::MouseHandler, osgWidget::KeyboardHandler, osgWidget::ResizeHandler, and osgWidget::CameraSwitchHandler.
References handle().
Referenced by handle().
virtual bool osgGA::GUIEventHandler::handle (const GUIEventAdapter & , GUIActionAdapter &) [inline, virtual]
Deprecated, Handle events, return true if handled, false otherwise.
Reimplemented in osgGA::AnimationPathManipulator, osgGA::CameraViewSwitchManipulator, osgGA::DriveManipulator, osgGA::FlightManipulator, osgGA::KeySwitchMatrixManipulator, osgGA::MatrixManipulator, osgGA::NodeTrackerManipulator, osgGA::StateSetManipulator, osgGA::TerrainManipulator, osgGA::TrackballManipulator, osgGA::UFOManipulator, osgViewer::HelpHandler, osgViewer::StatsHandler, osgViewer::WindowSizeHandler, osgViewer::ThreadingHandler, osgViewer::RecordCameraPathHandler, osgViewer::LODScaleHandler, osgViewer::ScreenCaptureHandler, and osgAnimation::StatsHandler.
bool osgGA::GUIEventHandler::handleWithCheckAgainstIgnoreHandledEventsMask (const GUIEventAdapter & ea, GUIActionAdapter & aa, osg::Object * object, osg::NodeVisitor * nv) [inline]
Convenience method that only passes on to the handle(,,,) method events that either haven't been handled yet, or have been handled but haven't be set to be ignored by the IgnoreHandledEventsMask.
Note, this method is an inline method, and not appropriate for users to override, override the handle(,,,) method instead.
References osgGA::GUIEventAdapter::getEventType(), osgGA::GUIEventAdapter::getHandled(), and osgGA::GUIEventAdapter::setHandled().
bool osgGA::GUIEventHandler::handleWithCheckAgainstIgnoreHandledEventsMask (const GUIEventAdapter & ea, GUIActionAdapter & aa) [inline]
Convenience method that only passes on to the handle(,) method events that either haven't been handled yet, or have been handled but haven't be set to be ignored by the IgnoreHandledEventsMask.
Note, this method is an inline method, and not appropriate for users to override, override the handle(,) method instead.
References osgGA::GUIEventAdapter::getEventType(), osgGA::GUIEventAdapter::getHandled(), and osgGA::GUIEventAdapter::setHandled().
osgGA::GUIEventHandler::META_Object (osgGA , GUIEventHandler)
virtual void osgGA::GUIEventHandler::operator() (osg::Node * node, osg::NodeVisitor * nv) [virtual]
Event traversal node callback method.
void osgGA::GUIEventHandler::setIgnoreHandledEventsMask (unsigned int mask) [inline]
Set a mask of osgGA::GUIEeventAdapter::Event to be ignored if marked as handled.
Member Data Documentation
unsigned int osgGA::GUIEventHandler::_ignoreHandledEventsMask [protected]
The documentation for this class was generated from the following file:
osgGA/GUIEventHandler
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.