OpenSceneGraph: osgAnimation::Motion Class Reference
osgAnimation::Motion Class Reference
Public Types
enum TimeBehaviour { CLAMP, LOOP }
typedef float value_type
Public Member Functions
Motion (float startValue=0, float duration=1, float changeValue=1, TimeBehaviour tb=CLAMP)
virtual ~Motion ()
void reset ()
float getTime () const
float evaluateTime (float time) const
void update (float dt)
void setTime (float time)
void getValue (value_type &result) const
value_type getValue () const
void getValueAt (float time, value_type &result) const
value_type getValueAt (float time) const
virtual void getValueInNormalizedRange (float t, value_type &result) const =0
float getDuration () const
Protected Attributes
float _time
float _startValue
float _changeValue
float _duration
TimeBehaviour _behaviour
Member Typedef Documentation
typedef float osgAnimation::Motion::value_type
Member Enumeration Documentation
enum osgAnimation::Motion::TimeBehaviour
Enumerator:
CLAMP
LOOP
Constructor & Destructor Documentation
osgAnimation::Motion::Motion (float startValue = 0, float duration = 1, float changeValue = 1, TimeBehaviour tb = CLAMP) [inline]
virtual osgAnimation::Motion::~Motion () [inline, virtual]
Member Function Documentation
float osgAnimation::Motion::evaluateTime (float time) const [inline]
References _behaviour, _duration, CLAMP, and LOOP.
Referenced by getValueAt(), setTime(), and update().
float osgAnimation::Motion::getDuration () const [inline]
References _duration.
Referenced by osgAnimation::CompositeMotion::getValueInNormalizedRange().
float osgAnimation::Motion::getTime () const [inline]
References _time.
void osgAnimation::Motion::getValue (value_type & result) const [inline]
References _time, and getValueAt().
value_type osgAnimation::Motion::getValue () const [inline]
References _time, and getValueAt().
value_type osgAnimation::Motion::getValueAt (float time) const [inline]
References evaluateTime(), and getValueAt().
void osgAnimation::Motion::getValueAt (float time, value_type & result) const [inline]
References _changeValue, _duration, _startValue, evaluateTime(), and getValueInNormalizedRange().
Referenced by getValue(), getValueAt(), osgAnimation::CompositeMotion::getValueInNormalizedRange(), and osgAnimation::MathMotionTemplate< T >::getValueInNormalizedRange().
virtual void osgAnimation::Motion::getValueInNormalizedRange (float t, value_type & result) const [pure virtual]
Implemented in osgAnimation::MathMotionTemplate< T >, osgAnimation::SamplerMotionTemplate< T >, and osgAnimation::CompositeMotion.
Referenced by getValueAt().
void osgAnimation::Motion::reset () [inline]
References setTime().
void osgAnimation::Motion::setTime (float time) [inline]
References _time, and evaluateTime().
Referenced by reset().
void osgAnimation::Motion::update (float dt) [inline]
References _time, and evaluateTime().
Member Data Documentation
TimeBehaviour osgAnimation::Motion::_behaviour [protected]
Referenced by evaluateTime().
float osgAnimation::Motion::_changeValue [protected]
Referenced by getValueAt().
float osgAnimation::Motion::_duration [protected]
Referenced by evaluateTime(), getDuration(), and getValueAt().
float osgAnimation::Motion::_startValue [protected]
Referenced by getValueAt().
float osgAnimation::Motion::_time [protected]
Referenced by getTime(), getValue(), setTime(), and update().
The documentation for this class was generated from the following file:
osgAnimation/EaseMotion
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.