OpenSceneGraph: osgManipulator::PointerInfo Class Reference
osgManipulator::PointerInfo Class Reference
Public Types
typedef std::pair
< osg::NodePath, osg::Vec3d > NodePathIntersectionPair
typedef std::list
< NodePathIntersectionPair > IntersectionList
Public Member Functions
PointerInfo ()
PointerInfo (const PointerInfo &rhs)
void reset ()
bool completed () const
void next ()
osg::Vec3d getLocalIntersectPoint () const
void setNearFarPoints (osg::Vec3d nearPoint, osg::Vec3d farPoint)
const osg::Vec3d & getEyeDir () const
void getNearFarPoints (osg::Vec3d &nearPoint, osg::Vec3d &farPoint) const
bool contains (const osg::Node *node) const
void setCamera (osg::Camera *camera)
void addIntersection (const osg::NodePath &nodePath, const osg::Vec3d &intersectionPoint)
void setMousePosition (float pixel_x, float pixel_y)
Public Attributes
IntersectionList _hitList
IntersectionList::const_iterator _hitIter
Protected Member Functions
bool projectWindowXYIntoObject (const osg::Vec2d &windowCoord, osg::Vec3d &nearPoint, osg::Vec3d &farPoint) const
Protected Attributes
osg::Vec3d _nearPoint
osg::Vec3d _farPoint
osg::Vec3d _eyeDir
osg::Matrix _MVPW
osg::Matrix _inverseMVPW
Member Typedef Documentation
typedef std::list< NodePathIntersectionPair> osgManipulator::PointerInfo::IntersectionList
typedef std::pair<osg::NodePath, osg::Vec3d> osgManipulator::PointerInfo::NodePathIntersectionPair
Constructor & Destructor Documentation
osgManipulator::PointerInfo::PointerInfo ()
osgManipulator::PointerInfo::PointerInfo (const PointerInfo & rhs) [inline]
Member Function Documentation
void osgManipulator::PointerInfo::addIntersection (const osg::NodePath & nodePath, const osg::Vec3d & intersectionPoint) [inline]
bool osgManipulator::PointerInfo::completed () const [inline]
bool osgManipulator::PointerInfo::contains (const osg::Node * node) const
const osg::Vec3d& osgManipulator::PointerInfo::getEyeDir () const [inline]
osg::Vec3d osgManipulator::PointerInfo::getLocalIntersectPoint () const [inline]
void osgManipulator::PointerInfo::getNearFarPoints (osg::Vec3d & nearPoint, osg::Vec3d & farPoint) const [inline]
void osgManipulator::PointerInfo::next () [inline]
bool osgManipulator::PointerInfo::projectWindowXYIntoObject (const osg::Vec2d & windowCoord, osg::Vec3d & nearPoint, osg::Vec3d & farPoint) const [protected]
void osgManipulator::PointerInfo::reset () [inline]
void osgManipulator::PointerInfo::setCamera (osg::Camera * camera) [inline]
References osg::Matrixd::getLookAt(), osg::Camera::getProjectionMatrix(), osg::Camera::getViewMatrix(), osg::Camera::getViewport(), and osg::Matrixd::postMult().
void osgManipulator::PointerInfo::setMousePosition (float pixel_x, float pixel_y) [inline]
void osgManipulator::PointerInfo::setNearFarPoints (osg::Vec3d nearPoint, osg::Vec3d farPoint) [inline]
Member Data Documentation
osg::Vec3d osgManipulator::PointerInfo::_eyeDir [protected]
osg::Vec3d osgManipulator::PointerInfo::_farPoint [protected]
IntersectionList::const_iterator osgManipulator::PointerInfo::_hitIter
IntersectionList osgManipulator::PointerInfo::_hitList
osg::Matrix osgManipulator::PointerInfo::_inverseMVPW [protected]
osg::Matrix osgManipulator::PointerInfo::_MVPW [protected]
osg::Vec3d osgManipulator::PointerInfo::_nearPoint [protected]
The documentation for this class was generated from the following file:
osgManipulator/Dragger
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.