OpenSceneGraph: osgVolume::ScalarProperty Class Reference
osgVolume::ScalarProperty Class Reference
Public Member Functions
ScalarProperty (const std::string &scaleName, float value)
ScalarProperty (const ScalarProperty &scalarProperty, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgVolume, ScalarProperty)
virtual void accept (PropertyVisitor &pv)
virtual void setValue (float v)
Set the value.
float getValue () const
Get the value.
osg::Uniform * getUniform ()
Get the underlying uniform.
const osg::Uniform * getUniform () const
Get the underlying uniform.
Protected Member Functions
virtual ~ScalarProperty ()
ScalarProperty ()
Protected Attributes
osg::ref_ptr< osg::Uniform > _uniform
Constructor & Destructor Documentation
osgVolume::ScalarProperty::ScalarProperty (const std::string & scaleName, float value)
osgVolume::ScalarProperty::ScalarProperty (const ScalarProperty & scalarProperty, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY)
virtual osgVolume::ScalarProperty::~ScalarProperty () [inline, protected, virtual]
osgVolume::ScalarProperty::ScalarProperty () [protected]
Member Function Documentation
virtual void osgVolume::ScalarProperty::accept (PropertyVisitor & pv) [inline, virtual]
Reimplemented from osgVolume::Property.
Reimplemented in osgVolume::IsoSurfaceProperty, osgVolume::AlphaFuncProperty, osgVolume::SampleDensityProperty, and osgVolume::TransparencyProperty.
References osgVolume::PropertyVisitor::apply().
osg::Uniform* osgVolume::ScalarProperty::getUniform () [inline]
Get the underlying uniform.
References osg::Uniform::get().
const osg::Uniform* osgVolume::ScalarProperty::getUniform () const [inline]
Get the underlying uniform.
References osg::Uniform::get().
float osgVolume::ScalarProperty::getValue () const [inline]
Get the value.
osgVolume::ScalarProperty::META_Object (osgVolume , ScalarProperty)
virtual void osgVolume::ScalarProperty::setValue (float v) [inline, virtual]
Set the value.
Reimplemented in osgVolume::AlphaFuncProperty.
Member Data Documentation
osg::ref_ptr<osg::Uniform> osgVolume::ScalarProperty::_uniform [protected]
The documentation for this class was generated from the following file:
osgVolume/Property
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.