OpenSceneGraph: osgUtil::RegisterRenderBinProxy Class Reference
osgUtil::RegisterRenderBinProxy Class Reference
Proxy class for automatic registration of renderbins with the RenderBin prototypelist.
Public Member Functions
RegisterRenderBinProxy (const std::string &binName, RenderBin *proto)
~RegisterRenderBinProxy ()
Protected Attributes
osg::ref_ptr< RenderBin > _rb
Detailed Description
Proxy class for automatic registration of renderbins with the RenderBin prototypelist.
Constructor & Destructor Documentation
osgUtil::RegisterRenderBinProxy::RegisterRenderBinProxy (const std::string & binName, RenderBin * proto) [inline]
References _rb, osgUtil::RenderBin::addRenderBinPrototype(), and osg::ref_ptr< T >::get().
osgUtil::RegisterRenderBinProxy::~RegisterRenderBinProxy () [inline]
References _rb, osg::ref_ptr< T >::get(), and osgUtil::RenderBin::removeRenderBinPrototype().
Member Data Documentation
osg::ref_ptr<RenderBin> osgUtil::RegisterRenderBinProxy::_rb [protected]
Referenced by RegisterRenderBinProxy(), and ~RegisterRenderBinProxy().
The documentation for this class was generated from the following file:
osgUtil/RenderBin
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.