OpenSceneGraph: osgIntrospection::ReaderWriter Class Reference
osgIntrospection::ReaderWriter Class Reference
This is the base class for reader/writer objects.
Classes
class Options
Public Member Functions
virtual std::ostream & writeTextValue (std::ostream &, const Value &v, const Options *=0) const
Writes a textual representation of the value's content to a stream.
virtual std::istream & readTextValue (std::istream &, Value &v, const Options *=0) const
Reads a textual representation of the value's content from a stream.
virtual std::wostream & writeTextValue (std::wostream &wos, const Value &v, const Options *op=0) const
Writes a textual representation of the value's content to a stream.
virtual std::wistream & readTextValue (std::wistream &, Value &v, const Options *=0) const
Reads a textual representation of the value's content from a stream.
virtual std::ostream & writeBinaryValue (std::ostream &, const Value &v, const Options *=0) const
Writes a binary representation of the value's content to a stream.
virtual std::istream & readBinaryValue (std::istream &, Value &v, const Options *=0) const
Reads a binary representation of the value's content from a stream.
virtual ~ReaderWriter ()
Virtual destructor.
Detailed Description
This is the base class for reader/writer objects.
A ReaderWriter's purpose is to provide the means for writing the content of a Value object to a stream and for reading it back. Descendants can either be specialized for just one data type or they can handle several types, that's up to the implementor. A derived class is not required to support all streaming operations (text write, text read, bin write and bin read), it can implement just some of them, although full support is strongly encouraged.
Constructor & Destructor Documentation
virtual osgIntrospection::ReaderWriter::~ReaderWriter () [inline, virtual]
Virtual destructor.
Member Function Documentation
virtual std::istream& osgIntrospection::ReaderWriter::readBinaryValue (std::istream & , Value & v, const Options * = 0) const [inline, virtual]
Reads a binary representation of the value's content from a stream.
Reimplemented in osgIntrospection::StdReaderWriter< T >, osgIntrospection::StdWReaderWriter< T >, and osgIntrospection::PtrReaderWriter< T >.
References osgIntrospection::StreamingNotSupportedException::BINARY_READ, osgIntrospection::Type::getExtendedTypeInfo(), and osgIntrospection::Value::getType().
virtual std::wistream& osgIntrospection::ReaderWriter::readTextValue (std::wistream & , Value & v, const Options * = 0) const [inline, virtual]
Reads a textual representation of the value's content from a stream.
Reimplemented in osgIntrospection::StdWReaderWriter< T >.
References osgIntrospection::Type::getExtendedTypeInfo(), osgIntrospection::Value::getType(), and osgIntrospection::StreamingNotSupportedException::TEXT_READ.
virtual std::istream& osgIntrospection::ReaderWriter::readTextValue (std::istream & , Value & v, const Options * = 0) const [inline, virtual]
Reads a textual representation of the value's content from a stream.
Reimplemented in osgIntrospection::StdReaderWriter< T >, and osgIntrospection::PtrReaderWriter< T >.
References osgIntrospection::Type::getExtendedTypeInfo(), osgIntrospection::Value::getType(), and osgIntrospection::StreamingNotSupportedException::TEXT_READ.
virtual std::ostream& osgIntrospection::ReaderWriter::writeBinaryValue (std::ostream & , const Value & v, const Options * = 0) const [inline, virtual]
Writes a binary representation of the value's content to a stream.
Reimplemented in osgIntrospection::StdReaderWriter< T >, osgIntrospection::StdWReaderWriter< T >, and osgIntrospection::PtrReaderWriter< T >.
References osgIntrospection::StreamingNotSupportedException::BINARY_WRITE, osgIntrospection::Type::getExtendedTypeInfo(), and osgIntrospection::Value::getType().
virtual std::wostream& osgIntrospection::ReaderWriter::writeTextValue (std::wostream & wos, const Value & v, const Options * op = 0) const [inline, virtual]
Writes a textual representation of the value's content to a stream.
Reimplemented in osgIntrospection::StdWReaderWriter< T >.
References writeTextValue().
Referenced by writeTextValue().
virtual std::ostream& osgIntrospection::ReaderWriter::writeTextValue (std::ostream & , const Value & v, const Options * = 0) const [inline, virtual]
Writes a textual representation of the value's content to a stream.
Reimplemented in osgIntrospection::StdReaderWriter< T >, and osgIntrospection::PtrReaderWriter< T >.
References osgIntrospection::Type::getExtendedTypeInfo(), osgIntrospection::Value::getType(), and osgIntrospection::StreamingNotSupportedException::TEXT_WRITE.
The documentation for this class was generated from the following file:
osgIntrospection/ReaderWriter
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.