OpenSceneGraph: osgAnimation::TemplateTarget< T > Class Template Reference
osgAnimation::TemplateTarget< T > Class Template Reference
Public Member Functions
TemplateTarget ()
TemplateTarget (const T &v)
TemplateTarget (const TemplateTarget &v)
void lerp (float t, const T &a, const T &b)
void update (float weight, const T &val, int priority)
The priority is used to detect a change of priority It's important to update animation target in priority order.
const T & getValue () const
void setValue (const T &value)
template<>
void lerp (float t, const osg::Quat &a, const osg::Quat &b)
Protected Attributes
T _target
template<class T>
class osgAnimation::TemplateTarget< T >
Constructor & Destructor Documentation
template<class T > osgAnimation::TemplateTarget< T >::TemplateTarget () [inline]
template<class T > osgAnimation::TemplateTarget< T >::TemplateTarget (const T & v) [inline]
References osgAnimation::TemplateTarget< T >::setValue().
template<class T > osgAnimation::TemplateTarget< T >::TemplateTarget (const TemplateTarget< T > & v) [inline]
References osgAnimation::TemplateTarget< T >::getValue(), and osgAnimation::TemplateTarget< T >::setValue().
Member Function Documentation
template<class T > const T& osgAnimation::TemplateTarget< T >::getValue () const [inline]
References osgAnimation::TemplateTarget< T >::_target.
Referenced by osgAnimation::TemplateTarget< T >::TemplateTarget().
template<> void osgAnimation::TemplateTarget< osg::Quat >::lerp (float t, const osg::Quat & a, const osg::Quat & b) [inline]
References osgAnimation::TemplateTarget< T >::_target, and osg::Quat::asVec4().
template<class T > void osgAnimation::TemplateTarget< T >::lerp (float t, const T & a, const T & b) [inline]
References osgAnimation::TemplateTarget< T >::_target.
Referenced by osgAnimation::TemplateTarget< T >::update().
template<class T > void osgAnimation::TemplateTarget< T >::setValue (const T & value) [inline]
References osgAnimation::TemplateTarget< T >::_target.
Referenced by osgAnimation::TemplateTarget< T >::TemplateTarget().
template<class T > void osgAnimation::TemplateTarget< T >::update (float weight, const T & val, int priority) [inline]
The priority is used to detect a change of priority It's important to update animation target in priority order.
eg: all animation with priority 1 all animation with priority 0 all animation with priority -1 ...
References osgAnimation::Target::_lastPriority, osgAnimation::Target::_priorityWeight, osgAnimation::TemplateTarget< T >::_target, osgAnimation::Target::_weight, and osgAnimation::TemplateTarget< T >::lerp().
Member Data Documentation
template<class T > T osgAnimation::TemplateTarget< T >::_target [protected]
Referenced by osgAnimation::TemplateTarget< T >::getValue(), osgAnimation::TemplateTarget< T >::lerp(), osgAnimation::TemplateTarget< T >::setValue(), and osgAnimation::TemplateTarget< T >::update().
The documentation for this class was generated from the following file:
osgAnimation/Target
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.