OpenSceneGraph: osgAnimation::TemplateSampler< F > Class Template Reference
osgAnimation::TemplateSampler< F > Class Template Reference
Public Types
typedef F::KeyframeType KeyframeType
typedef
TemplateKeyframeContainer
< KeyframeType > KeyframeContainerType
typedef F::UsingType UsingType
typedef F FunctorType
Public Member Functions
TemplateSampler ()
~TemplateSampler ()
void getValueAt (float time, UsingType &result) const
void setKeyframeContainer (KeyframeContainerType *kf)
virtual KeyframeContainer * getKeyframeContainer ()
virtual const KeyframeContainer * getKeyframeContainer () const
KeyframeContainerType * getKeyframeContainerTyped ()
const KeyframeContainerType * getKeyframeContainerTyped () const
KeyframeContainerType * getOrCreateKeyframeContainer ()
float getStartTime () const
float getEndTime () const
Protected Attributes
FunctorType _functor
osg::ref_ptr
< KeyframeContainerType > _keyframes
template<class F>
class osgAnimation::TemplateSampler< F >
Member Typedef Documentation
template<class F > typedef F osgAnimation::TemplateSampler< F >::FunctorType
template<class F > typedef TemplateKeyframeContainer<KeyframeType> osgAnimation::TemplateSampler< F >::KeyframeContainerType
template<class F > typedef F::KeyframeType osgAnimation::TemplateSampler< F >::KeyframeType
template<class F > typedef F::UsingType osgAnimation::TemplateSampler< F >::UsingType
Constructor & Destructor Documentation
template<class F > osgAnimation::TemplateSampler< F >::TemplateSampler () [inline]
template<class F > osgAnimation::TemplateSampler< F >::~TemplateSampler () [inline]
Member Function Documentation
template<class F > float osgAnimation::TemplateSampler< F >::getEndTime () const [inline]
References osgAnimation::TemplateSampler< F >::_keyframes.
template<class F > virtual KeyframeContainer* osgAnimation::TemplateSampler< F >::getKeyframeContainer () [inline, virtual]
Implements osgAnimation::Sampler.
References osgAnimation::TemplateSampler< F >::_keyframes, and osg::ref_ptr< T >::get().
template<class F > virtual const KeyframeContainer* osgAnimation::TemplateSampler< F >::getKeyframeContainer () const [inline, virtual]
Implements osgAnimation::Sampler.
References osgAnimation::TemplateSampler< F >::_keyframes, and osg::ref_ptr< T >::get().
template<class F > KeyframeContainerType* osgAnimation::TemplateSampler< F >::getKeyframeContainerTyped () [inline]
References osgAnimation::TemplateSampler< F >::_keyframes, and osg::ref_ptr< T >::get().
template<class F > const KeyframeContainerType* osgAnimation::TemplateSampler< F >::getKeyframeContainerTyped () const [inline]
References osgAnimation::TemplateSampler< F >::_keyframes, and osg::ref_ptr< T >::get().
template<class F > KeyframeContainerType* osgAnimation::TemplateSampler< F >::getOrCreateKeyframeContainer () [inline]
References osgAnimation::TemplateSampler< F >::_keyframes, and osg::ref_ptr< T >::get().
template<class F > float osgAnimation::TemplateSampler< F >::getStartTime () const [inline]
References osgAnimation::TemplateSampler< F >::_keyframes.
template<class F > void osgAnimation::TemplateSampler< F >::getValueAt (float time, UsingType & result) const [inline]
References osgAnimation::TemplateSampler< F >::_functor, and osgAnimation::TemplateSampler< F >::_keyframes.
template<class F > void osgAnimation::TemplateSampler< F >::setKeyframeContainer (KeyframeContainerType * kf) [inline]
References osgAnimation::TemplateSampler< F >::_keyframes.
Member Data Documentation
template<class F > FunctorType osgAnimation::TemplateSampler< F >::_functor [protected]
Referenced by osgAnimation::TemplateSampler< F >::getValueAt().
template<class F > osg::ref_ptr<KeyframeContainerType> osgAnimation::TemplateSampler< F >::_keyframes [protected]
Referenced by osgAnimation::TemplateSampler< F >::getEndTime(), osgAnimation::TemplateSampler< F >::getKeyframeContainer(), osgAnimation::TemplateSampler< F >::getKeyframeContainerTyped(), osgAnimation::TemplateSampler< F >::getOrCreateKeyframeContainer(), osgAnimation::TemplateSampler< F >::getStartTime(), osgAnimation::TemplateSampler< F >::getValueAt(), and osgAnimation::TemplateSampler< F >::setKeyframeContainer().
The documentation for this class was generated from the following file:
osgAnimation/Sampler
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.