OpenSceneGraph: osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 > Class Template Reference
osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 > Class Template Reference
Public Types
typedef void(C::* ConstFunctionType)(P0, P1, P2) const
typedef void(C::* FunctionType)(P0, P1, P2)
Public Member Functions
TypedMethodInfo3 (const std::string &qname, ConstFunctionType cf, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
TypedMethodInfo3 (const std::string &qname, FunctionType f, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
bool isConst () const
Returns whether the reflected method is const or not.
bool isStatic () const
Returns whether the reflected method is static or not.
Value invoke (const Value &instance, ValueList &args) const
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Value invoke (Value &instance, ValueList &args) const
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
template<typename C, typename P0, typename P1, typename P2>
class osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >
Member Typedef Documentation
template<typename C , typename P0 , typename P1 , typename P2 > typedef void(C::* osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::ConstFunctionType)(P0, P1, P2) const
template<typename C , typename P0 , typename P1 , typename P2 > typedef void(C::* osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::FunctionType)(P0, P1, P2)
Constructor & Destructor Documentation
template<typename C , typename P0 , typename P1 , typename P2 > osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::TypedMethodInfo3 (const std::string & qname, ConstFunctionType cf, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
template<typename C , typename P0 , typename P1 , typename P2 > osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::TypedMethodInfo3 (const std::string & qname, FunctionType f, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
Member Function Documentation
template<typename C , typename P0 , typename P1 , typename P2 > Value osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::invoke (const Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
References osgIntrospection::MethodInfo::getParameters(), osgIntrospection::Value::getType(), and osgIntrospection::variant_cast().
template<typename C , typename P0 , typename P1 , typename P2 > Value osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::invoke (Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
References osgIntrospection::MethodInfo::getParameters(), osgIntrospection::Value::getType(), and osgIntrospection::variant_cast().
template<typename C , typename P0 , typename P1 , typename P2 > bool osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::isConst () const [inline, virtual]
Returns whether the reflected method is const or not.
Implements osgIntrospection::MethodInfo.
template<typename C , typename P0 , typename P1 , typename P2 > bool osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::isStatic () const [inline, virtual]
Returns whether the reflected method is static or not.
Implements osgIntrospection::MethodInfo.
The documentation for this class was generated from the following file:
osgIntrospection/TypedMethodInfo
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.