OpenSceneGraph: osgDB::Vec4Serializer< C > Class Template Reference
osgDB::Vec4Serializer< C > Class Template Reference
Public Types
typedef osg::Vec4 V
typedef const V & P
typedef P(C::* GetterFunctionType)() const
typedef void(C::* SetterFunctionType)(P)
Public Member Functions
Vec4Serializer (const char *fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter)
bool write (osgDB::Output &fw, const osg::Object &obj)
bool read (osgDB::Input &fr, osg::Object &obj, bool &itrAdvanced)
Public Attributes
std::string _fieldName
V _default
GetterFunctionType _getter
SetterFunctionType _setter
template<typename C>
class osgDB::Vec4Serializer< C >
Member Typedef Documentation
template<typename C > typedef P(C::* osgDB::Vec4Serializer< C >::GetterFunctionType)() const
template<typename C > typedef const V& osgDB::Vec4Serializer< C >::P
template<typename C > typedef void(C::* osgDB::Vec4Serializer< C >::SetterFunctionType)(P)
template<typename C > typedef osg::Vec4 osgDB::Vec4Serializer< C >::V
Constructor & Destructor Documentation
template<typename C > osgDB::Vec4Serializer< C >::Vec4Serializer (const char * fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter) [inline]
Member Function Documentation
template<typename C > bool osgDB::Vec4Serializer< C >::read (osgDB::Input & fr, osg::Object & obj, bool & itrAdvanced) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::Vec4Serializer< C >::_fieldName, osgDB::Vec4Serializer< C >::_setter, and osgDB::Input::read().
template<typename C > bool osgDB::Vec4Serializer< C >::write (osgDB::Output & fw, const osg::Object & obj) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::Vec4Serializer< C >::_default, osgDB::Vec4Serializer< C >::_fieldName, osgDB::Vec4Serializer< C >::_getter, osgDB::Output::getWriteOutDefaultValues(), and osgDB::Output::indent().
Member Data Documentation
template<typename C > V osgDB::Vec4Serializer< C >::_default
Referenced by osgDB::Vec4Serializer< C >::write().
template<typename C > std::string osgDB::Vec4Serializer< C >::_fieldName
Referenced by osgDB::Vec4Serializer< C >::read(), and osgDB::Vec4Serializer< C >::write().
template<typename C > GetterFunctionType osgDB::Vec4Serializer< C >::_getter
Referenced by osgDB::Vec4Serializer< C >::write().
template<typename C > SetterFunctionType osgDB::Vec4Serializer< C >::_setter
Referenced by osgDB::Vec4Serializer< C >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.