OpenSceneGraph: osgAnimation::Vec3ArrayPacked Struct Reference
osgAnimation::Vec3ArrayPacked Struct Reference
Public Member Functions
void analyze (const std::vector< osg::Vec3 > &src)
void compress (const std::vector< osg::Vec3 > &src)
Public Attributes
std::vector< Vec3Packed > mVecCompressed
osg::Vec3 mMin
osg::Vec3 mScale
osg::Vec3 mScaleInv
Member Function Documentation
void osgAnimation::Vec3ArrayPacked::analyze (const std::vector< osg::Vec3 > & src) [inline]
References osg::maximum(), osg::minimum(), mMin, mScale, mScaleInv, and osg::Vec3f::set().
void osgAnimation::Vec3ArrayPacked::compress (const std::vector< osg::Vec3 > & src) [inline]
References mMin, mScaleInv, and mVecCompressed.
Member Data Documentation
osg::Vec3 osgAnimation::Vec3ArrayPacked::mMin
Referenced by analyze(), and compress().
osg::Vec3 osgAnimation::Vec3ArrayPacked::mScale
Referenced by analyze().
osg::Vec3 osgAnimation::Vec3ArrayPacked::mScaleInv
Referenced by analyze(), and compress().
std::vector<Vec3Packed> osgAnimation::Vec3ArrayPacked::mVecCompressed
Referenced by compress().
The documentation for this struct was generated from the following file:
osgAnimation/Vec3Packed
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.