OpenSceneGraph: osgWidget::WindowManager Class Reference
osgWidget::WindowManager Class Reference
Classes
struct WindowBinNumberCompare
struct WindowZCompare
Public Types
enum WmFlags { WM_USE_LUA = 0x00000001, WM_USE_PYTHON = 0x00000002, WM_USE_RENDERBINS = 0x00000004, WM_PICK_DEBUG = 0x00000008 }
enum PointerDirection {
PD_NONE = 0x00000000, PD_LEFT = 0x00000001, PD_RIGHT = 0x00000002, PD_UP = 0x00000004,
PD_DOWN = 0x00000008
}
enum PointerFocusMode { PFM_FOCUS = 0x00000000, PFM_UNFOCUS = 0x00000001, PFM_SLOPPY = 0x00000002 }
Public Member Functions
META_Object (osgWidget, WindowManager)
WindowManager (osgViewer::View *=0, point_type=0.0f, point_type=0.0f, unsigned int=0, unsigned int=0)
WindowManager (const WindowManager &, const osg::CopyOp &)
virtual ~WindowManager ()
bool pickAtXY (float, float, WidgetList &)
bool setFocused (Window *)
void setPointerXY (float, float)
void setStyleManager (StyleManager *)
void resizeAllWindows (bool=true)
XYCoord windowXY (double, double) const
XYCoord localXY (double, double) const
bool pointerMove (float, float)
bool pointerDrag (float, float)
bool mouseScroll (float, float)
osg::Camera * createParentOrthoCamera ()
unsigned int getNodeMask () const
point_type getWidth () const
point_type getHeight () const
bool isUsingLua () const
bool isUsingPython () const
bool isUsingRenderBins () const
int getMouseKeysDown () const
ScriptEngine * getLuaEngine ()
const ScriptEngine * getLuaEngine () const
ScriptEngine * getPythonEngine ()
const ScriptEngine * getPythonEngine () const
StyleManager * getStyleManager ()
const StyleManager * getStyleManager () const
PointerDirection getPointerVerticalDirection () const
PointerDirection getPointerHorizontalDirection () const
PointerFocusMode getPointerFocusMode () const
int getPointerDirectionVector () const
bool isPointerMovingUp () const
bool isPointerMovingDown () const
bool isPointerMovingLeft () const
bool isPointerMovingRight () const
bool isPointerMovingVertically () const
bool isPointerMovingHorizontally () const
bool isLeftMouseButtonDown () const
bool isMiddleMouseButtonDown () const
bool isRightMouseButtonDown () const
bool isMouseScrollingUp () const
bool isMouseScrollingDown () const
bool setFocusedByName (const std::string &name)
void setScrollingMotion (osgGA::GUIEventAdapter::ScrollingMotion sm)
void setPointerFocusMode (PointerFocusMode pfm)
void setWidth (point_type w)
void setHeight (point_type h)
void setSize (point_type w, point_type h)
void setWindowSize (point_type w, point_type h)
bool mousePushedLeft (float x, float y)
bool mousePushedMiddle (float x, float y)
bool mousePushedRight (float x, float y)
bool mouseReleasedLeft (float x, float y)
bool mouseReleasedMiddle (float x, float y)
bool mouseReleasedRight (float x, float y)
bool keyDown (int, int)
bool keyUp (int, int)
Static Public Member Functions
static void setEventFromInterface (Event &, EventInterface *)
template<typename T >
static EventInterface * getFirstEventInterface (T &, Event &)
Member Enumeration Documentation
enum osgWidget::WindowManager::PointerDirection
Enumerator:
PD_NONE
PD_LEFT
PD_RIGHT
PD_UP
PD_DOWN
enum osgWidget::WindowManager::PointerFocusMode
Enumerator:
PFM_FOCUS
PFM_UNFOCUS
PFM_SLOPPY
enum osgWidget::WindowManager::WmFlags
Enumerator:
WM_USE_LUA
WM_USE_PYTHON
WM_USE_RENDERBINS
WM_PICK_DEBUG
Constructor & Destructor Documentation
osgWidget::WindowManager::WindowManager (osgViewer::View * = 0, point_type = 0.0f, point_type = 0.0f, unsigned int = 0, unsigned int = 0)
osgWidget::WindowManager::WindowManager (const WindowManager & , const osg::CopyOp &)
virtual osgWidget::WindowManager::~WindowManager () [virtual]
Member Function Documentation
osg::Camera* osgWidget::WindowManager::createParentOrthoCamera ()
template<typename T > EventInterface * osgWidget::WindowManager::getFirstEventInterface (T & container, Event & ev) [static]
References osgWidget::Event::_widget, osgWidget::Event::_window, osgWidget::EventInterface::getEventMask(), osgWidget::Widget::getParent(), osgWidget::Window::getParentList(), and osgWidget::Event::type.
point_type osgWidget::WindowManager::getHeight () const [inline]
ScriptEngine* osgWidget::WindowManager::getLuaEngine () [inline]
const ScriptEngine* osgWidget::WindowManager::getLuaEngine () const [inline]
int osgWidget::WindowManager::getMouseKeysDown () const [inline]
References osgGA::GUIEventAdapter::LEFT_MOUSE_BUTTON, osgGA::GUIEventAdapter::MIDDLE_MOUSE_BUTTON, and osgGA::GUIEventAdapter::RIGHT_MOUSE_BUTTON.
unsigned int osgWidget::WindowManager::getNodeMask () const [inline]
int osgWidget::WindowManager::getPointerDirectionVector () const [inline]
PointerFocusMode osgWidget::WindowManager::getPointerFocusMode () const [inline]
PointerDirection osgWidget::WindowManager::getPointerHorizontalDirection () const [inline]
PointerDirection osgWidget::WindowManager::getPointerVerticalDirection () const [inline]
ScriptEngine* osgWidget::WindowManager::getPythonEngine () [inline]
const ScriptEngine* osgWidget::WindowManager::getPythonEngine () const [inline]
StyleManager* osgWidget::WindowManager::getStyleManager () [inline]
const StyleManager* osgWidget::WindowManager::getStyleManager () const [inline]
point_type osgWidget::WindowManager::getWidth () const [inline]
bool osgWidget::WindowManager::isLeftMouseButtonDown () const [inline]
bool osgWidget::WindowManager::isMiddleMouseButtonDown () const [inline]
bool osgWidget::WindowManager::isMouseScrollingDown () const [inline]
bool osgWidget::WindowManager::isMouseScrollingUp () const [inline]
bool osgWidget::WindowManager::isPointerMovingDown () const [inline]
bool osgWidget::WindowManager::isPointerMovingHorizontally () const [inline]
bool osgWidget::WindowManager::isPointerMovingLeft () const [inline]
bool osgWidget::WindowManager::isPointerMovingRight () const [inline]
bool osgWidget::WindowManager::isPointerMovingUp () const [inline]
bool osgWidget::WindowManager::isPointerMovingVertically () const [inline]
bool osgWidget::WindowManager::isRightMouseButtonDown () const [inline]
bool osgWidget::WindowManager::isUsingLua () const [inline]
bool osgWidget::WindowManager::isUsingPython () const [inline]
bool osgWidget::WindowManager::isUsingRenderBins () const [inline]
bool osgWidget::WindowManager::keyDown (int , int)
bool osgWidget::WindowManager::keyUp (int , int)
XYCoord osgWidget::WindowManager::localXY (double , double) const
osgWidget::WindowManager::META_Object (osgWidget , WindowManager)
bool osgWidget::WindowManager::mousePushedLeft (float x, float y) [inline]
bool osgWidget::WindowManager::mousePushedMiddle (float x, float y) [inline]
bool osgWidget::WindowManager::mousePushedRight (float x, float y) [inline]
bool osgWidget::WindowManager::mouseReleasedLeft (float x, float y) [inline]
bool osgWidget::WindowManager::mouseReleasedMiddle (float x, float y) [inline]
bool osgWidget::WindowManager::mouseReleasedRight (float x, float y) [inline]
bool osgWidget::WindowManager::mouseScroll (float , float)
bool osgWidget::WindowManager::pickAtXY (float , float , WidgetList &)
bool osgWidget::WindowManager::pointerDrag (float , float)
bool osgWidget::WindowManager::pointerMove (float , float)
void osgWidget::WindowManager::resizeAllWindows (bool = true)
static void osgWidget::WindowManager::setEventFromInterface (Event & , EventInterface *) [static]
bool osgWidget::WindowManager::setFocused (Window *)
bool osgWidget::WindowManager::setFocusedByName (const std::string & name) [inline]
void osgWidget::WindowManager::setHeight (point_type h) [inline]
void osgWidget::WindowManager::setPointerFocusMode (PointerFocusMode pfm) [inline]
void osgWidget::WindowManager::setPointerXY (float , float)
void osgWidget::WindowManager::setScrollingMotion (osgGA::GUIEventAdapter::ScrollingMotion sm) [inline]
void osgWidget::WindowManager::setSize (point_type w, point_type h) [inline]
void osgWidget::WindowManager::setStyleManager (StyleManager *)
void osgWidget::WindowManager::setWidth (point_type w) [inline]
void osgWidget::WindowManager::setWindowSize (point_type w, point_type h) [inline]
XYCoord osgWidget::WindowManager::windowXY (double , double) const
The documentation for this class was generated from the following file:
osgWidget/WindowManager
Generated at Thu Jun 9 2011 16:37:18 for the OpenSceneGraph by doxygen 1.7.1.