OpenThreads: OpenThreads::Block Class Reference
OpenThreads::Block Class Reference
Block is a block that can be used to halt a thread that is waiting another thread to release it.
Public Member Functions
Block ()
~Block ()
bool block ()
bool block (unsigned long timeout)
void release ()
void reset ()
void set (bool doRelease)
Protected Attributes
Mutex _mut
Condition _cond
bool _released
Detailed Description
Block is a block that can be used to halt a thread that is waiting another thread to release it.
Constructor & Destructor Documentation
OpenThreads::Block::Block () [inline]
OpenThreads::Block::~Block () [inline]
References release().
Member Function Documentation
bool OpenThreads::Block::block () [inline]
References _cond, _mut, _released, and OpenThreads::Condition::wait().
bool OpenThreads::Block::block (unsigned long timeout) [inline]
References _cond, _mut, _released, and OpenThreads::Condition::wait().
void OpenThreads::Block::release () [inline]
References _cond, _mut, _released, and OpenThreads::Condition::broadcast().
Referenced by set(), and ~Block().
void OpenThreads::Block::reset () [inline]
References _mut, and _released.
Referenced by set().
void OpenThreads::Block::set (bool doRelease) [inline]
References _released, release(), and reset().
Member Data Documentation
Condition OpenThreads::Block::_cond [protected]
Referenced by block(), and release().
Mutex OpenThreads::Block::_mut [protected]
Referenced by block(), release(), and reset().
bool OpenThreads::Block::_released [protected]
Referenced by block(), release(), reset(), and set().
The documentation for this class was generated from the following file:
OpenThreads/Block
Generated at Thu Jun 9 2011 16:37:29 for the OpenThreads by doxygen 1.7.1.