OpenThreads: OpenThreads::Condition Class Reference
OpenThreads::Condition Class Reference
This class provides an object-oriented thread condition interface.
Public Member Functions
Condition ()
Constructor.
virtual ~Condition ()
Destructor.
virtual int wait (Mutex *mutex)
Wait on a mutex.
virtual int wait (Mutex *mutex, unsigned long int ms)
Wait on a mutex for a given amount of time (ms).
virtual int signal ()
Signal a SINGLE thread to wake if it's waiting.
virtual int broadcast ()
Wake all threads waiting on this condition.
Detailed Description
This class provides an object-oriented thread condition interface.
Constructor & Destructor Documentation
OpenThreads::Condition::Condition ()
Constructor.
virtual OpenThreads::Condition::~Condition () [virtual]
Destructor.
Member Function Documentation
virtual int OpenThreads::Condition::broadcast () [virtual]
Wake all threads waiting on this condition.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
Referenced by OpenThreads::BlockCount::completed(), OpenThreads::BlockCount::release(), OpenThreads::Block::release(), and OpenThreads::BlockCount::reset().
virtual int OpenThreads::Condition::signal () [virtual]
Signal a SINGLE thread to wake if it's waiting.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
virtual int OpenThreads::Condition::wait (Mutex * mutex) [virtual]
Wait on a mutex.
Referenced by OpenThreads::BlockCount::block(), and OpenThreads::Block::block().
virtual int OpenThreads::Condition::wait (Mutex * mutex, unsigned long int ms) [virtual]
Wait on a mutex for a given amount of time (ms).
Returns:
0 if normal, -1 if errno set, errno code otherwise.
The documentation for this class was generated from the following file:
OpenThreads/Condition
Generated at Thu Jun 9 2011 16:37:29 for the OpenThreads by doxygen 1.7.1.