OpenThreads: OpenThreads::ReadWriteMutex Class Reference
OpenThreads::ReadWriteMutex Class Reference
Public Member Functions
ReadWriteMutex ()
virtual ~ReadWriteMutex ()
virtual int readLock ()
virtual int readUnlock ()
virtual int writeLock ()
virtual int writeUnlock ()
Protected Member Functions
ReadWriteMutex (const ReadWriteMutex &)
ReadWriteMutex & operator= (const ReadWriteMutex &)
Protected Attributes
OpenThreads::Mutex _readWriteMutex
OpenThreads::Mutex _readCountMutex
unsigned int _readCount
Constructor & Destructor Documentation
OpenThreads::ReadWriteMutex::ReadWriteMutex () [inline]
virtual OpenThreads::ReadWriteMutex::~ReadWriteMutex () [inline, virtual]
OpenThreads::ReadWriteMutex::ReadWriteMutex (const ReadWriteMutex &) [inline, protected]
Member Function Documentation
ReadWriteMutex& OpenThreads::ReadWriteMutex::operator= (const ReadWriteMutex &) [inline, protected]
virtual int OpenThreads::ReadWriteMutex::readLock () [inline, virtual]
References _readCount, _readCountMutex, _readWriteMutex, and OpenThreads::Mutex::lock().
Referenced by OpenThreads::ScopedReadLock::ScopedReadLock().
virtual int OpenThreads::ReadWriteMutex::readUnlock () [inline, virtual]
References _readCount, _readCountMutex, _readWriteMutex, and OpenThreads::Mutex::unlock().
Referenced by OpenThreads::ScopedReadLock::~ScopedReadLock().
virtual int OpenThreads::ReadWriteMutex::writeLock () [inline, virtual]
References _readWriteMutex, and OpenThreads::Mutex::lock().
Referenced by OpenThreads::ScopedWriteLock::ScopedWriteLock().
virtual int OpenThreads::ReadWriteMutex::writeUnlock () [inline, virtual]
References _readWriteMutex, and OpenThreads::Mutex::unlock().
Referenced by OpenThreads::ScopedWriteLock::~ScopedWriteLock().
Member Data Documentation
unsigned int OpenThreads::ReadWriteMutex::_readCount [protected]
Referenced by readLock(), and readUnlock().
OpenThreads::Mutex OpenThreads::ReadWriteMutex::_readCountMutex [protected]
Referenced by readLock(), and readUnlock().
OpenThreads::Mutex OpenThreads::ReadWriteMutex::_readWriteMutex [protected]
Referenced by readLock(), readUnlock(), writeLock(), and writeUnlock().
The documentation for this class was generated from the following file:
OpenThreads/ReadWriteMutex
Generated at Thu Jun 9 2011 16:37:29 for the OpenThreads by doxygen 1.7.1.