OpenSceneGraph: osgAnimation::Action::Callback Class Reference
osgAnimation::Action::Callback Class Reference
Public Member Functions
Callback ()
Callback (const Callback &nc, const osg::CopyOp &)
META_Object (osgAnimation, Callback)
virtual void operator() (Action *action, osgAnimation::ActionVisitor *nv)
Callback * getNestedCallback ()
void addNestedCallback (Callback *callback)
void removeCallback (Callback *cb)
Protected Attributes
osg::ref_ptr< Callback > _nestedCallback
Constructor & Destructor Documentation
osgAnimation::Action::Callback::Callback () [inline]
osgAnimation::Action::Callback::Callback (const Callback & nc, const osg::CopyOp &) [inline]
Member Function Documentation
void osgAnimation::Action::Callback::addNestedCallback (Callback * callback) [inline]
References addNestedCallback().
Referenced by addNestedCallback().
Callback* osgAnimation::Action::Callback::getNestedCallback () [inline]
Referenced by removeCallback().
osgAnimation::Action::Callback::META_Object (osgAnimation , Callback)
virtual void osgAnimation::Action::Callback::operator() (Action * action, osgAnimation::ActionVisitor * nv) [inline, virtual]
Reimplemented in osgAnimation::RunAction.
void osgAnimation::Action::Callback::removeCallback (Callback * cb) [inline]
References getNestedCallback(), and removeCallback().
Referenced by removeCallback().
Member Data Documentation
osg::ref_ptr<Callback> osgAnimation::Action::Callback::_nestedCallback [protected]
The documentation for this class was generated from the following file:
osgAnimation/Action
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.