OpenSceneGraph: osgAnimation::VertexInfluenceSet::BoneWeight Class Reference
osgAnimation::VertexInfluenceSet::BoneWeight Class Reference
Public Member Functions
BoneWeight (const std::string &name, float weight)
const std::string & getBoneName () const
float getWeight () const
void setWeight (float weight)
bool operator== (const BoneWeight &b) const
Protected Attributes
std::string _boneName
float _weight
Constructor & Destructor Documentation
osgAnimation::VertexInfluenceSet::BoneWeight::BoneWeight (const std::string & name, float weight) [inline]
Member Function Documentation
const std::string& osgAnimation::VertexInfluenceSet::BoneWeight::getBoneName () const [inline]
Referenced by operator==().
float osgAnimation::VertexInfluenceSet::BoneWeight::getWeight () const [inline]
Referenced by operator==().
bool osgAnimation::VertexInfluenceSet::BoneWeight::operator== (const BoneWeight & b) const [inline]
References getBoneName(), and getWeight().
void osgAnimation::VertexInfluenceSet::BoneWeight::setWeight (float weight) [inline]
Member Data Documentation
std::string osgAnimation::VertexInfluenceSet::BoneWeight::_boneName [protected]
float osgAnimation::VertexInfluenceSet::BoneWeight::_weight [protected]
The documentation for this class was generated from the following file:
osgAnimation/VertexInfluence
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.