OpenSceneGraph: osgAnimation::CompositeMotion Struct Reference
osgAnimation::CompositeMotion Struct Reference
Public Types
typedef std::vector
< osg::ref_ptr< Motion > > MotionList
Public Member Functions
MotionList & getMotionList ()
const MotionList & getMotionList () const
CompositeMotion (float startValue=0, float duration=1, float changeValue=1, TimeBehaviour tb=CLAMP)
virtual void getValueInNormalizedRange (float t, value_type &result) const
Public Attributes
MotionList _motions
Member Typedef Documentation
typedef std::vector<osg::ref_ptr<Motion> > osgAnimation::CompositeMotion::MotionList
Constructor & Destructor Documentation
osgAnimation::CompositeMotion::CompositeMotion (float startValue = 0, float duration = 1, float changeValue = 1, TimeBehaviour tb = CLAMP) [inline]
Member Function Documentation
MotionList& osgAnimation::CompositeMotion::getMotionList () [inline]
References _motions.
const MotionList& osgAnimation::CompositeMotion::getMotionList () const [inline]
References _motions.
virtual void osgAnimation::CompositeMotion::getValueInNormalizedRange (float t, value_type & result) const [inline, virtual]
Implements osgAnimation::Motion.
References _motions, osgAnimation::Motion::getDuration(), osgAnimation::Motion::getValueAt(), osg::notify(), and osg::WARN.
Member Data Documentation
MotionList osgAnimation::CompositeMotion::_motions
Referenced by getMotionList(), and getValueInNormalizedRange().
The documentation for this struct was generated from the following file:
osgAnimation/EaseMotion
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.