OpenSceneGraph: osgDB::EnumSerializer< C, P > Class Template Reference
osgDB::EnumSerializer< C, P > Class Template Reference
Public Types
typedef P(C::* GetterFunctionType)() const
typedef void(C::* SetterFunctionType)(P)
Public Member Functions
EnumSerializer (const char *fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter)
void add (P value, const char *str)
P getValue (const char *str)
const std::string & getString (P value)
bool write (osgDB::Output &fw, const osg::Object &obj)
bool read (osgDB::Input &fr, osg::Object &obj, bool &itrAdvanced)
Public Attributes
std::string _fieldName
P _default
GetterFunctionType _getter
SetterFunctionType _setter
IntLookup _lookup
template<typename C, typename P>
class osgDB::EnumSerializer< C, P >
Member Typedef Documentation
template<typename C , typename P > typedef P(C::* osgDB::EnumSerializer< C, P >::GetterFunctionType)() const
template<typename C , typename P > typedef void(C::* osgDB::EnumSerializer< C, P >::SetterFunctionType)(P)
Constructor & Destructor Documentation
template<typename C , typename P > osgDB::EnumSerializer< C, P >::EnumSerializer (const char * fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter) [inline]
Member Function Documentation
template<typename C , typename P > void osgDB::EnumSerializer< C, P >::add (P value, const char * str) [inline]
References osgDB::EnumSerializer< C, P >::_lookup, and osgDB::IntLookup::add().
template<typename C , typename P > const std::string& osgDB::EnumSerializer< C, P >::getString (P value) [inline]
References osgDB::EnumSerializer< C, P >::_lookup, and osgDB::IntLookup::getString().
Referenced by osgDB::EnumSerializer< C, P >::write().
template<typename C , typename P > P osgDB::EnumSerializer< C, P >::getValue (const char * str) [inline]
References osgDB::EnumSerializer< C, P >::_lookup, and osgDB::IntLookup::getValue().
Referenced by osgDB::EnumSerializer< C, P >::read().
template<typename C , typename P > bool osgDB::EnumSerializer< C, P >::read (osgDB::Input & fr, osg::Object & obj, bool & itrAdvanced) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::EnumSerializer< C, P >::_fieldName, osgDB::EnumSerializer< C, P >::_setter, and osgDB::EnumSerializer< C, P >::getValue().
template<typename C , typename P > bool osgDB::EnumSerializer< C, P >::write (osgDB::Output & fw, const osg::Object & obj) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::EnumSerializer< C, P >::_default, osgDB::EnumSerializer< C, P >::_fieldName, osgDB::EnumSerializer< C, P >::_getter, osgDB::EnumSerializer< C, P >::getString(), osgDB::Output::getWriteOutDefaultValues(), and osgDB::Output::indent().
Member Data Documentation
template<typename C , typename P > P osgDB::EnumSerializer< C, P >::_default
Referenced by osgDB::EnumSerializer< C, P >::write().
template<typename C , typename P > std::string osgDB::EnumSerializer< C, P >::_fieldName
Referenced by osgDB::EnumSerializer< C, P >::read(), and osgDB::EnumSerializer< C, P >::write().
template<typename C , typename P > GetterFunctionType osgDB::EnumSerializer< C, P >::_getter
Referenced by osgDB::EnumSerializer< C, P >::write().
template<typename C , typename P > IntLookup osgDB::EnumSerializer< C, P >::_lookup
Referenced by osgDB::EnumSerializer< C, P >::add(), osgDB::EnumSerializer< C, P >::getString(), and osgDB::EnumSerializer< C, P >::getValue().
template<typename C , typename P > SetterFunctionType osgDB::EnumSerializer< C, P >::_setter
Referenced by osgDB::EnumSerializer< C, P >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.