OpenSceneGraph: osg::Image Class Reference
osg::Image Class Reference
Image class for encapsulating the storage texture image data.
Public Types
enum WriteHint { NO_PREFERENCE, STORE_INLINE, EXTERNAL_FILE }
enum AllocationMode { NO_DELETE, USE_NEW_DELETE, USE_MALLOC_FREE }
enum Origin { BOTTOM_LEFT, TOP_LEFT }
typedef std::vector< unsigned int > MipmapDataType
Precomputed mipmaps stuff.
Public Member Functions
Image ()
Image (const Image &image, const CopyOp &copyop=CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
virtual Object * cloneType () const
Clone the type of an object, with Object* return type.
virtual Object * clone (const CopyOp &copyop) const
Clone an object, with Object* return type.
virtual bool isSameKindAs (const Object *obj) const
virtual const char * libraryName () const
return the name of the object's library.
virtual const char * className () const
return the name of the object's class type.
virtual int compare (const Image &rhs) const
Return -1 if *this < *rhs, 0 if *this==*rhs, 1 if *this>*rhs.
void setFileName (const std::string &fileName)
const std::string & getFileName () const
void setWriteHint (WriteHint writeHint)
WriteHint getWriteHint () const
void setAllocationMode (AllocationMode mode)
Set the method used for deleting data once it goes out of scope.
AllocationMode getAllocationMode () const
Get the method used for deleting data once it goes out of scope.
void allocateImage (int s, int t, int r, GLenum pixelFormat, GLenum type, int packing=1)
Allocate a pixel block of specified size and type.
void setImage (int s, int t, int r, GLint internalTextureformat, GLenum pixelFormat, GLenum type, unsigned char *data, AllocationMode mode, int packing=1)
Set the image dimensions, format and data.
void readPixels (int x, int y, int width, int height, GLenum pixelFormat, GLenum type)
Read pixels from current frame buffer at specified position and size, using glReadPixels.
void readImageFromCurrentTexture (unsigned int contextID, bool copyMipMapsIfAvailable, GLenum type=GL_UNSIGNED_BYTE)
Read the contents of the current bound texture, handling compressed pixelFormats if present.
void scaleImage (int s, int t, int r)
Scale image to specified size.
void scaleImage (int s, int t, int r, GLenum newDataType)
Scale image to specified size and with specified data type.
void copySubImage (int s_offset, int t_offset, int r_offset, const osg::Image *source)
Copy a source Image into a subpart of this Image at specified position.
void setOrigin (Origin origin)
Set the origin of the image.
Origin getOrigin () const
Get the origin of the image.
int s () const
Width of image.
int t () const
Height of image.
int r () const
Depth of image.
void setInternalTextureFormat (GLint internalFormat)
GLint getInternalTextureFormat () const
void setPixelFormat (GLenum pixelFormat)
GLenum getPixelFormat () const
void setDataType (GLenum dataType)
GLenum getDataType () const
void setPacking (unsigned int packing)
unsigned int getPacking () const
void setPixelAspectRatio (float pixelAspectRatio)
float getPixelAspectRatio () const
unsigned int getPixelSizeInBits () const
Return the number of bits required for each pixel.
unsigned int getRowSizeInBytes () const
Return the number of bytes each row of pixels occupies once it has been packed.
unsigned int getImageSizeInBytes () const
Return the number of bytes each image (_s*_t) of pixels occupies.
unsigned int getTotalSizeInBytes () const
Return the number of bytes the whole row/image/volume of pixels occupies.
unsigned int getTotalSizeInBytesIncludingMipmaps () const
Return the number of bytes the whole row/image/volume of pixels occupies, including all mip maps if included.
bool valid () const
Return true if the Image represent a valid and usable imagery.
unsigned char * data ()
Raw image data.
const unsigned char * data () const
Raw const image data.
unsigned char * data (int column, int row=0, int image=0)
const unsigned char * data (int column, int row=0, int image=0) const
Vec4 getColor (unsigned int s, unsigned t=0, unsigned r=0) const
Get the color value for specified texcoord.
Vec4 getColor (const Vec2 &texcoord) const
Get the color value for specified texcoord.
Vec4 getColor (const Vec3 &texcoord) const
Get the color value for specified texcoord.
void flipHorizontal ()
Flip the image horizontally.
void flipVertical ()
Flip the image vertically.
void ensureValidSizeForTexturing (GLint maxTextureSize)
Ensure image dimensions are a power of two.
void dirty ()
Dirty the image, which increments the modified count, to force osg::Texture to reload the image.
void setModifiedCount (unsigned int value)
Set the modified count value.
unsigned int getModifiedCount () const
Get modified count value.
bool isMipmap () const
unsigned int getNumMipmapLevels () const
void setMipmapLevels (const MipmapDataType &mipmapDataVector)
Send offsets into data.
const MipmapDataType & getMipmapLevels () const
unsigned int getMipmapOffset (unsigned int mipmapLevel) const
unsigned char * getMipmapData (unsigned int mipmapLevel)
const unsigned char * getMipmapData (unsigned int mipmapLevel) const
bool isImageTranslucent () const
Return true if this image is translucent - i.e.
void setPixelBufferObject (PixelBufferObject *buffer)
Set the optional PixelBufferObject used to map the image memory efficiently to graphics memory.
PixelBufferObject * getPixelBufferObject ()
Get the PixelBufferObject.
const PixelBufferObject * getPixelBufferObject () const
Get the const PixelBufferObject.
virtual void update (NodeVisitor *)
virtual bool sendPointerEvent (int, int, int)
method for sending pointer events to images that are acting as front ends to interactive surfaces such as a vnc or browser window.
virtual bool sendKeyEvent (int, bool)
method for sending key events to images that are acting as front ends to interactive surfaces such as a vnc or browser window.
virtual void setFrameLastRendered (const osg::FrameStamp *)
method for passing frame information to the custom Image classes, to be called only when objects associated with imagery are not culled.
Static Public Member Functions
static bool isPackedType (GLenum type)
static GLenum computePixelFormat (GLenum pixelFormat)
static GLenum computeFormatDataType (GLenum pixelFormat)
static unsigned int computeNumComponents (GLenum pixelFormat)
static unsigned int computePixelSizeInBits (GLenum pixelFormat, GLenum type)
static unsigned int computeRowWidthInBytes (int width, GLenum pixelFormat, GLenum type, int packing)
static int computeNearestPowerOfTwo (int s, float bias=0.5f)
static int computeNumberOfMipmapLevels (int s, int t=1, int r=1)
Protected Member Functions
virtual ~Image ()
Image & operator= (const Image &)
void deallocateData ()
void setData (unsigned char *data, AllocationMode allocationMode)
Protected Attributes
std::string _fileName
WriteHint _writeHint
Origin _origin
int _s
int _t
int _r
GLint _internalTextureFormat
GLenum _pixelFormat
GLenum _dataType
unsigned int _packing
float _pixelAspectRatio
AllocationMode _allocationMode
unsigned char * _data
unsigned int _modifiedCount
MipmapDataType _mipmapData
ref_ptr< PixelBufferObject > _bufferObject
Detailed Description
Image class for encapsulating the storage texture image data.
Member Typedef Documentation
typedef std::vector< unsigned int > osg::Image::MipmapDataType
Precomputed mipmaps stuff.
Member Enumeration Documentation
enum osg::Image::AllocationMode
Enumerator:
NO_DELETE
USE_NEW_DELETE
USE_MALLOC_FREE
enum osg::Image::Origin
Enumerator:
BOTTOM_LEFT
TOP_LEFT
enum osg::Image::WriteHint
Enumerator:
NO_PREFERENCE
STORE_INLINE
EXTERNAL_FILE
Constructor & Destructor Documentation
osg::Image::Image ()
osg::Image::Image (const Image & image, const CopyOp & copyop = CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
virtual osg::Image::~Image () [protected, virtual]
Member Function Documentation
void osg::Image::allocateImage (int s, int t, int r, GLenum pixelFormat, GLenum type, int packing = 1)
Allocate a pixel block of specified size and type.
virtual const char* osg::Image::className () const [inline, virtual]
return the name of the object's class type.
Must be defined by derived classes.
Implements osg::Object.
Reimplemented in osg::ImageSequence, and osg::ImageStream.
virtual Object* osg::Image::clone (const CopyOp &) const [inline, virtual]
Clone an object, with Object* return type.
Must be defined by derived classes.
Implements osg::Object.
Reimplemented in osg::ImageSequence, and osg::ImageStream.
virtual Object* osg::Image::cloneType () const [inline, virtual]
Clone the type of an object, with Object* return type.
Must be defined by derived classes.
Implements osg::Object.
Reimplemented in osg::ImageSequence, and osg::ImageStream.
virtual int osg::Image::compare (const Image & rhs) const [virtual]
Return -1 if *this < *rhs, 0 if *this==*rhs, 1 if *this>*rhs.
Reimplemented in osg::ImageSequence, and osg::ImageStream.
static GLenum osg::Image::computeFormatDataType (GLenum pixelFormat) [static]
static int osg::Image::computeNearestPowerOfTwo (int s, float bias = 0.5f) [static]
static int osg::Image::computeNumberOfMipmapLevels (int s, int t = 1, int r = 1) [static]
static unsigned int osg::Image::computeNumComponents (GLenum pixelFormat) [static]
static GLenum osg::Image::computePixelFormat (GLenum pixelFormat) [static]
static unsigned int osg::Image::computePixelSizeInBits (GLenum pixelFormat, GLenum type) [static]
static unsigned int osg::Image::computeRowWidthInBytes (int width, GLenum pixelFormat, GLenum type, int packing) [static]
void osg::Image::copySubImage (int s_offset, int t_offset, int r_offset, const osg::Image * source)
Copy a source Image into a subpart of this Image at specified position.
Typically used to copy to an already allocated image, such as creating a 3D image from a stack 2D images. If this Image is empty then image data is created to accomodate the source image in its offset position. If source is NULL then no operation happens, this Image is left unchanged.
unsigned char* osg::Image::data () [inline]
Raw image data.
Referenced by osg::modifyImage(), osg::readImage(), and osgUtil::CubeMapGenerator::set_pixel().
const unsigned char* osg::Image::data () const [inline]
Raw const image data.
unsigned char* osg::Image::data (int column, int row = 0, int image = 0) [inline]
const unsigned char* osg::Image::data (int column, int row = 0, int image = 0) const [inline]
void osg::Image::deallocateData () [protected]
void osg::Image::dirty () [inline]
Dirty the image, which increments the modified count, to force osg::Texture to reload the image.
void osg::Image::ensureValidSizeForTexturing (GLint maxTextureSize)
Ensure image dimensions are a power of two.
Mipmapped textures require the image dimensions to be power of two and are within the maxiumum texture size for the host machine.
void osg::Image::flipHorizontal ()
Flip the image horizontally.
void osg::Image::flipVertical ()
Flip the image vertically.
AllocationMode osg::Image::getAllocationMode () const [inline]
Get the method used for deleting data once it goes out of scope.
Vec4 osg::Image::getColor (unsigned int s, unsigned t = 0, unsigned r = 0) const
Get the color value for specified texcoord.
Vec4 osg::Image::getColor (const Vec2 & texcoord) const [inline]
Get the color value for specified texcoord.
References getColor(), osg::Vec2f::x(), and osg::Vec2f::y().
Referenced by getColor().
Vec4 osg::Image::getColor (const Vec3 & texcoord) const
Get the color value for specified texcoord.
GLenum osg::Image::getDataType () const [inline]
Referenced by osg::modifyImage(), and osg::readImage().
const std::string& osg::Image::getFileName () const [inline]
unsigned int osg::Image::getImageSizeInBytes () const [inline]
Return the number of bytes each image (_s*_t) of pixels occupies.
GLint osg::Image::getInternalTextureFormat () const [inline]
unsigned char* osg::Image::getMipmapData (unsigned int mipmapLevel) [inline]
const unsigned char* osg::Image::getMipmapData (unsigned int mipmapLevel) const [inline]
const MipmapDataType& osg::Image::getMipmapLevels () const [inline]
unsigned int osg::Image::getMipmapOffset (unsigned int mipmapLevel) const [inline]
unsigned int osg::Image::getModifiedCount () const [inline]
Get modified count value.
Used by osg::Texture when using texture subloading.
unsigned int osg::Image::getNumMipmapLevels () const [inline]
Origin osg::Image::getOrigin () const [inline]
Get the origin of the image.
unsigned int osg::Image::getPacking () const [inline]
float osg::Image::getPixelAspectRatio () const [inline]
PixelBufferObject* osg::Image::getPixelBufferObject () [inline]
Get the PixelBufferObject.
const PixelBufferObject* osg::Image::getPixelBufferObject () const [inline]
Get the const PixelBufferObject.
GLenum osg::Image::getPixelFormat () const [inline]
Referenced by osg::modifyImage(), and osg::readImage().
unsigned int osg::Image::getPixelSizeInBits () const [inline]
Return the number of bits required for each pixel.
unsigned int osg::Image::getRowSizeInBytes () const [inline]
Return the number of bytes each row of pixels occupies once it has been packed.
unsigned int osg::Image::getTotalSizeInBytes () const [inline]
Return the number of bytes the whole row/image/volume of pixels occupies.
unsigned int osg::Image::getTotalSizeInBytesIncludingMipmaps () const
Return the number of bytes the whole row/image/volume of pixels occupies, including all mip maps if included.
WriteHint osg::Image::getWriteHint () const [inline]
bool osg::Image::isImageTranslucent () const
Return true if this image is translucent - i.e.
it has alpha values that are less 1.0 (when normalized).
bool osg::Image::isMipmap () const [inline]
static bool osg::Image::isPackedType (GLenum type) [static]
virtual bool osg::Image::isSameKindAs (const Object * obj) const [inline, virtual]
Reimplemented from osg::Object.
Reimplemented in osg::ImageSequence, and osg::ImageStream.
virtual const char* osg::Image::libraryName () const [inline, virtual]
return the name of the object's library.
Must be defined by derived classes. The OpenSceneGraph convention is that the namespace of a library is the same as the library name.
Implements osg::Object.
Reimplemented in osg::ImageSequence, and osg::ImageStream.
Image& osg::Image::operator= (const Image &) [inline, protected]
int osg::Image::r () const [inline]
Depth of image.
Referenced by osg::modifyImage(), and osg::readImage().
void osg::Image::readImageFromCurrentTexture (unsigned int contextID, bool copyMipMapsIfAvailable, GLenum type = GL_UNSIGNED_BYTE)
Read the contents of the current bound texture, handling compressed pixelFormats if present.
Create memory for storage if required, reuse existing pixel coords if possible.
void osg::Image::readPixels (int x, int y, int width, int height, GLenum pixelFormat, GLenum type)
Read pixels from current frame buffer at specified position and size, using glReadPixels.
Create memory for storage if required, reuse existing pixel coords if possible.
int osg::Image::s () const [inline]
Width of image.
Referenced by osg::modifyImage(), and osg::readImage().
void osg::Image::scaleImage (int s, int t, int r, GLenum newDataType)
Scale image to specified size and with specified data type.
void osg::Image::scaleImage (int s, int t, int r) [inline]
Scale image to specified size.
References scaleImage().
Referenced by scaleImage().
virtual bool osg::Image::sendKeyEvent (int , bool) [inline, virtual]
method for sending key events to images that are acting as front ends to interactive surfaces such as a vnc or browser window.
Return true if handled.
virtual bool osg::Image::sendPointerEvent (int , int , int) [inline, virtual]
method for sending pointer events to images that are acting as front ends to interactive surfaces such as a vnc or browser window.
Return true if handled.
void osg::Image::setAllocationMode (AllocationMode mode) [inline]
Set the method used for deleting data once it goes out of scope.
void osg::Image::setData (unsigned char * data, AllocationMode allocationMode) [protected]
void osg::Image::setDataType (GLenum dataType)
void osg::Image::setFileName (const std::string & fileName)
virtual void osg::Image::setFrameLastRendered (const osg::FrameStamp *) [inline, virtual]
method for passing frame information to the custom Image classes, to be called only when objects associated with imagery are not culled.
void osg::Image::setImage (int s, int t, int r, GLint internalTextureformat, GLenum pixelFormat, GLenum type, unsigned char * data, AllocationMode mode, int packing = 1)
Set the image dimensions, format and data.
Reimplemented in osg::ImageSequence.
Referenced by osg::ImageSequence::setImage().
void osg::Image::setInternalTextureFormat (GLint internalFormat)
void osg::Image::setMipmapLevels (const MipmapDataType & mipmapDataVector) [inline]
Send offsets into data.
It is assumed that first mipmap offset (index 0) is 0.
void osg::Image::setModifiedCount (unsigned int value) [inline]
Set the modified count value.
Used by osg::Texture when using texture subloading.
void osg::Image::setOrigin (Origin origin) [inline]
Set the origin of the image.
The default value is BOTTOM_LEFT and is consistent with OpenGL. TOP_LEFT is used for imagery that follows standard Imagery convention, such as movies, and hasn't been flipped yet. For such images one much flip the t axis of the tex coords. to handle this origin position.
void osg::Image::setPacking (unsigned int packing) [inline]
void osg::Image::setPixelAspectRatio (float pixelAspectRatio) [inline]
void osg::Image::setPixelBufferObject (PixelBufferObject * buffer) [inline]
Set the optional PixelBufferObject used to map the image memory efficiently to graphics memory.
References osg::PixelBufferObject::setImage().
void osg::Image::setPixelFormat (GLenum pixelFormat)
void osg::Image::setWriteHint (WriteHint writeHint) [inline]
int osg::Image::t () const [inline]
Height of image.
Referenced by osg::modifyImage(), and osg::readImage().
virtual void osg::Image::update (NodeVisitor *) [inline, virtual]
Reimplemented in osg::ImageSequence.
bool osg::Image::valid () const [inline]
Return true if the Image represent a valid and usable imagery.
Referenced by osgTerrain::ContourLayer::getImage().
Member Data Documentation
AllocationMode osg::Image::_allocationMode [protected]
ref_ptr<PixelBufferObject> osg::Image::_bufferObject [protected]
unsigned char* osg::Image::_data [protected]
GLenum osg::Image::_dataType [protected]
std::string osg::Image::_fileName [protected]
GLint osg::Image::_internalTextureFormat [protected]
MipmapDataType osg::Image::_mipmapData [protected]
unsigned int osg::Image::_modifiedCount [protected]
Origin osg::Image::_origin [protected]
unsigned int osg::Image::_packing [protected]
float osg::Image::_pixelAspectRatio [protected]
GLenum osg::Image::_pixelFormat [protected]
int osg::Image::_r [protected]
int osg::Image::_s [protected]
int osg::Image::_t [protected]
WriteHint osg::Image::_writeHint [protected]
The documentation for this class was generated from the following file:
osg/Image
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.