OpenSceneGraph: osgSim::GeographicLocation Class Reference
osgSim::GeographicLocation Class Reference
Stores a double precision geographic location, latitude and longitude.
Public Member Functions
GeographicLocation ()
GeographicLocation (double lat, double lon)
bool operator== (const GeographicLocation &v) const
bool operator!= (const GeographicLocation &v) const
bool operator< (const GeographicLocation &v) const
double * ptr ()
const double * ptr () const
void set (double lat, double lon)
double & latitude ()
double & longitude ()
double latitude () const
double longitude () const
bool valid () const
bool isNaN () const
const GeographicLocation operator+ (const GeographicLocation &rhs) const
binary vector add
const GeographicLocation operator- (const GeographicLocation &rhs) const
binary vector subtract
Friends
std::ostream & operator<< (std::ostream &output, const GeographicLocation &loc)
Detailed Description
Stores a double precision geographic location, latitude and longitude.
Derived from Referenced so it can be used as an osg::Object userData.
Constructor & Destructor Documentation
osgSim::GeographicLocation::GeographicLocation () [inline]
Referenced by operator+(), and operator-().
osgSim::GeographicLocation::GeographicLocation (double lat, double lon) [inline]
Member Function Documentation
bool osgSim::GeographicLocation::isNaN () const [inline]
Referenced by valid().
double osgSim::GeographicLocation::latitude () const [inline]
double& osgSim::GeographicLocation::latitude () [inline]
double& osgSim::GeographicLocation::longitude () [inline]
double osgSim::GeographicLocation::longitude () const [inline]
bool osgSim::GeographicLocation::operator!= (const GeographicLocation & v) const [inline]
const GeographicLocation osgSim::GeographicLocation::operator+ (const GeographicLocation & rhs) const [inline]
binary vector add
References GeographicLocation().
const GeographicLocation osgSim::GeographicLocation::operator- (const GeographicLocation & rhs) const [inline]
binary vector subtract
References GeographicLocation().
bool osgSim::GeographicLocation::operator< (const GeographicLocation & v) const [inline]
bool osgSim::GeographicLocation::operator== (const GeographicLocation & v) const [inline]
const double* osgSim::GeographicLocation::ptr () const [inline]
double* osgSim::GeographicLocation::ptr () [inline]
void osgSim::GeographicLocation::set (double lat, double lon) [inline]
bool osgSim::GeographicLocation::valid () const [inline]
References isNaN().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & output, const GeographicLocation & loc) [friend]
The documentation for this class was generated from the following file:
osgSim/GeographicLocation
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.