OpenSceneGraph: osgIntrospection::MethodInfo Class Reference
osgIntrospection::MethodInfo Class Reference
Class MethodInfo stores information about a class method.
Inherits osgIntrospection::CustomAttributeProvider.
Inherited by osgIntrospection::StaticMethodInfo0< C, R >, osgIntrospection::StaticMethodInfo0< C, void >, osgIntrospection::StaticMethodInfo1< C, R, P0 >, osgIntrospection::StaticMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticMethodInfo1< C, void, P0 >, osgIntrospection::StaticMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo0< C, R >, osgIntrospection::StaticProtectedMethodInfo0< C, void >, osgIntrospection::StaticProtectedMethodInfo1< C, R, P0 >, osgIntrospection::StaticProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo1< C, void, P0 >, osgIntrospection::StaticProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo0< C, R >, osgIntrospection::TypedMethodInfo0< C, void >, osgIntrospection::TypedMethodInfo1< C, R, P0 >, osgIntrospection::TypedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo1< C, void, P0 >, osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo0< C, R >, osgIntrospection::TypedProtectedMethodInfo0< C, void >, osgIntrospection::TypedProtectedMethodInfo1< C, R, P0 >, osgIntrospection::TypedProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo1< C, void, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, and osgIntrospection::TypedProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >.
Public Types
enum VirtualState { NON_VIRTUAL = 0x0, VIRTUAL = 0x1, PURE_VIRTUAL = 0x3 }
Possible virtual states of the function.
Public Member Functions
MethodInfo (const std::string &qname, const Type &declarationType, const Type &rtype, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
Direct initialization constructor.
MethodInfo (const std::string &qname, const Type &declarationType, const Type &rtype, const ParameterInfoList &plist, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
Direct initialization constructor for static functions (no virtual specifier).
~MethodInfo ()
Destructor.
virtual const Type & getDeclaringType () const
Returns the Type object associated to the type that declares the reflected method.
virtual const std::string & getName () const
Returns the name of the reflected method.
const Type & getReturnType () const
Returns the return type of the reflected method.
const ParameterInfoList & getParameters () const
Returns a list of objects that describe the reflected method's parameters.
virtual const std::string & getBriefHelp () const
Returns the brief help of the reflected method.
virtual const std::string & getDetailedHelp () const
Returns the detailed help of the reflected method.
virtual bool isConst () const =0
Returns whether the reflected method is const or not.
virtual bool isStatic () const =0
Returns whether the reflected method is static or not.
virtual bool isVirtual () const
Returns whether the reflected method is virtual or not.
virtual bool isPureVirtual () const
Returns whether the reflected method is pure virtual or not.
bool overrides (const MethodInfo *other) const
Returns whether this method would override the given method.
virtual Value invoke (const Value &instance, ValueList &args) const
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
virtual Value invoke (Value &instance, ValueList &args) const
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
virtual Value invoke (ValueList &args) const
Invokes the reflected static method dynamically passing it the arguments as a list of Value objects.
Value invoke (const Value &instance) const
Invokes the reflected method dynamically on the given const instance, without arguments.
Value invoke (Value &instance) const
Invokes the reflected method dynamically on the given instance, without arguments.
Value invoke () const
Invokes the reflected static method without arguments.
Detailed Description
Class MethodInfo stores information about a class method.
It is an abstract class, so it must be derived to provide the actual implementation of isConst() and invoke(). Instances of this class can't be modified after their creation.
Member Enumeration Documentation
enum osgIntrospection::MethodInfo::VirtualState
Possible virtual states of the function.
Enumerator:
NON_VIRTUAL
VIRTUAL
PURE_VIRTUAL
Constructor & Destructor Documentation
osgIntrospection::MethodInfo::MethodInfo (const std::string & qname, const Type & declarationType, const Type & rtype, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
Direct initialization constructor.
osgIntrospection::MethodInfo::MethodInfo (const std::string & qname, const Type & declarationType, const Type & rtype, const ParameterInfoList & plist, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
Direct initialization constructor for static functions (no virtual specifier).
osgIntrospection::MethodInfo::~MethodInfo () [inline]
Destructor.
Member Function Documentation
const std::string & osgIntrospection::MethodInfo::getBriefHelp () const [inline, virtual]
Returns the brief help of the reflected method.
const Type & osgIntrospection::MethodInfo::getDeclaringType () const [inline, virtual]
Returns the Type object associated to the type that declares the reflected method.
const std::string & osgIntrospection::MethodInfo::getDetailedHelp () const [inline, virtual]
Returns the detailed help of the reflected method.
const std::string & osgIntrospection::MethodInfo::getName () const [inline, virtual]
Returns the name of the reflected method.
const ParameterInfoList & osgIntrospection::MethodInfo::getParameters () const [inline]
Returns a list of objects that describe the reflected method's parameters.
Referenced by osgIntrospection::TypedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >::invoke(), osgIntrospection::TypedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >::invoke(), osgIntrospection::TypedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >::invoke(), osgIntrospection::TypedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >::invoke(), osgIntrospection::TypedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >::invoke(), osgIntrospection::TypedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >::invoke(), osgIntrospection::TypedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::invoke(), osgIntrospection::TypedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >::invoke(), osgIntrospection::TypedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >::invoke(), osgIntrospection::TypedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >::invoke(), osgIntrospection::TypedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >::invoke(), osgIntrospection::TypedMethodInfo5< C, void, P0, P1, P2, P3, P4 >::invoke(), osgIntrospection::TypedMethodInfo4< C, void, P0, P1, P2, P3 >::invoke(), osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >::invoke(), osgIntrospection::TypedMethodInfo2< C, void, P0, P1 >::invoke(), osgIntrospection::TypedMethodInfo1< C, void, P0 >::invoke(), osgIntrospection::TypedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >::invoke(), osgIntrospection::TypedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >::invoke(), osgIntrospection::TypedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >::invoke(), osgIntrospection::TypedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >::invoke(), osgIntrospection::TypedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >::invoke(), osgIntrospection::TypedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >::invoke(), osgIntrospection::TypedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::invoke(), osgIntrospection::TypedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >::invoke(), osgIntrospection::TypedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >::invoke(), osgIntrospection::TypedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >::invoke(), osgIntrospection::TypedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >::invoke(), osgIntrospection::TypedMethodInfo5< C, R, P0, P1, P2, P3, P4 >::invoke(), osgIntrospection::TypedMethodInfo4< C, R, P0, P1, P2, P3 >::invoke(), osgIntrospection::TypedMethodInfo3< C, R, P0, P1, P2 >::invoke(), osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::invoke(), osgIntrospection::TypedMethodInfo1< C, R, P0 >::invoke(), osgIntrospection::StaticMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >::invoke(), osgIntrospection::StaticMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >::invoke(), osgIntrospection::StaticMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >::invoke(), osgIntrospection::StaticMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >::invoke(), osgIntrospection::StaticMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >::invoke(), osgIntrospection::StaticMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >::invoke(), osgIntrospection::StaticMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::invoke(), osgIntrospection::StaticMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >::invoke(), osgIntrospection::StaticMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >::invoke(), osgIntrospection::StaticMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >::invoke(), osgIntrospection::StaticMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >::invoke(), osgIntrospection::StaticMethodInfo5< C, void, P0, P1, P2, P3, P4 >::invoke(), osgIntrospection::StaticMethodInfo4< C, void, P0, P1, P2, P3 >::invoke(), osgIntrospection::StaticMethodInfo3< C, void, P0, P1, P2 >::invoke(), osgIntrospection::StaticMethodInfo2< C, void, P0, P1 >::invoke(), osgIntrospection::StaticMethodInfo1< C, void, P0 >::invoke(), osgIntrospection::StaticMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >::invoke(), osgIntrospection::StaticMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >::invoke(), osgIntrospection::StaticMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >::invoke(), osgIntrospection::StaticMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >::invoke(), osgIntrospection::StaticMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >::invoke(), osgIntrospection::StaticMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >::invoke(), osgIntrospection::StaticMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::invoke(), osgIntrospection::StaticMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >::invoke(), osgIntrospection::StaticMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >::invoke(), osgIntrospection::StaticMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >::invoke(), osgIntrospection::StaticMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >::invoke(), osgIntrospection::StaticMethodInfo5< C, R, P0, P1, P2, P3, P4 >::invoke(), osgIntrospection::StaticMethodInfo4< C, R, P0, P1, P2, P3 >::invoke(), osgIntrospection::StaticMethodInfo3< C, R, P0, P1, P2 >::invoke(), osgIntrospection::StaticMethodInfo2< C, R, P0, P1 >::invoke(), and osgIntrospection::StaticMethodInfo1< C, R, P0 >::invoke().
const Type & osgIntrospection::MethodInfo::getReturnType () const [inline]
Returns the return type of the reflected method.
Value osgIntrospection::MethodInfo::invoke (const Value & instance) const [inline]
Invokes the reflected method dynamically on the given const instance, without arguments.
References invoke().
Value osgIntrospection::MethodInfo::invoke (Value & instance) const [inline]
Invokes the reflected method dynamically on the given instance, without arguments.
References invoke().
Value osgIntrospection::MethodInfo::invoke () const [inline]
Invokes the reflected static method without arguments.
Referenced by invoke().
Value osgIntrospection::MethodInfo::invoke (Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
Reimplemented in osgIntrospection::TypedMethodInfo0< C, R >, osgIntrospection::TypedMethodInfo1< C, R, P0 >, osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo0< C, void >, osgIntrospection::TypedMethodInfo1< C, void, P0 >, osgIntrospection::TypedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, R >, osgIntrospection::TypedProtectedMethodInfo1< C, R, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, void >, osgIntrospection::TypedProtectedMethodInfo1< C, void, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, and osgIntrospection::TypedProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >.
Value osgIntrospection::MethodInfo::invoke (const Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Reimplemented in osgIntrospection::TypedMethodInfo0< C, R >, osgIntrospection::TypedMethodInfo1< C, R, P0 >, osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo0< C, void >, osgIntrospection::TypedMethodInfo1< C, void, P0 >, osgIntrospection::TypedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, R >, osgIntrospection::TypedProtectedMethodInfo1< C, R, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, void >, osgIntrospection::TypedProtectedMethodInfo1< C, void, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, and osgIntrospection::TypedProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >.
Value osgIntrospection::MethodInfo::invoke (ValueList & args) const [inline, virtual]
Invokes the reflected static method dynamically passing it the arguments as a list of Value objects.
Reimplemented in osgIntrospection::StaticMethodInfo0< C, R >, osgIntrospection::StaticMethodInfo1< C, R, P0 >, osgIntrospection::StaticMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticMethodInfo0< C, void >, osgIntrospection::StaticMethodInfo1< C, void, P0 >, osgIntrospection::StaticMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo0< C, R >, osgIntrospection::StaticProtectedMethodInfo1< C, R, P0 >, osgIntrospection::StaticProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo0< C, void >, osgIntrospection::StaticProtectedMethodInfo1< C, void, P0 >, osgIntrospection::StaticProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, and osgIntrospection::StaticProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >.
virtual bool osgIntrospection::MethodInfo::isConst () const [pure virtual]
Returns whether the reflected method is const or not.
Implemented in osgIntrospection::StaticMethodInfo0< C, R >, osgIntrospection::StaticMethodInfo1< C, R, P0 >, osgIntrospection::StaticMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticMethodInfo0< C, void >, osgIntrospection::StaticMethodInfo1< C, void, P0 >, osgIntrospection::StaticMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo0< C, R >, osgIntrospection::StaticProtectedMethodInfo1< C, R, P0 >, osgIntrospection::StaticProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo0< C, void >, osgIntrospection::StaticProtectedMethodInfo1< C, void, P0 >, osgIntrospection::StaticProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo0< C, R >, osgIntrospection::TypedMethodInfo1< C, R, P0 >, osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo0< C, void >, osgIntrospection::TypedMethodInfo1< C, void, P0 >, osgIntrospection::TypedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, R >, osgIntrospection::TypedProtectedMethodInfo1< C, R, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, void >, osgIntrospection::TypedProtectedMethodInfo1< C, void, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, and osgIntrospection::TypedProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >.
bool osgIntrospection::MethodInfo::isPureVirtual () const [inline, virtual]
Returns whether the reflected method is pure virtual or not.
References PURE_VIRTUAL.
virtual bool osgIntrospection::MethodInfo::isStatic () const [pure virtual]
Returns whether the reflected method is static or not.
Implemented in osgIntrospection::StaticMethodInfo0< C, R >, osgIntrospection::StaticMethodInfo1< C, R, P0 >, osgIntrospection::StaticMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticMethodInfo0< C, void >, osgIntrospection::StaticMethodInfo1< C, void, P0 >, osgIntrospection::StaticMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo0< C, R >, osgIntrospection::StaticProtectedMethodInfo1< C, R, P0 >, osgIntrospection::StaticProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::StaticProtectedMethodInfo0< C, void >, osgIntrospection::StaticProtectedMethodInfo1< C, void, P0 >, osgIntrospection::StaticProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::StaticProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::StaticProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::StaticProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::StaticProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::StaticProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::StaticProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::StaticProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::StaticProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::StaticProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::StaticProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::StaticProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::StaticProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::StaticProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::StaticProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo0< C, R >, osgIntrospection::TypedMethodInfo1< C, R, P0 >, osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedMethodInfo0< C, void >, osgIntrospection::TypedMethodInfo1< C, void, P0 >, osgIntrospection::TypedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, R >, osgIntrospection::TypedProtectedMethodInfo1< C, R, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, R, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, R, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, R, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, R, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, R, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, R, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, R, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, osgIntrospection::TypedProtectedMethodInfo16< C, R, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >, osgIntrospection::TypedProtectedMethodInfo0< C, void >, osgIntrospection::TypedProtectedMethodInfo1< C, void, P0 >, osgIntrospection::TypedProtectedMethodInfo2< C, void, P0, P1 >, osgIntrospection::TypedProtectedMethodInfo3< C, void, P0, P1, P2 >, osgIntrospection::TypedProtectedMethodInfo4< C, void, P0, P1, P2, P3 >, osgIntrospection::TypedProtectedMethodInfo5< C, void, P0, P1, P2, P3, P4 >, osgIntrospection::TypedProtectedMethodInfo6< C, void, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedProtectedMethodInfo7< C, void, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedProtectedMethodInfo8< C, void, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedProtectedMethodInfo9< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedProtectedMethodInfo10< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedProtectedMethodInfo11< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedProtectedMethodInfo12< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedProtectedMethodInfo13< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedProtectedMethodInfo14< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedProtectedMethodInfo15< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, and osgIntrospection::TypedProtectedMethodInfo16< C, void, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >.
bool osgIntrospection::MethodInfo::isVirtual () const [inline, virtual]
Returns whether the reflected method is virtual or not.
References VIRTUAL.
bool osgIntrospection::MethodInfo::overrides (const MethodInfo * other) const
Returns whether this method would override the given method.
Referenced by osgIntrospection::Reflector< T >::addMethod(), and osgIntrospection::Reflector< T >::addProtectedMethod().
The documentation for this class was generated from the following file:
osgIntrospection/MethodInfo
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.