OpenSceneGraph: osg::Matrixd Class Reference
osg::Matrixd Class Reference
Public Types
typedef double value_type
Public Member Functions
Matrixd ()
Matrixd (const Matrixd &mat)
Matrixd (const Matrixf &mat)
Matrixd (float const *const ptr)
Matrixd (double const *const ptr)
Matrixd (const Quat &quat)
Matrixd (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
~Matrixd ()
int compare (const Matrixd &m) const
bool operator< (const Matrixd &m) const
bool operator== (const Matrixd &m) const
bool operator!= (const Matrixd &m) const
value_type & operator() (int row, int col)
value_type operator() (int row, int col) const
bool valid () const
bool isNaN () const
Matrixd & operator= (const Matrixd &rhs)
Matrixd & operator= (const Matrixf &other)
void set (const Matrixd &rhs)
void set (const Matrixf &rhs)
void set (float const *const ptr)
void set (double const *const ptr)
void set (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
value_type * ptr ()
const value_type * ptr () const
bool isIdentity () const
void makeIdentity ()
void makeScale (const Vec3f &)
void makeScale (const Vec3d &)
void makeScale (value_type, value_type, value_type)
void makeTranslate (const Vec3f &)
void makeTranslate (const Vec3d &)
void makeTranslate (value_type, value_type, value_type)
void makeRotate (const Vec3f &from, const Vec3f &to)
void makeRotate (const Vec3d &from, const Vec3d &to)
void makeRotate (value_type angle, const Vec3f &axis)
void makeRotate (value_type angle, const Vec3d &axis)
void makeRotate (value_type angle, value_type x, value_type y, value_type z)
void makeRotate (const Quat &)
void makeRotate (value_type angle1, const Vec3f &axis1, value_type angle2, const Vec3f &axis2, value_type angle3, const Vec3f &axis3)
void makeRotate (value_type angle1, const Vec3d &axis1, value_type angle2, const Vec3d &axis2, value_type angle3, const Vec3d &axis3)
void decompose (osg::Vec3f &translation, osg::Quat &rotation, osg::Vec3f &scale, osg::Quat &so) const
decompose the matrix into translation, rotation, scale and scale orientation.
void decompose (osg::Vec3d &translation, osg::Quat &rotation, osg::Vec3d &scale, osg::Quat &so) const
decompose the matrix into translation, rotation, scale and scale orientation.
void makeOrtho (double left, double right, double bottom, double top, double zNear, double zFar)
Set to an orthographic projection.
bool getOrtho (double &left, double &right, double &bottom, double &top, double &zNear, double &zFar) const
Get the orthographic settings of the orthographic projection matrix.
void makeOrtho2D (double left, double right, double bottom, double top)
Set to a 2D orthographic projection.
void makeFrustum (double left, double right, double bottom, double top, double zNear, double zFar)
Set to a perspective projection.
bool getFrustum (double &left, double &right, double &bottom, double &top, double &zNear, double &zFar) const
Get the frustum settings of a perspective projection matrix.
void makePerspective (double fovy, double aspectRatio, double zNear, double zFar)
Set to a symmetrical perspective projection.
bool getPerspective (double &fovy, double &aspectRatio, double &zNear, double &zFar) const
Get the frustum settings of a symmetric perspective projection matrix.
void makeLookAt (const Vec3d &eye, const Vec3d &center, const Vec3d &up)
Set the position and orientation to be a view matrix, using the same convention as gluLookAt.
void getLookAt (Vec3f &eye, Vec3f &center, Vec3f &up, value_type lookDistance=1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
void getLookAt (Vec3d &eye, Vec3d &center, Vec3d &up, value_type lookDistance=1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
bool invert (const Matrixd &rhs)
invert the matrix rhs, automatically select invert_4x3 or invert_4x4.
bool invert_4x3 (const Matrixd &rhs)
4x3 matrix invert, not right hand column is assumed to be 0,0,0,1.
bool invert_4x4 (const Matrixd &rhs)
full 4x4 matrix invert.
void orthoNormalize (const Matrixd &rhs)
ortho-normalize the 3x3 rotation & scale matrix
Vec3f preMult (const Vec3f &v) const
Vec3d preMult (const Vec3d &v) const
Vec3f postMult (const Vec3f &v) const
Vec3d postMult (const Vec3d &v) const
Vec3f operator* (const Vec3f &v) const
Vec3d operator* (const Vec3d &v) const
Vec4f preMult (const Vec4f &v) const
Vec4d preMult (const Vec4d &v) const
Vec4f postMult (const Vec4f &v) const
Vec4d postMult (const Vec4d &v) const
Vec4f operator* (const Vec4f &v) const
Vec4d operator* (const Vec4d &v) const
void setRotate (const Quat &q)
Quat getRotate () const
Get the matrix rotation as a Quat.
void setTrans (value_type tx, value_type ty, value_type tz)
void setTrans (const Vec3f &v)
void setTrans (const Vec3d &v)
Vec3d getTrans () const
Vec3d getScale () const
void mult (const Matrixd &, const Matrixd &)
void preMult (const Matrixd &)
void postMult (const Matrixd &)
void preMultTranslate (const Vec3d &v)
Optimized version of preMult(translate(v));.
void preMultTranslate (const Vec3f &v)
void postMultTranslate (const Vec3d &v)
Optimized version of postMult(translate(v));.
void postMultTranslate (const Vec3f &v)
void preMultScale (const Vec3d &v)
Optimized version of preMult(scale(v));.
void preMultScale (const Vec3f &v)
void postMultScale (const Vec3d &v)
Optimized version of postMult(scale(v));.
void postMultScale (const Vec3f &v)
void preMultRotate (const Quat &q)
Optimized version of preMult(rotate(q));.
void postMultRotate (const Quat &q)
Optimized version of postMult(rotate(q));.
void operator*= (const Matrixd &other)
Matrixd operator* (const Matrixd &m) const
Static Public Member Functions
static Matrixd identity (void)
static Matrixd scale (const Vec3f &sv)
static Matrixd scale (const Vec3d &sv)
static Matrixd scale (value_type sx, value_type sy, value_type sz)
static Matrixd translate (const Vec3f &dv)
static Matrixd translate (const Vec3d &dv)
static Matrixd translate (value_type x, value_type y, value_type z)
static Matrixd rotate (const Vec3f &from, const Vec3f &to)
static Matrixd rotate (const Vec3d &from, const Vec3d &to)
static Matrixd rotate (value_type angle, value_type x, value_type y, value_type z)
static Matrixd rotate (value_type angle, const Vec3f &axis)
static Matrixd rotate (value_type angle, const Vec3d &axis)
static Matrixd rotate (value_type angle1, const Vec3f &axis1, value_type angle2, const Vec3f &axis2, value_type angle3, const Vec3f &axis3)
static Matrixd rotate (value_type angle1, const Vec3d &axis1, value_type angle2, const Vec3d &axis2, value_type angle3, const Vec3d &axis3)
static Matrixd rotate (const Quat &quat)
static Matrixd inverse (const Matrixd &matrix)
static Matrixd orthoNormal (const Matrixd &matrix)
static Matrixd ortho (double left, double right, double bottom, double top, double zNear, double zFar)
Create an orthographic projection matrix.
static Matrixd ortho2D (double left, double right, double bottom, double top)
Create a 2D orthographic projection.
static Matrixd frustum (double left, double right, double bottom, double top, double zNear, double zFar)
Create a perspective projection.
static Matrixd perspective (double fovy, double aspectRatio, double zNear, double zFar)
Create a symmetrical perspective projection.
static Matrixd lookAt (const Vec3f &eye, const Vec3f &center, const Vec3f &up)
Create the position and orientation as per a camera, using the same convention as gluLookAt.
static Matrixd lookAt (const Vec3d &eye, const Vec3d &center, const Vec3d &up)
Create the position and orientation as per a camera, using the same convention as gluLookAt.
static Vec3f transform3x3 (const Vec3f &v, const Matrixd &m)
apply a 3x3 transform of v*M[0..2,0..2].
static Vec3d transform3x3 (const Vec3d &v, const Matrixd &m)
apply a 3x3 transform of v*M[0..2,0..2].
static Vec3f transform3x3 (const Matrixd &m, const Vec3f &v)
apply a 3x3 transform of M[0..2,0..2]*v.
static Vec3d transform3x3 (const Matrixd &m, const Vec3d &v)
apply a 3x3 transform of M[0..2,0..2]*v.
Protected Attributes
value_type _mat [4][4]
Member Typedef Documentation
typedef double osg::Matrixd::value_type
Constructor & Destructor Documentation
osg::Matrixd::Matrixd () [inline]
Referenced by rotate().
osg::Matrixd::Matrixd (const Matrixd & mat) [inline]
References ptr().
osg::Matrixd::Matrixd (const Matrixf & mat)
osg::Matrixd::Matrixd (float const *const ptr) [inline, explicit]
osg::Matrixd::Matrixd (double const *const ptr) [inline, explicit]
osg::Matrixd::Matrixd (const Quat & quat) [inline, explicit]
osg::Matrixd::Matrixd (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
osg::Matrixd::~Matrixd () [inline]
Member Function Documentation
int osg::Matrixd::compare (const Matrixd & m) const
void osg::Matrixd::decompose (osg::Vec3f & translation, osg::Quat & rotation, osg::Vec3f & scale, osg::Quat & so) const
decompose the matrix into translation, rotation, scale and scale orientation.
void osg::Matrixd::decompose (osg::Vec3d & translation, osg::Quat & rotation, osg::Vec3d & scale, osg::Quat & so) const
decompose the matrix into translation, rotation, scale and scale orientation.
Matrixd osg::Matrixd::frustum (double left, double right, double bottom, double top, double zNear, double zFar) [inline, static]
Create a perspective projection.
See glFrustum for further details.
References makeFrustum().
bool osg::Matrixd::getFrustum (double & left, double & right, double & bottom, double & top, double & zNear, double & zFar) const
Get the frustum settings of a perspective projection matrix.
Note, if matrix is not a perspective matrix then invalid values will be returned.
void osg::Matrixd::getLookAt (Vec3f & eye, Vec3f & center, Vec3f & up, value_type lookDistance = 1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
Referenced by osgManipulator::PointerInfo::setCamera().
void osg::Matrixd::getLookAt (Vec3d & eye, Vec3d & center, Vec3d & up, value_type lookDistance = 1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
bool osg::Matrixd::getOrtho (double & left, double & right, double & bottom, double & top, double & zNear, double & zFar) const
Get the orthographic settings of the orthographic projection matrix.
Note, if matrix is not an orthographic matrix then invalid values will be returned.
bool osg::Matrixd::getPerspective (double & fovy, double & aspectRatio, double & zNear, double & zFar) const
Get the frustum settings of a symmetric perspective projection matrix.
Return false if matrix is not a perspective matrix, where parameter values are undefined. Note, if matrix is not a symmetric perspective matrix then the shear will be lost. Asymmetric matrices occur when stereo, power walls, caves and reality center display are used. In these configuration one should use the AsFrustum method instead.
Quat osg::Matrixd::getRotate () const
Get the matrix rotation as a Quat.
Note that this function assumes a non-scaled matrix and will return incorrect results for scaled matrixces. Consider decompose() instead.
Vec3d osg::Matrixd::getScale () const [inline]
References osg::Vec3d::length().
Vec3d osg::Matrixd::getTrans () const [inline]
Matrixd osg::Matrixd::identity (void) [inline, static]
References makeIdentity().
Referenced by osg::View::addSlave(), osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::computeMatrixForVertexSet(), and osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::computeMatrixForVertexSet().
Matrixd osg::Matrixd::inverse (const Matrixd & matrix) [inline, static]
References invert().
Referenced by osgGA::AnimationPathManipulator::getInverseMatrix(), osgUtil::LineSegmentIntersector::Intersection::getWorldIntersectNormal(), osgGA::TrackballManipulator::setByInverseMatrix(), osgGA::TerrainManipulator::setByInverseMatrix(), osgGA::NodeTrackerManipulator::setByInverseMatrix(), osgGA::FlightManipulator::setByInverseMatrix(), and osgGA::DriveManipulator::setByInverseMatrix().
bool osg::Matrixd::invert (const Matrixd & rhs) [inline]
invert the matrix rhs, automatically select invert_4x3 or invert_4x4.
References _mat.
Referenced by osgManipulator::Projector::getWorldToLocal(), inverse(), osgVolume::Locator::setTransform(), osgTerrain::Locator::setTransform(), osg::Polytope::transform(), and osg::Plane::transform().
bool osg::Matrixd::invert_4x3 (const Matrixd & rhs)
4x3 matrix invert, not right hand column is assumed to be 0,0,0,1.
bool osg::Matrixd::invert_4x4 (const Matrixd & rhs)
full 4x4 matrix invert.
bool osg::Matrixd::isIdentity () const [inline]
bool osg::Matrixd::isNaN () const [inline]
References osg::isNaN().
Matrixd osg::Matrixd::lookAt (const Vec3f & eye, const Vec3f & center, const Vec3f & up) [inline, static]
Create the position and orientation as per a camera, using the same convention as gluLookAt.
References makeLookAt().
Matrixd osg::Matrixd::lookAt (const Vec3d & eye, const Vec3d & center, const Vec3d & up) [inline, static]
Create the position and orientation as per a camera, using the same convention as gluLookAt.
References makeLookAt().
void osg::Matrixd::makeFrustum (double left, double right, double bottom, double top, double zNear, double zFar)
Set to a perspective projection.
See glFrustum for further details.
Referenced by frustum().
void osg::Matrixd::makeIdentity ()
Referenced by osg::Transform::computeLocalToWorldMatrix(), osg::Transform::computeWorldToLocalMatrix(), and identity().
void osg::Matrixd::makeLookAt (const Vec3d & eye, const Vec3d & center, const Vec3d & up)
Set the position and orientation to be a view matrix, using the same convention as gluLookAt.
Referenced by lookAt().
void osg::Matrixd::makeOrtho (double left, double right, double bottom, double top, double zNear, double zFar)
Set to an orthographic projection.
See glOrtho for further details.
Referenced by ortho().
void osg::Matrixd::makeOrtho2D (double left, double right, double bottom, double top) [inline]
Set to a 2D orthographic projection.
See glOrtho2D for further details.
Referenced by ortho2D().
void osg::Matrixd::makePerspective (double fovy, double aspectRatio, double zNear, double zFar)
Set to a symmetrical perspective projection.
See gluPerspective for further details. Aspect ratio is defined as width/height.
Referenced by perspective().
void osg::Matrixd::makeRotate (value_type angle1, const Vec3d & axis1, value_type angle2, const Vec3d & axis2, value_type angle3, const Vec3d & axis3)
void osg::Matrixd::makeRotate (value_type angle1, const Vec3f & axis1, value_type angle2, const Vec3f & axis2, value_type angle3, const Vec3f & axis3)
void osg::Matrixd::makeRotate (const Vec3f & from, const Vec3f & to)
Referenced by osg::AnimationPath::ControlPoint::getInverse(), osg::AnimationPath::ControlPoint::getMatrix(), and rotate().
void osg::Matrixd::makeRotate (const Vec3d & from, const Vec3d & to)
void osg::Matrixd::makeRotate (value_type angle, const Vec3f & axis)
void osg::Matrixd::makeRotate (value_type angle, const Vec3d & axis)
void osg::Matrixd::makeRotate (value_type angle, value_type x, value_type y, value_type z)
void osg::Matrixd::makeRotate (const Quat &)
void osg::Matrixd::makeScale (const Vec3f &)
Referenced by scale().
void osg::Matrixd::makeScale (const Vec3d &)
void osg::Matrixd::makeScale (value_type , value_type , value_type)
void osg::Matrixd::makeTranslate (const Vec3f &)
Referenced by osg::EllipsoidModel::computeLocalToWorldTransformFromXYZ(), and translate().
void osg::Matrixd::makeTranslate (const Vec3d &)
void osg::Matrixd::makeTranslate (value_type , value_type , value_type)
void osg::Matrixd::mult (const Matrixd & , const Matrixd &)
Referenced by operator*().
bool osg::Matrixd::operator!= (const Matrixd & m) const [inline]
value_type& osg::Matrixd::operator() (int row, int col) [inline]
value_type osg::Matrixd::operator() (int row, int col) const [inline]
Vec3f osg::Matrixd::operator* (const Vec3f & v) const [inline]
References postMult().
Vec3d osg::Matrixd::operator* (const Vec3d & v) const [inline]
References postMult().
Vec4f osg::Matrixd::operator* (const Vec4f & v) const [inline]
References postMult().
Vec4d osg::Matrixd::operator* (const Vec4d & v) const [inline]
References postMult().
Matrixd osg::Matrixd::operator* (const Matrixd & m) const [inline]
References mult().
void osg::Matrixd::operator*= (const Matrixd & other) [inline]
bool osg::Matrixd::operator< (const Matrixd & m) const [inline]
Matrixd& osg::Matrixd::operator= (const Matrixd & rhs) [inline]
References ptr().
Matrixd& osg::Matrixd::operator= (const Matrixf & other)
bool osg::Matrixd::operator== (const Matrixd & m) const [inline]
Matrixd osg::Matrixd::ortho (double left, double right, double bottom, double top, double zNear, double zFar) [inline, static]
Create an orthographic projection matrix.
See glOrtho for further details.
References makeOrtho().
Matrixd osg::Matrixd::ortho2D (double left, double right, double bottom, double top) [inline, static]
Create a 2D orthographic projection.
See glOrtho for further details.
References makeOrtho2D().
Matrixd osg::Matrixd::orthoNormal (const Matrixd & matrix) [inline, static]
References orthoNormalize().
void osg::Matrixd::orthoNormalize (const Matrixd & rhs)
ortho-normalize the 3x3 rotation & scale matrix
Referenced by orthoNormal().
Matrixd osg::Matrixd::perspective (double fovy, double aspectRatio, double zNear, double zFar) [inline, static]
Create a symmetrical perspective projection.
See gluPerspective for further details. Aspect ratio is defined as width/height.
References makePerspective().
Vec3f osg::Matrixd::postMult (const Vec3f & v) const [inline]
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by operator*(), postMultRotate(), and osgManipulator::PointerInfo::setCamera().
Vec3d osg::Matrixd::postMult (const Vec3d & v) const [inline]
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Vec4d osg::Matrixd::postMult (const Vec4d & v) const [inline]
References _mat, osg::Vec4d::w(), osg::Vec4d::x(), osg::Vec4d::y(), and osg::Vec4d::z().
void osg::Matrixd::postMult (const Matrixd &)
Vec4f osg::Matrixd::postMult (const Vec4f & v) const [inline]
References _mat, osg::Vec4f::w(), osg::Vec4f::x(), osg::Vec4f::y(), and osg::Vec4f::z().
void osg::Matrixd::postMultRotate (const Quat & q) [inline]
Optimized version of postMult(rotate(q));.
References postMult(), setRotate(), and osg::Quat::zeroRotation().
void osg::Matrixd::postMultScale (const Vec3d & v) [inline]
Optimized version of postMult(scale(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getInverse().
void osg::Matrixd::postMultScale (const Vec3f & v) [inline]
References _mat.
void osg::Matrixd::postMultTranslate (const Vec3d & v) [inline]
Optimized version of postMult(translate(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getMatrix().
void osg::Matrixd::postMultTranslate (const Vec3f & v) [inline]
References _mat.
Vec3f osg::Matrixd::preMult (const Vec3f & v) const [inline]
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by osg::operator*(), preMultRotate(), osgParticle::ParticleProcessor::rotateLocalToWorld(), osgParticle::ParticleProcessor::rotateWorldToLocal(), osgParticle::Particle::transformAngleVelocity(), osgParticle::ParticleProcessor::transformLocalToWorld(), osgParticle::Particle::transformPositionVelocity(), and osgParticle::ParticleProcessor::transformWorldToLocal().
void osg::Matrixd::preMult (const Matrixd &)
Vec3d osg::Matrixd::preMult (const Vec3d & v) const [inline]
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Vec4f osg::Matrixd::preMult (const Vec4f & v) const [inline]
References _mat, osg::Vec4f::w(), osg::Vec4f::x(), osg::Vec4f::y(), and osg::Vec4f::z().
Vec4d osg::Matrixd::preMult (const Vec4d & v) const [inline]
References _mat, osg::Vec4d::w(), osg::Vec4d::x(), osg::Vec4d::y(), and osg::Vec4d::z().
void osg::Matrixd::preMultRotate (const Quat & q) [inline]
Optimized version of preMult(rotate(q));.
References preMult(), setRotate(), and osg::Quat::zeroRotation().
void osg::Matrixd::preMultScale (const Vec3f & v) [inline]
References _mat.
void osg::Matrixd::preMultScale (const Vec3d & v) [inline]
Optimized version of preMult(scale(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getMatrix().
void osg::Matrixd::preMultTranslate (const Vec3f & v) [inline]
References _mat.
void osg::Matrixd::preMultTranslate (const Vec3d & v) [inline]
Optimized version of preMult(translate(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getInverse().
value_type* osg::Matrixd::ptr () [inline]
Referenced by osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::accummulateMatrix(), osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::accummulateMatrix(), osg::State::applyModelViewMatrix(), osg::State::applyProjectionMatrix(), Matrixd(), and operator=().
const value_type* osg::Matrixd::ptr () const [inline]
Matrixd osg::Matrixd::rotate (value_type angle1, const Vec3d & axis1, value_type angle2, const Vec3d & axis2, value_type angle3, const Vec3d & axis3) [inline, static]
References makeRotate().
Matrixd osg::Matrixd::rotate (value_type angle, value_type x, value_type y, value_type z) [inline, static]
References makeRotate().
Matrixd osg::Matrixd::rotate (const Quat & quat) [inline, static]
References Matrixd().
Matrixd osg::Matrixd::rotate (value_type angle, const Vec3d & axis) [inline, static]
References makeRotate().
Matrixd osg::Matrixd::rotate (value_type angle1, const Vec3f & axis1, value_type angle2, const Vec3f & axis2, value_type angle3, const Vec3f & axis3) [inline, static]
References makeRotate().
Matrixd osg::Matrixd::rotate (const Vec3f & from, const Vec3f & to) [inline, static]
References makeRotate().
Referenced by osgManipulator::Rotate3DCommand::getMotionMatrix().
Matrixd osg::Matrixd::rotate (const Vec3d & from, const Vec3d & to) [inline, static]
References makeRotate().
Matrixd osg::Matrixd::rotate (value_type angle, const Vec3f & axis) [inline, static]
References makeRotate().
Matrixd osg::Matrixd::scale (const Vec3d & sv) [inline, static]
References scale(), osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Matrixd osg::Matrixd::scale (value_type sx, value_type sy, value_type sz) [inline, static]
References makeScale().
Matrixd osg::Matrixd::scale (const Vec3f & sv) [inline, static]
References osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by osg::Viewport::computeWindowMatrix(), osgManipulator::ScaleUniformCommand::getMotionMatrix(), osgManipulator::Scale2DCommand::getMotionMatrix(), osgManipulator::Scale1DCommand::getMotionMatrix(), and scale().
void osg::Matrixd::set (float const *const ptr) [inline]
void osg::Matrixd::set (double const *const ptr) [inline]
void osg::Matrixd::set (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
void osg::Matrixd::set (const Matrixf & rhs)
void osg::Matrixd::set (const Matrixd & rhs) [inline]
Referenced by osg::CullStack::createOrReuseMatrix(), and osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::resetMatrix().
void osg::Matrixd::setRotate (const Quat & q)
Referenced by postMultRotate(), and preMultRotate().
void osg::Matrixd::setTrans (value_type tx, value_type ty, value_type tz)
void osg::Matrixd::setTrans (const Vec3d & v)
void osg::Matrixd::setTrans (const Vec3f & v)
Vec3f osg::Matrixd::transform3x3 (const Vec3f & v, const Matrixd & m) [inline, static]
apply a 3x3 transform of v*M[0..2,0..2].
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by osgAnimation::TransformVertexFunctor::computeNormal(), osgAnimation::RigTransformSoftware::computeNormal(), osgUtil::LineSegmentIntersector::Intersection::getWorldIntersectNormal(), and osgParticle::Particle::transformPositionVelocity().
Vec3f osg::Matrixd::transform3x3 (const Matrixd & m, const Vec3f & v) [inline, static]
apply a 3x3 transform of M[0..2,0..2]*v.
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Vec3d osg::Matrixd::transform3x3 (const Matrixd & m, const Vec3d & v) [inline, static]
apply a 3x3 transform of M[0..2,0..2]*v.
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Vec3d osg::Matrixd::transform3x3 (const Vec3d & v, const Matrixd & m) [inline, static]
apply a 3x3 transform of v*M[0..2,0..2].
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Matrixd osg::Matrixd::translate (const Vec3d & dv) [inline, static]
References translate(), osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Matrixd osg::Matrixd::translate (const Vec3f & dv) [inline, static]
References osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by osg::Viewport::computeWindowMatrix(), osgManipulator::ScaleUniformCommand::getMotionMatrix(), osgManipulator::Scale2DCommand::getMotionMatrix(), osgManipulator::Scale1DCommand::getMotionMatrix(), osgManipulator::TranslateInPlaneCommand::getMotionMatrix(), osgManipulator::TranslateInLineCommand::getMotionMatrix(), and translate().
Matrixd osg::Matrixd::translate (value_type x, value_type y, value_type z) [inline, static]
References makeTranslate().
bool osg::Matrixd::valid () const [inline]
References osg::isNaN().
Member Data Documentation
value_type osg::Matrixd::_mat[4][4] [protected]
Referenced by invert(), postMult(), postMultScale(), postMultTranslate(), preMult(), preMultScale(), preMultTranslate(), and transform3x3().
The documentation for this class was generated from the following file:
osg/Matrixd
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.