OpenSceneGraph: osgDB::IntLookup Class Reference
osgDB::IntLookup Class Reference
Public Types
typedef int Value
typedef std::map< std::string,
Value > StringToValue
typedef std::map< Value,
std::string > ValueToString
Public Member Functions
IntLookup (Value defaultValue)
void add (Value value, const char *str)
Value getValue (const char *str)
const std::string & getString (Value value)
Public Attributes
StringToValue _stringToValue
ValueToString _valueToString
Value _default
Member Typedef Documentation
typedef std::map<std::string, Value> osgDB::IntLookup::StringToValue
typedef int osgDB::IntLookup::Value
typedef std::map<Value, std::string> osgDB::IntLookup::ValueToString
Constructor & Destructor Documentation
osgDB::IntLookup::IntLookup (Value defaultValue) [inline]
Member Function Documentation
void osgDB::IntLookup::add (Value value, const char * str) [inline]
References _stringToValue, and _valueToString.
Referenced by osgDB::EnumSerializer< C, P >::add().
const std::string& osgDB::IntLookup::getString (Value value) [inline]
References _default, and _valueToString.
Referenced by osgDB::EnumSerializer< C, P >::getString().
Value osgDB::IntLookup::getValue (const char * str) [inline]
References _default, and _stringToValue.
Referenced by osgDB::EnumSerializer< C, P >::getValue().
Member Data Documentation
Value osgDB::IntLookup::_default
Referenced by getString(), and getValue().
StringToValue osgDB::IntLookup::_stringToValue
Referenced by add(), and getValue().
ValueToString osgDB::IntLookup::_valueToString
Referenced by add(), and getString().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.