OpenSceneGraph: osgDB::ParameterOutput Class Reference
osgDB::ParameterOutput Class Reference
Public Member Functions
ParameterOutput (Output &fw)
ParameterOutput (Output &fw, int numItemsPerLine)
void begin ()
void newLine ()
void end ()
template<class T >
void write (const T &t)
template<class Iterator >
void write (Iterator first, Iterator last)
template<class Iterator >
void writeAsInts (Iterator first, Iterator last)
Protected Member Functions
ParameterOutput & operator= (const ParameterOutput &)
Protected Attributes
Output & _fw
int _numItemsPerLine
int _column
Constructor & Destructor Documentation
osgDB::ParameterOutput::ParameterOutput (Output & fw) [inline]
osgDB::ParameterOutput::ParameterOutput (Output & fw, int numItemsPerLine) [inline]
Member Function Documentation
void osgDB::ParameterOutput::begin () [inline]
References _fw, osgDB::Output::indent(), and osgDB::Output::moveIn().
void osgDB::ParameterOutput::end () [inline]
References _column, _fw, osgDB::Output::indent(), and osgDB::Output::moveOut().
void osgDB::ParameterOutput::newLine () [inline]
References _column, and _fw.
ParameterOutput& osgDB::ParameterOutput::operator= (const ParameterOutput &) [inline, protected]
template<class T > void osgDB::ParameterOutput::write (const T & t) [inline]
References _column, _fw, _numItemsPerLine, and osgDB::Output::indent().
Referenced by write(), and writeAsInts().
template<class Iterator > void osgDB::ParameterOutput::write (Iterator first, Iterator last) [inline]
References write().
template<class Iterator > void osgDB::ParameterOutput::writeAsInts (Iterator first, Iterator last) [inline]
References write().
Member Data Documentation
int osgDB::ParameterOutput::_column [protected]
Referenced by end(), newLine(), and write().
Output& osgDB::ParameterOutput::_fw [protected]
Referenced by begin(), end(), newLine(), and write().
int osgDB::ParameterOutput::_numItemsPerLine [protected]
Referenced by write().
The documentation for this class was generated from the following file:
osgDB/ParameterOutput
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.