OpenSceneGraph: osg::Program::PerContextProgram Class Reference
osg::Program::PerContextProgram Class Reference
PerContextProgram (PCP) is an OSG-internal encapsulation of glPrograms per-GL context.
Public Member Functions
PerContextProgram (const Program *program, unsigned int contextID)
GLuint getHandle () const
void requestLink ()
void linkProgram ()
bool validateProgram ()
bool needsLink () const
bool isLinked () const
bool getInfoLog (std::string &infoLog) const
void useProgram () const
void resetAppliedUniforms () const
void apply (const Uniform &uniform) const
const ActiveUniformMap & getActiveUniforms () const
const ActiveVarInfoMap & getActiveAttribs () const
GLint getUniformLocation (unsigned int uniformNameID) const
GLint getUniformLocation (const std::string &uniformName) const
Alternative version of getUniformLocation(unsigned int uniformNameID) retrofited into OSG for backward compatibility with osgCal, after uniform ids were refactored from std::strings to GLints in OSG version 2.9.10.
GLint getAttribLocation (const std::string &name) const
void addShaderToAttach (Shader *shader)
void addShaderToDetach (Shader *shader)
Protected Types
typedef std::pair
< osg::ref_ptr< const
osg::Uniform >, unsigned int > UniformModifiedCountPair
typedef std::vector
< UniformModifiedCountPair > LastAppliedUniformList
typedef std::vector< ref_ptr
< Shader > > ShaderList
Protected Member Functions
~PerContextProgram ()
Protected Attributes
const Program * _program
Pointer to our parent Program.
osg::ref_ptr< GL2Extensions > _extensions
Pointer to this context's extension functions.
GLuint _glProgramHandle
Handle to the actual OpenGL glProgram.
bool _needsLink
Does our glProgram need to be linked?
bool _isLinked
Is our glProgram successfully linked?
const unsigned int _contextID
ActiveUniformMap _uniformInfoMap
ActiveVarInfoMap _attribInfoMap
LastAppliedUniformList _lastAppliedUniformList
ShaderList _shadersToDetach
ShaderList _shadersToAttach
Detailed Description
PerContextProgram (PCP) is an OSG-internal encapsulation of glPrograms per-GL context.
Member Typedef Documentation
typedef std::vector<UniformModifiedCountPair> osg::Program::PerContextProgram::LastAppliedUniformList [protected]
typedef std::vector< ref_ptr<Shader> > osg::Program::PerContextProgram::ShaderList [protected]
typedef std::pair<osg::ref_ptr<const osg::Uniform>, unsigned int> osg::Program::PerContextProgram::UniformModifiedCountPair [protected]
Constructor & Destructor Documentation
osg::Program::PerContextProgram::PerContextProgram (const Program * program, unsigned int contextID)
osg::Program::PerContextProgram::~PerContextProgram () [protected]
Member Function Documentation
void osg::Program::PerContextProgram::addShaderToAttach (Shader * shader) [inline]
void osg::Program::PerContextProgram::addShaderToDetach (Shader * shader) [inline]
void osg::Program::PerContextProgram::apply (const Uniform & uniform) const [inline]
References osg::Uniform::apply(), osg::Uniform::getModifiedCount(), and osg::Uniform::getNameID().
Referenced by osg::State::applyUniformList(), and osg::State::applyUniformMap().
const ActiveVarInfoMap& osg::Program::PerContextProgram::getActiveAttribs () const [inline]
const ActiveUniformMap& osg::Program::PerContextProgram::getActiveUniforms () const [inline]
GLint osg::Program::PerContextProgram::getAttribLocation (const std::string & name) const [inline]
GLuint osg::Program::PerContextProgram::getHandle () const [inline]
bool osg::Program::PerContextProgram::getInfoLog (std::string & infoLog) const
GLint osg::Program::PerContextProgram::getUniformLocation (unsigned int uniformNameID) const [inline]
GLint osg::Program::PerContextProgram::getUniformLocation (const std::string & uniformName) const [inline]
Alternative version of getUniformLocation(unsigned int uniformNameID) retrofited into OSG for backward compatibility with osgCal, after uniform ids were refactored from std::strings to GLints in OSG version 2.9.10.
Drawbacks: This method is not particularly fast. It has to access mutexed static map of uniform ids. So don't overuse it or your app performance will suffer.
References osg::Uniform::getNameID(), and getUniformLocation().
Referenced by getUniformLocation().
bool osg::Program::PerContextProgram::isLinked () const [inline]
void osg::Program::PerContextProgram::linkProgram ()
bool osg::Program::PerContextProgram::needsLink () const [inline]
void osg::Program::PerContextProgram::requestLink ()
void osg::Program::PerContextProgram::resetAppliedUniforms () const [inline]
void osg::Program::PerContextProgram::useProgram () const
bool osg::Program::PerContextProgram::validateProgram ()
Member Data Documentation
ActiveVarInfoMap osg::Program::PerContextProgram::_attribInfoMap [protected]
const unsigned int osg::Program::PerContextProgram::_contextID [protected]
osg::ref_ptr<GL2Extensions> osg::Program::PerContextProgram::_extensions [protected]
Pointer to this context's extension functions.
GLuint osg::Program::PerContextProgram::_glProgramHandle [protected]
Handle to the actual OpenGL glProgram.
bool osg::Program::PerContextProgram::_isLinked [protected]
Is our glProgram successfully linked?
LastAppliedUniformList osg::Program::PerContextProgram::_lastAppliedUniformList [mutable, protected]
bool osg::Program::PerContextProgram::_needsLink [protected]
Does our glProgram need to be linked?
const Program* osg::Program::PerContextProgram::_program [protected]
Pointer to our parent Program.
ShaderList osg::Program::PerContextProgram::_shadersToAttach [protected]
ShaderList osg::Program::PerContextProgram::_shadersToDetach [protected]
ActiveUniformMap osg::Program::PerContextProgram::_uniformInfoMap [protected]
The documentation for this class was generated from the following file:
osg/Program
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.