OpenSceneGraph: osgFX::Registry Class Reference
osgFX::Registry Class Reference
Classes
struct Proxy
Public Types
typedef std::map< std::string,
osg::ref_ptr< const Effect > > EffectMap
Public Member Functions
void registerEffect (const Effect *effect)
const EffectMap & getEffectMap () const
Static Public Member Functions
static Registry * instance ()
Protected Member Functions
Registry ()
~Registry ()
Member Typedef Documentation
typedef std::map<std::string, osg::ref_ptr<const Effect> > osgFX::Registry::EffectMap
Constructor & Destructor Documentation
osgFX::Registry::Registry () [protected]
osgFX::Registry::~Registry () [inline, protected]
Member Function Documentation
const Registry::EffectMap & osgFX::Registry::getEffectMap () const [inline]
static Registry* osgFX::Registry::instance () [static]
Referenced by osgFX::Registry::Proxy::Proxy().
void osgFX::Registry::registerEffect (const Effect * effect) [inline]
References osgFX::Effect::effectName().
Referenced by osgFX::Registry::Proxy::Proxy().
The documentation for this class was generated from the following file:
osgFX/Registry
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.