OpenSceneGraph: osg::RenderInfo Class Reference
osg::RenderInfo Class Reference
Public Member Functions
RenderInfo ()
RenderInfo (const RenderInfo &rhs)
RenderInfo (State *state, View *view)
RenderInfo & operator= (const RenderInfo &rhs)
unsigned int getContextID () const
void setState (State *state)
State * getState ()
const State * getState () const
void setView (View *view)
View * getView ()
const View * getView () const
void pushCamera (Camera *camera)
void popCamera ()
Camera * getCurrentCamera ()
void setUserData (Referenced *userData)
Referenced * getUserData ()
const Referenced * getUserData () const
Protected Types
typedef std::vector< Camera * > Cameras
Protected Attributes
ref_ptr< State > _state
observer_ptr< View > _view
Cameras _cameras
ref_ptr< Referenced > _userData
Member Typedef Documentation
typedef std::vector<Camera*> osg::RenderInfo::Cameras [protected]
Constructor & Destructor Documentation
osg::RenderInfo::RenderInfo () [inline]
osg::RenderInfo::RenderInfo (const RenderInfo & rhs) [inline]
osg::RenderInfo::RenderInfo (State * state, View * view) [inline]
Member Function Documentation
unsigned int osg::RenderInfo::getContextID () const [inline]
References _state, and osg::ref_ptr< T >::valid().
Referenced by osg::Drawable::draw().
Camera* osg::RenderInfo::getCurrentCamera () [inline]
References _cameras.
State* osg::RenderInfo::getState () [inline]
References _state, and osg::ref_ptr< T >::get().
Referenced by osg::Drawable::CullCallback::cull(), and osg::Drawable::draw().
const State* osg::RenderInfo::getState () const [inline]
References _state, and osg::ref_ptr< T >::get().
Referenced* osg::RenderInfo::getUserData () [inline]
References _userData, and osg::ref_ptr< T >::get().
const Referenced* osg::RenderInfo::getUserData () const [inline]
References _userData, and osg::ref_ptr< T >::get().
const View* osg::RenderInfo::getView () const [inline]
References _view, and osg::observer_ptr< T >::get().
View* osg::RenderInfo::getView () [inline]
References _view, and osg::observer_ptr< T >::get().
RenderInfo& osg::RenderInfo::operator= (const RenderInfo & rhs) [inline]
References _cameras, _state, _userData, and _view.
void osg::RenderInfo::popCamera () [inline]
References _cameras.
void osg::RenderInfo::pushCamera (Camera * camera) [inline]
References _cameras.
void osg::RenderInfo::setState (State * state) [inline]
References _state.
void osg::RenderInfo::setUserData (Referenced * userData) [inline]
References _userData.
void osg::RenderInfo::setView (View * view) [inline]
References _view.
Member Data Documentation
Cameras osg::RenderInfo::_cameras [protected]
Referenced by getCurrentCamera(), operator=(), popCamera(), and pushCamera().
ref_ptr<State> osg::RenderInfo::_state [protected]
Referenced by getContextID(), getState(), operator=(), and setState().
ref_ptr<Referenced> osg::RenderInfo::_userData [protected]
Referenced by getUserData(), operator=(), and setUserData().
observer_ptr<View> osg::RenderInfo::_view [protected]
Referenced by getView(), operator=(), and setView().
The documentation for this class was generated from the following file:
osg/RenderInfo
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.