OpenSceneGraph: osgDB::RegisterReaderWriterProxy< T > Class Template Reference
osgDB::RegisterReaderWriterProxy< T > Class Template Reference
Proxy class for automatic registration of reader/writers with the Registry.
Public Member Functions
RegisterReaderWriterProxy ()
~RegisterReaderWriterProxy ()
T * get ()
Protected Attributes
osg::ref_ptr< T > _rw
Detailed Description
template<class T>
class osgDB::RegisterReaderWriterProxy< T >
Proxy class for automatic registration of reader/writers with the Registry.
Constructor & Destructor Documentation
template<class T> osgDB::RegisterReaderWriterProxy< T >::RegisterReaderWriterProxy () [inline]
References osgDB::RegisterReaderWriterProxy< T >::_rw, osgDB::Registry::addReaderWriter(), and osgDB::Registry::instance().
template<class T> osgDB::RegisterReaderWriterProxy< T >::~RegisterReaderWriterProxy () [inline]
References osgDB::RegisterReaderWriterProxy< T >::_rw, osgDB::Registry::instance(), and osgDB::Registry::removeReaderWriter().
Member Function Documentation
template<class T> T* osgDB::RegisterReaderWriterProxy< T >::get () [inline]
References osgDB::RegisterReaderWriterProxy< T >::_rw.
Member Data Documentation
template<class T> osg::ref_ptr<T> osgDB::RegisterReaderWriterProxy< T >::_rw [protected]
Referenced by osgDB::RegisterReaderWriterProxy< T >::get(), osgDB::RegisterReaderWriterProxy< T >::RegisterReaderWriterProxy(), and osgDB::RegisterReaderWriterProxy< T >::~RegisterReaderWriterProxy().
The documentation for this class was generated from the following file:
osgDB/Registry
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.