OpenSceneGraph: osgDB::Registry::ReadFileCallback Class Reference
osgDB::Registry::ReadFileCallback Class Reference
Public Member Functions
virtual ReaderWriter::ReadResult openArchive (const std::string &filename, ReaderWriter::ArchiveStatus status, unsigned int indexBlockSizeHint, const ReaderWriter::Options *useObjectCache)
virtual ReaderWriter::ReadResult readObject (const std::string &filename, const ReaderWriter::Options *options)
virtual ReaderWriter::ReadResult readImage (const std::string &filename, const ReaderWriter::Options *options)
virtual ReaderWriter::ReadResult readHeightField (const std::string &filename, const ReaderWriter::Options *options)
virtual ReaderWriter::ReadResult readNode (const std::string &filename, const ReaderWriter::Options *options)
virtual ReaderWriter::ReadResult readShader (const std::string &filename, const ReaderWriter::Options *options)
Protected Member Functions
virtual ~ReadFileCallback ()
Constructor & Destructor Documentation
virtual osgDB::Registry::ReadFileCallback::~ReadFileCallback () [inline, protected, virtual]
Member Function Documentation
virtual ReaderWriter::ReadResult osgDB::Registry::ReadFileCallback::openArchive (const std::string & filename, ReaderWriter::ArchiveStatus status, unsigned int indexBlockSizeHint, const ReaderWriter::Options * useObjectCache) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::openArchiveImplementation().
virtual ReaderWriter::ReadResult osgDB::Registry::ReadFileCallback::readHeightField (const std::string & filename, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::readHeightFieldImplementation().
virtual ReaderWriter::ReadResult osgDB::Registry::ReadFileCallback::readImage (const std::string & filename, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::readImageImplementation().
virtual ReaderWriter::ReadResult osgDB::Registry::ReadFileCallback::readNode (const std::string & filename, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::readNodeImplementation().
virtual ReaderWriter::ReadResult osgDB::Registry::ReadFileCallback::readObject (const std::string & filename, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::readObjectImplementation().
virtual ReaderWriter::ReadResult osgDB::Registry::ReadFileCallback::readShader (const std::string & filename, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::readShaderImplementation().
The documentation for this class was generated from the following file:
osgDB/Registry
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.