OpenSceneGraph: osg::RenderBuffer Class Reference
osg::RenderBuffer Class Reference
Public Member Functions
RenderBuffer ()
RenderBuffer (int width, int height, GLenum internalFormat, int samples=0, int colorSamples=0)
RenderBuffer (const RenderBuffer &copy, const CopyOp &copyop=CopyOp::SHALLOW_COPY)
META_Object (osg, RenderBuffer)
int getWidth () const
int getHeight () const
void setWidth (int w)
void setHeight (int h)
void setSize (int w, int h)
GLenum getInternalFormat () const
void setInternalFormat (GLenum format)
int getSamples () const
int getColorSamples () const
void setSamples (int samples)
void setColorSamples (int colorSamples)
GLuint getObjectID (unsigned int contextID, const FBOExtensions *ext) const
int compare (const RenderBuffer &rb) const
Static Public Member Functions
static void deleteRenderBuffer (unsigned int contextID, GLuint rb)
Mark internal RenderBuffer for deletion.
static void flushDeletedRenderBuffers (unsigned int contextID, double currentTime, double &availableTime)
flush all the cached RenderBuffers which need to be deleted in the OpenGL context related to contextID.
static void discardDeletedRenderBuffers (unsigned int contextID)
discard all the cached RenderBuffers which need to be deleted in the OpenGL context related to contextID.
static int getMaxSamples (unsigned int contextID, const FBOExtensions *ext)
Protected Member Functions
virtual ~RenderBuffer ()
RenderBuffer & operator= (const RenderBuffer &)
void dirtyAll () const
Constructor & Destructor Documentation
osg::RenderBuffer::RenderBuffer ()
osg::RenderBuffer::RenderBuffer (int width, int height, GLenum internalFormat, int samples = 0, int colorSamples = 0)
osg::RenderBuffer::RenderBuffer (const RenderBuffer & copy, const CopyOp & copyop = CopyOp::SHALLOW_COPY)
virtual osg::RenderBuffer::~RenderBuffer () [protected, virtual]
Member Function Documentation
int osg::RenderBuffer::compare (const RenderBuffer & rb) const [inline]
static void osg::RenderBuffer::deleteRenderBuffer (unsigned int contextID, GLuint rb) [static]
Mark internal RenderBuffer for deletion.
Deletion requests are queued until they can be executed in the proper GL context.
void osg::RenderBuffer::dirtyAll () const [inline, protected]
References osg::buffered_value< T >::setAllElementsTo().
Referenced by setColorSamples(), setHeight(), setInternalFormat(), setSamples(), setSize(), and setWidth().
static void osg::RenderBuffer::discardDeletedRenderBuffers (unsigned int contextID) [static]
discard all the cached RenderBuffers which need to be deleted in the OpenGL context related to contextID.
Note, unlike flush no OpenGL calls are made, instead the handles are all removed. this call is useful for when an OpenGL context has been destroyed.
static void osg::RenderBuffer::flushDeletedRenderBuffers (unsigned int contextID, double currentTime, double & availableTime) [static]
flush all the cached RenderBuffers which need to be deleted in the OpenGL context related to contextID.
int osg::RenderBuffer::getColorSamples () const [inline]
int osg::RenderBuffer::getHeight () const [inline]
GLenum osg::RenderBuffer::getInternalFormat () const [inline]
static int osg::RenderBuffer::getMaxSamples (unsigned int contextID, const FBOExtensions * ext) [static]
GLuint osg::RenderBuffer::getObjectID (unsigned int contextID, const FBOExtensions * ext) const
int osg::RenderBuffer::getSamples () const [inline]
int osg::RenderBuffer::getWidth () const [inline]
osg::RenderBuffer::META_Object (osg , RenderBuffer)
RenderBuffer& osg::RenderBuffer::operator= (const RenderBuffer &) [inline, protected]
void osg::RenderBuffer::setColorSamples (int colorSamples) [inline]
References dirtyAll().
void osg::RenderBuffer::setHeight (int h) [inline]
References dirtyAll().
void osg::RenderBuffer::setInternalFormat (GLenum format) [inline]
References dirtyAll().
void osg::RenderBuffer::setSamples (int samples) [inline]
References dirtyAll().
void osg::RenderBuffer::setSize (int w, int h) [inline]
References dirtyAll().
void osg::RenderBuffer::setWidth (int w) [inline]
References dirtyAll().
The documentation for this class was generated from the following file:
osg/FrameBufferObject
Generated at Thu Jun 9 2011 16:37:14 for the OpenSceneGraph by doxygen 1.7.1.