OpenSceneGraph: osgUtil::RenderBin Class Reference
osgUtil::RenderBin Class Reference
RenderBin base class.
Classes
struct DrawCallback
struct SortCallback
Public Types
enum SortMode { SORT_BY_STATE, SORT_BY_STATE_THEN_FRONT_TO_BACK, SORT_FRONT_TO_BACK, SORT_BACK_TO_FRONT }
typedef std::vector< RenderLeaf * > RenderLeafList
typedef std::vector< StateGraph * > StateGraphList
typedef std::map< int,
osg::ref_ptr< RenderBin > > RenderBinList
Public Member Functions
RenderBin ()
RenderBin (SortMode mode)
RenderBin (const RenderBin &rhs, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
virtual osg::Object * cloneType () const
Clone the type of an object, with Object* return type.
virtual osg::Object * clone (const osg::CopyOp &copyop) const
Clone an object, with Object* return type.
virtual bool isSameKindAs (const osg::Object *obj) const
virtual const char * libraryName () const
return the name of the object's library.
virtual const char * className () const
return the name of the object's class type.
virtual void reset ()
void setStateSet (osg::StateSet *stateset)
osg::StateSet * getStateSet ()
const osg::StateSet * getStateSet () const
RenderBin * getParent ()
const RenderBin * getParent () const
RenderStage * getStage ()
const RenderStage * getStage () const
int getBinNum () const
StateGraphList & getStateGraphList ()
const StateGraphList & getStateGraphList () const
RenderBinList & getRenderBinList ()
const RenderBinList & getRenderBinList () const
RenderLeafList & getRenderLeafList ()
const RenderLeafList & getRenderLeafList () const
RenderBin * find_or_insert (int binNum, const std::string &binName)
void addStateGraph (StateGraph *rg)
virtual void sort ()
virtual void sortImplementation ()
void setSortMode (SortMode mode)
SortMode getSortMode () const
virtual void sortByState ()
virtual void sortByStateThenFrontToBack ()
virtual void sortFrontToBack ()
virtual void sortBackToFront ()
void setSortCallback (SortCallback *sortCallback)
SortCallback * getSortCallback ()
const SortCallback * getSortCallback () const
virtual void draw (osg::RenderInfo &renderInfo, RenderLeaf *&previous)
virtual void drawImplementation (osg::RenderInfo &renderInfo, RenderLeaf *&previous)
void setDrawCallback (DrawCallback *drawCallback)
DrawCallback * getDrawCallback ()
const DrawCallback * getDrawCallback () const
bool getStats (Statistics &primStats) const
Extract stats for current draw list.
virtual unsigned int computeNumberOfDynamicRenderLeaves () const
Compute the number of dynamic RenderLeaves.
void copyLeavesFromStateGraphListToRenderLeafList ()
Static Public Member Functions
static RenderBin * createRenderBin (const std::string &binName)
static RenderBin * getRenderBinPrototype (const std::string &binName)
static void addRenderBinPrototype (const std::string &binName, RenderBin *proto)
static void removeRenderBinPrototype (RenderBin *proto)
static void setDefaultRenderBinSortMode (SortMode mode)
static SortMode getDefaultRenderBinSortMode ()
Protected Member Functions
virtual ~RenderBin ()
Protected Attributes
int _binNum
RenderBin * _parent
RenderStage * _stage
RenderBinList _bins
StateGraphList _stateGraphList
RenderLeafList _renderLeafList
bool _sorted
SortMode _sortMode
osg::ref_ptr< SortCallback > _sortCallback
osg::ref_ptr< DrawCallback > _drawCallback
osg::ref_ptr< osg::StateSet > _stateset
Detailed Description
RenderBin base class.
Renderbin contains geometries to be rendered as a group, renderbins are rendered once each. They can improve efficiency or use different rendering algorithms. A renderBin can contain further renderBins producing a tree hierarchy of renderBins.
Member Typedef Documentation
typedef std::map< int, osg::ref_ptr<RenderBin> > osgUtil::RenderBin::RenderBinList
typedef std::vector<RenderLeaf*> osgUtil::RenderBin::RenderLeafList
typedef std::vector<StateGraph*> osgUtil::RenderBin::StateGraphList
Member Enumeration Documentation
enum osgUtil::RenderBin::SortMode
Enumerator:
SORT_BY_STATE
SORT_BY_STATE_THEN_FRONT_TO_BACK
SORT_FRONT_TO_BACK
SORT_BACK_TO_FRONT
Constructor & Destructor Documentation
osgUtil::RenderBin::RenderBin ()
osgUtil::RenderBin::RenderBin (SortMode mode)
osgUtil::RenderBin::RenderBin (const RenderBin & rhs, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
virtual osgUtil::RenderBin::~RenderBin () [protected, virtual]
Member Function Documentation
static void osgUtil::RenderBin::addRenderBinPrototype (const std::string & binName, RenderBin * proto) [static]
Referenced by osgUtil::RegisterRenderBinProxy::RegisterRenderBinProxy().
void osgUtil::RenderBin::addStateGraph (StateGraph * rg) [inline]
Referenced by osgUtil::CullVisitor::addDrawable(), and osgUtil::CullVisitor::addDrawableAndDepth().
virtual const char* osgUtil::RenderBin::className () const [inline, virtual]
return the name of the object's class type.
Must be defined by derived classes.
Implements osg::Object.
Reimplemented in osgUtil::RenderStage.
virtual osg::Object* osgUtil::RenderBin::clone (const osg::CopyOp &) const [inline, virtual]
Clone an object, with Object* return type.
Must be defined by derived classes.
Implements osg::Object.
Reimplemented in osgUtil::RenderStage.
virtual osg::Object* osgUtil::RenderBin::cloneType () const [inline, virtual]
Clone the type of an object, with Object* return type.
Must be defined by derived classes.
Implements osg::Object.
Reimplemented in osgUtil::RenderStage.
virtual unsigned int osgUtil::RenderBin::computeNumberOfDynamicRenderLeaves () const [virtual]
Compute the number of dynamic RenderLeaves.
Reimplemented in osgUtil::RenderStage.
void osgUtil::RenderBin::copyLeavesFromStateGraphListToRenderLeafList ()
static RenderBin* osgUtil::RenderBin::createRenderBin (const std::string & binName) [static]
virtual void osgUtil::RenderBin::draw (osg::RenderInfo & renderInfo, RenderLeaf *& previous) [virtual]
Reimplemented in osgUtil::RenderStage.
virtual void osgUtil::RenderBin::drawImplementation (osg::RenderInfo & renderInfo, RenderLeaf *& previous) [virtual]
Reimplemented in osgUtil::RenderStage.
RenderBin* osgUtil::RenderBin::find_or_insert (int binNum, const std::string & binName)
int osgUtil::RenderBin::getBinNum () const [inline]
static SortMode osgUtil::RenderBin::getDefaultRenderBinSortMode () [static]
DrawCallback* osgUtil::RenderBin::getDrawCallback () [inline]
const DrawCallback* osgUtil::RenderBin::getDrawCallback () const [inline]
RenderBin* osgUtil::RenderBin::getParent () [inline]
const RenderBin* osgUtil::RenderBin::getParent () const [inline]
RenderBinList& osgUtil::RenderBin::getRenderBinList () [inline]
const RenderBinList& osgUtil::RenderBin::getRenderBinList () const [inline]
static RenderBin* osgUtil::RenderBin::getRenderBinPrototype (const std::string & binName) [static]
RenderLeafList& osgUtil::RenderBin::getRenderLeafList () [inline]
const RenderLeafList& osgUtil::RenderBin::getRenderLeafList () const [inline]
SortCallback* osgUtil::RenderBin::getSortCallback () [inline]
const SortCallback* osgUtil::RenderBin::getSortCallback () const [inline]
SortMode osgUtil::RenderBin::getSortMode () const [inline]
RenderStage* osgUtil::RenderBin::getStage () [inline]
Referenced by osgUtil::CullVisitor::addPositionedAttribute(), osgUtil::CullVisitor::addPositionedTextureAttribute(), and osgUtil::CullVisitor::getCurrentRenderStage().
const RenderStage* osgUtil::RenderBin::getStage () const [inline]
StateGraphList& osgUtil::RenderBin::getStateGraphList () [inline]
const StateGraphList& osgUtil::RenderBin::getStateGraphList () const [inline]
osg::StateSet* osgUtil::RenderBin::getStateSet () [inline]
const osg::StateSet* osgUtil::RenderBin::getStateSet () const [inline]
bool osgUtil::RenderBin::getStats (Statistics & primStats) const
Extract stats for current draw list.
Reimplemented in osgUtil::RenderStage.
virtual bool osgUtil::RenderBin::isSameKindAs (const osg::Object * obj) const [inline, virtual]
Reimplemented from osg::Object.
Reimplemented in osgUtil::RenderStage.
virtual const char* osgUtil::RenderBin::libraryName () const [inline, virtual]
return the name of the object's library.
Must be defined by derived classes. The OpenSceneGraph convention is that the namespace of a library is the same as the library name.
Implements osg::Object.
static void osgUtil::RenderBin::removeRenderBinPrototype (RenderBin * proto) [static]
Referenced by osgUtil::RegisterRenderBinProxy::~RegisterRenderBinProxy().
virtual void osgUtil::RenderBin::reset () [virtual]
Reimplemented in osgUtil::RenderStage.
static void osgUtil::RenderBin::setDefaultRenderBinSortMode (SortMode mode) [static]
void osgUtil::RenderBin::setDrawCallback (DrawCallback * drawCallback) [inline]
void osgUtil::RenderBin::setSortCallback (SortCallback * sortCallback) [inline]
void osgUtil::RenderBin::setSortMode (SortMode mode)
void osgUtil::RenderBin::setStateSet (osg::StateSet * stateset) [inline]
virtual void osgUtil::RenderBin::sort () [virtual]
Reimplemented in osgUtil::RenderStage.
virtual void osgUtil::RenderBin::sortBackToFront () [virtual]
virtual void osgUtil::RenderBin::sortByState () [virtual]
virtual void osgUtil::RenderBin::sortByStateThenFrontToBack () [virtual]
virtual void osgUtil::RenderBin::sortFrontToBack () [virtual]
virtual void osgUtil::RenderBin::sortImplementation () [virtual]
Member Data Documentation
int osgUtil::RenderBin::_binNum [protected]
RenderBinList osgUtil::RenderBin::_bins [protected]
osg::ref_ptr<DrawCallback> osgUtil::RenderBin::_drawCallback [protected]
RenderBin* osgUtil::RenderBin::_parent [protected]
RenderLeafList osgUtil::RenderBin::_renderLeafList [protected]
osg::ref_ptr<SortCallback> osgUtil::RenderBin::_sortCallback [protected]
bool osgUtil::RenderBin::_sorted [protected]
SortMode osgUtil::RenderBin::_sortMode [protected]
RenderStage* osgUtil::RenderBin::_stage [protected]
StateGraphList osgUtil::RenderBin::_stateGraphList [protected]
osg::ref_ptr<osg::StateSet> osgUtil::RenderBin::_stateset [protected]
The documentation for this class was generated from the following file:
osgUtil/RenderBin
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.