OpenSceneGraph: osgAnimation::RigTransformSoftware Class Reference
osgAnimation::RigTransformSoftware Class Reference
This class manage format for hardware skinning.
Classes
class BoneWeight
class UniqBoneSetVertexSet
Public Types
typedef std::vector< BoneWeight > BoneWeightList
typedef std::vector< int > VertexList
Public Member Functions
RigTransformSoftware ()
virtual void operator() (RigGeometry &)
template<class V >
void compute (const osg::Matrix &transform, const osg::Matrix &invTransform, const V *src, V *dst)
template<class V >
void computeNormal (const osg::Matrix &transform, const osg::Matrix &invTransform, const V *src, V *dst)
Protected Member Functions
bool init (RigGeometry &)
void initVertexSetFromBones (const BoneMap &map, const VertexInfluenceSet::UniqVertexSetToBoneSetList &influence)
Protected Attributes
std::vector< UniqBoneSetVertexSet > _boneSetVertexSet
bool _needInit
Detailed Description
This class manage format for hardware skinning.
Member Typedef Documentation
typedef std::vector<BoneWeight> osgAnimation::RigTransformSoftware::BoneWeightList
typedef std::vector<int> osgAnimation::RigTransformSoftware::VertexList
Constructor & Destructor Documentation
osgAnimation::RigTransformSoftware::RigTransformSoftware ()
Member Function Documentation
template<class V > void osgAnimation::RigTransformSoftware::compute (const osg::Matrix & transform, const osg::Matrix & invTransform, const V * src, V * dst) [inline]
References osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::computeMatrixForVertexSet(), osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::getMatrix(), and osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::getVertexes().
template<class V > void osgAnimation::RigTransformSoftware::computeNormal (const osg::Matrix & transform, const osg::Matrix & invTransform, const V * src, V * dst) [inline]
References osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::computeMatrixForVertexSet(), osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::getMatrix(), osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::getVertexes(), and osg::Matrixd::transform3x3().
bool osgAnimation::RigTransformSoftware::init (RigGeometry &) [protected]
void osgAnimation::RigTransformSoftware::initVertexSetFromBones (const BoneMap & map, const VertexInfluenceSet::UniqVertexSetToBoneSetList & influence) [protected]
virtual void osgAnimation::RigTransformSoftware::operator() (RigGeometry &) [virtual]
Reimplemented from osgAnimation::RigTransform.
Member Data Documentation
std::vector<UniqBoneSetVertexSet> osgAnimation::RigTransformSoftware::_boneSetVertexSet [protected]
bool osgAnimation::RigTransformSoftware::_needInit [protected]
The documentation for this class was generated from the following file:
osgAnimation/RigTransformSoftware
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.