OpenSceneGraph: osgIntrospection::StdPairReflector< T, PT1, PT2 > Struct Template Reference
osgIntrospection::StdPairReflector< T, PT1, PT2 > Struct Template Reference
Classes
struct Accessor
Public Types
typedef ValueReflector< T >
::instance_creator_type instance_creator_type
Public Member Functions
StdPairReflector (const std::string &name)
template<typename T, typename PT1, typename PT2>
struct osgIntrospection::StdPairReflector< T, PT1, PT2 >
Member Typedef Documentation
template<typename T , typename PT1 , typename PT2 > typedef ValueReflector<T>::instance_creator_type osgIntrospection::StdPairReflector< T, PT1, PT2 >::instance_creator_type
Reimplemented from osgIntrospection::ValueReflector< T >.
Constructor & Destructor Documentation
template<typename T , typename PT1 , typename PT2 > osgIntrospection::StdPairReflector< T, PT1, PT2 >::StdPairReflector (const std::string & name) [inline]
References osgIntrospection::CustomAttributeProvider::addAttribute(), osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::addProperty(), and typeof.
The documentation for this struct was generated from the following file:
osgIntrospection/Reflector
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.