OpenSceneGraph: osgDB::StringSerializer< C > Class Template Reference
osgDB::StringSerializer< C > Class Template Reference
Public Types
typedef const std::string & P
typedef P(C::* GetterFunctionType)() const
typedef void(C::* SetterFunctionType)(P)
Public Member Functions
StringSerializer (const char *fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter)
bool write (osgDB::Output &fw, const osg::Object &obj)
bool read (osgDB::Input &fr, osg::Object &obj, bool &itrAdvanced)
Public Attributes
std::string _fieldName
std::string _default
GetterFunctionType _getter
SetterFunctionType _setter
template<typename C>
class osgDB::StringSerializer< C >
Member Typedef Documentation
template<typename C > typedef P(C::* osgDB::StringSerializer< C >::GetterFunctionType)() const
template<typename C > typedef const std::string& osgDB::StringSerializer< C >::P
template<typename C > typedef void(C::* osgDB::StringSerializer< C >::SetterFunctionType)(P)
Constructor & Destructor Documentation
template<typename C > osgDB::StringSerializer< C >::StringSerializer (const char * fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter) [inline]
Member Function Documentation
template<typename C > bool osgDB::StringSerializer< C >::read (osgDB::Input & fr, osg::Object & obj, bool & itrAdvanced) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::StringSerializer< C >::_fieldName, and osgDB::StringSerializer< C >::_setter.
template<typename C > bool osgDB::StringSerializer< C >::write (osgDB::Output & fw, const osg::Object & obj) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::StringSerializer< C >::_default, osgDB::StringSerializer< C >::_fieldName, osgDB::StringSerializer< C >::_getter, osgDB::Output::getWriteOutDefaultValues(), osgDB::Output::indent(), and osgDB::Output::wrapString().
Member Data Documentation
template<typename C > std::string osgDB::StringSerializer< C >::_default
Referenced by osgDB::StringSerializer< C >::write().
template<typename C > std::string osgDB::StringSerializer< C >::_fieldName
Referenced by osgDB::StringSerializer< C >::read(), and osgDB::StringSerializer< C >::write().
template<typename C > GetterFunctionType osgDB::StringSerializer< C >::_getter
Referenced by osgDB::StringSerializer< C >::write().
template<typename C > SetterFunctionType osgDB::StringSerializer< C >::_setter
Referenced by osgDB::StringSerializer< C >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.