OpenSceneGraph: osg::TemplatePrimitiveFunctor< T > Class Template Reference
osg::TemplatePrimitiveFunctor< T > Class Template Reference
Provides access to the primitives that compose an osg::Drawable.
Public Member Functions
TemplatePrimitiveFunctor ()
virtual ~TemplatePrimitiveFunctor ()
void setTreatVertexDataAsTemporary (bool treatVertexDataAsTemporary)
bool getTreatVertexDataAsTemporary () const
virtual void setVertexArray (unsigned int, const Vec2 *)
Sets the array of vertices used to describe the primitives.
virtual void setVertexArray (unsigned int count, const Vec3 *vertices)
Sets the array of vertices used to describe the primitives.
virtual void setVertexArray (unsigned int, const Vec4 *)
Sets the array of vertices used to describe the primitives.
virtual void setVertexArray (unsigned int, const Vec2d *)
Sets the array of vertices used to describe the primitives.
virtual void setVertexArray (unsigned int, const Vec3d *)
Sets the array of vertices used to describe the primitives.
virtual void setVertexArray (unsigned int, const Vec4d *)
Sets the array of vertices used to describe the primitives.
virtual void drawArrays (GLenum mode, GLint first, GLsizei count)
Mimics the OpenGL glDrawArrays() function.
template<class IndexType >
void drawElementsTemplate (GLenum mode, GLsizei count, const IndexType *indices)
virtual void drawElements (GLenum mode, GLsizei count, const GLubyte *indices)
Mimics the OpenGL glDrawElements() function.
virtual void drawElements (GLenum mode, GLsizei count, const GLushort *indices)
Mimics the OpenGL glDrawElements() function.
virtual void drawElements (GLenum mode, GLsizei count, const GLuint *indices)
Mimics the OpenGL glDrawElements() function.
virtual void begin (GLenum mode)
Note: begin(..),vertex(..) & end() are convenience methods for adapting non vertex array primitives to vertex array based primitives.
virtual void vertex (const Vec2 &vert)
Mimics the OpenGL glVertex() "family of functions".
virtual void vertex (const Vec3 &vert)
Mimics the OpenGL glVertex() "family of functions".
virtual void vertex (const Vec4 &vert)
Mimics the OpenGL glVertex() "family of functions".
virtual void vertex (float x, float y)
Mimics the OpenGL glVertex() "family of functions".
virtual void vertex (float x, float y, float z)
Mimics the OpenGL glVertex() "family of functions".
virtual void vertex (float x, float y, float z, float w)
Mimics the OpenGL glVertex() "family of functions".
virtual void end ()
Mimics the OpenGL glEnd() function.
Protected Attributes
unsigned int _vertexArraySize
const Vec3 * _vertexArrayPtr
GLenum _modeCache
std::vector< Vec3 > _vertexCache
bool _treatVertexDataAsTemporary
Detailed Description
template<class T>
class osg::TemplatePrimitiveFunctor< T >
Provides access to the primitives that compose an osg::Drawable.
Notice that TemplatePrimitiveFunctor is a class template, and that it inherits from its template parameter T. This template parameter must implement operator()(const osg::Vec3 v1, const osg::Vec3 v2, const osg::Vec3 v3, bool treatVertexDataAsTemporary), operator()(const osg::Vec3 v1, const osg::Vec3 v2, bool treatVertexDataAsTemporary), operator()(const osg::Vec3 v1, const osg::Vec3 v2, const osg::Vec3 v3, bool treatVertexDataAsTemporary), and operator()(const osg::Vec3 v1, const osg::Vec3 v2, const osg::Vec3 v3, const osg::Vec3 v4, bool treatVertexDataAsTemporary) which will be called for the matching primitive when the functor is applied to a Drawable. Parameters v1, v2, v3, and v4 are the vertices of the primitive. The last parameter, treatVertexDataAsTemporary, indicates whether these vertices are coming from a "real" vertex array, or from a temporary vertex array, created by the TemplatePrimitiveFunctor from some other geometry representation.
See also:
PrimitiveFunctor for general usage hints.
Constructor & Destructor Documentation
template<class T > osg::TemplatePrimitiveFunctor< T >::TemplatePrimitiveFunctor () [inline]
References osg::TemplatePrimitiveFunctor< T >::_modeCache, osg::TemplatePrimitiveFunctor< T >::_treatVertexDataAsTemporary, osg::TemplatePrimitiveFunctor< T >::_vertexArrayPtr, and osg::TemplatePrimitiveFunctor< T >::_vertexArraySize.
template<class T > virtual osg::TemplatePrimitiveFunctor< T >::~TemplatePrimitiveFunctor () [inline, virtual]
Member Function Documentation
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::begin (GLenum mode) [inline, virtual]
Note: begin(..),vertex(..) & end() are convenience methods for adapting non vertex array primitives to vertex array based primitives.
This is done to simplify the implementation of primitive functor subclasses - users only need override drawArray and drawElements.
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_modeCache, and osg::TemplatePrimitiveFunctor< T >::_vertexCache.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::drawArrays (GLenum mode, GLint first, GLsizei count) [inline, virtual]
Mimics the OpenGL glDrawArrays() function.
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_treatVertexDataAsTemporary, and osg::TemplatePrimitiveFunctor< T >::_vertexArrayPtr.
Referenced by osg::TemplatePrimitiveFunctor< T >::end().
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::drawElements (GLenum mode, GLsizei count, const GLubyte * indices) [inline, virtual]
Mimics the OpenGL glDrawElements() function.
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::drawElementsTemplate().
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::drawElements (GLenum mode, GLsizei count, const GLuint * indices) [inline, virtual]
Mimics the OpenGL glDrawElements() function.
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::drawElementsTemplate().
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::drawElements (GLenum mode, GLsizei count, const GLushort * indices) [inline, virtual]
Mimics the OpenGL glDrawElements() function.
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::drawElementsTemplate().
template<class T > template<class IndexType > void osg::TemplatePrimitiveFunctor< T >::drawElementsTemplate (GLenum mode, GLsizei count, const IndexType * indices) [inline]
References osg::TemplatePrimitiveFunctor< T >::_treatVertexDataAsTemporary, and osg::TemplatePrimitiveFunctor< T >::_vertexArrayPtr.
Referenced by osg::TemplatePrimitiveFunctor< T >::drawElements().
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::end () [inline, virtual]
Mimics the OpenGL glEnd() function.
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_modeCache, osg::TemplatePrimitiveFunctor< T >::_treatVertexDataAsTemporary, osg::TemplatePrimitiveFunctor< T >::_vertexCache, osg::TemplatePrimitiveFunctor< T >::drawArrays(), and osg::TemplatePrimitiveFunctor< T >::setVertexArray().
template<class T > bool osg::TemplatePrimitiveFunctor< T >::getTreatVertexDataAsTemporary () const [inline]
References osg::TemplatePrimitiveFunctor< T >::_treatVertexDataAsTemporary.
template<class T > void osg::TemplatePrimitiveFunctor< T >::setTreatVertexDataAsTemporary (bool treatVertexDataAsTemporary) [inline]
References osg::TemplatePrimitiveFunctor< T >::_treatVertexDataAsTemporary.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::setVertexArray (unsigned count, const Vec2 * vertices) [inline, virtual]
Sets the array of vertices used to describe the primitives.
Somehow mimics the OpenGL glVertexPointer() function.
Implements osg::PrimitiveFunctor.
References osg::notify(), and osg::WARN.
Referenced by osg::TemplatePrimitiveFunctor< T >::end().
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::setVertexArray (unsigned count, const Vec4d * vertices) [inline, virtual]
Sets the array of vertices used to describe the primitives.
Somehow mimics the OpenGL glVertexPointer() function.
Implements osg::PrimitiveFunctor.
References osg::notify(), and osg::WARN.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::setVertexArray (unsigned int count, const Vec3 * vertices) [inline, virtual]
Sets the array of vertices used to describe the primitives.
Somehow mimics the OpenGL glVertexPointer() function.
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_vertexArrayPtr, and osg::TemplatePrimitiveFunctor< T >::_vertexArraySize.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::setVertexArray (unsigned count, const Vec4 * vertices) [inline, virtual]
Sets the array of vertices used to describe the primitives.
Somehow mimics the OpenGL glVertexPointer() function.
Implements osg::PrimitiveFunctor.
References osg::notify(), and osg::WARN.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::setVertexArray (unsigned count, const Vec2d * vertices) [inline, virtual]
Sets the array of vertices used to describe the primitives.
Somehow mimics the OpenGL glVertexPointer() function.
Implements osg::PrimitiveFunctor.
References osg::notify(), and osg::WARN.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::setVertexArray (unsigned count, const Vec3d * vertices) [inline, virtual]
Sets the array of vertices used to describe the primitives.
Somehow mimics the OpenGL glVertexPointer() function.
Implements osg::PrimitiveFunctor.
References osg::notify(), and osg::WARN.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::vertex (float x, float y, float z) [inline, virtual]
Mimics the OpenGL glVertex() "family of functions".
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_vertexCache.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::vertex (float x, float y, float z, float w) [inline, virtual]
Mimics the OpenGL glVertex() "family of functions".
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_vertexCache.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::vertex (const Vec3 & vert) [inline, virtual]
Mimics the OpenGL glVertex() "family of functions".
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_vertexCache.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::vertex (float x, float y) [inline, virtual]
Mimics the OpenGL glVertex() "family of functions".
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_vertexCache.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::vertex (const Vec2 & vert) [inline, virtual]
Mimics the OpenGL glVertex() "family of functions".
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_vertexCache.
template<class T > virtual void osg::TemplatePrimitiveFunctor< T >::vertex (const Vec4 & vert) [inline, virtual]
Mimics the OpenGL glVertex() "family of functions".
Implements osg::PrimitiveFunctor.
References osg::TemplatePrimitiveFunctor< T >::_vertexCache.
Member Data Documentation
template<class T > GLenum osg::TemplatePrimitiveFunctor< T >::_modeCache [protected]
Referenced by osg::TemplatePrimitiveFunctor< T >::begin(), osg::TemplatePrimitiveFunctor< T >::end(), and osg::TemplatePrimitiveFunctor< T >::TemplatePrimitiveFunctor().
template<class T > bool osg::TemplatePrimitiveFunctor< T >::_treatVertexDataAsTemporary [protected]
Referenced by osg::TemplatePrimitiveFunctor< T >::drawArrays(), osg::TemplatePrimitiveFunctor< T >::drawElementsTemplate(), osg::TemplatePrimitiveFunctor< T >::end(), osg::TemplatePrimitiveFunctor< T >::getTreatVertexDataAsTemporary(), osg::TemplatePrimitiveFunctor< T >::setTreatVertexDataAsTemporary(), and osg::TemplatePrimitiveFunctor< T >::TemplatePrimitiveFunctor().
template<class T > const Vec3* osg::TemplatePrimitiveFunctor< T >::_vertexArrayPtr [protected]
Referenced by osg::TemplatePrimitiveFunctor< T >::drawArrays(), osg::TemplatePrimitiveFunctor< T >::drawElementsTemplate(), osg::TemplatePrimitiveFunctor< T >::setVertexArray(), and osg::TemplatePrimitiveFunctor< T >::TemplatePrimitiveFunctor().
template<class T > unsigned int osg::TemplatePrimitiveFunctor< T >::_vertexArraySize [protected]
Referenced by osg::TemplatePrimitiveFunctor< T >::setVertexArray(), and osg::TemplatePrimitiveFunctor< T >::TemplatePrimitiveFunctor().
template<class T > std::vector<Vec3> osg::TemplatePrimitiveFunctor< T >::_vertexCache [protected]
Referenced by osg::TemplatePrimitiveFunctor< T >::begin(), osg::TemplatePrimitiveFunctor< T >::end(), and osg::TemplatePrimitiveFunctor< T >::vertex().
The documentation for this class was generated from the following file:
osg/TemplatePrimitiveFunctor
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.