OpenSceneGraph: osgIntrospection::TypedMethodInfo0< C, void > Class Template Reference
osgIntrospection::TypedMethodInfo0< C, void > Class Template Reference
Public Types
typedef void(C::* ConstFunctionType)() const
typedef void(C::* FunctionType)()
Public Member Functions
TypedMethodInfo0 (const std::string &qname, ConstFunctionType cf, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
TypedMethodInfo0 (const std::string &qname, FunctionType f, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
bool isConst () const
Returns whether the reflected method is const or not.
bool isStatic () const
Returns whether the reflected method is static or not.
Value invoke (const Value &instance, ValueList &) const
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Value invoke (Value &instance, ValueList &) const
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
template<typename C>
class osgIntrospection::TypedMethodInfo0< C, void >
Member Typedef Documentation
template<typename C > typedef void(C::* osgIntrospection::TypedMethodInfo0< C, void >::ConstFunctionType)() const
template<typename C > typedef void(C::* osgIntrospection::TypedMethodInfo0< C, void >::FunctionType)()
Constructor & Destructor Documentation
template<typename C > osgIntrospection::TypedMethodInfo0< C, void >::TypedMethodInfo0 (const std::string & qname, ConstFunctionType cf, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
template<typename C > osgIntrospection::TypedMethodInfo0< C, void >::TypedMethodInfo0 (const std::string & qname, FunctionType f, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
Member Function Documentation
template<typename C > Value osgIntrospection::TypedMethodInfo0< C, void >::invoke (const Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
References osgIntrospection::Value::getType(), osgIntrospection::Type::isConstPointer(), and osgIntrospection::Type::isPointer().
template<typename C > Value osgIntrospection::TypedMethodInfo0< C, void >::invoke (Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
References osgIntrospection::Value::getType(), osgIntrospection::Type::isConstPointer(), and osgIntrospection::Type::isPointer().
template<typename C > bool osgIntrospection::TypedMethodInfo0< C, void >::isConst () const [inline, virtual]
Returns whether the reflected method is const or not.
Implements osgIntrospection::MethodInfo.
template<typename C > bool osgIntrospection::TypedMethodInfo0< C, void >::isStatic () const [inline, virtual]
Returns whether the reflected method is static or not.
Implements osgIntrospection::MethodInfo.
The documentation for this class was generated from the following file:
osgIntrospection/TypedMethodInfo
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.