OpenSceneGraph: osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet Class Reference
osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet Class Reference
Public Member Functions
BoneWeightList & getBones ()
VertexList & getVertexes ()
void resetMatrix ()
void accummulateMatrix (const osg::Matrix &invBindMatrix, const osg::Matrix &matrix, osg::Matrix::value_type weight)
void computeMatrixForVertexSet ()
const osg::Matrix & getMatrix () const
Protected Attributes
BoneWeightList _bones
VertexList _vertexes
osg::Matrix _result
Member Function Documentation
void osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::accummulateMatrix (const osg::Matrix & invBindMatrix, const osg::Matrix & matrix, osg::Matrix::value_type weight) [inline]
References osg::Matrixd::ptr().
void osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::computeMatrixForVertexSet () [inline]
References osgAnimation::Bone::getInvBindMatrixInSkeletonSpace(), osgAnimation::Bone::getMatrixInSkeletonSpace(), osg::Matrixd::identity(), osg::notify(), and osg::WARN.
Referenced by osgAnimation::RigTransformSoftware::compute(), and osgAnimation::RigTransformSoftware::computeNormal().
BoneWeightList& osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::getBones () [inline]
const osg::Matrix& osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::getMatrix () const [inline]
Referenced by osgAnimation::RigTransformSoftware::compute(), and osgAnimation::RigTransformSoftware::computeNormal().
VertexList& osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::getVertexes () [inline]
Referenced by osgAnimation::RigTransformSoftware::compute(), and osgAnimation::RigTransformSoftware::computeNormal().
void osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::resetMatrix () [inline]
Member Data Documentation
BoneWeightList osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::_bones [protected]
osg::Matrix osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::_result [protected]
VertexList osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::_vertexes [protected]
The documentation for this class was generated from the following file:
osgAnimation/RigTransformSoftware
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.