OpenSceneGraph: osgAnimation::RigGeometry::UpdateVertex Struct Reference
osgAnimation::RigGeometry::UpdateVertex Struct Reference
Public Member Functions
virtual void update (osg::NodeVisitor *, osg::Drawable *drw)
do customized update code.
Member Function Documentation
virtual void osgAnimation::RigGeometry::UpdateVertex::update (osg::NodeVisitor * , osg::Drawable *) [inline, virtual]
do customized update code.
Reimplemented from osg::Drawable::UpdateCallback.
References osgAnimation::RigGeometry::FindNearestParentSkeleton::_root, osgAnimation::RigGeometry::buildVertexInfluenceSet(), osgAnimation::RigGeometry::computeMatrixFromRootSkeleton(), osg::ref_ptr< T >::get(), osg::Object::getName(), osgAnimation::RigGeometry::getNeedToComputeMatrix(), osg::Drawable::getParents(), osgAnimation::RigGeometry::getSkeleton(), osg::notify(), osgAnimation::RigGeometry::setSkeleton(), osgAnimation::RigGeometry::update(), osg::ref_ptr< T >::valid(), and osg::WARN.
The documentation for this struct was generated from the following file:
osgAnimation/RigGeometry
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.