OpenSceneGraph: osgWidget::Window Class Reference
osgWidget::Window Class Reference
Classes
class EmbeddedWindow
struct Sizes
Public Types
enum Strata { STRATA_NONE, STRATA_BACKGROUND, STRATA_FOREGROUND }
enum VisibilityMode { VM_FULL, VM_PARTIAL, VM_ENTIRE }
enum VerticalAnchor { VA_NONE, VA_CENTER, VA_TOP, VA_BOTTOM }
enum HorizontalAnchor { HA_NONE, HA_CENTER, HA_LEFT, HA_RIGHT }
typedef std::list
< osg::observer_ptr< Window > > WindowList
typedef point_type(Widget::* Getter)() const
Public Member Functions
Window (const std::string &="")
Window (const Window &, const osg::CopyOp &)
bool resize (point_type=0.0f, point_type=0.0f)
bool resizeAdd (point_type=0.0f, point_type=0.0f)
bool resizePercent (point_type=0.0f, point_type=0.0f)
virtual void update ()
virtual void managed (WindowManager *)
virtual void unmanaged (WindowManager *)
virtual bool addWidget (Widget *)
virtual bool insertWidget (Widget *, unsigned int)
virtual bool removeWidget (Widget *)
virtual bool replaceWidget (Widget *, Widget *)
unsigned int addDrawableAndGetIndex (osg::Drawable *)
unsigned int addChildAndGetIndex (osg::Node *)
bool isVisible () const
bool isXYWithinVisible (float, float) const
void setVisibleArea (int=0, int=0, int=0, int=0)
void addVisibleArea (int=0, int=0, int=0, int=0)
bool setFocused (const Widget *)
bool setFocused (const std::string &)
bool grabFocus ()
bool setFirstFocusable ()
bool setNextFocusable ()
bool getFocusList (WidgetList &) const
bool getEmbeddedList (WindowList &) const
void getParentList (WindowList &) const
XYCoord localXY (double, double) const
XYCoord getAbsoluteOrigin () const
EmbeddedWindow * embed (const std::string &="", Widget::Layer=Widget::LAYER_MIDDLE, unsigned int=0)
Widget * getFocused ()
const Widget * getFocused () const
bool show ()
bool hide ()
bool isPointerXYWithinVisible (float x, float y) const
osg::Geode * getGeode ()
const osg::Geode * getGeode () const
Widget * getBackground ()
const Widget * getBackground () const
WindowManager * getWindowManager ()
const WindowManager * getWindowManager () const
Window * getParent ()
const Window * getParent () const
Window * getTopmostParent ()
const Window * getTopmostParent () const
unsigned int getIndex () const
matrix_type getX () const
matrix_type getY () const
matrix_type getZ () const
point_type getWidth () const
point_type getHeight () const
point_type getMinWidth () const
point_type getMinHeight () const
VerticalAnchor getAnchorVertical () const
HorizontalAnchor getAnchorHorizontal () const
XYCoord getOrigin () const
XYCoord getSize () const
XYCoord getMinSize () const
matrix_type getZRange () const
Strata getStrata () const
const Quad & getVisibleArea () const
VisibilityMode getVisibilityMode () const
Point getPosition () const
matrix_type getRotate () const
matrix_type getScale () const
matrix_type getScaleDenominator () const
void setX (matrix_type x)
void setY (matrix_type y)
void setZ (matrix_type z)
void setZRange (matrix_type zRange)
void setPosition (matrix_type x, matrix_type y, matrix_type z)
void setPosition (const Point &p)
void setOrigin (matrix_type x, matrix_type y)
void setOrigin (const XYCoord &xy)
void setRotate (matrix_type r)
void setScale (matrix_type s)
void setScaleDenominator (matrix_type sd)
void setAnchorVertical (VerticalAnchor va)
void setAnchorHorizontal (HorizontalAnchor ha)
void setStrata (Strata s)
void setVisibilityMode (VisibilityMode v)
void addX (matrix_type x)
void addY (matrix_type y)
void addZ (matrix_type z)
void addRotate (matrix_type r)
void addScale (matrix_type s)
void addOrigin (matrix_type x, matrix_type y)
void attachMoveCallback ()
void attachRotateCallback ()
void attachScaleCallback ()
void attachTabFocusCallback ()
Protected Types
typedef std::less< point_type > Less
typedef std::greater< point_type > Greater
typedef std::plus< point_type > Plus
Protected Member Functions
template<typename T >
point_type _forEachAssignOrApply (Getter get, int begin, int end, int add, bool assign) const
void _setWidthAndHeightUnknownSizeError (const std::string &, point_type)
void _setWidthAndHeightNotPAError (const std::string &, point_type)
void _setWidthAndHeight ()
void _removeFromGeode (Widget *)
Widget * _getBackground () const
Window * _getTopmostParent () const
template<typename T >
point_type _compare (Getter get, int begin=0, int end=0, int add=1) const
template<typename T >
point_type _accumulate (Getter get, int begin=0, int end=0, int add=1) const
osg::Geode * _geode ()
const osg::Geode * _geode () const
Widget * _bg ()
const Widget * _bg () const
osg::Scissor * _scissor ()
bool _setWidget (Widget *, int=-1)
bool _setVisible (bool)
void _setFocused (Widget *)
void _setStyled (Widget *)
void _setParented (Widget *, bool=false)
void _setManaged (Widget *, bool=false)
void _positionWidget (Widget *, point_type, point_type)
point_type _getMinWidgetWidth (int=0, int=0, int=1) const
point_type _getMinWidgetHeight (int=0, int=0, int=1) const
point_type _getMaxWidgetWidth (int=0, int=0, int=1) const
point_type _getMaxWidgetHeight (int=0, int=0, int=1) const
point_type _getMinWidgetMinWidth (int=0, int=0, int=1) const
point_type _getMinWidgetMinHeight (int=0, int=0, int=1) const
point_type _getMaxWidgetMinWidth (int=0, int=0, int=1) const
point_type _getMaxWidgetMinHeight (int=0, int=0, int=1) const
point_type _getMinWidgetWidthTotal (int=0, int=0, int=1) const
point_type _getMinWidgetHeightTotal (int=0, int=0, int=1) const
point_type _getMaxWidgetWidthTotal (int=0, int=0, int=1) const
point_type _getMaxWidgetHeightTotal (int=0, int=0, int=1) const
point_type _getMinWidgetMinWidthTotal (int=0, int=0, int=1) const
point_type _getMinWidgetMinHeightTotal (int=0, int=0, int=1) const
point_type _getMaxWidgetMinWidthTotal (int=0, int=0, int=1) const
point_type _getMaxWidgetMinHeightTotal (int=0, int=0, int=1) const
point_type _getMinWidgetPadHorizontal (int=0, int=0, int=1) const
point_type _getMinWidgetPadVertical (int=0, int=0, int=1) const
point_type _getMaxWidgetPadHorizontal (int=0, int=0, int=1) const
point_type _getMaxWidgetPadVertical (int=0, int=0, int=1) const
point_type _getNumFill (int=0, int=0, int=1) const
virtual void _resizeImplementation (point_type, point_type)=0
virtual Sizes _getWidthImplementation () const
virtual Sizes _getHeightImplementation () const
Protected Attributes
Window * _parent
WindowManager * _wm
unsigned int _index
matrix_type _x
matrix_type _y
matrix_type _z
matrix_type _zRange
Strata _strata
VisibilityMode _vis
matrix_type _r
matrix_type _s
matrix_type _scaleDenom
Sizes _width
Sizes _height
VerticalAnchor _vAnchor
HorizontalAnchor _hAnchor
osg::observer_ptr< Widget > _focused
Quad _visibleArea
Friends
class WindowManager
Member Typedef Documentation
typedef point_type(Widget::* osgWidget::Window::Getter)() const
typedef std::greater<point_type> osgWidget::Window::Greater [protected]
typedef std::less<point_type> osgWidget::Window::Less [protected]
typedef std::plus<point_type> osgWidget::Window::Plus [protected]
typedef std::list<osg::observer_ptr<Window> > osgWidget::Window::WindowList
Member Enumeration Documentation
enum osgWidget::Window::HorizontalAnchor
Enumerator:
HA_NONE
HA_CENTER
HA_LEFT
HA_RIGHT
enum osgWidget::Window::Strata
Enumerator:
STRATA_NONE
STRATA_BACKGROUND
STRATA_FOREGROUND
enum osgWidget::Window::VerticalAnchor
Enumerator:
VA_NONE
VA_CENTER
VA_TOP
VA_BOTTOM
enum osgWidget::Window::VisibilityMode
Enumerator:
VM_FULL
VM_PARTIAL
VM_ENTIRE
Constructor & Destructor Documentation
osgWidget::Window::Window (const std::string & = "")
osgWidget::Window::Window (const Window & , const osg::CopyOp &)
Member Function Documentation
template<typename T > point_type osgWidget::Window::_accumulate (Getter get, int begin = 0, int end = 0, int add = 1) const [inline, protected]
Widget* osgWidget::Window::_bg () [inline, protected]
const Widget* osgWidget::Window::_bg () const [inline, protected]
template<typename T > point_type osgWidget::Window::_compare (Getter get, int begin = 0, int end = 0, int add = 1) const [inline, protected]
template<typename T > point_type osgWidget::Window::_forEachAssignOrApply (Getter get, int begin, int end, int add, bool assign) const [inline, protected]
const osg::Geode* osgWidget::Window::_geode () const [inline, protected]
osg::Geode* osgWidget::Window::_geode () [inline, protected]
Widget* osgWidget::Window::_getBackground () const [protected]
virtual Sizes osgWidget::Window::_getHeightImplementation () const [protected, virtual]
Reimplemented in osgWidget::Box, and osgWidget::Table.
point_type osgWidget::Window::_getMaxWidgetHeight (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetHeightTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetMinHeight (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetMinHeightTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetMinWidth (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetMinWidthTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetPadHorizontal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetPadVertical (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetWidth (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMaxWidgetWidthTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetHeight (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetHeightTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetMinHeight (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetMinHeightTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetMinWidth (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetMinWidthTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetPadHorizontal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetPadVertical (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetWidth (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getMinWidgetWidthTotal (int = 0, int = 0, int = 1) const [protected]
point_type osgWidget::Window::_getNumFill (int = 0, int = 0, int = 1) const [protected]
Window* osgWidget::Window::_getTopmostParent () const [protected]
virtual Sizes osgWidget::Window::_getWidthImplementation () const [protected, virtual]
Reimplemented in osgWidget::Box, and osgWidget::Table.
void osgWidget::Window::_positionWidget (Widget * , point_type , point_type) [protected]
void osgWidget::Window::_removeFromGeode (Widget *) [protected]
virtual void osgWidget::Window::_resizeImplementation (point_type , point_type) [protected, pure virtual]
Implemented in osgWidget::Box, osgWidget::Canvas, and osgWidget::Table.
osg::Scissor* osgWidget::Window::_scissor () [inline, protected]
References osg::StateAttribute::SCISSOR.
void osgWidget::Window::_setFocused (Widget *) [protected]
void osgWidget::Window::_setManaged (Widget * , bool = false) [protected]
void osgWidget::Window::_setParented (Widget * , bool = false) [protected]
void osgWidget::Window::_setStyled (Widget *) [protected]
bool osgWidget::Window::_setVisible (bool) [protected]
bool osgWidget::Window::_setWidget (Widget * , int = -1) [protected]
void osgWidget::Window::_setWidthAndHeight () [protected]
void osgWidget::Window::_setWidthAndHeightNotPAError (const std::string & , point_type) [protected]
void osgWidget::Window::_setWidthAndHeightUnknownSizeError (const std::string & , point_type) [protected]
unsigned int osgWidget::Window::addChildAndGetIndex (osg::Node *)
unsigned int osgWidget::Window::addDrawableAndGetIndex (osg::Drawable *)
void osgWidget::Window::addOrigin (matrix_type x, matrix_type y) [inline]
void osgWidget::Window::addRotate (matrix_type r) [inline]
void osgWidget::Window::addScale (matrix_type s) [inline]
void osgWidget::Window::addVisibleArea (int = 0, int = 0, int = 0, int = 0)
virtual bool osgWidget::Window::addWidget (Widget *) [virtual]
Reimplemented in osgWidget::Table.
void osgWidget::Window::addX (matrix_type x) [inline]
void osgWidget::Window::addY (matrix_type y) [inline]
void osgWidget::Window::addZ (matrix_type z) [inline]
void osgWidget::Window::attachMoveCallback () [inline]
References osgWidget::callbackWindowMove(), and osgWidget::EVENT_MOUSE_DRAG.
void osgWidget::Window::attachRotateCallback () [inline]
References osgWidget::callbackWindowRotate(), and osgWidget::EVENT_MOUSE_DRAG.
void osgWidget::Window::attachScaleCallback () [inline]
References osgWidget::callbackWindowScale(), and osgWidget::EVENT_MOUSE_DRAG.
void osgWidget::Window::attachTabFocusCallback () [inline]
References osgWidget::callbackWindowTabFocus(), and osgWidget::EVENT_KEY_DOWN.
EmbeddedWindow* osgWidget::Window::embed (const std::string & = "", Widget::Layer = Widget::LAYER_MIDDLE, unsigned int = 0)
XYCoord osgWidget::Window::getAbsoluteOrigin () const
HorizontalAnchor osgWidget::Window::getAnchorHorizontal () const [inline]
VerticalAnchor osgWidget::Window::getAnchorVertical () const [inline]
const Widget* osgWidget::Window::getBackground () const [inline]
Widget* osgWidget::Window::getBackground () [inline]
bool osgWidget::Window::getEmbeddedList (WindowList &) const
const Widget* osgWidget::Window::getFocused () const [inline]
Widget* osgWidget::Window::getFocused () [inline]
bool osgWidget::Window::getFocusList (WidgetList &) const
osg::Geode* osgWidget::Window::getGeode () [inline]
const osg::Geode* osgWidget::Window::getGeode () const [inline]
point_type osgWidget::Window::getHeight () const [inline]
unsigned int osgWidget::Window::getIndex () const [inline]
point_type osgWidget::Window::getMinHeight () const [inline]
XYCoord osgWidget::Window::getMinSize () const [inline]
point_type osgWidget::Window::getMinWidth () const [inline]
XYCoord osgWidget::Window::getOrigin () const [inline]
Window* osgWidget::Window::getParent () [inline]
const Window* osgWidget::Window::getParent () const [inline]
void osgWidget::Window::getParentList (WindowList &) const
Referenced by osgWidget::WindowManager::getFirstEventInterface().
Point osgWidget::Window::getPosition () const [inline]
matrix_type osgWidget::Window::getRotate () const [inline]
matrix_type osgWidget::Window::getScale () const [inline]
matrix_type osgWidget::Window::getScaleDenominator () const [inline]
XYCoord osgWidget::Window::getSize () const [inline]
Strata osgWidget::Window::getStrata () const [inline]
const Window* osgWidget::Window::getTopmostParent () const [inline]
Window* osgWidget::Window::getTopmostParent () [inline]
VisibilityMode osgWidget::Window::getVisibilityMode () const [inline]
const Quad& osgWidget::Window::getVisibleArea () const [inline]
point_type osgWidget::Window::getWidth () const [inline]
WindowManager* osgWidget::Window::getWindowManager () [inline]
const WindowManager* osgWidget::Window::getWindowManager () const [inline]
matrix_type osgWidget::Window::getX () const [inline]
matrix_type osgWidget::Window::getY () const [inline]
matrix_type osgWidget::Window::getZ () const [inline]
matrix_type osgWidget::Window::getZRange () const [inline]
bool osgWidget::Window::grabFocus ()
bool osgWidget::Window::hide () [inline]
virtual bool osgWidget::Window::insertWidget (Widget * , unsigned int) [virtual]
bool osgWidget::Window::isPointerXYWithinVisible (float x, float y) const [inline]
References osg::Vec2f::x(), and osg::Vec2f::y().
bool osgWidget::Window::isVisible () const
bool osgWidget::Window::isXYWithinVisible (float , float) const
XYCoord osgWidget::Window::localXY (double , double) const
virtual void osgWidget::Window::managed (WindowManager *) [virtual]
virtual bool osgWidget::Window::removeWidget (Widget *) [virtual]
virtual bool osgWidget::Window::replaceWidget (Widget * , Widget *) [virtual]
bool osgWidget::Window::resize (point_type = 0.0f, point_type = 0.0f)
bool osgWidget::Window::resizeAdd (point_type = 0.0f, point_type = 0.0f)
bool osgWidget::Window::resizePercent (point_type = 0.0f, point_type = 0.0f)
void osgWidget::Window::setAnchorHorizontal (HorizontalAnchor ha) [inline]
void osgWidget::Window::setAnchorVertical (VerticalAnchor va) [inline]
bool osgWidget::Window::setFirstFocusable ()
bool osgWidget::Window::setFocused (const Widget *)
bool osgWidget::Window::setFocused (const std::string &)
bool osgWidget::Window::setNextFocusable ()
void osgWidget::Window::setOrigin (const XYCoord & xy) [inline]
References osg::Vec2f::x(), and osg::Vec2f::y().
void osgWidget::Window::setOrigin (matrix_type x, matrix_type y) [inline]
void osgWidget::Window::setPosition (matrix_type x, matrix_type y, matrix_type z) [inline]
void osgWidget::Window::setPosition (const Point & p) [inline]
void osgWidget::Window::setRotate (matrix_type r) [inline]
void osgWidget::Window::setScale (matrix_type s) [inline]
void osgWidget::Window::setScaleDenominator (matrix_type sd) [inline]
void osgWidget::Window::setStrata (Strata s) [inline]
void osgWidget::Window::setVisibilityMode (VisibilityMode v) [inline]
void osgWidget::Window::setVisibleArea (int = 0, int = 0, int = 0, int = 0)
void osgWidget::Window::setX (matrix_type x) [inline]
void osgWidget::Window::setY (matrix_type y) [inline]
void osgWidget::Window::setZ (matrix_type z) [inline]
void osgWidget::Window::setZRange (matrix_type zRange) [inline]
bool osgWidget::Window::show () [inline]
virtual void osgWidget::Window::unmanaged (WindowManager *) [virtual]
virtual void osgWidget::Window::update () [virtual]
Friends And Related Function Documentation
friend class WindowManager [friend]
Member Data Documentation
osg::observer_ptr<Widget> osgWidget::Window::_focused [protected]
HorizontalAnchor osgWidget::Window::_hAnchor [protected]
Sizes osgWidget::Window::_height [protected]
unsigned int osgWidget::Window::_index [protected]
Window* osgWidget::Window::_parent [protected]
matrix_type osgWidget::Window::_r [protected]
matrix_type osgWidget::Window::_s [protected]
matrix_type osgWidget::Window::_scaleDenom [protected]
Strata osgWidget::Window::_strata [protected]
VerticalAnchor osgWidget::Window::_vAnchor [protected]
VisibilityMode osgWidget::Window::_vis [protected]
Quad osgWidget::Window::_visibleArea [protected]
Sizes osgWidget::Window::_width [protected]
WindowManager* osgWidget::Window::_wm [protected]
matrix_type osgWidget::Window::_x [protected]
matrix_type osgWidget::Window::_y [protected]
matrix_type osgWidget::Window::_z [protected]
matrix_type osgWidget::Window::_zRange [protected]
The documentation for this class was generated from the following file:
osgWidget/Window
Generated at Thu Jun 9 2011 16:37:18 for the OpenSceneGraph by doxygen 1.7.1.