OpenSceneGraph: osgDB Namespace Reference
osgDB Namespace Reference
The osgDB library provides support for reading and writing scene graphs, providing a plugin framework and file utility classes.
Classes
class Archive
Base class for implementing database Archives.
class AuthenticationDetails
class AuthenticationMap
class DatabasePager
Database paging class which manages the loading of files in a background thread, and synchronizing of loaded models with the main scene graph.
class DotOsgWrapper
Wrapper class for specifying read and write functions for extending the .osg file format.
class DynamicLibrary
DynamicLibrary - encapsulates the loading and unloading of dynamic libraries, typically used for loading ReaderWriter plug-ins.
class Field
class FieldReader
class FieldReaderIterator
class FileCache
class fstream
Replacements for std::fstream, std::ifstream, and std::ofstream to automatically handle UTF-8 to UTF-16 filename conversion.
class ifstream
class ofstream
class ImageOptions
class ImagePager
class Input
Class for managing the reading of ASCII .osg files.
class Output
ofstream wrapper class for adding support for indenting.
class ParameterOutput
class ReaderWriterInfo
class ReaderWriter
pure virtual base class for reading and writing of non native formats.
struct basic_type_wrapper
basic structure for custom runtime inheritance checking
struct type_wrapper
a class template that checks inheritance between a given Object's class and a class defined at compile time through the template parameter T.
class Registry
Registry is a singleton factory which stores the reader/writers which are linked in at runtime for reading non-native file formats.
class RegisterDotOsgWrapperProxy
Proxy class for automatic registration of DotOsgWrappers with the Registry.
class TemplateRegisterDotOsgWrapperProxy
class RegisterReaderWriterProxy
Proxy class for automatic registration of reader/writers with the Registry.
struct PluginFunctionProxy
class IntLookup
class Serializer
class EnumSerializer
class StringSerializer
class TemplateSerializer
class Vec4Serializer
class BoolSerializer
class SharedStateManager
Typedefs
typedef std::vector< std::string > DirectoryContents
simple list of names to represent a directory's contents.
typedef std::list< std::string > FileNameList
typedef std::list
< osg::ref_ptr
< ReaderWriterInfo > > ReaderWriterInfoList
typedef std::deque< std::string > FilePathList
list of directories to search through which searching for files.
Enumerations
enum CaseSensitivity { CASE_SENSITIVE, CASE_INSENSITIVE }
enum FileType { FILE_NOT_FOUND, REGULAR_FILE, DIRECTORY }
Functions
OSGDB_EXPORT Archive * openArchive (const std::string &filename, ReaderWriter::ArchiveStatus status, unsigned int indexBlockSizeHint=4096)
Open an archive for reading or writing.
OSGDB_EXPORT Archive * openArchive (const std::string &filename, ReaderWriter::ArchiveStatus status, unsigned int indexBlockSizeHint, ReaderWriter::Options *options)
Open an archive for reading or writing.
OSGDB_EXPORT std::string convertUTF16toUTF8 (const wchar_t *source, unsigned sourceLength)
OSGDB_EXPORT std::wstring convertUTF8toUTF16 (const char *source, unsigned sourceLength)
OSGDB_EXPORT std::string convertUTF16toUTF8 (const std::wstring &s)
OSGDB_EXPORT std::string convertUTF16toUTF8 (const wchar_t *s)
OSGDB_EXPORT std::wstring convertUTF8toUTF16 (const std::string &s)
OSGDB_EXPORT std::wstring convertUTF8toUTF16 (const char *s)
OSGDB_EXPORT std::string convertStringFromCurrentCodePageToUTF8 (const char *source, unsigned sourceLength)
OSGDB_EXPORT std::string convertStringFromUTF8toCurrentCodePage (const char *source, unsigned sourceLength)
OSGDB_EXPORT std::string convertStringFromCurrentCodePageToUTF8 (const std::string &s)
OSGDB_EXPORT std::string convertStringFromCurrentCodePageToUTF8 (const char *s)
OSGDB_EXPORT std::string convertStringFromUTF8toCurrentCodePage (const std::string &s)
OSGDB_EXPORT std::string convertStringFromUTF8toCurrentCodePage (const char *s)
OSGDB_EXPORT std::string getFilePath (const std::string &filename)
OSGDB_EXPORT std::string getFileExtension (const std::string &filename)
OSGDB_EXPORT std::string getFileExtensionIncludingDot (const std::string &filename)
OSGDB_EXPORT std::string getLowerCaseFileExtension (const std::string &filename)
OSGDB_EXPORT std::string getSimpleFileName (const std::string &fileName)
OSGDB_EXPORT std::string getNameLessExtension (const std::string &fileName)
OSGDB_EXPORT std::string getStrippedName (const std::string &fileName)
OSGDB_EXPORT std::string convertFileNameToWindowsStyle (const std::string &fileName)
OSGDB_EXPORT std::string convertFileNameToUnixStyle (const std::string &fileName)
OSGDB_EXPORT std::string convertToLowerCase (const std::string &fileName)
OSGDB_EXPORT bool isFileNameNativeStyle (const std::string &fileName)
OSGDB_EXPORT std::string convertFileNameToNativeStyle (const std::string &fileName)
OSGDB_EXPORT bool equalCaseInsensitive (const std::string &lhs, const std::string &rhs)
OSGDB_EXPORT bool equalCaseInsensitive (const std::string &lhs, const char *rhs)
OSGDB_EXPORT bool containsServerAddress (const std::string &filename)
OSGDB_EXPORT std::string getServerAddress (const std::string &filename)
OSGDB_EXPORT std::string getServerFileName (const std::string &filename)
OSGDB_EXPORT std::string concatPaths (const std::string &left, const std::string &right)
Concatenates two paths.
OSGDB_EXPORT std::string getRealPath (const std::string &path)
Removes .
OSGDB_EXPORT FILE * fopen (const char *filename, const char *mode)
OSGDB_EXPORT bool makeDirectory (const std::string &directoryPath)
OSGDB_EXPORT bool makeDirectoryForFile (const std::string &filePath)
OSGDB_EXPORT std::string getCurrentWorkingDirectory (void)
OSGDB_EXPORT bool setCurrentWorkingDirectory (const std::string &newCurrentWorkingDirectory)
OSGDB_EXPORT bool fileExists (const std::string &filename)
return true if a file exists.
OSGDB_EXPORT FileType fileType (const std::string &filename)
return type of file.
OSGDB_EXPORT std::string findFileInPath (const std::string &filename, const FilePathList &filePath, CaseSensitivity caseSensitivity=CASE_SENSITIVE)
find specified file in specified file path.
OSGDB_EXPORT std::string findFileInDirectory (const std::string &fileName, const std::string &dirName, CaseSensitivity caseSensitivity=CASE_SENSITIVE)
return the directory/filename of a file if its is contained within specified directory.
OSGDB_EXPORT DirectoryContents getDirectoryContents (const std::string &dirName)
return the contents of a directory.
void setDataFilePathList (const FilePathList &filepath)
void setDataFilePathList (const std::string &paths)
FilePathList & getDataFilePathList ()
OSGDB_EXPORT std::string findDataFile (const std::string &filename, CaseSensitivity caseSensitivity=CASE_SENSITIVE)
Search for specified file in file system, checking the DataFilePathList for possible paths, returning the full path of the first valid file found, return an empty string if no string is found.
OSGDB_EXPORT std::string findDataFile (const std::string &filename, const ReaderWriter::Options *options, CaseSensitivity caseSensitivity=CASE_SENSITIVE)
Search for specified file in file system, checking first the database path set in the Options structure, then the DataFilePathList for possible paths, returning the full path of the first valid file found, return an empty string if no string is found.
void setLibraryFilePathList (const FilePathList &filepaths)
void setLibraryFilePathList (const std::string &paths)
FilePathList & getLibraryFilePathList ()
OSGDB_EXPORT std::string findLibraryFile (const std::string &filename, CaseSensitivity caseSensitivity=CASE_SENSITIVE)
OSGDB_EXPORT void convertStringPathIntoFilePathList (const std::string &paths, FilePathList &filepath)
convert a string containing a list of paths delimited either with ';' (Windows) or ':' (All other platforms) into FilePath representation.
OSGDB_EXPORT void appendPlatformSpecificLibraryFilePaths (FilePathList &filepath)
OSGDB_EXPORT void appendPlatformSpecificResourceFilePaths (FilePathList &filepath)
template<class Iterator >
void writeArray (Output &fw, Iterator first, Iterator last, int noItemsPerLine=0)
template<class Iterator >
void writeArrayAsInts (Output &fw, Iterator first, Iterator last, int noItemsPerLine=0)
FileNameList OSGDB_EXPORT listAllAvailablePlugins ()
bool OSGDB_EXPORT queryPlugin (const std::string &fileName, ReaderWriterInfoList &infoList)
bool OSGDB_EXPORT outputPluginDetails (std::ostream &out, const std::string &fileName)
OSGDB_EXPORT osg::Object * readObjectFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Object from file.
osg::Object * readObjectFile (const std::string &filename)
Read an osg::Object from file.
OSGDB_EXPORT osg::Image * readImageFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Image from file.
osg::Image * readImageFile (const std::string &filename)
Read an osg::Image from file.
OSGDB_EXPORT osg::HeightField * readHeightFieldFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::HeightField from file.
osg::HeightField * readHeightFieldFile (const std::string &filename)
Read an osg::HeightField from file.
OSGDB_EXPORT osg::Node * readNodeFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Node from file.
osg::Node * readNodeFile (const std::string &filename)
Read an osg::Node from file.
OSGDB_EXPORT osg::Node * readNodeFiles (std::vector< std::string > &commandLine, const ReaderWriter::Options *options)
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
osg::Node * readNodeFiles (std::vector< std::string > &commandLine)
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
OSGDB_EXPORT osg::Node * readNodeFiles (osg::ArgumentParser &parser, const ReaderWriter::Options *options)
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
osg::Node * readNodeFiles (osg::ArgumentParser &parser)
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
OSGDB_EXPORT osg::Shader * readShaderFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Shader from file.
osg::Shader * readShaderFile (const std::string &filename)
Read an osg::Shader from file.
osg::Shader * readShaderFile (osg::Shader::Type type, const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Shader from file and set to specified shader type.
osg::Shader * readShaderFile (osg::Shader::Type type, const std::string &filename)
Read an osg::Shader from file and set to specified shader type Return valid osg::Shader on success, return NULL on failure.
OSGDB_EXPORT osg::ref_ptr
< osg::Object > readRefObjectFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Object from file.
osg::ref_ptr< osg::Object > readRefObjectFile (const std::string &filename)
Read an osg::Object from file.
OSGDB_EXPORT osg::ref_ptr
< osg::Image > readRefImageFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Image from file.
osg::ref_ptr< osg::Image > readRefImageFile (const std::string &filename)
Read an osg::Image from file.
OSGDB_EXPORT osg::ref_ptr
< osg::HeightField > readRefHeightFieldFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::HeightField from file.
osg::ref_ptr< osg::HeightField > readRefHeightFieldFile (const std::string &filename)
Read an osg::HeightField from file.
OSGDB_EXPORT osg::ref_ptr
< osg::Node > readRefNodeFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Node from file.
osg::ref_ptr< osg::Node > readRefNodeFile (const std::string &filename)
Read an osg::Node from file.
OSGDB_EXPORT osg::ref_ptr
< osg::Shader > readRefShaderFile (const std::string &filename, const ReaderWriter::Options *options)
Read an osg::Shader from file.
osg::ref_ptr< osg::Shader > readRefShaderFile (const std::string &filename)
Read an osg::Shader from file.
void readCommandLine (osg::ArgumentParser &parser)
read the command line arguments.
OSGDB_EXPORT bool writeObjectFile (const osg::Object &object, const std::string &filename, const ReaderWriter::Options *options)
Write an osg::Object to file.
bool writeObjectFile (const osg::Object &object, const std::string &filename)
Write an osg::Object to file.
OSGDB_EXPORT bool writeImageFile (const osg::Image &image, const std::string &filename, const ReaderWriter::Options *options)
Write an osg::Image to file.
bool writeImageFile (const osg::Image &image, const std::string &filename)
Write an osg::Image to file.
OSGDB_EXPORT bool writeHeightFieldFile (const osg::HeightField &hf, const std::string &filename, const ReaderWriter::Options *options)
Write an osg::HeightField to file.
bool writeHeightFieldFile (const osg::HeightField &hf, const std::string &filename)
Write an osg::HeightField to file.
OSGDB_EXPORT bool writeNodeFile (const osg::Node &node, const std::string &filename, const ReaderWriter::Options *options)
Write an osg::Node to file.
bool writeNodeFile (const osg::Node &node, const std::string &filename)
Write an osg::Node to file.
OSGDB_EXPORT bool writeShaderFile (const osg::Shader &shader, const std::string &filename, const ReaderWriter::Options *options)
Write an osg::Shader to file.
bool writeShaderFile (const osg::Shader &shader, const std::string &filename)
Write an osg::Shader to file.
Detailed Description
The osgDB library provides support for reading and writing scene graphs, providing a plugin framework and file utility classes.
The plugin framework in centered around the osgDB::Registry, and allows plugins which provide specific file format support to be dynamically loaded on demand.
Typedef Documentation
typedef std::vector<std::string> osgDB::DirectoryContents
simple list of names to represent a directory's contents.
typedef std::list<std::string> osgDB::FileNameList
typedef std::deque<std::string> osgDB::FilePathList
list of directories to search through which searching for files.
typedef std::list< osg::ref_ptr<ReaderWriterInfo> > osgDB::ReaderWriterInfoList
Enumeration Type Documentation
enum osgDB::CaseSensitivity
Enumerator:
CASE_SENSITIVE
CASE_INSENSITIVE
enum osgDB::FileType
Enumerator:
FILE_NOT_FOUND
REGULAR_FILE
DIRECTORY
Function Documentation
OSGDB_EXPORT void osgDB::appendPlatformSpecificLibraryFilePaths (FilePathList & filepath)
OSGDB_EXPORT void osgDB::appendPlatformSpecificResourceFilePaths (FilePathList & filepath)
OSGDB_EXPORT std::string osgDB::concatPaths (const std::string & left, const std::string & right)
Concatenates two paths.
OSGDB_EXPORT bool osgDB::containsServerAddress (const std::string & filename)
OSGDB_EXPORT std::string osgDB::convertFileNameToNativeStyle (const std::string & fileName)
OSGDB_EXPORT std::string osgDB::convertFileNameToUnixStyle (const std::string & fileName)
OSGDB_EXPORT std::string osgDB::convertFileNameToWindowsStyle (const std::string & fileName)
OSGDB_EXPORT std::string osgDB::convertStringFromCurrentCodePageToUTF8 (const char * source, unsigned sourceLength)
OSGDB_EXPORT std::string osgDB::convertStringFromCurrentCodePageToUTF8 (const std::string & s)
OSGDB_EXPORT std::string osgDB::convertStringFromCurrentCodePageToUTF8 (const char * s)
OSGDB_EXPORT std::string osgDB::convertStringFromUTF8toCurrentCodePage (const char * source, unsigned sourceLength)
OSGDB_EXPORT std::string osgDB::convertStringFromUTF8toCurrentCodePage (const std::string & s)
OSGDB_EXPORT std::string osgDB::convertStringFromUTF8toCurrentCodePage (const char * s)
OSGDB_EXPORT void osgDB::convertStringPathIntoFilePathList (const std::string & paths, FilePathList & filepath)
convert a string containing a list of paths delimited either with ';' (Windows) or ':' (All other platforms) into FilePath representation.
OSGDB_EXPORT std::string osgDB::convertToLowerCase (const std::string & fileName)
OSGDB_EXPORT std::string osgDB::convertUTF16toUTF8 (const std::wstring & s)
OSGDB_EXPORT std::string osgDB::convertUTF16toUTF8 (const wchar_t * source, unsigned sourceLength)
OSGDB_EXPORT std::string osgDB::convertUTF16toUTF8 (const wchar_t * s)
OSGDB_EXPORT std::wstring osgDB::convertUTF8toUTF16 (const char * s)
OSGDB_EXPORT std::wstring osgDB::convertUTF8toUTF16 (const char * source, unsigned sourceLength)
OSGDB_EXPORT std::wstring osgDB::convertUTF8toUTF16 (const std::string & s)
OSGDB_EXPORT bool osgDB::equalCaseInsensitive (const std::string & lhs, const std::string & rhs)
OSGDB_EXPORT bool osgDB::equalCaseInsensitive (const std::string & lhs, const char * rhs)
OSGDB_EXPORT bool osgDB::fileExists (const std::string & filename)
return true if a file exists.
OSGDB_EXPORT FileType osgDB::fileType (const std::string & filename)
return type of file.
OSGDB_EXPORT std::string osgDB::findDataFile (const std::string & filename, CaseSensitivity caseSensitivity = CASE_SENSITIVE)
Search for specified file in file system, checking the DataFilePathList for possible paths, returning the full path of the first valid file found, return an empty string if no string is found.
OSGDB_EXPORT std::string osgDB::findDataFile (const std::string & filename, const ReaderWriter::Options * options, CaseSensitivity caseSensitivity = CASE_SENSITIVE)
Search for specified file in file system, checking first the database path set in the Options structure, then the DataFilePathList for possible paths, returning the full path of the first valid file found, return an empty string if no string is found.
OSGDB_EXPORT std::string osgDB::findFileInDirectory (const std::string & fileName, const std::string & dirName, CaseSensitivity caseSensitivity = CASE_SENSITIVE)
return the directory/filename of a file if its is contained within specified directory.
return "" if directory does not contain file. If caseInsensitive is set to true then a case insensitive comparison is used to compare fileName to directory contents. This is useful when unix programs attempt read case insensitive windows filenames.
OSGDB_EXPORT std::string osgDB::findFileInPath (const std::string & filename, const FilePathList & filePath, CaseSensitivity caseSensitivity = CASE_SENSITIVE)
find specified file in specified file path.
OSGDB_EXPORT std::string osgDB::findLibraryFile (const std::string & filename, CaseSensitivity caseSensitivity = CASE_SENSITIVE)
OSGDB_EXPORT FILE* osgDB::fopen (const char * filename, const char * mode)
OSGDB_EXPORT std::string osgDB::getCurrentWorkingDirectory (void)
FilePathList& osgDB::getDataFilePathList () [inline]
References osgDB::Registry::getDataFilePathList(), and osgDB::Registry::instance().
OSGDB_EXPORT DirectoryContents osgDB::getDirectoryContents (const std::string & dirName)
return the contents of a directory.
returns an empty array on any error.
OSGDB_EXPORT std::string osgDB::getFileExtension (const std::string & filename)
OSGDB_EXPORT std::string osgDB::getFileExtensionIncludingDot (const std::string & filename)
OSGDB_EXPORT std::string osgDB::getFilePath (const std::string & filename)
FilePathList& osgDB::getLibraryFilePathList () [inline]
References osgDB::Registry::getLibraryFilePathList(), and osgDB::Registry::instance().
OSGDB_EXPORT std::string osgDB::getLowerCaseFileExtension (const std::string & filename)
OSGDB_EXPORT std::string osgDB::getNameLessExtension (const std::string & fileName)
OSGDB_EXPORT std::string osgDB::getRealPath (const std::string & path)
Removes .
. and . dirs in a path
OSGDB_EXPORT std::string osgDB::getServerAddress (const std::string & filename)
OSGDB_EXPORT std::string osgDB::getServerFileName (const std::string & filename)
OSGDB_EXPORT std::string osgDB::getSimpleFileName (const std::string & fileName)
OSGDB_EXPORT std::string osgDB::getStrippedName (const std::string & fileName)
OSGDB_EXPORT bool osgDB::isFileNameNativeStyle (const std::string & fileName)
FileNameList OSGDB_EXPORT osgDB::listAllAvailablePlugins ()
OSGDB_EXPORT bool osgDB::makeDirectory (const std::string & directoryPath)
OSGDB_EXPORT bool osgDB::makeDirectoryForFile (const std::string & filePath)
OSGDB_EXPORT Archive* osgDB::openArchive (const std::string & filename, ReaderWriter::ArchiveStatus status, unsigned int indexBlockSizeHint, ReaderWriter::Options * options)
Open an archive for reading or writing.
OSGDB_EXPORT Archive* osgDB::openArchive (const std::string & filename, ReaderWriter::ArchiveStatus status, unsigned int indexBlockSizeHint = 4096)
Open an archive for reading or writing.
bool OSGDB_EXPORT osgDB::outputPluginDetails (std::ostream & out, const std::string & fileName)
bool OSGDB_EXPORT osgDB::queryPlugin (const std::string & fileName, ReaderWriterInfoList & infoList)
void osgDB::readCommandLine (osg::ArgumentParser & parser) [inline]
read the command line arguments.
References osgDB::Registry::instance(), and osgDB::Registry::readCommandLine().
Referenced by osg::CullSettings::CullSettings(), and osg::DisplaySettings::DisplaySettings().
OSGDB_EXPORT osg::HeightField* osgDB::readHeightFieldFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::HeightField from file.
Return valid osg::HeightField on success, return NULL on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readHeightFieldFile().
osg::HeightField* osgDB::readHeightFieldFile (const std::string & filename) [inline]
Read an osg::HeightField from file.
Return valid osg::HeightField on success, return NULL on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readHeightFieldFile().
osg::Image* osgDB::readImageFile (const std::string & filename) [inline]
Read an osg::Image from file.
Return valid osg::Image on success, return NULL on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readImageFile().
OSGDB_EXPORT osg::Image* osgDB::readImageFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Image from file.
Return valid osg::Image on success, return NULL on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readImageFile().
osg::Node* osgDB::readNodeFile (const std::string & filename) [inline]
Read an osg::Node from file.
Return valid osg::Node on success, return NULL on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readNodeFile().
OSGDB_EXPORT osg::Node* osgDB::readNodeFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Node from file.
Return valid osg::Node on success, return NULL on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readNodeFile().
OSGDB_EXPORT osg::Node* osgDB::readNodeFiles (std::vector< std::string > & commandLine, const ReaderWriter::Options * options)
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
Use the Options object to control cache operations and file search paths in osgDB::Registry.
Referenced by readNodeFiles().
osg::Node* osgDB::readNodeFiles (std::vector< std::string > & commandLine) [inline]
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
References osgDB::Registry::instance(), and readNodeFiles().
OSGDB_EXPORT osg::Node* osgDB::readNodeFiles (osg::ArgumentParser & parser, const ReaderWriter::Options * options)
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
Use the Options object to control cache operations and file search paths in osgDB::Registry.
osg::Node* osgDB::readNodeFiles (osg::ArgumentParser & parser) [inline]
Read an osg::Node subgraph from files, creating a osg::Group to contain the nodes if more than one subgraph has been loaded.
References osgDB::Registry::instance(), and readNodeFiles().
osg::Object* osgDB::readObjectFile (const std::string & filename) [inline]
Read an osg::Object from file.
Return valid osg::Object on success, return NULL on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readObjectFile().
OSGDB_EXPORT osg::Object* osgDB::readObjectFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Object from file.
Return valid osg::Object on success, return NULL on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readObjectFile().
OSGDB_EXPORT osg::ref_ptr<osg::HeightField> osgDB::readRefHeightFieldFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::HeightField from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readRefHeightFieldFile().
osg::ref_ptr<osg::HeightField> osgDB::readRefHeightFieldFile (const std::string & filename) [inline]
Read an osg::HeightField from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readRefHeightFieldFile().
OSGDB_EXPORT osg::ref_ptr<osg::Image> osgDB::readRefImageFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Image from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readRefImageFile().
osg::ref_ptr<osg::Image> osgDB::readRefImageFile (const std::string & filename) [inline]
Read an osg::Image from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readRefImageFile().
OSGDB_EXPORT osg::ref_ptr<osg::Node> osgDB::readRefNodeFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Node from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readRefNodeFile().
osg::ref_ptr<osg::Node> osgDB::readRefNodeFile (const std::string & filename) [inline]
Read an osg::Node from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readRefNodeFile().
OSGDB_EXPORT osg::ref_ptr<osg::Object> osgDB::readRefObjectFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Object from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readRefObjectFile().
osg::ref_ptr<osg::Object> osgDB::readRefObjectFile (const std::string & filename) [inline]
Read an osg::Object from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readRefObjectFile().
osg::ref_ptr<osg::Shader> osgDB::readRefShaderFile (const std::string & filename) [inline]
Read an osg::Shader from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readRefShaderFile().
OSGDB_EXPORT osg::ref_ptr<osg::Shader> osgDB::readRefShaderFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Shader from file.
Return an assigned osg::ref_ptr on success, return an osg::ref_ptr with a NULL pointer assigned to it on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readRefShaderFile().
OSGDB_EXPORT osg::Shader* osgDB::readShaderFile (const std::string & filename, const ReaderWriter::Options * options)
Read an osg::Shader from file.
Return valid osg::Shader on success, return NULL on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
Referenced by readShaderFile().
osg::Shader* osgDB::readShaderFile (const std::string & filename) [inline]
Read an osg::Shader from file.
Return valid osg::Shader on success, return NULL on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readShaderFile().
osg::Shader* osgDB::readShaderFile (osg::Shader::Type type, const std::string & filename, const ReaderWriter::Options * options) [inline]
Read an osg::Shader from file and set to specified shader type.
Return valid osg::Shader on success, return NULL on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References readShaderFile(), osg::Shader::setType(), and osg::Shader::UNDEFINED.
osg::Shader* osgDB::readShaderFile (osg::Shader::Type type, const std::string & filename) [inline]
Read an osg::Shader from file and set to specified shader type Return valid osg::Shader on success, return NULL on failure.
The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to read the specified file.
References osgDB::Registry::instance(), and readShaderFile().
OSGDB_EXPORT bool osgDB::setCurrentWorkingDirectory (const std::string & newCurrentWorkingDirectory)
void osgDB::setDataFilePathList (const FilePathList & filepath) [inline]
References osgDB::Registry::instance(), and osgDB::Registry::setDataFilePathList().
void osgDB::setDataFilePathList (const std::string & paths) [inline]
References osgDB::Registry::instance(), and osgDB::Registry::setDataFilePathList().
void osgDB::setLibraryFilePathList (const std::string & paths) [inline]
References osgDB::Registry::instance(), and osgDB::Registry::setLibraryFilePathList().
void osgDB::setLibraryFilePathList (const FilePathList & filepaths) [inline]
References osgDB::Registry::instance(), and osgDB::Registry::setLibraryFilePathList().
template<class Iterator > void osgDB::writeArray (Output & fw, Iterator first, Iterator last, int noItemsPerLine = 0)
References osgDB::Output::getNumIndicesPerLine(), osgDB::Output::indent(), osgDB::Output::moveIn(), and osgDB::Output::moveOut().
template<class Iterator > void osgDB::writeArrayAsInts (Output & fw, Iterator first, Iterator last, int noItemsPerLine = 0)
References osgDB::Output::getNumIndicesPerLine(), osgDB::Output::indent(), osgDB::Output::moveIn(), and osgDB::Output::moveOut().
bool osgDB::writeHeightFieldFile (const osg::HeightField & hf, const std::string & filename) [inline]
Write an osg::HeightField to file.
Return true on success, return false on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
References osgDB::Registry::instance(), and writeHeightFieldFile().
OSGDB_EXPORT bool osgDB::writeHeightFieldFile (const osg::HeightField & hf, const std::string & filename, const ReaderWriter::Options * options)
Write an osg::HeightField to file.
Return true on success, return false on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
Referenced by writeHeightFieldFile().
OSGDB_EXPORT bool osgDB::writeImageFile (const osg::Image & image, const std::string & filename, const ReaderWriter::Options * options)
Write an osg::Image to file.
Return true on success, return false on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
Referenced by writeImageFile().
bool osgDB::writeImageFile (const osg::Image & image, const std::string & filename) [inline]
Write an osg::Image to file.
Return true on success, return false on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
References osgDB::Registry::instance(), and writeImageFile().
OSGDB_EXPORT bool osgDB::writeNodeFile (const osg::Node & node, const std::string & filename, const ReaderWriter::Options * options)
Write an osg::Node to file.
Return true on success, return false on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
Referenced by writeNodeFile().
bool osgDB::writeNodeFile (const osg::Node & node, const std::string & filename) [inline]
Write an osg::Node to file.
Return true on success, return false on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
References osgDB::Registry::instance(), and writeNodeFile().
OSGDB_EXPORT bool osgDB::writeObjectFile (const osg::Object & object, const std::string & filename, const ReaderWriter::Options * options)
Write an osg::Object to file.
Return true on success, return false on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
Referenced by writeObjectFile().
bool osgDB::writeObjectFile (const osg::Object & object, const std::string & filename) [inline]
Write an osg::Object to file.
Return true on success, return false on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
References osgDB::Registry::instance(), and writeObjectFile().
bool osgDB::writeShaderFile (const osg::Shader & shader, const std::string & filename) [inline]
Write an osg::Shader to file.
Return true on success, return false on failure. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
References osgDB::Registry::instance(), and writeShaderFile().
OSGDB_EXPORT bool osgDB::writeShaderFile (const osg::Shader & shader, const std::string & filename, const ReaderWriter::Options * options)
Write an osg::Shader to file.
Return true on success, return false on failure. Use the Options object to control cache operations and file search paths in osgDB::Registry. The osgDB::Registry is used to load the appropriate ReaderWriter plugin for the filename extension, and this plugin then handles the request to write the specified file.
Referenced by writeShaderFile().
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.