OpenSceneGraph: osgParticle::BoxPlacer Class Reference
osgParticle::BoxPlacer Class Reference
A box-shaped particle placer.
Public Member Functions
BoxPlacer ()
BoxPlacer (const BoxPlacer &copy, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
const rangef & getXRange () const
Get the range of possible values along the X axis.
void setXRange (const rangef &r)
Set the range of possible values along the X axis.
void setXRange (float r1, float r2)
Set the range of possible values along the X axis.
const rangef & getYRange () const
Get the range of possible values along the Y axis.
void setYRange (const rangef &r)
Set the range of possible values along the Y axis.
void setYRange (float r1, float r2)
Set the range of possible values along the Y axis.
const rangef & getZRange () const
Get the range of possible values along the Z axis.
void setZRange (const rangef &r)
Set the range of possible values along the Z axis.
void setZRange (float r1, float r2)
Set the range of possible values along the Z axis.
META_Object (osgParticle, BoxPlacer)
void place (Particle *P) const
Place a particle. Do not call it manually.
osg::Vec3 getControlPosition () const
return the control position
Protected Member Functions
virtual ~BoxPlacer ()
BoxPlacer & operator= (const BoxPlacer &)
Detailed Description
A box-shaped particle placer.
This placer sets the initial position of incoming particle by choosing a random position within the volume of a box; this placer is defined by four parameters: a center point, which is inherited directly from osgParticle::CenteredPlacer, and three ranges of values for the valid X, Y, and Z coordinates.
Constructor & Destructor Documentation
osgParticle::BoxPlacer::BoxPlacer () [inline]
osgParticle::BoxPlacer::BoxPlacer (const BoxPlacer & copy, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
virtual osgParticle::BoxPlacer::~BoxPlacer () [inline, protected, virtual]
Member Function Documentation
osg::Vec3 osgParticle::BoxPlacer::getControlPosition () const [inline, virtual]
return the control position
Implements osgParticle::Placer.
References osgParticle::CenteredPlacer::getCenter().
const rangef & osgParticle::BoxPlacer::getXRange () const [inline]
Get the range of possible values along the X axis.
const rangef & osgParticle::BoxPlacer::getYRange () const [inline]
Get the range of possible values along the Y axis.
const rangef & osgParticle::BoxPlacer::getZRange () const [inline]
Get the range of possible values along the Z axis.
osgParticle::BoxPlacer::META_Object (osgParticle , BoxPlacer)
BoxPlacer& osgParticle::BoxPlacer::operator= (const BoxPlacer &) [inline, protected]
void osgParticle::BoxPlacer::place (Particle * P) const [inline, virtual]
Place a particle. Do not call it manually.
Implements osgParticle::Placer.
References osgParticle::range< ValueType >::get_random(), osgParticle::CenteredPlacer::getCenter(), osgParticle::Particle::setPosition(), osg::Vec3f::y(), and osg::Vec3f::z().
void osgParticle::BoxPlacer::setXRange (const rangef & r) [inline]
Set the range of possible values along the X axis.
void osgParticle::BoxPlacer::setXRange (float r1, float r2) [inline]
Set the range of possible values along the X axis.
References osgParticle::range< ValueType >::maximum, and osgParticle::range< ValueType >::minimum.
void osgParticle::BoxPlacer::setYRange (const rangef & r) [inline]
Set the range of possible values along the Y axis.
void osgParticle::BoxPlacer::setYRange (float r1, float r2) [inline]
Set the range of possible values along the Y axis.
References osgParticle::range< ValueType >::maximum, and osgParticle::range< ValueType >::minimum.
void osgParticle::BoxPlacer::setZRange (const rangef & r) [inline]
Set the range of possible values along the Z axis.
void osgParticle::BoxPlacer::setZRange (float r1, float r2) [inline]
Set the range of possible values along the Z axis.
References osgParticle::range< ValueType >::maximum, and osgParticle::range< ValueType >::minimum.
The documentation for this class was generated from the following file:
osgParticle/BoxPlacer
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.