OpenSceneGraph: osgAnimation::Bone Class Reference
osgAnimation::Bone Class Reference
Public Types
typedef osg::Matrix MatrixType
Public Member Functions
META_Node (osgAnimation, Bone)
Bone (const Bone &b, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
Bone (const std::string &name="")
void setDefaultUpdateCallback (const std::string &name="")
Bone * getBoneParent ()
const Bone * getBoneParent () const
const osg::Matrix & getMatrixInBoneSpace () const
const osg::Matrix & getMatrixInSkeletonSpace () const
const osg::Matrix & getInvBindMatrixInSkeletonSpace () const
void setMatrixInSkeletonSpace (const osg::Matrix &matrix)
void setInvBindMatrixInSkeletonSpace (const osg::Matrix &matrix)
Protected Attributes
osg::Matrix _invBindInSkeletonSpace
osg::Matrix _boneInSkeletonSpace
Member Typedef Documentation
typedef osg::Matrix osgAnimation::Bone::MatrixType
Constructor & Destructor Documentation
osgAnimation::Bone::Bone (const Bone & b, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY)
osgAnimation::Bone::Bone (const std::string & name = "")
Member Function Documentation
Bone* osgAnimation::Bone::getBoneParent ()
const Bone* osgAnimation::Bone::getBoneParent () const
const osg::Matrix& osgAnimation::Bone::getInvBindMatrixInSkeletonSpace () const [inline]
Referenced by osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::computeMatrixForVertexSet(), and osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::computeMatrixForVertexSet().
const osg::Matrix& osgAnimation::Bone::getMatrixInBoneSpace () const [inline]
const osg::Matrix& osgAnimation::Bone::getMatrixInSkeletonSpace () const [inline]
Referenced by osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::computeMatrixForVertexSet(), and osgAnimation::RigTransformSoftware::UniqBoneSetVertexSet::computeMatrixForVertexSet().
osgAnimation::Bone::META_Node (osgAnimation , Bone)
void osgAnimation::Bone::setDefaultUpdateCallback (const std::string & name = "")
void osgAnimation::Bone::setInvBindMatrixInSkeletonSpace (const osg::Matrix & matrix) [inline]
void osgAnimation::Bone::setMatrixInSkeletonSpace (const osg::Matrix & matrix) [inline]
Member Data Documentation
osg::Matrix osgAnimation::Bone::_boneInSkeletonSpace [protected]
osg::Matrix osgAnimation::Bone::_invBindInSkeletonSpace [protected]
The documentation for this class was generated from the following file:
osgAnimation/Bone
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.