OpenSceneGraph: osgUtil::BaseOptimizerVisitor Class Reference
osgUtil::BaseOptimizerVisitor Class Reference
Helper base class for implementing Optimizer techniques.
Public Member Functions
BaseOptimizerVisitor (Optimizer *optimizer, unsigned int operation)
bool isOperationPermissibleForObject (const osg::StateSet *object) const
bool isOperationPermissibleForObject (const osg::StateAttribute *object) const
bool isOperationPermissibleForObject (const osg::Drawable *object) const
bool isOperationPermissibleForObject (const osg::Node *object) const
Protected Attributes
Optimizer * _optimizer
unsigned int _operationType
Detailed Description
Helper base class for implementing Optimizer techniques.
Constructor & Destructor Documentation
osgUtil::BaseOptimizerVisitor::BaseOptimizerVisitor (Optimizer * optimizer, unsigned int operation) [inline]
Member Function Documentation
bool osgUtil::BaseOptimizerVisitor::isOperationPermissibleForObject (const osg::StateSet * object) const [inline]
References _operationType, _optimizer, and osgUtil::Optimizer::isOperationPermissibleForObject().
bool osgUtil::BaseOptimizerVisitor::isOperationPermissibleForObject (const osg::Node * object) const [inline]
References _operationType, _optimizer, and osgUtil::Optimizer::isOperationPermissibleForObject().
bool osgUtil::BaseOptimizerVisitor::isOperationPermissibleForObject (const osg::Drawable * object) const [inline]
References _operationType, _optimizer, and osgUtil::Optimizer::isOperationPermissibleForObject().
bool osgUtil::BaseOptimizerVisitor::isOperationPermissibleForObject (const osg::StateAttribute * object) const [inline]
References _operationType, _optimizer, and osgUtil::Optimizer::isOperationPermissibleForObject().
Member Data Documentation
unsigned int osgUtil::BaseOptimizerVisitor::_operationType [protected]
Referenced by isOperationPermissibleForObject().
Optimizer* osgUtil::BaseOptimizerVisitor::_optimizer [protected]
Referenced by isOperationPermissibleForObject().
The documentation for this class was generated from the following file:
osgUtil/Optimizer
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.