OpenSceneGraph: osgParticle::AngularAccelOperator Class Reference
osgParticle::AngularAccelOperator Class Reference
An operator class that applies a constant angular acceleration to the particles.
Public Member Functions
AngularAccelOperator ()
AngularAccelOperator (const AngularAccelOperator &copy, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgParticle, AngularAccelOperator)
const osg::Vec3 & getAngularAcceleration () const
Get the angular acceleration vector.
void setAngularAcceleration (const osg::Vec3 &v)
Set the angular acceleration vector.
void operate (Particle *P, double dt)
Apply the angular acceleration to a particle. Do not call this method manually.
void beginOperate (Program *prg)
Perform some initializations. Do not call this method manually.
Protected Member Functions
virtual ~AngularAccelOperator ()
AngularAccelOperator & operator= (const AngularAccelOperator &)
Detailed Description
An operator class that applies a constant angular acceleration to the particles.
Constructor & Destructor Documentation
osgParticle::AngularAccelOperator::AngularAccelOperator () [inline]
osgParticle::AngularAccelOperator::AngularAccelOperator (const AngularAccelOperator & copy, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
virtual osgParticle::AngularAccelOperator::~AngularAccelOperator () [inline, protected, virtual]
Member Function Documentation
void osgParticle::AngularAccelOperator::beginOperate (Program * prg) [inline, virtual]
Perform some initializations. Do not call this method manually.
Reimplemented from osgParticle::Operator.
References osgParticle::ParticleProcessor::getReferenceFrame(), and osgParticle::ParticleProcessor::rotateLocalToWorld().
const osg::Vec3 & osgParticle::AngularAccelOperator::getAngularAcceleration () const [inline]
Get the angular acceleration vector.
osgParticle::AngularAccelOperator::META_Object (osgParticle , AngularAccelOperator)
void osgParticle::AngularAccelOperator::operate (Particle * P, double dt) [inline, virtual]
Apply the angular acceleration to a particle. Do not call this method manually.
Implements osgParticle::Operator.
References osgParticle::Particle::addAngularVelocity().
AngularAccelOperator& osgParticle::AngularAccelOperator::operator= (const AngularAccelOperator &) [inline, protected]
void osgParticle::AngularAccelOperator::setAngularAcceleration (const osg::Vec3 & v) [inline]
Set the angular acceleration vector.
The documentation for this class was generated from the following file:
osgParticle/AngularAccelOperator
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.