OpenSceneGraph: osgIntrospection::ConstructorInfo Class Reference
osgIntrospection::ConstructorInfo Class Reference
Public Member Functions
ConstructorInfo (const Type &declaratiionType, const ParameterInfoList &params, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
ConstructorInfo (const Type &declaratiionType, const ParameterInfoList &params, bool isExplicit, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
virtual ~ConstructorInfo ()
virtual const std::string & getBriefHelp () const
Returns the brief help of the reflected construtor.
virtual const std::string & getDetailedHelp () const
Returns the detailed help of the reflected contructor.
const Type & getDeclaringType () const
Returns the Type object associated to the type that declares the reflected constructor.
const ParameterInfoList & getParameters () const
Returns a list of objects that describe the reflected constructor's parameters.
bool isExplicit () const
Returns true if this constructor is explicit.
virtual Value createInstance (ValueList &args) const =0
Invokes the reflected constructor dynamically passing it the arguments as a list of Value objects.
Protected Member Functions
virtual void getInheritedProviders (CustomAttributeProviderList &providers) const
Constructor & Destructor Documentation
osgIntrospection::ConstructorInfo::ConstructorInfo (const Type & declaratiionType, const ParameterInfoList & params, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
osgIntrospection::ConstructorInfo::ConstructorInfo (const Type & declaratiionType, const ParameterInfoList & params, bool isExplicit, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
virtual osgIntrospection::ConstructorInfo::~ConstructorInfo () [inline, virtual]
Member Function Documentation
virtual Value osgIntrospection::ConstructorInfo::createInstance (ValueList & args) const [pure virtual]
Invokes the reflected constructor dynamically passing it the arguments as a list of Value objects.
Implemented in osgIntrospection::TypedConstructorInfo0< C, IC >, osgIntrospection::TypedConstructorInfo1< C, IC, P0 >, osgIntrospection::TypedConstructorInfo2< C, IC, P0, P1 >, osgIntrospection::TypedConstructorInfo3< C, IC, P0, P1, P2 >, osgIntrospection::TypedConstructorInfo4< C, IC, P0, P1, P2, P3 >, osgIntrospection::TypedConstructorInfo5< C, IC, P0, P1, P2, P3, P4 >, osgIntrospection::TypedConstructorInfo6< C, IC, P0, P1, P2, P3, P4, P5 >, osgIntrospection::TypedConstructorInfo7< C, IC, P0, P1, P2, P3, P4, P5, P6 >, osgIntrospection::TypedConstructorInfo8< C, IC, P0, P1, P2, P3, P4, P5, P6, P7 >, osgIntrospection::TypedConstructorInfo9< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8 >, osgIntrospection::TypedConstructorInfo10< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >, osgIntrospection::TypedConstructorInfo11< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >, osgIntrospection::TypedConstructorInfo12< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >, osgIntrospection::TypedConstructorInfo13< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >, osgIntrospection::TypedConstructorInfo14< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >, osgIntrospection::TypedConstructorInfo15< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >, and osgIntrospection::TypedConstructorInfo16< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >.
virtual const std::string& osgIntrospection::ConstructorInfo::getBriefHelp () const [inline, virtual]
Returns the brief help of the reflected construtor.
const Type& osgIntrospection::ConstructorInfo::getDeclaringType () const [inline]
Returns the Type object associated to the type that declares the reflected constructor.
virtual const std::string& osgIntrospection::ConstructorInfo::getDetailedHelp () const [inline, virtual]
Returns the detailed help of the reflected contructor.
virtual void osgIntrospection::ConstructorInfo::getInheritedProviders (CustomAttributeProviderList & providers) const [protected, virtual]
Implements osgIntrospection::CustomAttributeProvider.
const ParameterInfoList& osgIntrospection::ConstructorInfo::getParameters () const [inline]
Returns a list of objects that describe the reflected constructor's parameters.
Referenced by osgIntrospection::TypedConstructorInfo16< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >::createInstance(), osgIntrospection::TypedConstructorInfo15< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >::createInstance(), osgIntrospection::TypedConstructorInfo14< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >::createInstance(), osgIntrospection::TypedConstructorInfo13< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >::createInstance(), osgIntrospection::TypedConstructorInfo12< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >::createInstance(), osgIntrospection::TypedConstructorInfo11< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >::createInstance(), osgIntrospection::TypedConstructorInfo10< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::createInstance(), osgIntrospection::TypedConstructorInfo9< C, IC, P0, P1, P2, P3, P4, P5, P6, P7, P8 >::createInstance(), osgIntrospection::TypedConstructorInfo8< C, IC, P0, P1, P2, P3, P4, P5, P6, P7 >::createInstance(), osgIntrospection::TypedConstructorInfo7< C, IC, P0, P1, P2, P3, P4, P5, P6 >::createInstance(), osgIntrospection::TypedConstructorInfo6< C, IC, P0, P1, P2, P3, P4, P5 >::createInstance(), osgIntrospection::TypedConstructorInfo5< C, IC, P0, P1, P2, P3, P4 >::createInstance(), osgIntrospection::TypedConstructorInfo4< C, IC, P0, P1, P2, P3 >::createInstance(), osgIntrospection::TypedConstructorInfo3< C, IC, P0, P1, P2 >::createInstance(), osgIntrospection::TypedConstructorInfo2< C, IC, P0, P1 >::createInstance(), and osgIntrospection::TypedConstructorInfo1< C, IC, P0 >::createInstance().
bool osgIntrospection::ConstructorInfo::isExplicit () const [inline]
Returns true if this constructor is explicit.
The documentation for this class was generated from the following file:
osgIntrospection/ConstructorInfo
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.