OpenSceneGraph: osgGA::EventVisitor Class Reference
osgGA::EventVisitor Class Reference
Basic EventVisitor implementation for animating a scene.
Public Types
typedef std::list
< osg::ref_ptr
< GUIEventAdapter > > EventList
Public Member Functions
EventVisitor ()
virtual ~EventVisitor ()
META_NodeVisitor ("osgGA","EventVisitor") void setActionAdapter(osgGA
osgGA::GUIActionAdapter * getActionAdapter ()
const osgGA::GUIActionAdapter * getActionAdapter () const
void addEvent (GUIEventAdapter *event)
void removeEvent (GUIEventAdapter *event)
void setEventHandled (bool handled)
bool getEventHandled () const
void setEvents (const EventQueue::Events &events)
EventQueue::Events & getEvents ()
const EventQueue::Events & getEvents () const
virtual void reset ()
Method to call to reset visitor.
virtual void apply (osg::Node &node)
During traversal each type of node calls its callbacks and its children traversed.
virtual void apply (osg::Geode &node)
virtual void apply (osg::Billboard &node)
virtual void apply (osg::LightSource &node)
virtual void apply (osg::Group &node)
virtual void apply (osg::Transform &node)
virtual void apply (osg::Projection &node)
virtual void apply (osg::Switch &node)
virtual void apply (osg::LOD &node)
virtual void apply (osg::OccluderNode &node)
Protected Member Functions
EventVisitor & operator= (const EventVisitor &)
Prevent unwanted copy operator.
void handle_callbacks (osg::StateSet *stateset)
void handle_callbacks_and_traverse (osg::Node &node)
void handle_geode_callbacks (osg::Geode &node)
void traverseGeode (osg::Geode &geode)
Protected Attributes
osgGA::GUIActionAdapter * _actionAdapter
osg::ref_ptr< GUIEventAdapter > _accumulateEventState
bool _handled
EventQueue::Events _events
Detailed Description
Basic EventVisitor implementation for animating a scene.
This visitor traverses the scene graph, calling each nodes appCallback if it exists.
Member Typedef Documentation
typedef std::list< osg::ref_ptr<GUIEventAdapter> > osgGA::EventVisitor::EventList
Constructor & Destructor Documentation
osgGA::EventVisitor::EventVisitor ()
virtual osgGA::EventVisitor::~EventVisitor () [virtual]
Member Function Documentation
void osgGA::EventVisitor::addEvent (GUIEventAdapter * event)
virtual void osgGA::EventVisitor::apply (osg::Group & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::Transform & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::Projection & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::Switch & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::LOD & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::OccluderNode & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::Node & node) [inline, virtual]
During traversal each type of node calls its callbacks and its children traversed.
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::Geode & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::Billboard & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
virtual void osgGA::EventVisitor::apply (osg::LightSource & node) [inline, virtual]
Reimplemented from osg::NodeVisitor.
osgGA::GUIActionAdapter* osgGA::EventVisitor::getActionAdapter () [inline]
const osgGA::GUIActionAdapter* osgGA::EventVisitor::getActionAdapter () const [inline]
bool osgGA::EventVisitor::getEventHandled () const [inline]
EventQueue::Events& osgGA::EventVisitor::getEvents () [inline]
const EventQueue::Events& osgGA::EventVisitor::getEvents () const [inline]
void osgGA::EventVisitor::handle_callbacks (osg::StateSet * stateset) [inline, protected]
References osg::StateSet::requiresEventTraversal(), and osg::StateSet::runEventCallbacks().
void osgGA::EventVisitor::handle_callbacks_and_traverse (osg::Node & node) [inline, protected]
References osg::Node::getEventCallback(), and osg::Node::getStateSet().
void osgGA::EventVisitor::handle_geode_callbacks (osg::Geode & node) [inline, protected]
References osg::Node::getEventCallback(), and osg::Node::getStateSet().
osgGA::EventVisitor::META_NodeVisitor ("osgGA" , "EventVisitor") [inline]
EventVisitor& osgGA::EventVisitor::operator= (const EventVisitor &) [inline, protected]
Prevent unwanted copy operator.
void osgGA::EventVisitor::removeEvent (GUIEventAdapter * event)
virtual void osgGA::EventVisitor::reset () [virtual]
Method to call to reset visitor.
Useful if your visitor accumulates state during a traversal, and you plan to reuse the visitor. To flush that state for the next traversal: call reset() prior to each traversal.
Reimplemented from osg::NodeVisitor.
void osgGA::EventVisitor::setEventHandled (bool handled) [inline]
void osgGA::EventVisitor::setEvents (const EventQueue::Events & events) [inline]
void osgGA::EventVisitor::traverseGeode (osg::Geode & geode) [inline, protected]
References osg::Drawable::EventCallback::event(), osg::Node::getEventCallback(), and osg::Node::getStateSet().
Member Data Documentation
osg::ref_ptr<GUIEventAdapter> osgGA::EventVisitor::_accumulateEventState [protected]
osgGA::GUIActionAdapter* osgGA::EventVisitor::_actionAdapter [protected]
EventQueue::Events osgGA::EventVisitor::_events [protected]
bool osgGA::EventVisitor::_handled [protected]
The documentation for this class was generated from the following file:
osgGA/EventVisitor
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.