OpenSceneGraph: osgUtil::LineSegmentIntersector::Intersection Struct Reference
osgUtil::LineSegmentIntersector::Intersection Struct Reference
Public Types
typedef std::vector< unsigned int > IndexList
typedef std::vector< double > RatioList
Public Member Functions
Intersection ()
bool operator< (const Intersection &rhs) const
const osg::Vec3d & getLocalIntersectPoint () const
osg::Vec3d getWorldIntersectPoint () const
const osg::Vec3 & getLocalIntersectNormal () const
osg::Vec3 getWorldIntersectNormal () const
Public Attributes
double ratio
osg::NodePath nodePath
osg::ref_ptr< osg::Drawable > drawable
osg::ref_ptr< osg::RefMatrix > matrix
osg::Vec3d localIntersectionPoint
osg::Vec3 localIntersectionNormal
IndexList indexList
RatioList ratioList
unsigned int primitiveIndex
Member Typedef Documentation
typedef std::vector<unsigned int> osgUtil::LineSegmentIntersector::Intersection::IndexList
typedef std::vector<double> osgUtil::LineSegmentIntersector::Intersection::RatioList
Constructor & Destructor Documentation
osgUtil::LineSegmentIntersector::Intersection::Intersection () [inline]
Member Function Documentation
const osg::Vec3& osgUtil::LineSegmentIntersector::Intersection::getLocalIntersectNormal () const [inline]
const osg::Vec3d& osgUtil::LineSegmentIntersector::Intersection::getLocalIntersectPoint () const [inline]
osg::Vec3 osgUtil::LineSegmentIntersector::Intersection::getWorldIntersectNormal () const [inline]
References osg::Matrixd::inverse(), osg::Matrixd::transform3x3(), and osg::Vec3f::valid().
osg::Vec3d osgUtil::LineSegmentIntersector::Intersection::getWorldIntersectPoint () const [inline]
References osg::Vec3d::valid().
bool osgUtil::LineSegmentIntersector::Intersection::operator< (const Intersection & rhs) const [inline]
References ratio.
Member Data Documentation
osg::ref_ptr<osg::Drawable> osgUtil::LineSegmentIntersector::Intersection::drawable
IndexList osgUtil::LineSegmentIntersector::Intersection::indexList
osg::Vec3 osgUtil::LineSegmentIntersector::Intersection::localIntersectionNormal
osg::Vec3d osgUtil::LineSegmentIntersector::Intersection::localIntersectionPoint
osg::ref_ptr<osg::RefMatrix> osgUtil::LineSegmentIntersector::Intersection::matrix
osg::NodePath osgUtil::LineSegmentIntersector::Intersection::nodePath
unsigned int osgUtil::LineSegmentIntersector::Intersection::primitiveIndex
double osgUtil::LineSegmentIntersector::Intersection::ratio
Referenced by operator<().
RatioList osgUtil::LineSegmentIntersector::Intersection::ratioList
The documentation for this struct was generated from the following file:
osgUtil/LineSegmentIntersector
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.