OpenSceneGraph: osg::Matrix2 Class Reference
osg::Matrix2 Class Reference
Public Member Functions
Matrix2 ()
Matrix2 (const Matrix2 &mat)
Matrix2 (float a00, float a01, float a10, float a11)
~Matrix2 ()
float & operator() (int row, int col)
float operator() (int row, int col) const
Matrix2 & operator= (const Matrix2 &rhs)
void set (const Matrix2 &rhs)
void set (float const *const ptr)
void set (float a00, float a01, float a10, float a11)
float * ptr ()
const float * ptr () const
float & operator[] (int i)
float operator[] (int i) const
void makeIdentity ()
Protected Attributes
float _mat [2][2]
Constructor & Destructor Documentation
osg::Matrix2::Matrix2 () [inline]
osg::Matrix2::Matrix2 (const Matrix2 & mat) [inline]
References ptr().
osg::Matrix2::Matrix2 (float a00, float a01, float a10, float a11) [inline]
osg::Matrix2::~Matrix2 () [inline]
Member Function Documentation
void osg::Matrix2::makeIdentity () [inline]
float& osg::Matrix2::operator() (int row, int col) [inline]
float osg::Matrix2::operator() (int row, int col) const [inline]
Matrix2& osg::Matrix2::operator= (const Matrix2 & rhs) [inline]
References ptr().
float& osg::Matrix2::operator[] (int i) [inline]
float osg::Matrix2::operator[] (int i) const [inline]
const float* osg::Matrix2::ptr () const [inline]
float* osg::Matrix2::ptr () [inline]
Referenced by Matrix2(), and operator=().
void osg::Matrix2::set (float const *const ptr) [inline]
void osg::Matrix2::set (const Matrix2 & rhs) [inline]
void osg::Matrix2::set (float a00, float a01, float a10, float a11) [inline]
Member Data Documentation
float osg::Matrix2::_mat[2][2] [protected]
The documentation for this class was generated from the following file:
osg/Uniform
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.