OpenSceneGraph: osgWidget::NotifyWidget Struct Reference
osgWidget::NotifyWidget Struct Reference
Public Member Functions
META_Object (osgWidget, NotifyWidget)
NotifyWidget (const std::string &n="", point_type w=0.0f, point_type h=0.0f)
NotifyWidget (const NotifyWidget &widget, const osg::CopyOp &co)
bool focus (const WindowManager *)
bool unfocus (const WindowManager *)
bool mouseEnter (double, double, const WindowManager *)
bool mouseOver (double, double, const WindowManager *)
bool mouseLeave (double, double, const WindowManager *)
bool mouseDrag (double, double, const WindowManager *)
bool mousePush (double, double, const WindowManager *)
bool mouseRelease (double, double, const WindowManager *)
bool mouseScroll (double, double, const WindowManager *)
bool keyPress (int, int, const WindowManager *)
bool keyRelease (int, int, const WindowManager *)
Constructor & Destructor Documentation
osgWidget::NotifyWidget::NotifyWidget (const std::string & n = "", point_type w = 0.0f, point_type h = 0.0f) [inline]
References osgWidget::EVENT_ALL, and osgWidget::EventInterface::setEventMask().
osgWidget::NotifyWidget::NotifyWidget (const NotifyWidget & widget, const osg::CopyOp & co) [inline]
Member Function Documentation
bool osgWidget::NotifyWidget::focus (const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::keyPress (int , int , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::keyRelease (int , int , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
osgWidget::NotifyWidget::META_Object (osgWidget , NotifyWidget)
bool osgWidget::NotifyWidget::mouseDrag (double , double , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::mouseEnter (double , double , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::mouseLeave (double , double , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::mouseOver (double , double , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::mousePush (double , double , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::mouseRelease (double , double , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::mouseScroll (double , double , const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
bool osgWidget::NotifyWidget::unfocus (const WindowManager *) [inline]
References osg::Object::_name, osg::NOTICE, and osg::notify().
The documentation for this struct was generated from the following file:
osgWidget/Widget
Generated at Thu Jun 9 2011 16:37:18 for the OpenSceneGraph by doxygen 1.7.1.