OpenSceneGraph: osgVolume::Locator Class Reference
osgVolume::Locator Class Reference
Public Member Functions
Locator ()
Locator (const osg::Matrixd &transform)
Locator (const Locator &locator, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
META_Object (osgVolume, Locator)
void setTransform (const osg::Matrixd &transform)
Set the transformation from local coordinates to model coordinates.
const osg::Matrixd & getTransform () const
Set the transformation from local coordinates to model coordinates.
void setTransformAsExtents (double minX, double minY, double maxX, double maxY, double minZ, double maxZ)
Set the extents of the local coords.
virtual bool convertLocalToModel (const osg::Vec3d &, osg::Vec3d &) const
virtual bool convertModelToLocal (const osg::Vec3d &, osg::Vec3d &) const
bool computeLocalBounds (osg::Vec3d &bottomLeft, osg::Vec3d &topRight) const
bool computeLocalBounds (Locator &source, osg::Vec3d &bottomLeft, osg::Vec3d &topRight) const
Static Public Member Functions
static bool convertLocalCoordBetween (const Locator &source, const osg::Vec3d &sourceNDC, const Locator &destination, osg::Vec3d &destinationNDC)
Protected Attributes
osg::Matrixd _transform
osg::Matrixd _inverse
Constructor & Destructor Documentation
osgVolume::Locator::Locator () [inline]
osgVolume::Locator::Locator (const osg::Matrixd & transform) [inline]
osgVolume::Locator::Locator (const Locator & locator, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
Copy constructor using CopyOp to manage deep vs shallow copy.
Member Function Documentation
bool osgVolume::Locator::computeLocalBounds (osg::Vec3d & bottomLeft, osg::Vec3d & topRight) const
bool osgVolume::Locator::computeLocalBounds (Locator & source, osg::Vec3d & bottomLeft, osg::Vec3d & topRight) const
static bool osgVolume::Locator::convertLocalCoordBetween (const Locator & source, const osg::Vec3d & sourceNDC, const Locator & destination, osg::Vec3d & destinationNDC) [inline, static]
References convertLocalToModel(), and convertModelToLocal().
virtual bool osgVolume::Locator::convertLocalToModel (const osg::Vec3d & , osg::Vec3d &) const [virtual]
Referenced by convertLocalCoordBetween().
virtual bool osgVolume::Locator::convertModelToLocal (const osg::Vec3d & , osg::Vec3d &) const [virtual]
Referenced by convertLocalCoordBetween().
const osg::Matrixd& osgVolume::Locator::getTransform () const [inline]
Set the transformation from local coordinates to model coordinates.
osgVolume::Locator::META_Object (osgVolume , Locator)
void osgVolume::Locator::setTransform (const osg::Matrixd & transform) [inline]
Set the transformation from local coordinates to model coordinates.
References osg::Matrixd::invert().
void osgVolume::Locator::setTransformAsExtents (double minX, double minY, double maxX, double maxY, double minZ, double maxZ)
Set the extents of the local coords.
Member Data Documentation
osg::Matrixd osgVolume::Locator::_inverse [protected]
osg::Matrixd osgVolume::Locator::_transform [protected]
The documentation for this class was generated from the following file:
osgVolume/Locator
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.