OpenSceneGraph: osg::Matrixf Class Reference
osg::Matrixf Class Reference
Public Types
typedef float value_type
Public Member Functions
Matrixf ()
Matrixf (const Matrixf &mat)
Matrixf (const Matrixd &mat)
Matrixf (float const *const ptr)
Matrixf (double const *const ptr)
Matrixf (const Quat &quat)
Matrixf (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
~Matrixf ()
int compare (const Matrixf &m) const
bool operator< (const Matrixf &m) const
bool operator== (const Matrixf &m) const
bool operator!= (const Matrixf &m) const
value_type & operator() (int row, int col)
value_type operator() (int row, int col) const
bool valid () const
bool isNaN () const
Matrixf & operator= (const Matrixf &rhs)
Matrixf & operator= (const Matrixd &other)
void set (const Matrixf &rhs)
void set (const Matrixd &rhs)
void set (float const *const ptr)
void set (double const *const ptr)
void set (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
value_type * ptr ()
const value_type * ptr () const
bool isIdentity () const
void makeIdentity ()
void makeScale (const Vec3f &)
void makeScale (const Vec3d &)
void makeScale (value_type, value_type, value_type)
void makeTranslate (const Vec3f &)
void makeTranslate (const Vec3d &)
void makeTranslate (value_type, value_type, value_type)
void makeRotate (const Vec3f &from, const Vec3f &to)
void makeRotate (const Vec3d &from, const Vec3d &to)
void makeRotate (value_type angle, const Vec3f &axis)
void makeRotate (value_type angle, const Vec3d &axis)
void makeRotate (value_type angle, value_type x, value_type y, value_type z)
void makeRotate (const Quat &)
void makeRotate (value_type angle1, const Vec3f &axis1, value_type angle2, const Vec3f &axis2, value_type angle3, const Vec3f &axis3)
void makeRotate (value_type angle1, const Vec3d &axis1, value_type angle2, const Vec3d &axis2, value_type angle3, const Vec3d &axis3)
void decompose (osg::Vec3f &translation, osg::Quat &rotation, osg::Vec3f &scale, osg::Quat &so) const
decompose the matrix into translation, rotation, scale and scale orientation.
void decompose (osg::Vec3d &translation, osg::Quat &rotation, osg::Vec3d &scale, osg::Quat &so) const
decompose the matrix into translation, rotation, scale and scale orientation.
void makeOrtho (double left, double right, double bottom, double top, double zNear, double zFar)
Set to an orthographic projection.
bool getOrtho (double &left, double &right, double &bottom, double &top, double &zNear, double &zFar) const
Get the orthographic settings of the orthographic projection matrix.
void makeOrtho2D (double left, double right, double bottom, double top)
Set to a 2D orthographic projection.
void makeFrustum (double left, double right, double bottom, double top, double zNear, double zFar)
Set to a perspective projection.
bool getFrustum (double &left, double &right, double &bottom, double &top, double &zNear, double &zFar) const
Get the frustum settings of a perspective projection matrix.
void makePerspective (double fovy, double aspectRatio, double zNear, double zFar)
Set to a symmetrical perspective projection.
bool getPerspective (double &fovy, double &aspectRatio, double &zNear, double &zFar) const
Get the frustum settings of a symmetric perspective projection matrix.
void makeLookAt (const Vec3d &eye, const Vec3d &center, const Vec3d &up)
Set the position and orientation to be a view matrix, using the same convention as gluLookAt.
void getLookAt (Vec3f &eye, Vec3f &center, Vec3f &up, value_type lookDistance=1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
void getLookAt (Vec3d &eye, Vec3d &center, Vec3d &up, value_type lookDistance=1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
bool invert (const Matrixf &rhs)
invert the matrix rhs, automatically select invert_4x3 or invert_4x4.
bool invert_4x3 (const Matrixf &rhs)
4x3 matrix invert, not right hand column is assumed to be 0,0,0,1.
bool invert_4x4 (const Matrixf &rhs)
full 4x4 matrix invert.
void orthoNormalize (const Matrixf &rhs)
ortho-normalize the 3x3 rotation & scale matrix
Vec3f preMult (const Vec3f &v) const
Vec3d preMult (const Vec3d &v) const
Vec3f postMult (const Vec3f &v) const
Vec3d postMult (const Vec3d &v) const
Vec3f operator* (const Vec3f &v) const
Vec3d operator* (const Vec3d &v) const
Vec4f preMult (const Vec4f &v) const
Vec4d preMult (const Vec4d &v) const
Vec4f postMult (const Vec4f &v) const
Vec4d postMult (const Vec4d &v) const
Vec4f operator* (const Vec4f &v) const
Vec4d operator* (const Vec4d &v) const
void setRotate (const Quat &q)
Quat getRotate () const
Get the matrix rotation as a Quat.
void setTrans (value_type tx, value_type ty, value_type tz)
void setTrans (const Vec3f &v)
void setTrans (const Vec3d &v)
Vec3d getTrans () const
Vec3d getScale () const
void mult (const Matrixf &, const Matrixf &)
void preMult (const Matrixf &)
void postMult (const Matrixf &)
void preMultTranslate (const Vec3d &v)
Optimized version of preMult(translate(v));.
void preMultTranslate (const Vec3f &v)
void postMultTranslate (const Vec3d &v)
Optimized version of postMult(translate(v));.
void postMultTranslate (const Vec3f &v)
void preMultScale (const Vec3d &v)
Optimized version of preMult(scale(v));.
void preMultScale (const Vec3f &v)
void postMultScale (const Vec3d &v)
Optimized version of postMult(scale(v));.
void postMultScale (const Vec3f &v)
void preMultRotate (const Quat &q)
Optimized version of preMult(rotate(q));.
void postMultRotate (const Quat &q)
Optimized version of postMult(rotate(q));.
void operator*= (const Matrixf &other)
Matrixf operator* (const Matrixf &m) const
Static Public Member Functions
static Matrixf identity (void)
static Matrixf scale (const Vec3f &sv)
static Matrixf scale (const Vec3d &sv)
static Matrixf scale (value_type sx, value_type sy, value_type sz)
static Matrixf translate (const Vec3f &dv)
static Matrixf translate (const Vec3d &dv)
static Matrixf translate (value_type x, value_type y, value_type z)
static Matrixf rotate (const Vec3f &from, const Vec3f &to)
static Matrixf rotate (const Vec3d &from, const Vec3d &to)
static Matrixf rotate (value_type angle, value_type x, value_type y, value_type z)
static Matrixf rotate (value_type angle, const Vec3f &axis)
static Matrixf rotate (value_type angle, const Vec3d &axis)
static Matrixf rotate (value_type angle1, const Vec3f &axis1, value_type angle2, const Vec3f &axis2, value_type angle3, const Vec3f &axis3)
static Matrixf rotate (value_type angle1, const Vec3d &axis1, value_type angle2, const Vec3d &axis2, value_type angle3, const Vec3d &axis3)
static Matrixf rotate (const Quat &quat)
static Matrixf inverse (const Matrixf &matrix)
static Matrixf orthoNormal (const Matrixf &matrix)
static Matrixf ortho (double left, double right, double bottom, double top, double zNear, double zFar)
Create an orthographic projection matrix.
static Matrixf ortho2D (double left, double right, double bottom, double top)
Create a 2D orthographic projection.
static Matrixf frustum (double left, double right, double bottom, double top, double zNear, double zFar)
Create a perspective projection.
static Matrixf perspective (double fovy, double aspectRatio, double zNear, double zFar)
Create a symmetrical perspective projection.
static Matrixf lookAt (const Vec3f &eye, const Vec3f &center, const Vec3f &up)
Create the position and orientation as per a camera, using the same convention as gluLookAt.
static Matrixf lookAt (const Vec3d &eye, const Vec3d &center, const Vec3d &up)
Create the position and orientation as per a camera, using the same convention as gluLookAt.
static Vec3f transform3x3 (const Vec3f &v, const Matrixf &m)
apply a 3x3 transform of v*M[0..2,0..2].
static Vec3d transform3x3 (const Vec3d &v, const Matrixf &m)
apply a 3x3 transform of v*M[0..2,0..2].
static Vec3f transform3x3 (const Matrixf &m, const Vec3f &v)
apply a 3x3 transform of M[0..2,0..2]*v.
static Vec3d transform3x3 (const Matrixf &m, const Vec3d &v)
apply a 3x3 transform of M[0..2,0..2]*v.
Protected Attributes
value_type _mat [4][4]
Member Typedef Documentation
typedef float osg::Matrixf::value_type
Constructor & Destructor Documentation
osg::Matrixf::Matrixf () [inline]
Referenced by rotate().
osg::Matrixf::Matrixf (const Matrixf & mat) [inline]
References ptr().
osg::Matrixf::Matrixf (const Matrixd & mat)
osg::Matrixf::Matrixf (float const *const ptr) [inline, explicit]
osg::Matrixf::Matrixf (double const *const ptr) [inline, explicit]
osg::Matrixf::Matrixf (const Quat & quat) [inline, explicit]
osg::Matrixf::Matrixf (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
osg::Matrixf::~Matrixf () [inline]
Member Function Documentation
int osg::Matrixf::compare (const Matrixf & m) const
void osg::Matrixf::decompose (osg::Vec3f & translation, osg::Quat & rotation, osg::Vec3f & scale, osg::Quat & so) const
decompose the matrix into translation, rotation, scale and scale orientation.
void osg::Matrixf::decompose (osg::Vec3d & translation, osg::Quat & rotation, osg::Vec3d & scale, osg::Quat & so) const
decompose the matrix into translation, rotation, scale and scale orientation.
Matrixf osg::Matrixf::frustum (double left, double right, double bottom, double top, double zNear, double zFar) [inline, static]
Create a perspective projection.
See glFrustum for further details.
References makeFrustum().
bool osg::Matrixf::getFrustum (double & left, double & right, double & bottom, double & top, double & zNear, double & zFar) const
Get the frustum settings of a perspective projection matrix.
Note, if matrix is not a perspective matrix then invalid values will be returned.
void osg::Matrixf::getLookAt (Vec3f & eye, Vec3f & center, Vec3f & up, value_type lookDistance = 1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
void osg::Matrixf::getLookAt (Vec3d & eye, Vec3d & center, Vec3d & up, value_type lookDistance = 1.0f) const
Get to the position and orientation of a modelview matrix, using the same convention as gluLookAt.
bool osg::Matrixf::getOrtho (double & left, double & right, double & bottom, double & top, double & zNear, double & zFar) const
Get the orthographic settings of the orthographic projection matrix.
Note, if matrix is not an orthographic matrix then invalid values will be returned.
bool osg::Matrixf::getPerspective (double & fovy, double & aspectRatio, double & zNear, double & zFar) const
Get the frustum settings of a symmetric perspective projection matrix.
Return false if matrix is not a perspective matrix, where parameter values are undefined. Note, if matrix is not a symmetric perspective matrix then the shear will be lost. Asymmetric matrices occur when stereo, power walls, caves and reality center display are used. In these configuration one should use the AsFrustum method instead.
Quat osg::Matrixf::getRotate () const
Get the matrix rotation as a Quat.
Note that this function assumes a non-scaled matrix and will return incorrect results for scaled matrixces. Consider decompose() instead.
Vec3d osg::Matrixf::getScale () const [inline]
References osg::Vec3d::length().
Vec3d osg::Matrixf::getTrans () const [inline]
Matrixf osg::Matrixf::identity (void) [inline, static]
References makeIdentity().
Matrixf osg::Matrixf::inverse (const Matrixf & matrix) [inline, static]
References invert().
bool osg::Matrixf::invert (const Matrixf & rhs) [inline]
invert the matrix rhs, automatically select invert_4x3 or invert_4x4.
References _mat.
Referenced by inverse().
bool osg::Matrixf::invert_4x3 (const Matrixf & rhs)
4x3 matrix invert, not right hand column is assumed to be 0,0,0,1.
bool osg::Matrixf::invert_4x4 (const Matrixf & rhs)
full 4x4 matrix invert.
bool osg::Matrixf::isIdentity () const [inline]
bool osg::Matrixf::isNaN () const [inline]
References osg::isNaN().
Matrixf osg::Matrixf::lookAt (const Vec3f & eye, const Vec3f & center, const Vec3f & up) [inline, static]
Create the position and orientation as per a camera, using the same convention as gluLookAt.
References makeLookAt().
Matrixf osg::Matrixf::lookAt (const Vec3d & eye, const Vec3d & center, const Vec3d & up) [inline, static]
Create the position and orientation as per a camera, using the same convention as gluLookAt.
References makeLookAt().
void osg::Matrixf::makeFrustum (double left, double right, double bottom, double top, double zNear, double zFar)
Set to a perspective projection.
See glFrustum for further details.
Referenced by frustum().
void osg::Matrixf::makeIdentity ()
Referenced by identity().
void osg::Matrixf::makeLookAt (const Vec3d & eye, const Vec3d & center, const Vec3d & up)
Set the position and orientation to be a view matrix, using the same convention as gluLookAt.
Referenced by lookAt().
void osg::Matrixf::makeOrtho (double left, double right, double bottom, double top, double zNear, double zFar)
Set to an orthographic projection.
See glOrtho for further details.
Referenced by ortho().
void osg::Matrixf::makeOrtho2D (double left, double right, double bottom, double top) [inline]
Set to a 2D orthographic projection.
See glOrtho2D for further details.
Referenced by ortho2D().
void osg::Matrixf::makePerspective (double fovy, double aspectRatio, double zNear, double zFar)
Set to a symmetrical perspective projection.
See gluPerspective for further details. Aspect ratio is defined as width/height.
Referenced by perspective().
void osg::Matrixf::makeRotate (value_type angle1, const Vec3d & axis1, value_type angle2, const Vec3d & axis2, value_type angle3, const Vec3d & axis3)
void osg::Matrixf::makeRotate (value_type angle1, const Vec3f & axis1, value_type angle2, const Vec3f & axis2, value_type angle3, const Vec3f & axis3)
void osg::Matrixf::makeRotate (const Vec3f & from, const Vec3f & to)
Referenced by osg::AnimationPath::ControlPoint::getInverse(), osg::AnimationPath::ControlPoint::getMatrix(), and rotate().
void osg::Matrixf::makeRotate (const Vec3d & from, const Vec3d & to)
void osg::Matrixf::makeRotate (value_type angle, const Vec3f & axis)
void osg::Matrixf::makeRotate (value_type angle, const Vec3d & axis)
void osg::Matrixf::makeRotate (value_type angle, value_type x, value_type y, value_type z)
void osg::Matrixf::makeRotate (const Quat &)
void osg::Matrixf::makeScale (const Vec3f &)
Referenced by scale().
void osg::Matrixf::makeScale (const Vec3d &)
void osg::Matrixf::makeScale (value_type , value_type , value_type)
void osg::Matrixf::makeTranslate (const Vec3f &)
Referenced by translate().
void osg::Matrixf::makeTranslate (const Vec3d &)
void osg::Matrixf::makeTranslate (value_type , value_type , value_type)
void osg::Matrixf::mult (const Matrixf & , const Matrixf &)
Referenced by operator*().
bool osg::Matrixf::operator!= (const Matrixf & m) const [inline]
value_type& osg::Matrixf::operator() (int row, int col) [inline]
value_type osg::Matrixf::operator() (int row, int col) const [inline]
Vec3f osg::Matrixf::operator* (const Vec3f & v) const [inline]
References postMult().
Vec3d osg::Matrixf::operator* (const Vec3d & v) const [inline]
References postMult().
Vec4f osg::Matrixf::operator* (const Vec4f & v) const [inline]
References postMult().
Vec4d osg::Matrixf::operator* (const Vec4d & v) const [inline]
References postMult().
Matrixf osg::Matrixf::operator* (const Matrixf & m) const [inline]
References mult().
void osg::Matrixf::operator*= (const Matrixf & other) [inline]
bool osg::Matrixf::operator< (const Matrixf & m) const [inline]
Matrixf& osg::Matrixf::operator= (const Matrixf & rhs) [inline]
References ptr().
Matrixf& osg::Matrixf::operator= (const Matrixd & other)
bool osg::Matrixf::operator== (const Matrixf & m) const [inline]
Matrixf osg::Matrixf::ortho (double left, double right, double bottom, double top, double zNear, double zFar) [inline, static]
Create an orthographic projection matrix.
See glOrtho for further details.
References makeOrtho().
Matrixf osg::Matrixf::ortho2D (double left, double right, double bottom, double top) [inline, static]
Create a 2D orthographic projection.
See glOrtho for further details.
References makeOrtho2D().
Matrixf osg::Matrixf::orthoNormal (const Matrixf & matrix) [inline, static]
References orthoNormalize().
void osg::Matrixf::orthoNormalize (const Matrixf & rhs)
ortho-normalize the 3x3 rotation & scale matrix
Referenced by orthoNormal().
Matrixf osg::Matrixf::perspective (double fovy, double aspectRatio, double zNear, double zFar) [inline, static]
Create a symmetrical perspective projection.
See gluPerspective for further details. Aspect ratio is defined as width/height.
References makePerspective().
Vec3f osg::Matrixf::postMult (const Vec3f & v) const [inline]
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by operator*(), and postMultRotate().
Vec3d osg::Matrixf::postMult (const Vec3d & v) const [inline]
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Vec4d osg::Matrixf::postMult (const Vec4d & v) const [inline]
References _mat, osg::Vec4d::w(), osg::Vec4d::x(), osg::Vec4d::y(), and osg::Vec4d::z().
void osg::Matrixf::postMult (const Matrixf &)
Vec4f osg::Matrixf::postMult (const Vec4f & v) const [inline]
References _mat, osg::Vec4f::w(), osg::Vec4f::x(), osg::Vec4f::y(), and osg::Vec4f::z().
void osg::Matrixf::postMultRotate (const Quat & q) [inline]
Optimized version of postMult(rotate(q));.
References postMult(), setRotate(), and osg::Quat::zeroRotation().
void osg::Matrixf::postMultScale (const Vec3d & v) [inline]
Optimized version of postMult(scale(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getInverse().
void osg::Matrixf::postMultScale (const Vec3f & v) [inline]
References _mat.
void osg::Matrixf::postMultTranslate (const Vec3d & v) [inline]
Optimized version of postMult(translate(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getMatrix().
void osg::Matrixf::postMultTranslate (const Vec3f & v) [inline]
References _mat.
Vec3f osg::Matrixf::preMult (const Vec3f & v) const [inline]
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by osg::operator*(), and preMultRotate().
void osg::Matrixf::preMult (const Matrixf &)
Vec3d osg::Matrixf::preMult (const Vec3d & v) const [inline]
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Vec4f osg::Matrixf::preMult (const Vec4f & v) const [inline]
References _mat, osg::Vec4f::w(), osg::Vec4f::x(), osg::Vec4f::y(), and osg::Vec4f::z().
Vec4d osg::Matrixf::preMult (const Vec4d & v) const [inline]
References _mat, osg::Vec4d::w(), osg::Vec4d::x(), osg::Vec4d::y(), and osg::Vec4d::z().
void osg::Matrixf::preMultRotate (const Quat & q) [inline]
Optimized version of preMult(rotate(q));.
References preMult(), setRotate(), and osg::Quat::zeroRotation().
void osg::Matrixf::preMultScale (const Vec3f & v) [inline]
References _mat.
void osg::Matrixf::preMultScale (const Vec3d & v) [inline]
Optimized version of preMult(scale(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getMatrix().
void osg::Matrixf::preMultTranslate (const Vec3f & v) [inline]
References _mat.
void osg::Matrixf::preMultTranslate (const Vec3d & v) [inline]
Optimized version of preMult(translate(v));.
References _mat.
Referenced by osg::AnimationPath::ControlPoint::getInverse().
value_type* osg::Matrixf::ptr () [inline]
Referenced by Matrixf(), and operator=().
const value_type* osg::Matrixf::ptr () const [inline]
Matrixf osg::Matrixf::rotate (value_type angle1, const Vec3d & axis1, value_type angle2, const Vec3d & axis2, value_type angle3, const Vec3d & axis3) [inline, static]
References makeRotate().
Matrixf osg::Matrixf::rotate (value_type angle, value_type x, value_type y, value_type z) [inline, static]
References makeRotate().
Matrixf osg::Matrixf::rotate (const Quat & quat) [inline, static]
References Matrixf().
Matrixf osg::Matrixf::rotate (value_type angle, const Vec3d & axis) [inline, static]
References makeRotate().
Matrixf osg::Matrixf::rotate (value_type angle1, const Vec3f & axis1, value_type angle2, const Vec3f & axis2, value_type angle3, const Vec3f & axis3) [inline, static]
References makeRotate().
Matrixf osg::Matrixf::rotate (const Vec3f & from, const Vec3f & to) [inline, static]
References makeRotate().
Matrixf osg::Matrixf::rotate (const Vec3d & from, const Vec3d & to) [inline, static]
References makeRotate().
Matrixf osg::Matrixf::rotate (value_type angle, const Vec3f & axis) [inline, static]
References makeRotate().
Matrixf osg::Matrixf::scale (const Vec3d & sv) [inline, static]
References scale(), osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Matrixf osg::Matrixf::scale (value_type sx, value_type sy, value_type sz) [inline, static]
References makeScale().
Matrixf osg::Matrixf::scale (const Vec3f & sv) [inline, static]
References osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by scale().
void osg::Matrixf::set (float const *const ptr) [inline]
void osg::Matrixf::set (double const *const ptr) [inline]
void osg::Matrixf::set (value_type a00, value_type a01, value_type a02, value_type a03, value_type a10, value_type a11, value_type a12, value_type a13, value_type a20, value_type a21, value_type a22, value_type a23, value_type a30, value_type a31, value_type a32, value_type a33)
void osg::Matrixf::set (const Matrixd & rhs)
void osg::Matrixf::set (const Matrixf & rhs) [inline]
void osg::Matrixf::setRotate (const Quat & q)
Referenced by postMultRotate(), and preMultRotate().
void osg::Matrixf::setTrans (value_type tx, value_type ty, value_type tz)
void osg::Matrixf::setTrans (const Vec3d & v)
void osg::Matrixf::setTrans (const Vec3f & v)
Vec3f osg::Matrixf::transform3x3 (const Vec3f & v, const Matrixf & m) [inline, static]
apply a 3x3 transform of v*M[0..2,0..2].
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Vec3f osg::Matrixf::transform3x3 (const Matrixf & m, const Vec3f & v) [inline, static]
apply a 3x3 transform of M[0..2,0..2]*v.
References _mat, osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Vec3d osg::Matrixf::transform3x3 (const Matrixf & m, const Vec3d & v) [inline, static]
apply a 3x3 transform of M[0..2,0..2]*v.
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Vec3d osg::Matrixf::transform3x3 (const Vec3d & v, const Matrixf & m) [inline, static]
apply a 3x3 transform of v*M[0..2,0..2].
References _mat, osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Matrixf osg::Matrixf::translate (const Vec3d & dv) [inline, static]
References translate(), osg::Vec3d::x(), osg::Vec3d::y(), and osg::Vec3d::z().
Matrixf osg::Matrixf::translate (const Vec3f & dv) [inline, static]
References osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by translate().
Matrixf osg::Matrixf::translate (value_type x, value_type y, value_type z) [inline, static]
References makeTranslate().
bool osg::Matrixf::valid () const [inline]
References osg::isNaN().
Member Data Documentation
value_type osg::Matrixf::_mat[4][4] [protected]
Referenced by invert(), postMult(), postMultScale(), postMultTranslate(), preMult(), preMultScale(), preMultTranslate(), and transform3x3().
The documentation for this class was generated from the following file:
osg/Matrixf
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.