OpenSceneGraph: osg::StateAttribute::ModeUsage Struct Reference
osg::StateAttribute::ModeUsage Struct Reference
Public Member Functions
virtual ~ModeUsage ()
virtual void usesMode (GLMode mode)=0
virtual void usesTextureMode (GLMode mode)=0
Constructor & Destructor Documentation
virtual osg::StateAttribute::ModeUsage::~ModeUsage () [inline, virtual]
Member Function Documentation
virtual void osg::StateAttribute::ModeUsage::usesMode (GLMode mode) [pure virtual]
Referenced by osg::VertexProgram::getModeUsage(), osg::StencilTwoSided::getModeUsage(), osg::Stencil::getModeUsage(), osg::Scissor::getModeUsage(), osg::PolygonStipple::getModeUsage(), osg::PolygonOffset::getModeUsage(), osg::PointSprite::getModeUsage(), osg::Point::getModeUsage(), osg::LogicOp::getModeUsage(), osg::LineStipple::getModeUsage(), osg::Light::getModeUsage(), osg::FragmentProgram::getModeUsage(), osg::Fog::getModeUsage(), osg::Depth::getModeUsage(), osg::CullFace::getModeUsage(), osg::ClipPlane::getModeUsage(), osg::BlendFunc::getModeUsage(), osg::BlendEquation::getModeUsage(), osg::BlendColor::getModeUsage(), and osg::AlphaFunc::getModeUsage().
virtual void osg::StateAttribute::ModeUsage::usesTextureMode (GLMode mode) [pure virtual]
Referenced by osg::Texture::getModeUsage(), and osg::TexGen::getModeUsage().
The documentation for this struct was generated from the following file:
osg/StateAttribute
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.