OpenSceneGraph: osgUtil::Optimizer Class Reference
osgUtil::Optimizer Class Reference
Traverses scene graph to improve efficiency.
Classes
class CheckGeometryVisitor
class CombineLODsVisitor
Optimize the LOD groups, by combining adjacent LOD's which have complementary ranges.
class CombineStaticTransformsVisitor
Combine Static Transform nodes that sit above one another.
class CopySharedSubgraphsVisitor
Copy any shared subgraphs, enabling flattening of static transforms.
class FlattenBillboardVisitor
Flatten MatrixTransform/Billboard pairs.
class FlattenStaticTransformsDuplicatingSharedSubgraphsVisitor
FlattenStaticTransformsDuplicatingSharedSubgraphsVisitor is similar to to FlattenStaticTransformsVisitor in that is desgined to remove static transforms from the scene graph, pushing down the transforms to the geometry leaves of the scene graph, but with the difference that any subgraphs that are shared between different transforms of duplicated and flatten individually.
class FlattenStaticTransformsVisitor
Flatten Static Transform nodes by applying their transform to the geometry on the leaves of the scene graph, then removing the now redundant transforms.
struct IsOperationPermissibleForObjectCallback
Callback for customizing what operations are permitted on objects in the scene graph.
class MergeGeodesVisitor
Combine geodes.
class MergeGeometryVisitor
class RemoveEmptyNodesVisitor
Remove rendundant nodes, such as groups with one single child.
class RemoveLoadedProxyNodesVisitor
Remove loaded proxy nodes.
class RemoveRedundantNodesVisitor
Remove redundant nodes, such as groups with one single child.
class SpatializeGroupsVisitor
Spatialize scene into a balanced quad/oct tree.
class StateVisitor
Optimize State in the scene graph by removing duplicate state, replacing it with shared instances, both for StateAttributes, and whole StateSets.
class StaticObjectDetectionVisitor
Optimize the setting of StateSet and Geometry objects in scene so that they have a STATIC DataVariance when they don't have any callbacks associated with them.
class TessellateVisitor
Tessellate all geodes, to remove POLYGONS.
class TextureAtlasBuilder
Texture Atlas Builder creates a set of textures/images which each contain multiple images.
class TextureAtlasVisitor
Optimize texture usage in the scene graph by combining textures into texture atlas Use of texture atlas cuts down on the number of seperate states in the scene, reducing state changes and improving the chances of use larger batches of geomertry.
class TextureVisitor
For all textures apply settings.
Public Types
enum OptimizationOptions {
FLATTEN_STATIC_TRANSFORMS = (1 << 0), REMOVE_REDUNDANT_NODES = (1 << 1), REMOVE_LOADED_PROXY_NODES = (1 << 2), COMBINE_ADJACENT_LODS = (1 << 3),
SHARE_DUPLICATE_STATE = (1 << 4), MERGE_GEOMETRY = (1 << 5), CHECK_GEOMETRY = (1 << 6), SPATIALIZE_GROUPS = (1 << 7),
COPY_SHARED_NODES = (1 << 8), TRISTRIP_GEOMETRY = (1 << 9), TESSELLATE_GEOMETRY = (1 << 10), OPTIMIZE_TEXTURE_SETTINGS = (1 << 11),
MERGE_GEODES = (1 << 12), FLATTEN_BILLBOARDS = (1 << 13), TEXTURE_ATLAS_BUILDER = (1 << 14), STATIC_OBJECT_DETECTION = (1 << 15),
FLATTEN_STATIC_TRANSFORMS_DUPLICATING_SHARED_SUBGRAPHS = (1 << 16), DEFAULT_OPTIMIZATIONS, ALL_OPTIMIZATIONS
}
Public Member Functions
Optimizer ()
virtual ~Optimizer ()
void reset ()
Reset internal data to initial state - the getPermissibleOptionsMap is cleared.
void optimize (osg::Node *node)
Traverse the node and its subgraph with a series of optimization visitors, specified by the OptimizationOptions.
virtual void optimize (osg::Node *node, unsigned int options)
Traverse the node and its subgraph with a series of optimization visitors, specified by the OptimizationOptions.
void setIsOperationPermissibleForObjectCallback (IsOperationPermissibleForObjectCallback *callback)
Set the callback for customizing what operations are permitted on objects in the scene graph.
IsOperationPermissibleForObjectCallback * getIsOperationPermissibleForObjectCallback ()
Get the callback for customizing what operations are permitted on objects in the scene graph.
const
IsOperationPermissibleForObjectCallback * getIsOperationPermissibleForObjectCallback () const
Get the callback for customizing what operations are permitted on objects in the scene graph.
void setPermissibleOptimizationsForObject (const osg::Object *object, unsigned int options)
unsigned int getPermissibleOptimizationsForObject (const osg::Object *object) const
bool isOperationPermissibleForObject (const osg::StateSet *object, unsigned int option) const
bool isOperationPermissibleForObject (const osg::StateAttribute *object, unsigned int option) const
bool isOperationPermissibleForObject (const osg::Drawable *object, unsigned int option) const
bool isOperationPermissibleForObject (const osg::Node *object, unsigned int option) const
bool isOperationPermissibleForObjectImplementation (const osg::StateSet *stateset, unsigned int option) const
bool isOperationPermissibleForObjectImplementation (const osg::StateAttribute *attribute, unsigned int option) const
bool isOperationPermissibleForObjectImplementation (const osg::Drawable *drawable, unsigned int option) const
bool isOperationPermissibleForObjectImplementation (const osg::Node *node, unsigned int option) const
Protected Types
typedef std::map< const
osg::Object *, unsigned int > PermissibleOptimizationsMap
Protected Attributes
osg::ref_ptr
< IsOperationPermissibleForObjectCallback > _isOperationPermissibleForObjectCallback
PermissibleOptimizationsMap _permissibleOptimizationsMap
Detailed Description
Traverses scene graph to improve efficiency.
See OptimizationOptions. For example of usage see examples/osgimpostor or osgviewer.
Member Typedef Documentation
typedef std::map<const osg::Object*,unsigned int> osgUtil::Optimizer::PermissibleOptimizationsMap [protected]
Member Enumeration Documentation
enum osgUtil::Optimizer::OptimizationOptions
Enumerator:
FLATTEN_STATIC_TRANSFORMS
REMOVE_REDUNDANT_NODES
REMOVE_LOADED_PROXY_NODES
COMBINE_ADJACENT_LODS
SHARE_DUPLICATE_STATE
MERGE_GEOMETRY
CHECK_GEOMETRY
SPATIALIZE_GROUPS
COPY_SHARED_NODES
TRISTRIP_GEOMETRY
TESSELLATE_GEOMETRY
OPTIMIZE_TEXTURE_SETTINGS
MERGE_GEODES
FLATTEN_BILLBOARDS
TEXTURE_ATLAS_BUILDER
STATIC_OBJECT_DETECTION
FLATTEN_STATIC_TRANSFORMS_DUPLICATING_SHARED_SUBGRAPHS
DEFAULT_OPTIMIZATIONS
ALL_OPTIMIZATIONS
Constructor & Destructor Documentation
osgUtil::Optimizer::Optimizer () [inline]
virtual osgUtil::Optimizer::~Optimizer () [inline, virtual]
Member Function Documentation
IsOperationPermissibleForObjectCallback* osgUtil::Optimizer::getIsOperationPermissibleForObjectCallback () [inline]
Get the callback for customizing what operations are permitted on objects in the scene graph.
const IsOperationPermissibleForObjectCallback* osgUtil::Optimizer::getIsOperationPermissibleForObjectCallback () const [inline]
Get the callback for customizing what operations are permitted on objects in the scene graph.
unsigned int osgUtil::Optimizer::getPermissibleOptimizationsForObject (const osg::Object * object) const [inline]
bool osgUtil::Optimizer::isOperationPermissibleForObject (const osg::StateSet * object, unsigned int option) const [inline]
References osgUtil::Optimizer::IsOperationPermissibleForObjectCallback::isOperationPermissibleForObjectImplementation().
Referenced by osgUtil::BaseOptimizerVisitor::isOperationPermissibleForObject().
bool osgUtil::Optimizer::isOperationPermissibleForObject (const osg::StateAttribute * object, unsigned int option) const [inline]
bool osgUtil::Optimizer::isOperationPermissibleForObject (const osg::Drawable * object, unsigned int option) const [inline]
bool osgUtil::Optimizer::isOperationPermissibleForObject (const osg::Node * object, unsigned int option) const [inline]
bool osgUtil::Optimizer::isOperationPermissibleForObjectImplementation (const osg::Drawable * drawable, unsigned int option) const [inline]
References osg::Drawable::getCullCallback(), osg::Drawable::getEventCallback(), osg::Drawable::getUpdateCallback(), and osg::Object::getUserData().
bool osgUtil::Optimizer::isOperationPermissibleForObjectImplementation (const osg::Node * node, unsigned int option) const [inline]
References osg::Node::getCullCallback(), osg::Node::getEventCallback(), osg::Node::getNodeMask(), osg::Node::getNumDescriptions(), osg::Node::getStateSet(), osg::Node::getUpdateCallback(), and osg::Object::getUserData().
bool osgUtil::Optimizer::isOperationPermissibleForObjectImplementation (const osg::StateSet * stateset, unsigned int option) const [inline]
Referenced by osgUtil::Optimizer::IsOperationPermissibleForObjectCallback::isOperationPermissibleForObjectImplementation().
bool osgUtil::Optimizer::isOperationPermissibleForObjectImplementation (const osg::StateAttribute * attribute, unsigned int option) const [inline]
void osgUtil::Optimizer::optimize (osg::Node * node)
Traverse the node and its subgraph with a series of optimization visitors, specified by the OptimizationOptions.
virtual void osgUtil::Optimizer::optimize (osg::Node * node, unsigned int options) [virtual]
Traverse the node and its subgraph with a series of optimization visitors, specified by the OptimizationOptions.
void osgUtil::Optimizer::reset ()
Reset internal data to initial state - the getPermissibleOptionsMap is cleared.
void osgUtil::Optimizer::setIsOperationPermissibleForObjectCallback (IsOperationPermissibleForObjectCallback * callback) [inline]
Set the callback for customizing what operations are permitted on objects in the scene graph.
void osgUtil::Optimizer::setPermissibleOptimizationsForObject (const osg::Object * object, unsigned int options) [inline]
Member Data Documentation
osg::ref_ptr<IsOperationPermissibleForObjectCallback> osgUtil::Optimizer::_isOperationPermissibleForObjectCallback [protected]
PermissibleOptimizationsMap osgUtil::Optimizer::_permissibleOptimizationsMap [protected]
The documentation for this class was generated from the following file:
osgUtil/Optimizer
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.