OpenSceneGraph: osgParticle::PointPlacer Class Reference
osgParticle::PointPlacer Class Reference
A point-shaped particle placer.
Public Member Functions
PointPlacer ()
PointPlacer (const PointPlacer &copy, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgParticle, PointPlacer)
void place (Particle *P) const
Place a particle.
osg::Vec3 getControlPosition () const
return the control position
Protected Member Functions
virtual ~PointPlacer ()
PointPlacer & operator= (const PointPlacer &)
Detailed Description
A point-shaped particle placer.
This placer class uses the center point defined in its base class CenteredPlacer to place there all incoming particles.
Constructor & Destructor Documentation
osgParticle::PointPlacer::PointPlacer () [inline]
osgParticle::PointPlacer::PointPlacer (const PointPlacer & copy, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY) [inline]
virtual osgParticle::PointPlacer::~PointPlacer () [inline, protected, virtual]
Member Function Documentation
osg::Vec3 osgParticle::PointPlacer::getControlPosition () const [inline, virtual]
return the control position
Implements osgParticle::Placer.
References osgParticle::CenteredPlacer::getCenter().
osgParticle::PointPlacer::META_Object (osgParticle , PointPlacer)
PointPlacer& osgParticle::PointPlacer::operator= (const PointPlacer &) [inline, protected]
void osgParticle::PointPlacer::place (Particle * P) const [inline, virtual]
Place a particle.
This method is called automatically by ModularEmitter and should not be called manually.
Implements osgParticle::Placer.
References osgParticle::CenteredPlacer::getCenter(), and osgParticle::Particle::setPosition().
The documentation for this class was generated from the following file:
osgParticle/PointPlacer
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.