OpenSceneGraph: osgDB::RegisterDotOsgWrapperProxy Class Reference
osgDB::RegisterDotOsgWrapperProxy Class Reference
Proxy class for automatic registration of DotOsgWrappers with the Registry.
Public Member Functions
RegisterDotOsgWrapperProxy (osg::Object *proto, const std::string &name, const std::string &associates, DotOsgWrapper::ReadFunc readFunc, DotOsgWrapper::WriteFunc writeFunc, DotOsgWrapper::ReadWriteMode readWriteMode=DotOsgWrapper::READ_AND_WRITE)
~RegisterDotOsgWrapperProxy ()
Protected Attributes
osg::ref_ptr< DotOsgWrapper > _wrapper
Detailed Description
Proxy class for automatic registration of DotOsgWrappers with the Registry.
Constructor & Destructor Documentation
osgDB::RegisterDotOsgWrapperProxy::RegisterDotOsgWrapperProxy (osg::Object * proto, const std::string & name, const std::string & associates, DotOsgWrapper::ReadFunc readFunc, DotOsgWrapper::WriteFunc writeFunc, DotOsgWrapper::ReadWriteMode readWriteMode = DotOsgWrapper::READ_AND_WRITE) [inline]
References _wrapper, osgDB::Registry::addDotOsgWrapper(), osg::ref_ptr< T >::get(), and osgDB::Registry::instance().
osgDB::RegisterDotOsgWrapperProxy::~RegisterDotOsgWrapperProxy () [inline]
References _wrapper, osg::ref_ptr< T >::get(), osgDB::Registry::instance(), and osgDB::Registry::removeDotOsgWrapper().
Member Data Documentation
osg::ref_ptr<DotOsgWrapper> osgDB::RegisterDotOsgWrapperProxy::_wrapper [protected]
Referenced by RegisterDotOsgWrapperProxy(), and ~RegisterDotOsgWrapperProxy().
The documentation for this class was generated from the following file:
osgDB/Registry
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.