OpenSceneGraph: osgManipulator::Selection Class Reference
osgManipulator::Selection Class Reference
Selection listens to motion commands generated by draggers.
Public Member Functions
Selection ()
virtual bool receive (const MotionCommand &)
Receive motion commands and set the MatrixTransform accordingly to transform selections.
virtual bool receive (const TranslateInLineCommand &command)
virtual bool receive (const TranslateInPlaneCommand &command)
virtual bool receive (const Scale1DCommand &command)
virtual bool receive (const Scale2DCommand &command)
virtual bool receive (const ScaleUniformCommand &command)
virtual bool receive (const Rotate3DCommand &command)
Protected Member Functions
virtual ~Selection ()
Protected Attributes
osg::Matrix _startMotionMatrix
osg::Matrix _localToWorld
osg::Matrix _worldToLocal
Detailed Description
Selection listens to motion commands generated by draggers.
Constructor & Destructor Documentation
osgManipulator::Selection::Selection ()
virtual osgManipulator::Selection::~Selection () [protected, virtual]
Member Function Documentation
virtual bool osgManipulator::Selection::receive (const MotionCommand &) [virtual]
Receive motion commands and set the MatrixTransform accordingly to transform selections.
Returns true on success.
virtual bool osgManipulator::Selection::receive (const Rotate3DCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::Selection::receive (const ScaleUniformCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::Selection::receive (const Scale2DCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::Selection::receive (const Scale1DCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::Selection::receive (const TranslateInPlaneCommand & command) [inline, virtual]
References receive().
Referenced by receive().
virtual bool osgManipulator::Selection::receive (const TranslateInLineCommand & command) [inline, virtual]
References receive().
Referenced by receive().
Member Data Documentation
osg::Matrix osgManipulator::Selection::_localToWorld [protected]
osg::Matrix osgManipulator::Selection::_startMotionMatrix [protected]
osg::Matrix osgManipulator::Selection::_worldToLocal [protected]
The documentation for this class was generated from the following file:
osgManipulator/Selection
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.