OpenSceneGraph: osg::RefMatrixf Class Reference
osg::RefMatrixf Class Reference
Public Member Functions
RefMatrixf ()
RefMatrixf (const Matrixf &other)
RefMatrixf (const Matrixd &other)
RefMatrixf (const RefMatrixf &other)
RefMatrixf (Matrixf::value_type const *const def)
RefMatrixf (Matrixf::value_type a00, Matrixf::value_type a01, Matrixf::value_type a02, Matrixf::value_type a03, Matrixf::value_type a10, Matrixf::value_type a11, Matrixf::value_type a12, Matrixf::value_type a13, Matrixf::value_type a20, Matrixf::value_type a21, Matrixf::value_type a22, Matrixf::value_type a23, Matrixf::value_type a30, Matrixf::value_type a31, Matrixf::value_type a32, Matrixf::value_type a33)
virtual Object * cloneType () const
virtual Object * clone (const CopyOp &) const
virtual bool isSameKindAs (const Object *obj) const
virtual const char * libraryName () const
virtual const char * className () const
Protected Member Functions
virtual ~RefMatrixf ()
Constructor & Destructor Documentation
osg::RefMatrixf::RefMatrixf () [inline]
Referenced by clone(), and cloneType().
osg::RefMatrixf::RefMatrixf (const Matrixf & other) [inline]
osg::RefMatrixf::RefMatrixf (const Matrixd & other) [inline]
osg::RefMatrixf::RefMatrixf (const RefMatrixf & other) [inline]
osg::RefMatrixf::RefMatrixf (Matrixf::value_type const *const def) [inline, explicit]
osg::RefMatrixf::RefMatrixf (Matrixf::value_type a00, Matrixf::value_type a01, Matrixf::value_type a02, Matrixf::value_type a03, Matrixf::value_type a10, Matrixf::value_type a11, Matrixf::value_type a12, Matrixf::value_type a13, Matrixf::value_type a20, Matrixf::value_type a21, Matrixf::value_type a22, Matrixf::value_type a23, Matrixf::value_type a30, Matrixf::value_type a31, Matrixf::value_type a32, Matrixf::value_type a33) [inline]
virtual osg::RefMatrixf::~RefMatrixf () [inline, protected, virtual]
Member Function Documentation
virtual const char* osg::RefMatrixf::className () const [inline, virtual]
virtual Object* osg::RefMatrixf::clone (const CopyOp &) const [inline, virtual]
References RefMatrixf().
virtual Object* osg::RefMatrixf::cloneType () const [inline, virtual]
References RefMatrixf().
virtual bool osg::RefMatrixf::isSameKindAs (const Object * obj) const [inline, virtual]
References NULL.
virtual const char* osg::RefMatrixf::libraryName () const [inline, virtual]
The documentation for this class was generated from the following file:
osg/Matrixf
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.