OpenSceneGraph: osgAnimation::RigGeometry Class Reference
osgAnimation::RigGeometry Class Reference
Classes
struct FindNearestParentSkeleton
struct UpdateVertex
Public Member Functions
RigGeometry ()
RigGeometry (const RigGeometry &b, const osg::CopyOp &copyop=osg::CopyOp::SHALLOW_COPY)
META_Object (osgAnimation, RigGeometry)
void setInfluenceMap (VertexInfluenceMap *vertexInfluenceMap)
const VertexInfluenceMap * getInfluenceMap () const
VertexInfluenceMap * getInfluenceMap ()
const Skeleton * getSkeleton () const
Skeleton * getSkeleton ()
void setSkeleton (Skeleton *)
void setNeedToComputeMatrix (bool state)
bool getNeedToComputeMatrix () const
void buildVertexInfluenceSet ()
const VertexInfluenceSet & getVertexInfluenceSet () const
void computeMatrixFromRootSkeleton ()
void setRigTransformImplementation (RigTransform *)
RigTransform * getRigTransformImplementation ()
virtual void drawImplementation (osg::RenderInfo &renderInfo) const
Draw Geometry directly ignoring an OpenGL display list which could be attached.
void update ()
const osg::Matrix & getMatrixFromSkeletonToGeometry () const
const osg::Matrix & getInvMatrixFromSkeletonToGeometry () const
osg::Geometry * getSourceGeometry ()
const osg::Geometry * getSourceGeometry () const
void setSourceGeometry (osg::Geometry *geometry)
void copyFrom (osg::Geometry &from)
Protected Attributes
osg::ref_ptr< osg::Geometry > _geometry
osg::ref_ptr< RigTransform > _rigTransformImplementation
VertexInfluenceSet _vertexInfluenceSet
osg::ref_ptr< VertexInfluenceMap > _vertexInfluenceMap
osg::Matrix _matrixFromSkeletonToGeometry
osg::Matrix _invMatrixFromSkeletonToGeometry
osg::observer_ptr< Skeleton > _root
bool _needToComputeMatrix
Constructor & Destructor Documentation
osgAnimation::RigGeometry::RigGeometry ()
osgAnimation::RigGeometry::RigGeometry (const RigGeometry & b, const osg::CopyOp & copyop = osg::CopyOp::SHALLOW_COPY)
Member Function Documentation
void osgAnimation::RigGeometry::buildVertexInfluenceSet ()
Referenced by osgAnimation::RigGeometry::UpdateVertex::update().
void osgAnimation::RigGeometry::computeMatrixFromRootSkeleton ()
Referenced by osgAnimation::RigGeometry::UpdateVertex::update().
void osgAnimation::RigGeometry::copyFrom (osg::Geometry & from)
virtual void osgAnimation::RigGeometry::drawImplementation (osg::RenderInfo & renderInfo) const [virtual]
Draw Geometry directly ignoring an OpenGL display list which could be attached.
This is the internal draw method which does the drawing itself, and is the method to override when deriving from Geometry for user-drawn objects.
Reimplemented from osg::Geometry.
const VertexInfluenceMap* osgAnimation::RigGeometry::getInfluenceMap () const [inline]
VertexInfluenceMap* osgAnimation::RigGeometry::getInfluenceMap () [inline]
const osg::Matrix& osgAnimation::RigGeometry::getInvMatrixFromSkeletonToGeometry () const
const osg::Matrix& osgAnimation::RigGeometry::getMatrixFromSkeletonToGeometry () const
bool osgAnimation::RigGeometry::getNeedToComputeMatrix () const [inline]
Referenced by osgAnimation::RigGeometry::UpdateVertex::update().
RigTransform* osgAnimation::RigGeometry::getRigTransformImplementation ()
const Skeleton* osgAnimation::RigGeometry::getSkeleton () const
Referenced by osgAnimation::RigGeometry::UpdateVertex::update().
Skeleton* osgAnimation::RigGeometry::getSkeleton ()
osg::Geometry* osgAnimation::RigGeometry::getSourceGeometry ()
const osg::Geometry* osgAnimation::RigGeometry::getSourceGeometry () const
const VertexInfluenceSet& osgAnimation::RigGeometry::getVertexInfluenceSet () const
osgAnimation::RigGeometry::META_Object (osgAnimation , RigGeometry)
void osgAnimation::RigGeometry::setInfluenceMap (VertexInfluenceMap * vertexInfluenceMap) [inline]
void osgAnimation::RigGeometry::setNeedToComputeMatrix (bool state) [inline]
void osgAnimation::RigGeometry::setRigTransformImplementation (RigTransform *)
void osgAnimation::RigGeometry::setSkeleton (Skeleton *)
Referenced by osgAnimation::RigGeometry::UpdateVertex::update().
void osgAnimation::RigGeometry::setSourceGeometry (osg::Geometry * geometry)
void osgAnimation::RigGeometry::update ()
Referenced by osgAnimation::RigGeometry::UpdateVertex::update().
Member Data Documentation
osg::ref_ptr<osg::Geometry> osgAnimation::RigGeometry::_geometry [protected]
osg::Matrix osgAnimation::RigGeometry::_invMatrixFromSkeletonToGeometry [protected]
osg::Matrix osgAnimation::RigGeometry::_matrixFromSkeletonToGeometry [protected]
bool osgAnimation::RigGeometry::_needToComputeMatrix [protected]
osg::ref_ptr<RigTransform> osgAnimation::RigGeometry::_rigTransformImplementation [protected]
osg::observer_ptr<Skeleton> osgAnimation::RigGeometry::_root [protected]
osg::ref_ptr<VertexInfluenceMap> osgAnimation::RigGeometry::_vertexInfluenceMap [protected]
VertexInfluenceSet osgAnimation::RigGeometry::_vertexInfluenceSet [protected]
The documentation for this class was generated from the following file:
osgAnimation/RigGeometry
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.