OpenSceneGraph: osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType > Class Template Reference
osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType > Class Template Reference
Public Types
typedef T ElementDataType
Public Member Functions
TemplateIndexArray ()
TemplateIndexArray (const TemplateIndexArray &ta, const CopyOp &copyop=CopyOp::SHALLOW_COPY)
TemplateIndexArray (unsigned int no)
TemplateIndexArray (unsigned int no, T *ptr)
template<class InputIterator >
TemplateIndexArray (InputIterator first, InputIterator last)
TemplateIndexArray & operator= (const TemplateIndexArray &array)
virtual Object * cloneType () const
virtual Object * clone (const CopyOp &copyop) const
virtual void accept (ArrayVisitor &av)
virtual void accept (ConstArrayVisitor &av) const
virtual void accept (unsigned int index, ValueVisitor &vv)
virtual void accept (unsigned int index, ConstValueVisitor &vv) const
virtual int compare (unsigned int lhs, unsigned int rhs) const
virtual void trim ()
Frees unused space on this vector - i.e.
virtual const GLvoid * getDataPointer () const
virtual unsigned int getTotalDataSize () const
virtual unsigned int getNumElements () const
virtual unsigned int index (unsigned int pos) const
Protected Member Functions
virtual ~TemplateIndexArray ()
template<typename T, Array::Type ARRAYTYPE, int DataSize, int DataType>
class osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >
Member Typedef Documentation
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> typedef T osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::ElementDataType
Constructor & Destructor Documentation
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::TemplateIndexArray () [inline]
Referenced by osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::clone(), and osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::cloneType().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::TemplateIndexArray (const TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType > & ta, const CopyOp & copyop = CopyOp::SHALLOW_COPY) [inline]
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::TemplateIndexArray (unsigned int no) [inline]
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::TemplateIndexArray (unsigned int no, T * ptr) [inline]
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> template<class InputIterator > osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::TemplateIndexArray (InputIterator first, InputIterator last) [inline]
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::~TemplateIndexArray () [inline, protected, virtual]
Member Function Documentation
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> void osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::accept (ArrayVisitor & av) [inline, virtual]
References osg::ArrayVisitor::apply().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> void osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::accept (ConstArrayVisitor & av) const [inline, virtual]
References osg::ConstArrayVisitor::apply().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> void osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::accept (unsigned int index, ValueVisitor & vv) [inline, virtual]
References osg::ValueVisitor::apply().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> void osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::accept (unsigned int index, ConstValueVisitor & vv) const [inline, virtual]
References osg::ConstValueVisitor::apply().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual Object* osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::clone (const CopyOp & copyop) const [inline, virtual]
References osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::TemplateIndexArray().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual Object* osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::cloneType () const [inline, virtual]
References osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::TemplateIndexArray().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual int osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::compare (unsigned int lhs, unsigned int rhs) const [inline, virtual]
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual const GLvoid* osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::getDataPointer () const [inline, virtual]
References osg::MixinVector< T >::empty(), and osg::MixinVector< T >::front().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual unsigned int osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::getNumElements () const [inline, virtual]
References osg::MixinVector< T >::size().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual unsigned int osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::getTotalDataSize () const [inline, virtual]
References osg::MixinVector< T >::size().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual unsigned int osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::index (unsigned int pos) const [inline, virtual]
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> TemplateIndexArray& osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::operator= (const TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType > & array) [inline]
References osg::MixinVector< T >::assign(), osg::MixinVector< ValueT >::begin(), and osg::MixinVector< ValueT >::end().
template<typename T , Array::Type ARRAYTYPE, int DataSize, int DataType> virtual void osg::TemplateIndexArray< T, ARRAYTYPE, DataSize, DataType >::trim () [inline, virtual]
Frees unused space on this vector - i.e.
the difference between size() and max_size() of the underlying vector.
The documentation for this class was generated from the following file:
osg/Array
Generated at Thu Jun 9 2011 16:37:14 for the OpenSceneGraph by doxygen 1.7.1.