OpenSceneGraph: osgIntrospection::StdMapReflector< T, IT, VT > Struct Template Reference
osgIntrospection::StdMapReflector< T, IT, VT > Struct Template Reference
This class allows to define the means for reflecting STL associative containers which hold pairs of key+value, such as std::map.
Classes
struct Getter
struct Indexer
struct Remover
struct Setter
Public Types
typedef ValueReflector< T >
::instance_creator_type instance_creator_type
typedef T::iterator iterator
typedef T::const_iterator const_iterator
typedef T::key_type key_type
typedef T::mapped_type mapped_type
Public Member Functions
StdMapReflector (const std::string &name)
Detailed Description
template<typename T, typename IT, typename VT>
struct osgIntrospection::StdMapReflector< T, IT, VT >
This class allows to define the means for reflecting STL associative containers which hold pairs of key+value, such as std::map.
Member Typedef Documentation
template<typename T , typename IT , typename VT > typedef T::const_iterator osgIntrospection::StdMapReflector< T, IT, VT >::const_iterator
template<typename T , typename IT , typename VT > typedef ValueReflector<T>::instance_creator_type osgIntrospection::StdMapReflector< T, IT, VT >::instance_creator_type
Reimplemented from osgIntrospection::ValueReflector< T >.
template<typename T , typename IT , typename VT > typedef T::iterator osgIntrospection::StdMapReflector< T, IT, VT >::iterator
template<typename T , typename IT , typename VT > typedef T::key_type osgIntrospection::StdMapReflector< T, IT, VT >::key_type
template<typename T , typename IT , typename VT > typedef T::mapped_type osgIntrospection::StdMapReflector< T, IT, VT >::mapped_type
Constructor & Destructor Documentation
template<typename T , typename IT , typename VT > osgIntrospection::StdMapReflector< T, IT, VT >::StdMapReflector (const std::string & name) [inline]
References osgIntrospection::CustomAttributeProvider::addAttribute(), osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::addProperty(), and typeof.
The documentation for this struct was generated from the following file:
osgIntrospection/Reflector
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.