OpenSceneGraph: osgIntrospection::StdVectorReflector< T, VT > Struct Template Reference
osgIntrospection::StdVectorReflector< T, VT > Struct Template Reference
This class allows to define the means for reflecting STL containers such as std::deque and std::vector.
Classes
struct Adder
struct Counter
struct Getter
struct Inserter
struct Remover
struct Setter
Public Types
typedef ValueReflector< T >
::instance_creator_type instance_creator_type
Public Member Functions
StdVectorReflector (const std::string &name)
Detailed Description
template<typename T, typename VT>
struct osgIntrospection::StdVectorReflector< T, VT >
This class allows to define the means for reflecting STL containers such as std::deque and std::vector.
Member Typedef Documentation
template<typename T , typename VT > typedef ValueReflector<T>::instance_creator_type osgIntrospection::StdVectorReflector< T, VT >::instance_creator_type
Reimplemented from osgIntrospection::ValueReflector< T >.
Constructor & Destructor Documentation
template<typename T , typename VT > osgIntrospection::StdVectorReflector< T, VT >::StdVectorReflector (const std::string & name) [inline]
References osgIntrospection::CustomAttributeProvider::addAttribute(), osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::addProperty(), and typeof.
The documentation for this struct was generated from the following file:
osgIntrospection/Reflector
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.