OpenSceneGraph: osgAnimation::TransformVertexFunctor Class Reference
osgAnimation::TransformVertexFunctor Class Reference
This class manage format for software skinning it used the technic on this paper http://www.intel.com/cd/ids/developer/asmo-na/eng/172124.htm The idea is to prepare the data to do only v' = M x v with M a combined matrix as below M = Mbone1 * w1 + Mbone2 * w2 + ...
Classes
class BoneWeight
class UniqBoneSetVertexSet
Public Types
typedef osg::Matrix MatrixType
typedef osgAnimation::Bone BoneType
typedef Bone::BoneMap BoneMap
typedef std::vector< BoneWeight > BoneWeightList
typedef std::vector< int > VertexList
Public Member Functions
void init (const BoneMap &map, const osgAnimation::VertexInfluenceSet::UniqVertexSetToBoneSetList &influence)
template<class V >
void compute (const V *src, V *dst)
template<class V >
void compute (const MatrixType &transform, const MatrixType &invTransform, const V *src, V *dst)
template<class V >
void computeNormal (const MatrixType &transform, const MatrixType &invTransform, const V *src, V *dst)
Protected Attributes
std::vector< UniqBoneSetVertexSet > _boneSetVertexSet
Detailed Description
This class manage format for software skinning it used the technic on this paper http://www.intel.com/cd/ids/developer/asmo-na/eng/172124.htm The idea is to prepare the data to do only v' = M x v with M a combined matrix as below M = Mbone1 * w1 + Mbone2 * w2 + ...
a M matrix is uniq for a set of vertex then to fully compute the skinned mesh you have to iterate on each UniqBoneSetVertexSet
Member Typedef Documentation
typedef Bone::BoneMap osgAnimation::TransformVertexFunctor::BoneMap
typedef osgAnimation::Bone osgAnimation::TransformVertexFunctor::BoneType
typedef std::vector<BoneWeight> osgAnimation::TransformVertexFunctor::BoneWeightList
typedef osg::Matrix osgAnimation::TransformVertexFunctor::MatrixType
typedef std::vector<int> osgAnimation::TransformVertexFunctor::VertexList
Member Function Documentation
template<class V > void osgAnimation::TransformVertexFunctor::compute (const V * src, V * dst) [inline]
References _boneSetVertexSet, osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::computeMatrixForVertexSet(), osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getMatrix(), and osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getVertexes().
template<class V > void osgAnimation::TransformVertexFunctor::compute (const MatrixType & transform, const MatrixType & invTransform, const V * src, V * dst) [inline]
References _boneSetVertexSet, osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::computeMatrixForVertexSet(), osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getMatrix(), and osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getVertexes().
template<class V > void osgAnimation::TransformVertexFunctor::computeNormal (const MatrixType & transform, const MatrixType & invTransform, const V * src, V * dst) [inline]
References _boneSetVertexSet, osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::computeMatrixForVertexSet(), osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getMatrix(), osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getVertexes(), and osg::Matrixd::transform3x3().
void osgAnimation::TransformVertexFunctor::init (const BoneMap & map, const osgAnimation::VertexInfluenceSet::UniqVertexSetToBoneSetList & influence) [inline]
References _boneSetVertexSet, osgAnimation::VertexInfluenceSet::UniqVertexSetToBoneSet::getBones(), osgAnimation::VertexInfluenceSet::UniqVertexSetToBoneSet::getVertexes(), osg::notify(), and osg::WARN.
Member Data Documentation
std::vector<UniqBoneSetVertexSet> osgAnimation::TransformVertexFunctor::_boneSetVertexSet [protected]
Referenced by compute(), computeNormal(), and init().
The documentation for this class was generated from the following file:
osgAnimation/Skinning
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.