OpenSceneGraph: osgWidget::UIObjectParent< T > Class Template Reference
osgWidget::UIObjectParent< T > Class Template Reference
Public Types
typedef T object_type
typedef osg::observer_ptr
< object_type > ptr_type
typedef std::vector< ptr_type > Vector
typedef Vector::iterator Iterator
typedef Vector::const_iterator ConstIterator
Public Member Functions
Iterator begin ()
ConstIterator begin () const
Iterator end ()
ConstIterator end () const
Vector::size_type size () const
object_type * getByName (const std::string &name)
const object_type * getByName (const std::string &name) const
object_type * getByIndex (unsigned int index)
const object_type * getByIndex (unsigned int index) const
unsigned int getNumObjects () const
Vector & getObjects ()
const Vector & getObjects () const
Protected Member Functions
bool _remove (object_type *obj)
bool _removeByName (const std::string &name)
Protected Attributes
Vector _objects
template<typename T>
class osgWidget::UIObjectParent< T >
Member Typedef Documentation
template<typename T> typedef Vector::const_iterator osgWidget::UIObjectParent< T >::ConstIterator
template<typename T> typedef Vector::iterator osgWidget::UIObjectParent< T >::Iterator
template<typename T> typedef T osgWidget::UIObjectParent< T >::object_type
template<typename T> typedef osg::observer_ptr<object_type> osgWidget::UIObjectParent< T >::ptr_type
template<typename T> typedef std::vector<ptr_type> osgWidget::UIObjectParent< T >::Vector
Member Function Documentation
template<typename T> bool osgWidget::UIObjectParent< T >::_remove (object_type * obj) [inline, protected]
template<typename T> bool osgWidget::UIObjectParent< T >::_removeByName (const std::string & name) [inline, protected]
template<typename T> ConstIterator osgWidget::UIObjectParent< T >::begin () const [inline]
template<typename T> Iterator osgWidget::UIObjectParent< T >::begin () [inline]
Referenced by osgWidget::UIObjectParent< Window >::_remove(), and osgWidget::UIObjectParent< Window >::_removeByName().
template<typename T> ConstIterator osgWidget::UIObjectParent< T >::end () const [inline]
template<typename T> Iterator osgWidget::UIObjectParent< T >::end () [inline]
Referenced by osgWidget::UIObjectParent< Window >::_remove(), and osgWidget::UIObjectParent< Window >::_removeByName().
template<typename T> object_type* osgWidget::UIObjectParent< T >::getByIndex (unsigned int index) [inline]
template<typename T> const object_type* osgWidget::UIObjectParent< T >::getByIndex (unsigned int index) const [inline]
template<typename T> object_type* osgWidget::UIObjectParent< T >::getByName (const std::string & name) [inline]
template<typename T> const object_type* osgWidget::UIObjectParent< T >::getByName (const std::string & name) const [inline]
template<typename T> unsigned int osgWidget::UIObjectParent< T >::getNumObjects () const [inline]
template<typename T> Vector& osgWidget::UIObjectParent< T >::getObjects () [inline]
template<typename T> const Vector& osgWidget::UIObjectParent< T >::getObjects () const [inline]
template<typename T> Vector::size_type osgWidget::UIObjectParent< T >::size () const [inline]
Member Data Documentation
template<typename T> Vector osgWidget::UIObjectParent< T >::_objects [protected]
Referenced by osgWidget::UIObjectParent< Window >::_remove(), osgWidget::UIObjectParent< Window >::_removeByName(), osgWidget::UIObjectParent< Window >::begin(), osgWidget::UIObjectParent< Window >::end(), osgWidget::UIObjectParent< Window >::getNumObjects(), osgWidget::UIObjectParent< Window >::getObjects(), and osgWidget::UIObjectParent< Window >::size().
The documentation for this class was generated from the following file:
osgWidget/UIObjectParent
Generated at Thu Jun 9 2011 16:37:18 for the OpenSceneGraph by doxygen 1.7.1.