OpenSceneGraph: osg::Vec3f Class Reference
osg::Vec3f Class Reference
General purpose float triple for use as vertices, vectors and normals.
Public Types
enum { num_components = 3 }
Number of vector components.
typedef float value_type
Type of Vec class.
Public Member Functions
Vec3f ()
Vec3f (value_type x, value_type y, value_type z)
Vec3f (const Vec2f &v2, value_type zz)
bool operator== (const Vec3f &v) const
bool operator!= (const Vec3f &v) const
bool operator< (const Vec3f &v) const
value_type * ptr ()
const value_type * ptr () const
void set (value_type x, value_type y, value_type z)
void set (const Vec3f &rhs)
value_type & operator[] (int i)
value_type operator[] (int i) const
value_type & x ()
value_type & y ()
value_type & z ()
value_type x () const
value_type y () const
value_type z () const
bool valid () const
bool isNaN () const
value_type operator* (const Vec3f &rhs) const
Dot product.
const Vec3f operator^ (const Vec3f &rhs) const
Cross product.
const Vec3f operator* (value_type rhs) const
Multiply by scalar.
Vec3f & operator*= (value_type rhs)
Unary multiply by scalar.
const Vec3f operator/ (value_type rhs) const
Divide by scalar.
Vec3f & operator/= (value_type rhs)
Unary divide by scalar.
const Vec3f operator+ (const Vec3f &rhs) const
Binary vector add.
Vec3f & operator+= (const Vec3f &rhs)
Unary vector add.
const Vec3f operator- (const Vec3f &rhs) const
Binary vector subtract.
Vec3f & operator-= (const Vec3f &rhs)
Unary vector subtract.
const Vec3f operator- () const
Negation operator.
value_type length () const
Length of the vector = sqrt(vec .
value_type length2 () const
Length squared of the vector = vec .
value_type normalize ()
Normalize the vector so that it has length unity.
Public Attributes
value_type _v [3]
Detailed Description
General purpose float triple for use as vertices, vectors and normals.
Provides general math operations from addition through to cross products. No support yet added for float * Vec3f - is it necessary? Need to define a non-member non-friend operator* etc. Vec3f * float is okay
Member Typedef Documentation
typedef float osg::Vec3f::value_type
Type of Vec class.
Member Enumeration Documentation
anonymous enum
Number of vector components.
Enumerator:
num_components
Constructor & Destructor Documentation
osg::Vec3f::Vec3f () [inline]
References _v.
Referenced by operator*(), operator+(), operator-(), operator/(), and operator^().
osg::Vec3f::Vec3f (value_type x, value_type y, value_type z) [inline]
References _v.
osg::Vec3f::Vec3f (const Vec2f & v2, value_type zz) [inline]
References _v.
Member Function Documentation
bool osg::Vec3f::isNaN () const [inline]
References _v.
Referenced by valid().
value_type osg::Vec3f::length () const [inline]
Length of the vector = sqrt(vec .
vec)
References _v.
Referenced by osgUtil::ReflectionMapGenerator::compute_color(), osgUtil::HighlightMapGenerator::compute_color(), osgUtil::HalfWayMapGenerator::compute_color(), osgSim::ElevationRange::elevationSector(), normalize(), and osgUtil::CubeMapGenerator::vector_to_color().
value_type osg::Vec3f::length2 (void) const [inline]
Length squared of the vector = vec .
vec
References _v.
value_type osg::Vec3f::normalize () [inline]
Normalize the vector so that it has length unity.
Returns the previous length of the vector.
References _v, and length().
Referenced by osgShadow::OccluderGeometry::isLightPointSilhouetteEdge().
bool osg::Vec3f::operator!= (const Vec3f & v) const [inline]
References _v.
value_type osg::Vec3f::operator* (const Vec3f & rhs) const [inline]
Dot product.
References _v.
const Vec3f osg::Vec3f::operator* (value_type rhs) const [inline]
Multiply by scalar.
References _v, and Vec3f().
Vec3f& osg::Vec3f::operator*= (value_type rhs) [inline]
Unary multiply by scalar.
References _v.
const Vec3f osg::Vec3f::operator+ (const Vec3f & rhs) const [inline]
Binary vector add.
References _v, and Vec3f().
Vec3f& osg::Vec3f::operator+= (const Vec3f & rhs) [inline]
Unary vector add.
Slightly more efficient because no temporary intermediate object.
References _v.
const Vec3f osg::Vec3f::operator- (const Vec3f & rhs) const [inline]
Binary vector subtract.
References _v, and Vec3f().
const Vec3f osg::Vec3f::operator- () const [inline]
Negation operator.
Returns the negative of the Vec3f.
References _v, and Vec3f().
Vec3f& osg::Vec3f::operator-= (const Vec3f & rhs) [inline]
Unary vector subtract.
References _v.
const Vec3f osg::Vec3f::operator/ (value_type rhs) const [inline]
Divide by scalar.
References _v, and Vec3f().
Vec3f& osg::Vec3f::operator/= (value_type rhs) [inline]
Unary divide by scalar.
References _v.
bool osg::Vec3f::operator< (const Vec3f & v) const [inline]
References _v.
bool osg::Vec3f::operator== (const Vec3f & v) const [inline]
References _v.
value_type& osg::Vec3f::operator[] (int i) [inline]
References _v.
value_type osg::Vec3f::operator[] (int i) const [inline]
References _v.
const Vec3f osg::Vec3f::operator^ (const Vec3f & rhs) const [inline]
Cross product.
References _v, and Vec3f().
value_type* osg::Vec3f::ptr () [inline]
References _v.
const value_type* osg::Vec3f::ptr () const [inline]
References _v.
void osg::Vec3f::set (value_type x, value_type y, value_type z) [inline]
References _v.
Referenced by osgAnimation::Vec3ArrayPacked::analyze(), osgParticle::CenteredPlacer::setCenter(), osgParticle::AccelOperator::setToGravity(), osgParticle::SegmentPlacer::setVertexA(), and osgParticle::SegmentPlacer::setVertexB().
void osg::Vec3f::set (const Vec3f & rhs) [inline]
References _v.
bool osg::Vec3f::valid () const [inline]
References isNaN().
Referenced by osgUtil::LineSegmentIntersector::Intersection::getWorldIntersectNormal().
value_type& osg::Vec3f::x () [inline]
References _v.
Referenced by osgSim::AzimRange::azimSector(), osg::Plane::distance(), osg::Plane::dotProductNormal(), osgParticle::Interpolator::interpolate(), osgTerrain::ValidDataOperator::operator()(), osg::Matrixf::postMult(), osg::Matrixd::postMult(), osg::Matrixf::preMult(), osg::Matrixd::preMult(), osg::Matrixf::scale(), osg::Matrixd::scale(), osg::TexEnvCombine::setConstantColorAsLightDirection(), osg::Matrixf::transform3x3(), osg::Matrixd::transform3x3(), osg::Matrixf::translate(), osg::Matrixd::translate(), osgParticle::ParticleSystem::update_bounds(), and osgUtil::CubeMapGenerator::vector_to_color().
value_type osg::Vec3f::x () const [inline]
References _v.
value_type& osg::Vec3f::y () [inline]
References _v.
Referenced by osgSim::AzimRange::azimSector(), osg::Plane::distance(), osg::Plane::dotProductNormal(), osgParticle::Interpolator::interpolate(), osgTerrain::ValidDataOperator::operator()(), osgParticle::BoxPlacer::place(), osg::Matrixf::postMult(), osg::Matrixd::postMult(), osg::Matrixf::preMult(), osg::Matrixd::preMult(), osg::Matrixf::scale(), osg::Matrixd::scale(), osg::TexEnvCombine::setConstantColorAsLightDirection(), osg::Matrixf::transform3x3(), osg::Matrixd::transform3x3(), osg::Matrixf::translate(), osg::Matrixd::translate(), osgParticle::ParticleSystem::update_bounds(), and osgUtil::CubeMapGenerator::vector_to_color().
value_type osg::Vec3f::y () const [inline]
References _v.
value_type& osg::Vec3f::z () [inline]
References _v.
Referenced by osg::Plane::distance(), osg::Plane::dotProductNormal(), osgSim::ElevationRange::elevationSector(), osgParticle::Interpolator::interpolate(), osgTerrain::ValidDataOperator::operator()(), osgParticle::BoxPlacer::place(), osg::Matrixf::postMult(), osg::Matrixd::postMult(), osg::Matrixf::preMult(), osg::Matrixd::preMult(), osg::Matrixf::scale(), osg::Matrixd::scale(), osg::TexEnvCombine::setConstantColorAsLightDirection(), osg::Matrixf::transform3x3(), osg::Matrixd::transform3x3(), osg::Matrixf::translate(), osg::Matrixd::translate(), osgParticle::ParticleSystem::update_bounds(), and osgUtil::CubeMapGenerator::vector_to_color().
value_type osg::Vec3f::z () const [inline]
References _v.
Member Data Documentation
value_type osg::Vec3f::_v[3]
Referenced by isNaN(), length(), length2(), normalize(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), osg::operator<<(), operator==(), osg::operator>>(), operator[](), operator^(), ptr(), set(), osg::Vec3d::Vec3d(), Vec3f(), x(), y(), and z().
The documentation for this class was generated from the following file:
osg/Vec3f
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.