OpenSceneGraph: osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet Class Reference
osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet Class Reference
Public Member Functions
BoneWeightList & getBones ()
VertexList & getVertexes ()
void resetMatrix ()
void accummulateMatrix (const osg::Matrix &invBindMatrix, const osg::Matrix &matrix, osg::Matrix::value_type weight)
void computeMatrixForVertexSet ()
const MatrixType & getMatrix () const
Protected Attributes
BoneWeightList _bones
VertexList _vertexes
MatrixType _result
Member Function Documentation
void osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::accummulateMatrix (const osg::Matrix & invBindMatrix, const osg::Matrix & matrix, osg::Matrix::value_type weight) [inline]
References _result, and osg::Matrixd::ptr().
Referenced by computeMatrixForVertexSet().
void osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::computeMatrixForVertexSet () [inline]
References _bones, _result, accummulateMatrix(), osgAnimation::Bone::getInvBindMatrixInSkeletonSpace(), osgAnimation::Bone::getMatrixInSkeletonSpace(), osg::Matrixd::identity(), osg::notify(), resetMatrix(), and osg::WARN.
Referenced by osgAnimation::TransformVertexFunctor::compute(), and osgAnimation::TransformVertexFunctor::computeNormal().
BoneWeightList& osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getBones () [inline]
References _bones.
const MatrixType& osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getMatrix () const [inline]
References _result.
Referenced by osgAnimation::TransformVertexFunctor::compute(), and osgAnimation::TransformVertexFunctor::computeNormal().
VertexList& osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::getVertexes () [inline]
References _vertexes.
Referenced by osgAnimation::TransformVertexFunctor::compute(), and osgAnimation::TransformVertexFunctor::computeNormal().
void osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::resetMatrix () [inline]
References _result, and osg::Matrixd::set().
Referenced by computeMatrixForVertexSet().
Member Data Documentation
BoneWeightList osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::_bones [protected]
Referenced by computeMatrixForVertexSet(), and getBones().
MatrixType osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::_result [protected]
Referenced by accummulateMatrix(), computeMatrixForVertexSet(), getMatrix(), and resetMatrix().
VertexList osgAnimation::TransformVertexFunctor::UniqBoneSetVertexSet::_vertexes [protected]
Referenced by getVertexes().
The documentation for this class was generated from the following file:
osgAnimation/Skinning
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.