OpenSceneGraph: osg::Vec2d Class Reference
osg::Vec2d Class Reference
General purpose double pair, uses include representation of texture coordinates.
Public Types
enum { num_components = 2 }
Number of vector components.
typedef double value_type
Type of Vec class.
Public Member Functions
Vec2d ()
Vec2d (value_type x, value_type y)
Vec2d (const Vec2f &vec)
operator Vec2f () const
bool operator== (const Vec2d &v) const
bool operator!= (const Vec2d &v) const
bool operator< (const Vec2d &v) const
value_type * ptr ()
const value_type * ptr () const
void set (value_type x, value_type y)
value_type & operator[] (int i)
value_type operator[] (int i) const
value_type & x ()
value_type & y ()
value_type x () const
value_type y () const
bool valid () const
bool isNaN () const
value_type operator* (const Vec2d &rhs) const
Dot product.
const Vec2d operator* (value_type rhs) const
Multiply by scalar.
Vec2d & operator*= (value_type rhs)
Unary multiply by scalar.
const Vec2d operator/ (value_type rhs) const
Divide by scalar.
Vec2d & operator/= (value_type rhs)
Unary divide by scalar.
const Vec2d operator+ (const Vec2d &rhs) const
Binary vector add.
Vec2d & operator+= (const Vec2d &rhs)
Unary vector add.
const Vec2d operator- (const Vec2d &rhs) const
Binary vector subtract.
Vec2d & operator-= (const Vec2d &rhs)
Unary vector subtract.
const Vec2d operator- () const
Negation operator.
value_type length () const
Length of the vector = sqrt(vec .
value_type length2 (void) const
Length squared of the vector = vec .
value_type normalize ()
Normalize the vector so that it has length unity.
Public Attributes
value_type _v [2]
Detailed Description
General purpose double pair, uses include representation of texture coordinates.
No support yet added for double * Vec2d - is it necessary? Need to define a non-member non-friend operator* etc. BTW: Vec2d * double is okay
Member Typedef Documentation
typedef double osg::Vec2d::value_type
Type of Vec class.
Member Enumeration Documentation
anonymous enum
Number of vector components.
Enumerator:
num_components
Constructor & Destructor Documentation
osg::Vec2d::Vec2d () [inline]
References _v.
Referenced by operator*(), operator+(), operator-(), and operator/().
osg::Vec2d::Vec2d (value_type x, value_type y) [inline]
References _v.
osg::Vec2d::Vec2d (const Vec2f & vec) [inline]
References osg::Vec2f::_v, and _v.
Member Function Documentation
bool osg::Vec2d::isNaN () const [inline]
References _v.
Referenced by valid().
value_type osg::Vec2d::length () const [inline]
Length of the vector = sqrt(vec .
vec)
References _v.
Referenced by normalize().
value_type osg::Vec2d::length2 (void) const [inline]
Length squared of the vector = vec .
vec
References _v.
value_type osg::Vec2d::normalize () [inline]
Normalize the vector so that it has length unity.
Returns the previous length of the vector.
References _v, and length().
osg::Vec2d::operator Vec2f () const [inline]
References _v.
bool osg::Vec2d::operator!= (const Vec2d & v) const [inline]
References _v.
value_type osg::Vec2d::operator* (const Vec2d & rhs) const [inline]
Dot product.
References _v.
const Vec2d osg::Vec2d::operator* (value_type rhs) const [inline]
Multiply by scalar.
References _v, and Vec2d().
Vec2d& osg::Vec2d::operator*= (value_type rhs) [inline]
Unary multiply by scalar.
References _v.
const Vec2d osg::Vec2d::operator+ (const Vec2d & rhs) const [inline]
Binary vector add.
References _v, and Vec2d().
Vec2d& osg::Vec2d::operator+= (const Vec2d & rhs) [inline]
Unary vector add.
Slightly more efficient because no temporary intermediate object.
References _v.
const Vec2d osg::Vec2d::operator- (const Vec2d & rhs) const [inline]
Binary vector subtract.
References _v, and Vec2d().
const Vec2d osg::Vec2d::operator- () const [inline]
Negation operator.
Returns the negative of the Vec2d.
References _v, and Vec2d().
Vec2d& osg::Vec2d::operator-= (const Vec2d & rhs) [inline]
Unary vector subtract.
References _v.
const Vec2d osg::Vec2d::operator/ (value_type rhs) const [inline]
Divide by scalar.
References _v, and Vec2d().
Vec2d& osg::Vec2d::operator/= (value_type rhs) [inline]
Unary divide by scalar.
References _v.
bool osg::Vec2d::operator< (const Vec2d & v) const [inline]
References _v.
bool osg::Vec2d::operator== (const Vec2d & v) const [inline]
References _v.
value_type osg::Vec2d::operator[] (int i) const [inline]
References _v.
value_type& osg::Vec2d::operator[] (int i) [inline]
References _v.
value_type* osg::Vec2d::ptr () [inline]
References _v.
const value_type* osg::Vec2d::ptr () const [inline]
References _v.
void osg::Vec2d::set (value_type x, value_type y) [inline]
References _v.
bool osg::Vec2d::valid () const [inline]
References isNaN().
value_type& osg::Vec2d::x () [inline]
References _v.
value_type osg::Vec2d::x () const [inline]
References _v.
value_type& osg::Vec2d::y () [inline]
References _v.
value_type osg::Vec2d::y () const [inline]
References _v.
Member Data Documentation
value_type osg::Vec2d::_v[2]
Referenced by isNaN(), length(), length2(), normalize(), operator Vec2f(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), osg::operator<<(), operator==(), osg::operator>>(), operator[](), ptr(), set(), Vec2d(), x(), and y().
The documentation for this class was generated from the following file:
osg/Vec2d
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.