OpenSceneGraph: osg::Vec2f Class Reference
osg::Vec2f Class Reference
General purpose float pair.
Public Types
enum { num_components = 2 }
Number of vector components.
typedef float value_type
Type of Vec class.
Public Member Functions
Vec2f ()
Vec2f (value_type x, value_type y)
bool operator== (const Vec2f &v) const
bool operator!= (const Vec2f &v) const
bool operator< (const Vec2f &v) const
value_type * ptr ()
const value_type * ptr () const
void set (value_type x, value_type y)
value_type & operator[] (int i)
value_type operator[] (int i) const
value_type & x ()
value_type & y ()
value_type x () const
value_type y () const
bool valid () const
bool isNaN () const
value_type operator* (const Vec2f &rhs) const
Dot product.
const Vec2f operator* (value_type rhs) const
Multiply by scalar.
Vec2f & operator*= (value_type rhs)
Unary multiply by scalar.
const Vec2f operator/ (value_type rhs) const
Divide by scalar.
Vec2f & operator/= (value_type rhs)
Unary divide by scalar.
const Vec2f operator+ (const Vec2f &rhs) const
Binary vector add.
Vec2f & operator+= (const Vec2f &rhs)
Unary vector add.
const Vec2f operator- (const Vec2f &rhs) const
Binary vector subtract.
Vec2f & operator-= (const Vec2f &rhs)
Unary vector subtract.
const Vec2f operator- () const
Negation operator.
value_type length () const
Length of the vector = sqrt(vec .
value_type length2 (void) const
Length squared of the vector = vec .
value_type normalize ()
Normalize the vector so that it has length unity.
Public Attributes
value_type _v [2]
Vec member varaible.
Detailed Description
General purpose float pair.
Uses include representation of texture coordinates. No support yet added for float * Vec2f - is it necessary? Need to define a non-member non-friend operator* etc. BTW: Vec2f * float is okay
Member Typedef Documentation
typedef float osg::Vec2f::value_type
Type of Vec class.
Member Enumeration Documentation
anonymous enum
Number of vector components.
Enumerator:
num_components
Constructor & Destructor Documentation
osg::Vec2f::Vec2f () [inline]
References _v.
Referenced by operator*(), operator+(), operator-(), and operator/().
osg::Vec2f::Vec2f (value_type x, value_type y) [inline]
References _v.
Member Function Documentation
bool osg::Vec2f::isNaN () const [inline]
References _v.
Referenced by valid().
value_type osg::Vec2f::length () const [inline]
Length of the vector = sqrt(vec .
vec)
References _v.
Referenced by normalize().
value_type osg::Vec2f::length2 (void) const [inline]
Length squared of the vector = vec .
vec
References _v.
value_type osg::Vec2f::normalize () [inline]
Normalize the vector so that it has length unity.
Returns the previous length of the vector.
References _v, and length().
bool osg::Vec2f::operator!= (const Vec2f & v) const [inline]
References _v.
const Vec2f osg::Vec2f::operator* (value_type rhs) const [inline]
Multiply by scalar.
References _v, and Vec2f().
value_type osg::Vec2f::operator* (const Vec2f & rhs) const [inline]
Dot product.
References _v.
Vec2f& osg::Vec2f::operator*= (value_type rhs) [inline]
Unary multiply by scalar.
References _v.
const Vec2f osg::Vec2f::operator+ (const Vec2f & rhs) const [inline]
Binary vector add.
References _v, and Vec2f().
Vec2f& osg::Vec2f::operator+= (const Vec2f & rhs) [inline]
Unary vector add.
Slightly more efficient because no temporary intermediate object.
References _v.
const Vec2f osg::Vec2f::operator- (const Vec2f & rhs) const [inline]
Binary vector subtract.
References _v, and Vec2f().
const Vec2f osg::Vec2f::operator- () const [inline]
Negation operator.
Returns the negative of the Vec2f.
References _v, and Vec2f().
Vec2f& osg::Vec2f::operator-= (const Vec2f & rhs) [inline]
Unary vector subtract.
References _v.
const Vec2f osg::Vec2f::operator/ (value_type rhs) const [inline]
Divide by scalar.
References _v, and Vec2f().
Vec2f& osg::Vec2f::operator/= (value_type rhs) [inline]
Unary divide by scalar.
References _v.
bool osg::Vec2f::operator< (const Vec2f & v) const [inline]
References _v.
bool osg::Vec2f::operator== (const Vec2f & v) const [inline]
References _v.
value_type& osg::Vec2f::operator[] (int i) [inline]
References _v.
value_type osg::Vec2f::operator[] (int i) const [inline]
References _v.
value_type* osg::Vec2f::ptr () [inline]
References _v.
const value_type* osg::Vec2f::ptr () const [inline]
References _v.
void osg::Vec2f::set (value_type x, value_type y) [inline]
References _v.
bool osg::Vec2f::valid () const [inline]
References isNaN().
value_type& osg::Vec2f::x () [inline]
References _v.
Referenced by osgWidget::Widget::addOrigin(), osgWidget::Widget::addSize(), osg::Image::getColor(), osgWidget::Widget::getImageColorAtXY(), osgParticle::Interpolator::interpolate(), osgWidget::Window::isPointerXYWithinVisible(), osgTerrain::ValidDataOperator::operator()(), osgWidget::Widget::setMinimumSize(), osgWidget::Window::setOrigin(), osgWidget::Widget::setOrigin(), osgWidget::Widget::setSize(), osgWidget::Widget::setTexCoord(), and osgWidget::Widget::setTexCoordRegion().
value_type osg::Vec2f::x () const [inline]
References _v.
value_type osg::Vec2f::y () const [inline]
References _v.
value_type& osg::Vec2f::y () [inline]
References _v.
Referenced by osgWidget::Widget::addOrigin(), osgWidget::Widget::addSize(), osg::Image::getColor(), osgWidget::Widget::getImageColorAtXY(), osgParticle::Interpolator::interpolate(), osgWidget::Window::isPointerXYWithinVisible(), osgTerrain::ValidDataOperator::operator()(), osgWidget::Widget::setMinimumSize(), osgWidget::Window::setOrigin(), osgWidget::Widget::setOrigin(), osgWidget::Widget::setSize(), osgWidget::Widget::setTexCoord(), and osgWidget::Widget::setTexCoordRegion().
Member Data Documentation
value_type osg::Vec2f::_v[2]
Vec member varaible.
Referenced by isNaN(), length(), length2(), normalize(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), osg::operator<<(), operator==(), osg::operator>>(), operator[](), ptr(), set(), osg::Vec2d::Vec2d(), Vec2f(), x(), and y().
The documentation for this class was generated from the following file:
osg/Vec2f
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.