OpenSceneGraph: osg::VertexBufferObject Class Reference
osg::VertexBufferObject Class Reference
Public Types
typedef std::pair< BufferEntry,
Array * > BufferEntryArrayPair
typedef std::vector
< BufferEntryArrayPair > BufferEntryArrayPairs
Public Member Functions
VertexBufferObject ()
VertexBufferObject (const VertexBufferObject &vbo, const CopyOp &copyop=CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
META_Object (osg, VertexBufferObject)
unsigned int addArray (osg::Array *array)
void removeArray (osg::Array *array)
void setArray (unsigned int i, Array *array)
Array * getArray (unsigned int i)
const Array * getArray (unsigned int i) const
const GLvoid * getOffset (unsigned int i) const
virtual void compileBuffer (State &state) const
virtual void resizeGLObjectBuffers (unsigned int maxSize)
Resize any per context GLObject buffers to specified size.
Protected Member Functions
virtual ~VertexBufferObject ()
Protected Attributes
BufferEntryArrayPairs _bufferEntryArrayPairs
Member Typedef Documentation
typedef std::pair< BufferEntry, Array* > osg::VertexBufferObject::BufferEntryArrayPair
typedef std::vector< BufferEntryArrayPair > osg::VertexBufferObject::BufferEntryArrayPairs
Constructor & Destructor Documentation
osg::VertexBufferObject::VertexBufferObject ()
osg::VertexBufferObject::VertexBufferObject (const VertexBufferObject & vbo, const CopyOp & copyop = CopyOp::SHALLOW_COPY)
Copy constructor using CopyOp to manage deep vs shallow copy.
virtual osg::VertexBufferObject::~VertexBufferObject () [protected, virtual]
Member Function Documentation
unsigned int osg::VertexBufferObject::addArray (osg::Array * array)
Referenced by osg::Array::setVertexBufferObject().
virtual void osg::VertexBufferObject::compileBuffer (State & state) const [virtual]
Implements osg::BufferObject.
Referenced by osg::State::bindVertexBufferObject().
Array* osg::VertexBufferObject::getArray (unsigned int i) [inline]
const Array* osg::VertexBufferObject::getArray (unsigned int i) const [inline]
const GLvoid* osg::VertexBufferObject::getOffset (unsigned int i) const [inline]
Referenced by osg::State::setFogCoordPointer(), osg::State::setSecondaryColorPointer(), osg::State::setTexCoordPointer(), and osg::State::setVertexAttribPointer().
osg::VertexBufferObject::META_Object (osg , VertexBufferObject)
void osg::VertexBufferObject::removeArray (osg::Array * array)
virtual void osg::VertexBufferObject::resizeGLObjectBuffers (unsigned int maxSize) [virtual]
Resize any per context GLObject buffers to specified size.
Reimplemented from osg::BufferObject.
void osg::VertexBufferObject::setArray (unsigned int i, Array * array)
Member Data Documentation
BufferEntryArrayPairs osg::VertexBufferObject::_bufferEntryArrayPairs [protected]
The documentation for this class was generated from the following file:
osg/BufferObject
Generated at Thu Jun 9 2011 16:37:14 for the OpenSceneGraph by doxygen 1.7.1.