OpenSceneGraph: osgTerrain::ValidDataOperator Struct Reference
osgTerrain::ValidDataOperator Struct Reference
Public Member Functions
virtual bool operator() (float) const
virtual bool operator() (const osg::Vec2 &value) const
virtual bool operator() (const osg::Vec3 &value) const
virtual bool operator() (const osg::Vec4 &value) const
Member Function Documentation
virtual bool osgTerrain::ValidDataOperator::operator() (float) const [inline, virtual]
Reimplemented in osgTerrain::ValidRange, and osgTerrain::NoDataValue.
virtual bool osgTerrain::ValidDataOperator::operator() (const osg::Vec4 & value) const [inline, virtual]
References operator()(), osg::Vec4f::w(), osg::Vec4f::x(), osg::Vec4f::y(), and osg::Vec4f::z().
Referenced by operator()().
virtual bool osgTerrain::ValidDataOperator::operator() (const osg::Vec3 & value) const [inline, virtual]
References operator()(), osg::Vec3f::x(), osg::Vec3f::y(), and osg::Vec3f::z().
Referenced by operator()().
virtual bool osgTerrain::ValidDataOperator::operator() (const osg::Vec2 & value) const [inline, virtual]
References operator()(), osg::Vec2f::x(), and osg::Vec2f::y().
Referenced by operator()().
The documentation for this struct was generated from the following file:
osgTerrain/ValidDataOperator
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.