OpenSceneGraph: osg::Vec3d Class Reference
osg::Vec3d Class Reference
General purpose double triple for use as vertices, vectors and normals.
Public Types
enum { num_components = 3 }
Number of vector components.
typedef double value_type
Type of Vec class.
Public Member Functions
Vec3d ()
Vec3d (const Vec3f &vec)
operator Vec3f () const
Vec3d (value_type x, value_type y, value_type z)
Vec3d (const Vec2d &v2, value_type zz)
bool operator== (const Vec3d &v) const
bool operator!= (const Vec3d &v) const
bool operator< (const Vec3d &v) const
value_type * ptr ()
const value_type * ptr () const
void set (value_type x, value_type y, value_type z)
void set (const Vec3d &rhs)
value_type & operator[] (int i)
value_type operator[] (int i) const
value_type & x ()
value_type & y ()
value_type & z ()
value_type x () const
value_type y () const
value_type z () const
bool valid () const
bool isNaN () const
value_type operator* (const Vec3d &rhs) const
Dot product.
const Vec3d operator^ (const Vec3d &rhs) const
Cross product.
const Vec3d operator* (value_type rhs) const
Multiply by scalar.
Vec3d & operator*= (value_type rhs)
Unary multiply by scalar.
const Vec3d operator/ (value_type rhs) const
Divide by scalar.
Vec3d & operator/= (value_type rhs)
Unary divide by scalar.
const Vec3d operator+ (const Vec3d &rhs) const
Binary vector add.
Vec3d & operator+= (const Vec3d &rhs)
Unary vector add.
const Vec3d operator- (const Vec3d &rhs) const
Binary vector subtract.
Vec3d & operator-= (const Vec3d &rhs)
Unary vector subtract.
const Vec3d operator- () const
Negation operator.
value_type length () const
Length of the vector = sqrt(vec .
value_type length2 () const
Length squared of the vector = vec .
value_type normalize ()
Normalize the vector so that it has length unity.
Public Attributes
value_type _v [3]
Detailed Description
General purpose double triple for use as vertices, vectors and normals.
Provides general math operations from addition through to cross products. No support yet added for double * Vec3d - is it necessary? Need to define a non-member non-friend operator* etc. Vec3d * double is okay
Member Typedef Documentation
typedef double osg::Vec3d::value_type
Type of Vec class.
Member Enumeration Documentation
anonymous enum
Number of vector components.
Enumerator:
num_components
Constructor & Destructor Documentation
osg::Vec3d::Vec3d () [inline]
References _v.
Referenced by operator*(), operator+(), operator-(), operator/(), and operator^().
osg::Vec3d::Vec3d (const Vec3f & vec) [inline]
References osg::Vec3f::_v, and _v.
osg::Vec3d::Vec3d (value_type x, value_type y, value_type z) [inline]
References _v.
osg::Vec3d::Vec3d (const Vec2d & v2, value_type zz) [inline]
References _v.
Member Function Documentation
bool osg::Vec3d::isNaN () const [inline]
References _v.
Referenced by valid().
value_type osg::Vec3d::length () const [inline]
Length of the vector = sqrt(vec .
vec)
References _v.
Referenced by osg::Matrixf::getScale(), osg::Matrixd::getScale(), normalize(), and osg::Plane::set().
value_type osg::Vec3d::length2 (void) const [inline]
Length squared of the vector = vec .
vec
References _v.
value_type osg::Vec3d::normalize () [inline]
Normalize the vector so that it has length unity.
Returns the previous length of the vector.
References _v, and length().
Referenced by osg::EllipsoidModel::computeLocalUpVector().
osg::Vec3d::operator Vec3f () const [inline]
References _v.
bool osg::Vec3d::operator!= (const Vec3d & v) const [inline]
References _v.
value_type osg::Vec3d::operator* (const Vec3d & rhs) const [inline]
Dot product.
References _v.
const Vec3d osg::Vec3d::operator* (value_type rhs) const [inline]
Multiply by scalar.
References _v, and Vec3d().
Vec3d& osg::Vec3d::operator*= (value_type rhs) [inline]
Unary multiply by scalar.
References _v.
const Vec3d osg::Vec3d::operator+ (const Vec3d & rhs) const [inline]
Binary vector add.
References _v, and Vec3d().
Vec3d& osg::Vec3d::operator+= (const Vec3d & rhs) [inline]
Unary vector add.
Slightly more efficient because no temporary intermediate object.
References _v.
const Vec3d osg::Vec3d::operator- (const Vec3d & rhs) const [inline]
Binary vector subtract.
References _v, and Vec3d().
const Vec3d osg::Vec3d::operator- () const [inline]
Negation operator.
Returns the negative of the Vec3d.
References _v, and Vec3d().
Vec3d& osg::Vec3d::operator-= (const Vec3d & rhs) [inline]
Unary vector subtract.
References _v.
const Vec3d osg::Vec3d::operator/ (value_type rhs) const [inline]
Divide by scalar.
References _v, and Vec3d().
Vec3d& osg::Vec3d::operator/= (value_type rhs) [inline]
Unary divide by scalar.
References _v.
bool osg::Vec3d::operator< (const Vec3d & v) const [inline]
References _v.
bool osg::Vec3d::operator== (const Vec3d & v) const [inline]
References _v.
value_type& osg::Vec3d::operator[] (int i) [inline]
References _v.
value_type osg::Vec3d::operator[] (int i) const [inline]
References _v.
const Vec3d osg::Vec3d::operator^ (const Vec3d & rhs) const [inline]
Cross product.
References _v, and Vec3d().
value_type* osg::Vec3d::ptr () [inline]
References _v.
const value_type* osg::Vec3d::ptr () const [inline]
References _v.
void osg::Vec3d::set (const Vec3d & rhs) [inline]
References _v.
void osg::Vec3d::set (value_type x, value_type y, value_type z) [inline]
References _v.
Referenced by osg::Plane::set().
bool osg::Vec3d::valid () const [inline]
References isNaN().
Referenced by osgUtil::LineSegmentIntersector::Intersection::getWorldIntersectPoint().
value_type& osg::Vec3d::x () [inline]
References _v.
Referenced by osg::Plane::distance(), osg::Plane::dotProductNormal(), osg::Matrixf::postMult(), osg::Matrixd::postMult(), osg::Matrixf::preMult(), osg::Matrixd::preMult(), osg::Matrixf::scale(), osg::Matrixd::scale(), osg::Matrixf::transform3x3(), osg::Matrixd::transform3x3(), osg::Matrixf::translate(), and osg::Matrixd::translate().
value_type osg::Vec3d::x () const [inline]
References _v.
value_type& osg::Vec3d::y () [inline]
References _v.
Referenced by osg::Plane::distance(), osg::Plane::dotProductNormal(), osg::Matrixf::postMult(), osg::Matrixd::postMult(), osg::Matrixf::preMult(), osg::Matrixd::preMult(), osg::Matrixf::scale(), osg::Matrixd::scale(), osg::Matrixf::transform3x3(), osg::Matrixd::transform3x3(), osg::Matrixf::translate(), and osg::Matrixd::translate().
value_type osg::Vec3d::y () const [inline]
References _v.
value_type& osg::Vec3d::z () [inline]
References _v.
Referenced by osg::Plane::distance(), osg::Plane::dotProductNormal(), osg::Matrixf::postMult(), osg::Matrixd::postMult(), osg::Matrixf::preMult(), osg::Matrixd::preMult(), osg::Matrixf::scale(), osg::Matrixd::scale(), osg::Matrixf::transform3x3(), osg::Matrixd::transform3x3(), osg::Matrixf::translate(), and osg::Matrixd::translate().
value_type osg::Vec3d::z () const [inline]
References _v.
Member Data Documentation
value_type osg::Vec3d::_v[3]
Referenced by isNaN(), length(), length2(), normalize(), operator Vec3f(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), osg::operator<<(), operator==(), osg::operator>>(), operator[](), operator^(), ptr(), set(), Vec3d(), x(), y(), and z().
The documentation for this class was generated from the following file:
osg/Vec3d
Generated at Thu Jun 9 2011 16:37:15 for the OpenSceneGraph by doxygen 1.7.1.