OpenSceneGraph: osgDB::Registry::WriteFileCallback Class Reference
osgDB::Registry::WriteFileCallback Class Reference
Public Member Functions
virtual ReaderWriter::WriteResult writeObject (const osg::Object &obj, const std::string &fileName, const ReaderWriter::Options *options)
virtual ReaderWriter::WriteResult writeImage (const osg::Image &obj, const std::string &fileName, const ReaderWriter::Options *options)
virtual ReaderWriter::WriteResult writeHeightField (const osg::HeightField &obj, const std::string &fileName, const ReaderWriter::Options *options)
virtual ReaderWriter::WriteResult writeNode (const osg::Node &obj, const std::string &fileName, const ReaderWriter::Options *options)
virtual ReaderWriter::WriteResult writeShader (const osg::Shader &obj, const std::string &fileName, const ReaderWriter::Options *options)
Protected Member Functions
virtual ~WriteFileCallback ()
Constructor & Destructor Documentation
virtual osgDB::Registry::WriteFileCallback::~WriteFileCallback () [inline, protected, virtual]
Member Function Documentation
virtual ReaderWriter::WriteResult osgDB::Registry::WriteFileCallback::writeHeightField (const osg::HeightField & obj, const std::string & fileName, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::writeHeightFieldImplementation().
virtual ReaderWriter::WriteResult osgDB::Registry::WriteFileCallback::writeImage (const osg::Image & obj, const std::string & fileName, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::writeImageImplementation().
virtual ReaderWriter::WriteResult osgDB::Registry::WriteFileCallback::writeNode (const osg::Node & obj, const std::string & fileName, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::writeNodeImplementation().
virtual ReaderWriter::WriteResult osgDB::Registry::WriteFileCallback::writeObject (const osg::Object & obj, const std::string & fileName, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::writeObjectImplementation().
Referenced by osgDB::Registry::writeObject().
virtual ReaderWriter::WriteResult osgDB::Registry::WriteFileCallback::writeShader (const osg::Shader & obj, const std::string & fileName, const ReaderWriter::Options * options) [inline, virtual]
References osgDB::Registry::instance(), and osgDB::Registry::writeShaderImplementation().
The documentation for this class was generated from the following file:
osgDB/Registry
Generated at Thu Jun 9 2011 16:37:16 for the OpenSceneGraph by doxygen 1.7.1.