OpenSceneGraph: osgWidget Namespace Reference
osgWidget Namespace Reference
The osgWidget library is a NodeKit that extends the core scene graph to support a 2D (and eventually 3D) GUI widget set.
Classes
class Box
The Box object is a Window subclass that can be configured to uniformly (or non-uniformly) position it's children either vertically or horizontally.
class BrowserManager
class BrowserImage
Pure virtual base class for that provides the browser inteface for integration with 3rd party implementations.
class Browser
Convinience class that provides a interactive quad that can be placed directly in the scene.
class Canvas
class Event
struct CallbackInterface
class ObjectCallback
class FunctionCallback
class Callback
class EventInterface
class Frame
class Input
class Label
class LuaEngine
struct GeometryHints
Hints structure that can be passed to PdfReader and VncClient classes to help guide them on what geometry to build.
class PdfImage
Pure virtual base class for interfacing with implementation of PDF reader.
class PdfReader
Convinience class that provides a interactive quad that can be placed directly in the scene.
class PythonEngine
class ScriptEngine
class StyleInterface
class Style
class StyleManager
class Table
class UIObjectParent
class MouseHandler
class KeyboardHandler
class ResizeHandler
class CameraSwitchHandler
class VncImage
Pure virtual base class for VncImage that is sublcassed by vnc plugin to provide the actual implementation.
class VncClient
Convinience Vnc Client class that provides a interactive quad that can be placed directly in the scene.
class Widget
struct NotifyWidget
struct NullWidget
class Window
class WindowManager
Typedefs
typedef
osgDB::FieldReaderIterator & Reader
typedef osg::Vec2Array TexCoordArray
typedef osg::Vec3Array PointArray
typedef osg::Vec4Array ColorArray
typedef TexCoordArray::value_type TexCoord
typedef PointArray::value_type Point
typedef ColorArray::value_type Color
typedef TexCoord::value_type texcoord_type
typedef Point::value_type point_type
typedef Color::value_type color_type
typedef osg::Vec2 XYCoord
typedef osg::Vec4 Quad
typedef osg::Matrix::value_type matrix_type
typedef std::list
< osg::observer_ptr< Widget > > WidgetList
typedef Window::WindowList WindowList
typedef
osgUtil::LineSegmentIntersector::Intersections Intersections
Enumerations
enum EventType {
EVENT_NONE = 0x0000, EVENT_FOCUS = 0x0001, EVENT_UNFOCUS = 0x0002, EVENT_MOUSE_ENTER = 0x0004,
EVENT_MOUSE_OVER = 0x0008, EVENT_MOUSE_LEAVE = 0x0010, EVENT_MOUSE_DRAG = 0x0020, EVENT_MOUSE_PUSH = 0x0040,
EVENT_MOUSE_RELEASE = 0x0080, EVENT_MOUSE_SCROLL = 0x0100, EVENT_KEY_DOWN = 0x0200, EVENT_KEY_UP = 0x0400,
EVENT_ALL = 0xFFFF
}
enum EventMask {
EVENT_MASK_FOCUS = EVENT_FOCUS | EVENT_UNFOCUS, EVENT_MASK_MOUSE_MOVE = EVENT_MOUSE_ENTER | EVENT_MOUSE_OVER | EVENT_MOUSE_LEAVE, EVENT_MASK_MOUSE_CLICK = EVENT_MOUSE_PUSH | EVENT_MOUSE_RELEASE, EVENT_MASK_MOUSE_DRAG = EVENT_MASK_MOUSE_MOVE | EVENT_MASK_MOUSE_CLICK | EVENT_MOUSE_DRAG,
EVENT_MASK_KEY = EVENT_KEY_UP | EVENT_KEY_DOWN
}
Functions
const std::string DESCENT_STRING ("qpl")
std::ostream & _notify (osg::NotifySeverity ns=osg::INFO)
std::ostream & warn ()
std::ostream & info ()
std::string lowerCase (const std::string &str)
template<typename T >
bool hasDecimal (T v)
OSGWIDGET_EXPORT std::string getFilePath (const std::string &)
OSGWIDGET_EXPORT std::string generateRandomName (const std::string &)
OSGWIDGET_EXPORT osg::Camera * createOrthoCamera (matrix_type, matrix_type)
OSGWIDGET_EXPORT int createExample (osgViewer::Viewer &, WindowManager *, osg::Node *=0)
OSGWIDGET_EXPORT bool writeWindowManagerNode (WindowManager *)
bool OSGWIDGET_EXPORT callbackWindowMove (Event &)
bool OSGWIDGET_EXPORT callbackWindowRotate (Event &)
bool OSGWIDGET_EXPORT callbackWindowScale (Event &)
bool OSGWIDGET_EXPORT callbackWindowTabFocus (Event &)
Variables
const int OSGWIDGET_RENDERBIN_MOD = 5000
Detailed Description
The osgWidget library is a NodeKit that extends the core scene graph to support a 2D (and eventually 3D) GUI widget set.
Typedef Documentation
typedef ColorArray::value_type osgWidget::Color
typedef Color::value_type osgWidget::color_type
typedef osg::Vec4Array osgWidget::ColorArray
typedef osgUtil::LineSegmentIntersector::Intersections osgWidget::Intersections
typedef osg::Matrix::value_type osgWidget::matrix_type
typedef PointArray::value_type osgWidget::Point
typedef Point::value_type osgWidget::point_type
typedef osg::Vec3Array osgWidget::PointArray
typedef osg::Vec4 osgWidget::Quad
typedef osgDB::FieldReaderIterator& osgWidget::Reader
typedef TexCoordArray::value_type osgWidget::TexCoord
typedef TexCoord::value_type osgWidget::texcoord_type
typedef osg::Vec2Array osgWidget::TexCoordArray
typedef std::list<osg::observer_ptr<Widget> > osgWidget::WidgetList
typedef Window::WindowList osgWidget::WindowList
typedef osg::Vec2 osgWidget::XYCoord
Enumeration Type Documentation
enum osgWidget::EventMask
Enumerator:
EVENT_MASK_FOCUS
EVENT_MASK_MOUSE_MOVE
EVENT_MASK_MOUSE_CLICK
EVENT_MASK_MOUSE_DRAG
EVENT_MASK_KEY
enum osgWidget::EventType
Enumerator:
EVENT_NONE
EVENT_FOCUS
EVENT_UNFOCUS
EVENT_MOUSE_ENTER
EVENT_MOUSE_OVER
EVENT_MOUSE_LEAVE
EVENT_MOUSE_DRAG
EVENT_MOUSE_PUSH
EVENT_MOUSE_RELEASE
EVENT_MOUSE_SCROLL
EVENT_KEY_DOWN
EVENT_KEY_UP
EVENT_ALL
Function Documentation
std::ostream& osgWidget::_notify (osg::NotifySeverity ns = osg::INFO) [inline]
References osg::notify().
Referenced by info(), and warn().
bool OSGWIDGET_EXPORT osgWidget::callbackWindowMove (Event &)
Referenced by osgWidget::Window::attachMoveCallback().
bool OSGWIDGET_EXPORT osgWidget::callbackWindowRotate (Event &)
Referenced by osgWidget::Window::attachRotateCallback().
bool OSGWIDGET_EXPORT osgWidget::callbackWindowScale (Event &)
Referenced by osgWidget::Window::attachScaleCallback().
bool OSGWIDGET_EXPORT osgWidget::callbackWindowTabFocus (Event &)
Referenced by osgWidget::Window::attachTabFocusCallback().
OSGWIDGET_EXPORT int osgWidget::createExample (osgViewer::Viewer & , WindowManager * , osg::Node * = 0)
OSGWIDGET_EXPORT osg::Camera* osgWidget::createOrthoCamera (matrix_type , matrix_type)
const std::string osgWidget::DESCENT_STRING ("qpl")
OSGWIDGET_EXPORT std::string osgWidget::generateRandomName (const std::string &)
OSGWIDGET_EXPORT std::string osgWidget::getFilePath (const std::string &)
template<typename T > bool osgWidget::hasDecimal (T v) [inline]
std::ostream& osgWidget::info () [inline]
References _notify().
std::string osgWidget::lowerCase (const std::string & str) [inline]
std::ostream& osgWidget::warn () [inline]
References _notify(), and osg::WARN.
OSGWIDGET_EXPORT bool osgWidget::writeWindowManagerNode (WindowManager *)
Variable Documentation
const int osgWidget::OSGWIDGET_RENDERBIN_MOD = 5000
Generated at Thu Jun 9 2011 16:37:17 for the OpenSceneGraph by doxygen 1.7.1.