OpenThreads: OpenThreads::ReentrantMutex Class Reference
OpenThreads::ReentrantMutex Class Reference
Public Member Functions
ReentrantMutex ()
virtual ~ReentrantMutex ()
virtual int lock ()
Lock the mutex.
virtual int unlock ()
Unlock the mutex.
virtual int trylock ()
Test if mutex can be locked.
Constructor & Destructor Documentation
OpenThreads::ReentrantMutex::ReentrantMutex () [inline]
virtual OpenThreads::ReentrantMutex::~ReentrantMutex () [inline, virtual]
Member Function Documentation
virtual int OpenThreads::ReentrantMutex::lock () [inline, virtual]
Lock the mutex.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
Reimplemented from OpenThreads::Mutex.
References OpenThreads::Thread::CurrentThread().
Referenced by trylock(), and unlock().
virtual int OpenThreads::ReentrantMutex::trylock () [inline, virtual]
Test if mutex can be locked.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
Reimplemented from OpenThreads::Mutex.
References OpenThreads::Thread::CurrentThread(), and lock().
virtual int OpenThreads::ReentrantMutex::unlock () [inline, virtual]
Unlock the mutex.
Returns:
0 if normal, -1 if errno set, errno code otherwise.
Reimplemented from OpenThreads::Mutex.
References OpenThreads::Thread::CurrentThread(), and lock().
The documentation for this class was generated from the following file:
OpenThreads/ReentrantMutex
Generated at Thu Jun 9 2011 16:37:29 for the OpenThreads by doxygen 1.7.1.